CHANGELOG.md
=> doc: update cluster entry in CHANGELOG

CHANGELOG.md
=> doc: Add http keepalive behavior to CHANGELOG.md

CHANGELOG.md
=> docs: remove incorrect entry from changelog

lib/buffer.js, lib/net.js, src/tcp_wrap.cc, test/parallel/test-net-create-connection.js, test/parallel/test-net-localerror.js
Two recent commits:
buffer: reword Buffer.concat error message
net: allow port 0 in connect()
=> Cherrypicked commits from joyent/node

.mailmap
=> doc: add Malte-Thorben Bruns to .mailmap

README.md
=> doc: add ofrobots as collaborator

README.md
And yes, I'll add the PR-URL :)
=> doc: add domenic as collaborator

README.md
Ref: https://github.com/nodejs/io.js/issues/2102
=> doc: add targos as a collaborator

lib/internal/readme.md
I'm not 100% sure this is a good idea, but with things like https://github.com/nodejs/node/pull/2497 I figure it may be worthwhile.
=> doc: internal modules notice

doc/tsc-meetings/2015-08-26.md
Yesterday's meeting
Audio recording @ https://soundcloud.com/node-foundation/tsc-meeting-2015-08-26
=> doc: add TSC meeting minutes 2015-08-26

src/node_crypto.cc
Cherry-pick of #2723 for v0.10
/R=@bnoordhuis, @indutny
=> crypto: replace rwlocks with simple mutexes (v0.10)

doc/tsc-meetings/2015-09-30.md
* **Audio Recording**: https://soundcloud.com/node-foundation/tsc-meeting-2015-09-30
* **GitHub Issue**: https://github.com/nodejs/node/issues/3126
* **Minutes Google Doc**: https://docs.google.com/document/d/1RkLAWTIrhD3BTB2rs9_FahWI0C7lt9F8xnQXaueJPIE
=> doc: add TSC meeting minutes 2015-09-30

README.md
=> doc: add zkat to collaborators

README.md
=> doc: add JungMinu to collaborators

README.md
=> doc: add rmg to collaborators

README.md
- doc
I could have sworn that I did this when @chrisdickinson onboarded me a year ago, but I would be swearing falsely. Thanks to the heads up from @rvagg and @chrisdickinson that this needed to be done.
**r**: @chrisdickinson
=> doc: add @othiym23 to list of collaborators

LICENSE
doc
The licenses for both Marked and ESLint have updated.
Created using `tools/license-builder.sh`
=> doc: update licenses

doc/api/events.md
doc
Just fixed a typo. There was an extra 'for' thrown in the middle of the sentence.
=> Fixed typo in Events documentation.

doc/ctc-meetings/2016-08-24.md
doc
Catching up on getting these committed.
/cc @nodejs/ctc
=> doc: add CTC meeting minutes 2016-08-24

doc/api/fs.md
=> doc: fix typo

CHANGELOG.md
doc
fixes some markdown/html formatting problems for v4 and v0.10 in the release lines table
=> doc: fix some table problems in changelog.md

doc/ctc-meetings/2016-09-28.md
doc
as in title
@jasnell - make sure to capture these last couple before porting to the CTC repo. Thanks!
/cc @nodejs/ctc
=> doc: add 2016-09-28 CTC meeting minutes

README.md
=> doc: add Luca Maraschi to collaborators

CHANGELOG.md
=> doc: fix typo in changelog

test/parallel/parallel.status
Ref: https://github.com/nodejs/node/issues/14015
We deserve some green in our life (or at least Yellow)
test,npm,arm
=> test: mark test-npm-install flaky on arm

doc/api/dns.md
They were sorted in https://github.com/nodejs/node/pull/12726, but not maintained.
doc
=> doc: sort bottom-of-file dns markdown links

src/node_url.cc
=> src: remove unused computation

BUILDING.md, test/addons-napi/test_error/test.js, test/parallel/test-buffer-zero-fill-reset.js, test/parallel/test-cli-syntax.js, test/parallel/test-cluster-disconnect-race.js, test/parallel/test-cluster-disconnect-suicide-race.js, test/parallel/test-cluster-server-restart-rr.js, test/parallel/test-dsa-fips-invalid-key.js, test/parallel/test-http2-respond-file-204.js, test/parallel/test-http2-respond-file-compat.js, test/parallel/test-http2-serve-file.js, test/parallel/test-https-eof-for-eom.js, test/parallel/test-https-host-headers.js, test/parallel/test-npm-install.js, test/parallel/test-path-resolve.js, test/parallel/test-preload.js, test/parallel/test-repl-persistent-history.js, test/parallel/test-stdin-from-file.js, test/parallel/test-zlib-const.js, test/parallel/test-zlib-flush-drain.js, test/parallel/test-zlib-from-gzip.js, test/parallel/test-zlib-from-string.js, test/sequential/test-child-process-execsync.js, tools/doc/html.js, tools/license2rtf.js
This is just a meta PR for me to prevent running the CI for each PR individually before landing these commits. Small things got fixed in here like lint errors and commit messages.
I close it when I landed these. It might make sense to have another look from some collaborators nevertheless in here.
test,doc,tools
=> meta - ci run

doc/api/buffer.md
Refs: https://github.com/nodejs/node/pull/17427#discussion_r155305344
R= @Trott 
doc
=> doc: fix typo in Buffer.prototype.fill()

README.md
=> doc: add BethGriggs to collaborators

lib/dns.js, lib/internal/bootstrap/node.js, lib/internal/dns/promises.js, lib/internal/dns/utils.js, lib/internal/net.js, lib/tls.js, src/cares_wrap.cc, test/internet/test-dns.js, test/parallel/test-dns-lookup.js, test/parallel/test-tls-canonical-ip.js, test/sequential/test-async-wrap-getasyncid.js
Refs: https://github.com/nodejs/node/issues/22160
=> dns: make process.binding('cares_wrap') internal

deps/v8/gypfiles/v8.gyp
=> deps: add iterator torque module to v8.gyp

deps/v8/gypfiles/v8.gyp
=> deps: update v8.gyp

doc/api/deprecations.md
Refs: https://github.com/nodejs/node/pull/25377
cc @cjihrig
=> doc: fix deprecations metadata

doc/changelogs/CHANGELOG_V11.md
=> doc: fix changelog entry

.github/main.workflow
=> "on push" runs three Actions

.github/main.workflow
=> meta: try GitHub Action for cpplint

doc/api/http.md
This PR clarifies `http.ClientRequest` path description.
Fixes: https://github.com/nodejs/node/issues/25864
=> doc: clarify http.ClientRequest path description

doc/api/deprecations.md, lib/repl.js, test/parallel/test-repl-options.js
=> doc,test,repl: fix deprecation code

tools/node_modules/eslint/lib/rules/implicit-arrow-linebreak.js, tools/node_modules/eslint/node_modules/inquirer/node_modules/strip-ansi/index.js, tools/node_modules/eslint/node_modules/inquirer/node_modules/strip-ansi/package.json, tools/node_modules/eslint/node_modules/inquirer/node_modules/strip-ansi/readme.md, tools/node_modules/eslint/node_modules/table/node_modules/strip-ansi/index.js, tools/node_modules/eslint/node_modules/table/node_modules/strip-ansi/package.json, tools/node_modules/eslint/node_modules/table/node_modules/strip-ansi/readme.md, tools/node_modules/eslint/package.json
=> tools: update ESLint to 5.15.3

doc/api/errors.md, doc/api/os.md
- remove old `errors_system_errors` which partially predate the existence of the class, any useful information in it moved into the `SystemError` class docs
- outdent `SystemError` class docs to the same level as all the other classes
=> doc: remove old system_errors

doc/api/deprecations.md
Spotted while reviewing the [v11.14.0 proposal](https://github.com/nodejs/node/pull/27163).
Refs: https://github.com/nodejs/node/pull/26982
=> doc: assign missed deprecation code

doc/api/deprecations.md
=> doc: add missing status to DEP0121

doc/api/n-api.md
=> doc,n-api: fix typo

doc/api/assert.md
Revise the text for the `assert` module's legacy mode to make it simpler
and more scannable.
=> doc: revise assert legacy mode text

doc/api/stream.md
Revise the text of "Organization of this Document" in stream.md for
simplicity.
=> doc: update stream.md "Organization of this Document"

.mailmap, README.md
update my personal email in README
=> doc: update collaborator email address

doc/api/perf_hooks.md
=> doc: fix typographical error

test/root.status
=> test: remove duplicate entries from root.status

.github/workflows/CI.yml
Build docs using GitHub Actions. Uses [artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts) so that the built docs can be downloaded once all of the builds in the workflow complete (for up to 90 days on current GitHub policy).
=> build: build docs in GitHub Actions CI workflow

README.md
I sent an email to inactive collaborators (in the previous 6 months at
the time, no commits, no PRs reviewed, and no commits landed) asking if
it was time to move to emeritus.
Some replied affirmatively and I have moved those people to emeritus.
Others replied indicating a desire to remain collaborators, and I left
them as collaborators.
The remaining folks are being moved to emeritus in this change.
@claudiorodriguez @iarna @italoacasas @MoonBall @rubys @seishun @trevnorris If any of you wish to remain collaborators for any reason whatsoever, just let me know in the next 72 hours and I'll remove you from this PR. (You don't even have to tell me what the reason is. Leave a comment here or send me an email.)
Thanks for all the great contributions and collaboration over the years!
=> meta: move inactive collaborators to emeriti

SECURITY.md
Refs: https://github.com/nodejs/nodejs.org/pull/3106#issuecomment-614258785
=> doc: synch SECURITY.md with website

test/parallel/test-finalization-group-error.js
Related: https://github.com/nodejs/node-v8/issues/156#issuecomment-617482518
Note: this is target to `canary-base`
=> test: add required flag to FinalizationGroupError test

doc/changelogs/CHANGELOG_V14.md, tools/lint-md.js, tools/node-lint-md-cli-rollup/package-lock.json, tools/node-lint-md-cli-rollup/package.json
tools: update dependencies for markdown linting
Also:
doc: prepare 14.x changelog for remark update
Add a comment to disable a rule in the 14.x changelog that will be
needed once we update remark lint dependencies. This comment appears in
the other changelogs.
Refs: https://github.com/nodejs/remark-preset-lint-node/pull/89#issuecomment-628978791
=> tools: update dependencies for markdown linting

README.md
Add Richard Lau and his Release key.
Refs: https://github.com/nodejs/Release/issues/585
cc @MylesBorins @nodejs/releasers
=> doc: add release key for Richard Lau

doc/api/policy.md
=> doc: make general copy-edit changes to policy.md

doc/api/deprecations.md
=> doc: fix broken link to response.finished in deprecations doc

doc/api/cli.md
Remove incorrect second `#` in URl.
=> doc: fix incorrect URL in cli.md

doc/api/fs.md
=> doc: fix broken link in fs.md

doc/api/perf_hooks.md
=> doc: fix broken link in perf_hooks.md

README.md
=> meta: update my collab entry

.mailmap, AUTHORS, README.md
=> doc: update contact info for Ash Cripps

deps/v8/src/wasm/wasm-module-builder.h
Fix https://github.com/nodejs/node-v8/issues/172
=> deps: V8: fix build on windows

doc/guides/technical-values.md
Make the section a bit shorter and comply with minor elements of
Microsoft Style Guide.
=> doc: revise stability section of values doc

doc/api/policy.md
=> doc: revise dependency redirection text in policy.md

doc/api/synopsis.md
=> doc: replace "this guide" link text with guide title

doc/api/child_process.md
This consolidates information about Windows environment variables and
has a few other smaller improvements (punctuation, present tense, etc.).
=> doc: revise introductory child_process text

doc/api/packages.md
Some minor adjustments, mostly moving things to present tense and
avoiding the ambiguity of _may_.
Refs: https://github.com/nodejs/node/pull/35370#issuecomment-700798044
=> doc: copyedit packages.md

doc/api/errors.md
* add kbd elements
* correct period/parenthesis order
* make fragment a full sentence
=> doc: improve SIGINT error text

doc/api/webcrypto.md
0 is deprecated. Change to 1, which is experimental.
Before:
After:
=> doc: fix stability indicator in webcrypto doc

doc/api/process.md
Refs: https://github.com/nodejs/node/runs/1275049330
=> doc: fix YAML lint error on master

test/fixtures/wpt/README.md, test/fixtures/wpt/url/urlsearchparams-constructor.any.js, test/fixtures/wpt/versions.json
Refs: https://github.com/web-platform-tests/wpt/pull/26126
=> test: add upstream test cases to urlsearchparams

README.md
Pulled from https://github.com/nodejs/node/pull/35478/commits/41608219072121255bacfad3f4fe3fffe1ce4d32.
```
It's been ten years and it's time for a change. September 30 was my
last day at IBM and my last day as a full-time Node.js maintainer.
I feel Deno is the future and that's why I'm joining that scrappy
startup, Deno Land Inc., to make that future happen.
```
=> doc: move bnoordhuis to emeritus

test/parallel/parallel.status
=> test: add missing ref comments to parallel.status

doc/api/debugger.md
Use apostrophe for possessive.
=> doc: fix typo in debugger.md

test/common/inspector-helper.js
=> test: fix typo in inspector-helper.js

tools/doc/package-lock.json, tools/doc/package.json
=> tools: bump unist-util-find@1.0.1 to unist-util-find@1.0.2

src/res/node.rc
This is the name that appears in task manager by default
cc @nodejs/platform-windows
=> src: update node.rc file description

lib/readline.js, test/parallel/test-readline-csi.js
Fixes: https://github.com/nodejs/node/issues/36301
=> readline: cursorTo throw error on NaN

doc/api/worker_threads.md
=> doc: simplify worker_threads.md text

doc/api/worker_threads.md
=> doc: fixup type in metadata entry

doc/api/buffer.md
'transferring' was misspelled as 'transfering'
=> doc: typo corrected in doc/api/buffer.md

.github/workflows/misc.yml, Makefile
=> tools: run doctool tests on GitHub Actions CI

doc/guides/maintaining-V8.md, doc/guides/node-postmortem-support.md
changes as per doc styling guidelines
=> doc: apply sentence case to headers in doc/guides

doc/api/url.md
Fixes: https://github.com/nodejs/node/issues/37492
=> doc: add url.resolve replacement example

doc/guides/contributing/pull-requests.md
changes as per doc styling guidelines
=> doc: apply sentence case to headers in doc/guides/contributing/pull-requests.md

test/parallel/parallel.status
This CI test failure hasn't been reported for some time.
Closes: https://github.com/nodejs/node/issues/26610
=> test: remove FLAKY status for test-async-hooks-http-parser-destroy

doc/api/assert.md
=> doc: fix linter issue

doc/api/http.md
=> doc: fix typo in description of close event

doc/api/n-api.md, src/js_native_api.h, src/js_native_api_types.h, src/node_api.h, src/node_api_types.h, src/node_version.h, test/js-native-api/test_general/test.js, test/js-native-api/test_object/test_object.c, test/node-api/test_async_cleanup_hook/binding.c
Mark as stable the APIs that define Node-API version 8.
PR-URL: https://github.com/nodejs/node/pull/37652
Reviewed-By: @Flarna
Reviewed-By: @mhdawson
Reviewed-By: @legendecas
=> [v12.x] node-api: define version 8

README.md
fixes: https://github.com/nodejs/node/issues/37619
=> doc: add @linkgoron to collaborators

README.md
Move myself to collaborators emeriti as I haven't been active since I moved from V8 to DevTools and I'm moving teams again
=> doc: move psmarshall to collaborators emeriti

doc/api/fs.md
=> doc: fix typo in fs.md

README.md
=> doc: update TSC members list with three new members

tools/doc/generate.js
Fixes: https://github.com/nodejs/node/issues/38391
=> tools: fix doc generation when version info is not available

doc/api/crypto.md
=> doc: fix code example in ecdh.setPublicKey

doc/api/fs.md
=> fs: grammar/typo fix

test/es-module/test-esm-exports-deprecations.mjs
Those have been migrated to runtime deprecation in v16.0.0.
=> test: remove unnecessary `--pending-deprecation` flag

lib/internal/inspector/_inspect.js, lib/internal/inspector/inspect_client.js, lib/internal/inspector/inspect_repl.js
=> debugger: remove unnecessary boilerplate copyright comment

tools/lint-md.js, tools/node-lint-md-cli-rollup/package-lock.json
=> tools: update remark-preset-lint-node to 2.4.1

doc/api/vm.md
=> doc: move vm.measureMemory() to expected location in doc

doc/api_assets/style.css
=> doc: normalize CSS variable names and indentation

doc/guides/adding-new-napi-api.md
=> doc: rename datatypes to data types

README.md
Sam confirmed in email that they are not opposed to moving to emeritus
at this time.
=> doc: move Sam Ruby to emeritus

onboarding.md
=> doc: use "repository" instead of "repo" in onboarding.md

README.md
Ali indicated in email that it makes sense to move him to collaborator
emeritus at this time.
=> doc: move ofrobots to collaborator emeritus

README.md
In private email, Andreas Madsen indicated it would be OK to move him to
emeritus.
=> doc: move AndreasMadsen to emeritus

test/common/debugger.js
Optimistically removing workaround code in the debugger test tool.
=> test: remove debugger workaround for AIX

doc/api/buffer.md, doc/api/cli.md, doc/api/errors.md, doc/api/fs.md, doc/api/http.md, doc/api/stream.md, doc/guides/investigating_native_memory_leak.md, doc/node.1
Refs: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/bits-bytes-terms
=> doc: use consistent abbreviation formatting

.github/workflows/commit-lint.yml
commit-lint.yml uses setup-node@v1 but all our other GitHub Actions use
v2. Update commit-lint.yml.
=> build: update to setup-node@v2

README.md
I have not contributed to Node.js in a couple of years. While I would
love to continue doing so, there's not a high likelihood of this happening
in the near future. This commit moves my status from collaborator to
emeritus.
It's been fun!
Signed-off-by: Lance Ball <lball@redhat.com>
=> doc: move lball@redhat.com to emeritus

doc/api/async_hooks.md
=> doc: fix typo error

README.md
Even though I'm only an emeritus at this point, because I'm on the moderation team, people within the organization might want to know my pronouns. Since I now identify as nonbinary, those pronouns have changed. Updating the emeritus list accordingly!
=> doc: update Forrest Norvell's pronouns

doc/abi_version_registry.json
Claims ABI version for Electron 18.
=> doc: claim ABI version for Electron 18

.github/workflows/tools.yml
=> build: fix tools.yml errors

README.md
Use clear and concise language.
=> doc: improve README.md lede section

tools/lint-md/lint-md.mjs, tools/lint-md/package-lock.json, tools/lint-md/package.json
Patch updates for remark-parse, remark-stringify, and unified.
Patch updates to rollup plugins and minor update to rollup.
=> tools: update lint-md dependencies

lib/repl.js, test/parallel/test-repl-tab-complete-import.js, test/parallel/test-repl-tab-complete.js
=> repl: fix and extend require/import tab complete

.github/ISSUE_TEMPLATE/2-feature-request.md
=> meta: add feature request label for issue template

test/parallel/test-url-format-whatwg.js
https://nodejs.org/dist/latest-v17.x/docs/api/url.html#urlurltohttpoptionsurl
=> test: Add `auth` option case for `url.format`

README.md
:)
Signed-off-by: Tierney Cyren <hello@bnb.im>
=> doc: add @bnb as a collaborator

README.md
I've been inactive on this repo since a long time now, I think it's time to drop the commit bit. If possible, you can keep my team memberships for occasional activity.
=> meta: Move myself to emeriti

doc/changelogs/CHANGELOG_V12.md
Refs: https://github.com/nodejs/node/pull/41161
=> doc: fix date for v12.22.8

lib/internal/policy/manifest.js
=> policy: add missing JSDoc @param entry

lib/internal/modules/esm/resolve.js
=> esm: reconcile JSDoc vs. actual parameter name

lib/internal/source_map/source_map.js
=> lib: remove spurious JSDoc entry

doc/api/inspector.md
The output message was changed in f3e107aeef2f75cb3a705fd15260f65dd77e78d4.
=> doc: update output in inspector examples

doc/api/esm.md
Refs: https://github.com/nodejs/node/pull/41434
=> doc: add missing YAML tag in `esm.md`

BUILDING.md
=> doc: add 16 and 17 to previous versions

doc/api/url.md
=> doc: clarify treatment of non-string base in URL()

.mailmap, AUTHORS
Refs: https://github.com/nodejs/node/pull/41683#pullrequestreview-861551695
=> meta: adjust mailmap/AUTHORS to reflect README change

.mailmap, AUTHORS
Use the same email address in AUTHORS, README.md, and git metadata for
existing collaborator.
=> meta: update mailmap/AUTHORS info for existing collaborator

README.md
=> doc: add missing space before hyphen

README.md
Refs: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www
=> doc: use sentence case in readme introduction

doc/api/deprecations.md
=> doc: edit process.config deprecation text

doc/api/webstreams.md
=> doc: add missing `buffer` in the `stream/consumers` import example

.github/workflows/tools.yml
Refs: https://github.com/nodejs/node/pull/41973#issuecomment-1039780665
=> build: move tool updates workflow runtime a day later

test/parallel/test-http-agent-timeout.js, test/sequential/test-tls-psk-client.js
=> test: fix typographical error

README.md
Fixes: https://github.com/nodejs/node/issues/41781
=> doc: add marsonya to collaborators

lib/internal/bootstrap/pre_execution.js
Refs: https://github.com/nodejs/node/pull/41969#issuecomment-1039448684
=> lib: stop installing webcrypto if `no_browser_globals` is `true`

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/3-api-ref-docs-problem.yml
Refs: https://github.com/nodejs/node/issues/41987
=> meta: use plain emojis instead of escape sequences

src/crypto/crypto_common.cc
Match other call sites of `BIO_new(BIO_s_mem())` and `CHECK` the result of the call.
Refs: https://github.com/nodejs/node/commit/fb3a9cd0d8e8cf5f3120012a28643230b31c1f83
=> crypto: check result of BIO_new in X509ToObject

test/parallel/test-vm-basic.js
This improves a test coverage in `lib/vm.js`.
ref: https://coverage.nodejs.org/coverage-cd5689eed3be54a5/lib/vm.js.html#L364
This PR  add a test that the `compileFucntion` method with the `produceCachedData` option.
=> test: improve vm test coverage

README.md
=> meta: remove collaborator

README.md
I want to apply to become a triager.
My motivation is to help manage issues and make more contributions to Node.js. I will try my best!
I have read and understood the Code of Conduct and will adhere to that.
=> doc: add meixg to triagers

.github/ISSUE_TEMPLATE/2-feature-request.yml
=> meta: correct link to feature request document

lib/internal/blob.js
Fix: https://github.com/nodejs/node/issues/42108
before:
after:
`start` only runs once, and `pull` usually will be executed multiple times.
=> buffer: improve blob read performance

.github/workflows/close-stale-feature-requests.yml
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> build: fix usage of input in feature action

README.md
Fixes: https://github.com/nodejs/node/issues/42079
=> doc: add JakobJingleheimer to collaborators list

test/parallel/test-crypto-prime.js
This adds coverage for this branch:
https://github.com/nodejs/node/blob/29bb2bb57d2a993e4e79172fe6b954f8047eee81/src/crypto/crypto_random.cc#L126-L129
It's currently [not covered](https://coverage.nodejs.org/coverage-010cb714161102de/cxxcoverage.crypto_crypto_random.cc.html).
=> test: cover 32-bit sizes in generatePrime

doc/api/v8.md
"considered undefined" suggests that it's not REALLY undefined. It's
really undefined. Be firm!
=> doc: remove "considered" for clarity

doc/api/cluster.md
=> doc: remove erroneous comma in cluster explainer

.github/label-pr-config.yml
Add https://github.com/nodejs/node/labels/dependencies label to label-pr-config.
=> meta: add dependencies label to label-pr-config

src/node.cc
=> src: use emplace_back instead of push_back

test/wpt/test-webcrypto.js
=> test: use global webcrypto for WPT tests

test/parallel/test-url-relative.js
Refs: https://github.com/nodejs/node/issues/42279
~The first commit in this PR is https://github.com/nodejs/node/pull/42280. Once that lands, it can be removed from here. Marking as blocked for now.~
=> test: add test case for reverted 17.7 regression

src/crypto/crypto_ec.cc
This should not usually happen but it's better not to silently assume that.
=> src: check EC_POINT_get_affine_coordinates result

README.md
=> doc: remove unneeded lint disable comment

README.md
* The logo takes a lot of room doesn't add information.
* Make Node.js a top-level header and Table of Contents a  second-level
header.
This looks better, improve semantics, makes the README.md more usable in
its raw form, and aligns us with README.md practices in other projects
like TypeScript and Deno.
=> doc: improve README.md usability

README.md
=> doc: add link to section

doc/contributing/security-steward-on-off-boarding.md
This change is helpful when publishing release announcements.
=> doc: update security release onboarding

doc/contributing/collaborator-guide.md
=> doc: fix internal link in collaborator-guide.md

test/parallel/test-fs-promises-file-handle-write.js
Refs: https://github.com/nodejs/node/pull/42518
=> test: improve `FileHandle.prototype.write` coverage

doc/api/webcrypto.md
=> doc: simplify recommendation in webcrypto.md

lib/internal/crypto/keygen.js, test/parallel/test-crypto-keygen.js
Many of the validations could be simplified and cleaned up by using
validators and to keep consistency.
=> crypto: cleanup validation

doc/api/webstreams.md
=> doc: add missing punctuation in Web Streams doc

doc/contributing/security-release-process.md
Refs: https://github.com/nodejs/nodejs.org/pull/4487
Refs: https://github.com/nodejs/nodejs.org/pull/4497
=> doc: record March 2022 security release steward

lib/internal/per_context/domexception.js
The linked issue, https://bugs.chromium.org/p/v8/issues/detail?id=6593,
is marked as "Fixed", so I think we can revert this now.
This reverts commit 08a9c4a996964aca909cd75fa8ecafd652c54885.
cc @joyeecheung
Refs: https://bugs.chromium.org/p/v8/issues/detail?id=9187
Signed-off-by: Darshan Sen <raisinten@gmail.com>
=> bootstrap: stop delaying instantiation of maps in per-context scripts

doc/api/cluster.md
=> doc: use serial comma in cluster docs

doc/contributing/releases.md
=> doc: improve commit message example for releases

README.md
=> doc: add the preferred name for @himself65

.github/workflows/build-windows.yml, .github/workflows/coverage-windows.yml
re-enable if https://github.com/nodejs/node/issues/43092 is fixed.
=> build: temp disable windows-2022

doc/api/modules.md
=> doc: use serial comma in modules docs

doc/contributing/strategic-initiatives.md
Add a new strategic initiative for Shadow Realm support in Node.js.
Closes https://github.com/nodejs/TSC/issues/1221
=> doc: add strategic initiative for shadow realm

doc/api/dns.md
=> doc: use serial comma in dns docs

doc/api/dgram.md
=> doc: use serial comma in dgram docs

Makefile, tools/license2rtf.js, vcbuild.bat
This reverts commit 30cb1bf8b8594e3ec8aa9b9b7a7220fe1cc9c926.
Fixes: https://github.com/nodejs/node/issues/43213
Refs: https://github.com/nodejs/node/pull/43101
=> Revert "tools: refactor `tools/license2rtf` to ESM"

doc/api/worker_threads.md
=> doc: use serial comma in worker_threads docs

doc/api/console.md
=> doc: use serial comma in console docs

doc/api/net.md
=> doc: use serial comma in net docs

doc/api/webstreams.md
=> doc: use serial comma in webstreams docs

doc/api/globals.md
Use apostrophe for possessive.
Signed-off-by: Daeyeon Jeong daeyeon.dev@gmail.com
=> doc: fix typo in globals.md

doc/contributing/security-model-strategy.md
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> doc: fixup after rename of primary nodejs branch

onboarding.md
Refs: https://github.com/nodejs/node/issues/33864
=> doc: update main branch name in onboarding.md

Makefile
Refs: https://github.com/nodejs/node/issues/33864
=> doc: update main branch name in Makefile

src/README.md
Refs: https://github.com/nodejs/node/issues/33864
=> doc: update main branch name in src/README

doc/contributing/security-release-process.md
=> doc: include CVSS mention

doc/api/fs.md
Refs: https://github.com/nodejs/node/issues/43669
=> doc: add note regarding special case of 0 stat.size

README.md
=> doc: add Geoffrey Booth to TSC

doc/api/process.md
=> doc: remove extra 'in's

test/parallel/parallel.status
See also https://github.com/nodejs/node/pull/43754#issuecomment-1180108835.
Refs: https://github.com/nodejs/node/issues/43680
=> test: mark test-http-client-response-timeout flaky

deps/ngtcp2/README.md
updated `deps/ngtcp2/README.md` doc #43766
=> docs: updated ngtcp2 readme

test/wpt/test-url.js
=> test: complete TODO in test/wpt/test-url.js

README.md
I want to volunteer and become a triager,
I am looking forward to getting more involved in the node project, and one day becoming a collaborator
I have read node's [code of conduct](https://github.com/nodejs/admin/blob/HEAD/CODE_OF_CONDUCT.md), and I  will adhere to it
=> doc: add MoLow to triagers

doc/api/globals.md
Refs: https://github.com/nodejs/node/pull/37970
=> doc: add history info for `global.performance`

doc/api/http.md
the returns need to be lowercase
=> doc: fix typo in http.md

tools/doc/package-lock.json
Fixes: https://github.com/nodejs/node/issues/43864
=> deps: update hast-util-raw

test/parallel/test-repl-preview.js, test/parallel/test-repl-top-level-await.js
Use `for await` in combination with `events.on` to simplify control flow.
=> test: simplify ReplStream.wait()

lib/internal/process/per_thread.js
Uses essentially the fix suggested there, which is by @michaelfig
Refs: https://github.com/endojs/endo/issues/576
Fixes: https://github.com/nodejs/node/issues/43496
=> fix: avoid override by assignment

.github/label-pr-config.yml
Signed-off-by: Daeyeon Jeong daeyeon.dev@gmail.com
=> meta: update `node-api` in label-pr-config

src/crypto/README.md
=> doc: fix typo in src/crypto/README.md

.mailmap, README.md
=> doc: update email and mailmap for BethGriggs

tools/find-inactive-collaborators.mjs
=> tools: add verbose flag to find-inactive-collaborators

doc/api/test.md
=> doc: fix typos in `test.md`

doc/abi_version_registry.json
This PR claims a new ABI version for Electron 21.
=> doc: claim ABI version for Electron 21

README.md
I am volunteering to be a triager. I'd like to become more involved,
help users with their issues, and eventually become a collaborator.
I've understood & agree to the code of conduct.
=> doc: add kvakil to triagers

.mailmap, AUTHORS, README.md
Updating my email on the collaborator section of README.
=> doc: update collaborator email

README.md
Fixes: https://github.com/nodejs/node/issues/43755
=> doc: add ErickWendel to collaborators

.github/workflows/test-internet.yml
Refs: https://github.com/nodejs/node/pull/44054#issuecomment-1200246681
=> build: allow test-internet on forks if not scheduled

.github/CODEOWNERS
Ping @nodejs/startup on PRs like https://github.com/nodejs/node/pull/44104.
=> meta: add codeowner for src/node_snapshot*

onboarding.md
LTS repo is now Release.
readable-stream is important but a bit of a specialized topic. The others listed here are of general interest.
=> doc: update repository list in onboarding doc

lib/internal/test_runner/test.js
=> test_runner: refactor to use more primordials

doc/api/assert.md
This function appears to be unused, so remove it.
=> doc: remove unused code in call tracker example

src/node_snapshotable.cc
To improve startup performance.
=> bootstrap: turn on FunctionCodeHandling::kKeep in the snapshot builder

test/parallel/parallel.status
The issue was fixed by https://github.com/nodejs/node/pull/43890.
Fixes: https://github.com/nodejs/node/issues/43680
=> test: remove test-http-client-response-timeout flaky designation

README.md
Fixes: https://github.com/nodejs/node/issues/44120
=> doc: add MoLow to collaborators

lib/internal/crypto/aes.js, lib/internal/crypto/cfrg.js, lib/internal/crypto/ec.js, lib/internal/crypto/mac.js, lib/internal/crypto/rsa.js, lib/internal/crypto/util.js, test/parallel/test-webcrypto-encrypt-decrypt-aes.js, test/parallel/test-webcrypto-encrypt-decrypt-rsa.js, test/wpt/status/WebCryptoAPI.json
This PR fixes WebCryptoAPI behaviour when it comes to operation specific errors.
Fixes 21 WPTs
=> crypto: fix webcrypto operation errors to be OperationError

README.md
Fixes: https://github.com/nodejs/node/issues/44123
=> doc: add cola119 to collaborators

lib/internal/tls/secure-context.js
Use the logical OR operator instead of the ternary operator where applicable.
A micro-optimization, but also a little more readable.
=> tls: use logical OR operator

.github/label-pr-config.yml
cc @nodejs/whatwg-stream
Signed-off-by: Daeyeon Jeong daeyeon.dev@gmail.com
=> meta: update `web streams` in label-pr-config

lib/internal/event_target.js, lib/internal/util.js, lib/internal/worker/io.js, lib/util.js
Left over from https://github.com/nodejs/node/pull/43270 (lint rule fix coming in a follow up PR)
=> lib: refactor to avoid prototype pollution

doc/api/packages.md
=> doc: fix named export detection "esm" → "cjs" module lexer

README.md
Fixes: https://github.com/nodejs/node/issues/44142
Signed-off-by: Daeyeon Jeong daeyeon.dev@gmail.com
=> doc: add daeyeon to collaborators

src/crypto/crypto_ec.cc
There is no need to explicitly branch based on `num_curves` or on the return value of the second call to `EC_get_builtin_curves`. Remove unnecessary branches and replace the loop with a functional transform.
Previously, the last line of the function body was never executed because, in practice, `num_curves > 0`.
=> src: simplify ECDH::GetCurves()

doc/contributing/releases.md
Added an extra command to make sure to remind me (and other releasers)
to update the `main` branch _before_ cherry-picking the release commit
to the branch.
Adding this command will often avoid unnecessary extra-work in case
there are mismatches between the local state of the main branch and
remote.
cc @nodejs/releasers
=> doc: note on release guide to update main branch

src/node_options.cc
=> doc: put a space after a period

tools/eslint-rules/avoid-prototype-pollution.js
=> tools: fix typo in `avoid-prototype-pollution` lint rule

doc/api/tls.md
=> doc: add missing parenthesis in TLSSocket section

tools/test.py
=> tools: fix shebang to use python3 by default

lib/internal/cluster/primary.js, lib/internal/util/inspector.js
follow up from https://github.com/nodejs/node/pull/44520, this utilizes a new utility
=> cluster: use inspector utils

test/parallel/test-repl.js
This is needed for https://github.com/nodejs/node/pull/42083, since it's not a semver-major change I thought it would be a good idea to land it in its own PR.
=> test: fix `test-repl` not validating leaked globals properly

.github/label-pr-config.yml
=> meta: update test_runner in label-pr-config

tools/update-nghttp2.sh
=> tools: fix typo in update-nghttp2.sh

BUILDING.md
[Windows Boxstarter Powershell installation](https://github.com/nodejs/node/blob/main/BUILDING.md#option-2-automated-install-with-boxstarter) states:
```powershell
Set-ExecutionPolicy Unrestricted -Force
iex ((New-Object System.Net.WebClient).DownloadString('https://boxstarter.org/bootstrapper.ps1'))
get-boxstarter -Force
Install-BoxstarterPackage https://raw.githubusercontent.com/nodejs/node/HEAD/tools/bootstrap/windows_boxstarter -DisableReboots
```
but omits a useful final command `refreshenv`. The terminal emits this message amidst a lot of other output:
> note the below emphasis
```powershell
Environment Vars (like PATH) have changed. Close/reopen your shell to
see the changes (or in powershell/cmd.exe just type `refreshenv`).
```
The guidance does not mention this step, so following …
=> doc: improve building doc for Windows Powershell

README.md
👋🏻 
Following #44555 I have updated the README to remove myself from the collaborators list. I have updated my contact email and the name I would like to show. I hope it's not a problem.
Closes #44555 .
=> meta: move dnlup to emeriti

doc/api/fs.md
=> doc: remove extra space on threadpool usage

doc/abi_version_registry.json
This PR reserves a new node module version for Electron 22.
=> doc: add registry number for Electron 22

test/sequential/test-debugger-low-level.js
Signed-off-by: Meghana Ramesh <meghanaramesh96@gmail.com>
=> test: update test-debugger-low-level to use await/async

tools/eslint-rules/no-unescaped-regexp-dot.js
Refactoring function-style format to object-style notation.
=> tools: refactor deprecated format to use object-style notation

test/sequential/test-debugger-exec.js
=> test: refactor to async/await

doc/api/cli.md
=> doc: add anchor link for --preserve-symlinks

README.md
Refs: https://github.com/nodejs/Release/blob/3cd3c6a65188d0e64017d0cee11b9834a5753fd5/GOVERNANCE.md#offboarding-releasers
Refs: https://github.com/nodejs/Release/pull/784
=> doc: move release keys we don't use anymore in README

test/parallel/test-cli-node-options-disallowed.js
Ref: https://github.com/nodejs/node/pull/42658#issuecomment-1093060992
=> test: check `--test` is disallowed in NODE_OPTIONS

doc/changelogs/CHANGELOG_V12.md
=> (changelog_v12) Fix typo

doc/contributing/collaborator-guide.md
=> doc: fix label name in collaborator guide

lib/inspector/promises.js
Limit the effect of users mutating `node:util`, `node:inspector`, or `Array.prototype`.
=> inspector: refactor `inspector/promises` to be more robust

doc/api/util.md
Refs: https://github.com/nodejs/node/pull/44631
=> doc: fix typo in parseArgs default value

CHANGELOG.md
Node.js 16's End-of-Life date was brought forward to coincide with the end of support for upstream OpenSSL 1.1.1.
Refs: https://nodejs.org/en/blog/announcements/nodejs16-eol/
Refs: https://github.com/nodejs/Release/pull/752
Refs: https://github.com/nodejs/TSC/issues/1222
=> doc: update Node.js 16 End-of-Life date

CHANGELOG.md
v17.x is EOL on 2022-06-01
Refs: https://github.com/nodejs/Release/blob/main/schedule.json
=> doc: mark Node.js v17.x as EOL

doc/contributing/releases.md
Refs: https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/
=> doc: add note about latest GitHub release

.github/workflows/authors.yml, .github/workflows/find-inactive-collaborators.yml, .github/workflows/find-inactive-tsc.yml, .github/workflows/license-builder.yml, .github/workflows/timezone-update.yml, .github/workflows/tools.yml
Refs: https://github.com/nodejs/node/pull/45022#issuecomment-1290397901
=> tools: fix `create-or-update-pull-request-action` hash on GHA

README.md
Fixes: https://github.com/nodejs/node/issues/44828
=> doc: add lukekarrys to collaborators

CHANGELOG.md
=> doc: mark Node.js 12 as End-of-Life

README.md
This is usually generated by a GitHub Action, but PR-generation is currently not working for several GitHub Actions. (See https://github.com/nodejs/node/pull/45022#issuecomment-1289916064.)
So I ran the tool manually instead.
=> meta: move a collaborator to emeritus

README.md
Refs: https://github.com/nodejs/node/pull/45249#issuecomment-1296576197
=> meta: fix email address typo in README

README.md
=> meta: update collaborator email address in README

doc/api/async_context.md
=> fix "task_processor.js" typo

doc/contributing/pull-requests.md, onboarding.md
The name has been changed from nodejs-dev to nodejs-core.
=> doc: update name of Node.js core Slack channel

.mailmap, AUTHORS, README.md
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> doc: Fix email for Ashley

doc/contributing/offboarding.md
=> meta: be more proactive about removing from teams

doc/contributing/maintaining-dependencies.md
=> doc: fix typo in maintaining-dependencies.md

src/env.h
=> src: remove the unused PackageConfig class

README.md
Update VoltrexMaster's GitHub username to the new one.
=> meta: update VoltrexMaster's username

SECURITY.md
Refs: https://github.com/nodejs/node/pull/45223
=> doc: fix typo in threat model

.github/workflows/test-asan.yml
This should be a temporary bandaid until #45578 is resolved.
Refs https://github.com/nodejs/node/issues/45578
=> tools: have test-asan use ubuntu-20.04

README.md
Refs: https://github.com/nodejs/TSC/issues/1308
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> doc: add Rafael to the tsc

doc/abi_version_registry.json
This PR reserves a new node module version for Electron 23 & Electron 24.
=> doc: add registry number for Electron 23 & 24

doc/contributing/releases.md
- The pull request is automatically closed.
- The branch is automatically deleted.
=> doc: remove release cleanup step

doc/contributing/releases.md
Switch to the `patience` git diff algorithm to reduce the likelihood of mismerges when the release commit is cherry-picked to the `main` branch.
Refs: https://github.com/nodejs/Release/issues/771#issuecomment-1352165054
cc @nodejs/releasers
=> doc: reduce likelihood of mismerges during release

test/fixtures/wpt/README.md, test/fixtures/wpt/url/resources/percent-encoding.json, test/fixtures/wpt/versions.json
This pull request updates URL web platform tests to latest
=> test: update url wpt to latest

.github/workflows/close-stale-feature-requests.yml, .github/workflows/close-stalled.yml
Update the GitHub workflow action used for closing stalled issues and PRs.
=> tools: update GitHub workflow action

.github/workflows/authors.yml
This should simplify the review of `AUTHORS` file updates.
=> tools: add url to `AUTHORS` update automation

deps/v8/include/v8-version.h, deps/v8/src/ast/scopes.cc, deps/v8/src/codegen/arm/assembler-arm.cc, deps/v8/src/compiler/backend/x64/code-generator-x64.cc, deps/v8/src/wasm/graph-builder-interface.cc, deps/v8/test/mjsunit/regress/regress-crbug-1394973.js
Refs: https://github.com/v8/v8/compare/10.9.194.6...10.9.194.9
=> deps: patch V8 to 10.9.194.9

lib/async_hooks.js
=> async_hooks: refactor to use `validateObject`

lib/internal/vm.js
=> vm: refactor to use `validateStringArray`

lib/internal/event_target.js
Capital letter is followed after 'k' prefix.
=> events: fix violation of symbol naming convention

README.md
Refs: https://github.com/nodejs/node/pull/11089#issuecomment-277060503
=> doc: add personal pronouns option

doc/contributing/releases.md
Fixes: https://github.com/nodejs/Release/issues/765
=> doc: add note about major release rotation

benchmark/.eslintrc.yaml, benchmark/net/net-c2s.js, benchmark/net/net-pipe.js, benchmark/net/net-s2c.js, benchmark/net/net-wrap-js-stream-passthrough.js, benchmark/net/tcp-raw-c2s.js, benchmark/net/tcp-raw-pipe.js, benchmark/net/tcp-raw-s2c.js
=> benchmark: add trailing commas in `benchmark/net`

benchmark/.eslintrc.yaml, benchmark/module/module-loader-circular.js, benchmark/module/module-loader-deep.js, benchmark/module/module-loader.js, benchmark/module/module-require.js
=> benchmark: add trailing commas in `benchmark/module`

test/parallel/test-eslint-prefer-primordials.js, tools/eslint-rules/prefer-primordials.js
Refs: https://github.com/nodejs/node/pull/46648#discussion_r1106168908
=> tools: fix bug in `prefer-primordials` lint rule

README.md
So long and thanks for all the bike sheds 🚲🏚
Fixes #46682
=> doc: move bcoe to emeriti

tools/getsharedopensslhasquic.py, tools/js2c.py, tools/v8_gypfiles/GN-scraper.py
Opening this to reland https://github.com/nodejs/node/pull/46585 but this time with the metadata required. Sorry for the mess this has turned out to be for a simple change, @josusky. I hope it's OK that I'm doing this on your behalf. (You're still the author on the commit here.)
=> tools: fix regex strings in Python tools

doc/api/debugger.md
@cola119 closed https://github.com/nodejs/node/pull/43018, probably because it had sat for so long without action. I think we should land it. Can folks please take a look? @nodejs/diagnostics
=> doc: add document for profiling and heap snapshot

test/parallel/test-tls-alert.js
Avoid the process `'exit'` event handler and use `execFile` instead of manual stream operations.
Refs: https://github.com/nodejs/node/pull/46751
=> test: simplify test-tls-alert

benchmark/events/eventtarget-add-remove.js
Added a simple benchmark similar to `benchmark/events/ee-add-remove.js`
Refs: https://github.com/nodejs/performance/issues/60
=> benchmark: add benchmark for EventTarget add and remove

.github/workflows/tools.yml
related to: https://github.com/nodejs/security-wg/issues/828
Automate llhttp update
=> tools: automate llhttp update

test/fixtures/wpt/README.md, test/fixtures/wpt/url/failure.html, test/fixtures/wpt/url/resources/setters_tests.json, test/fixtures/wpt/url/resources/urltestdata.json, test/fixtures/wpt/url/urlsearchparams-size.any.js, test/fixtures/wpt/versions.json
Update wpt url test. Added case for https://github.com/nodejs/node/issues/46850 by https://github.com/web-platform-tests/wpt/pull/38711.
Rely on https://github.com/nodejs/node/pull/46853
=> test: update web-platform tests for url

README.md
Refs: https://github.com/nodejs/Release/issues/829
=> doc: add release key for Juan Arboleda

lib/internal/per_context/primordials.js, typings/primordials.d.ts
=> typings: improve `primordials` typings

.github/workflows/tools.yml, doc/contributing/maintaining-c-ares.md, tools/dep_updaters/update-c-ares.sh, tools/dep_updaters/update-cares.sh
=> tools: automate cares update

.github/workflows/tools.yml, tools/dep_updaters/update-ada.sh
Align `update-ada.sh` with other scripts.
--
Signed-off-by: Tony Gorez <gorez.tony@gmail.com>
=> tools: align update-ada.sh with other scripts

doc/contributing/collaborator-guide.md
=> doc: fix grammar in the collaborator guide

.github/workflows/tools.yml
Refs: https://github.com/nodejs/node/issues/47326
Mistake in update nghttp2 path
=> tools: fix typo in nghttp2 path

.github/workflows/close-stale-feature-requests.yml, .github/workflows/close-stalled.yml
=> build: update stale action from v7 to v8

benchmark/_http-benchmarkers.js
Location of `writing-and-running-benchmarks.md` is `doc/contributing` (not benchmark).
=> benchmark: fix invalid requirementsURL

README.md
@MoLow has been doing great work and is to join the TSC.
Refs: https://github.com/nodejs/TSC/issues/1364
=> doc: add MoLow to the TSC

doc/api/webcrypto.md
=> doc: fix typo in webcrypto metadata

doc/api/wasi.md
This should fix the linter error on `main`.
=> doc: fix lint error in `wasi.md`

test/js-native-api/test_number/binding.gyp, test/js-native-api/test_number/test_null.c, test/js-native-api/test_number/test_null.h, test/js-native-api/test_number/test_null.js, test/js-native-api/test_number/test_number.c
=> node-api: test passing NULL to number APIs

test/js-native-api/test_constructor/binding.gyp, test/js-native-api/test_constructor/test_constructor.c, test/js-native-api/test_constructor/test_null.c, test/js-native-api/test_constructor/test_null.h, test/js-native-api/test_constructor/test_null.js
=> node-api: test passing NULL to napi_define_class

doc/api/dns.md, lib/dns.js, lib/internal/dns/promises.js, lib/internal/dns/utils.js, test/internet/test-dns-getDefaultResultOrder.js
Fixes: https://github.com/nodejs/node/issues/46919
=> dns: expose getDefaultResultOrder

doc/contributing/sharing-project-news.md
=> doc: add link to news for Node.js core

README.md
=> doc: move BethGriggs to regular member

.github/CODEOWNERS
=> meta: ping nodejs/startup for startup test changes

BUILDING.md
Remove EOL release lines and add missing supported release lines.
=> doc: update BUILDING.md previous versions links

doc/api/cli.md
=> doc: add stability experimental to pm

BUILDING.md
Refs: https://github.com/nodejs/build/issues/3134
=> doc: update supported version of FreeBSD to 12.4

lib/internal/crypto/pbkdf2.js
This partially addresses:
https://github.com/nodejs/node/blob/af9b48a2f17b11b66a8b81beeaba3c408b863795/lib/internal/crypto/util.js#L77-L80
=> crypto: remove default encoding from pbkdf2

test/parallel/test-webcrypto-export-import-cfrg.js
Refs: #47864
cc @tniessen @fhanau
=> test: use appropriate usages for a negative import test

src/crypto/crypto_x509.cc
Refs: https://github.com/nodejs/node/pull/39809
Refs: https://github.com/nodejs/node/pull/40239
=> src: register ext reference for Fingerprint512

lib/internal/crypto/scrypt.js
=> crypto: remove default encoding from scrypt

.github/workflows/tools.yml
Sync with other files updated in dca352a9b6acb.
=> meta: bump actions/setup-python from 4.5.0 to 4.6.0

.github/workflows/scorecard.yml
=> meta: bump github/codeql-action from 2.3.2 to 2.3.3

.github/workflows/scorecard.yml
=> meta: bump step-security/harden-runner from 2.3.1 to 2.4.0

doc/api/permissions.md
These limitations are not specific to the file system, so they should not be listed in the "File System Permissions" section.
=> doc: add heading for permission model limitations

lib/internal/crypto/cipher.js
This partially addresses:
https://github.com/nodejs/node/blob/af9b48a2f17b11b66a8b81beeaba3c408b863795/lib/internal/crypto/util.js#L77-L80
=> crypto: remove default encoding from cipher

doc/api/crypto.md
=> doc: fix typo in crypto legacy streams API section

doc/api/single-executable-applications.md
=> doc: add version info on the SEA docs

README.md
I recently started [contributing](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3AatlowChemi) to the node project. I am looking forward to getting more involved in the node project, and one day becoming a collaborator 🙏🏽 
I have read node's [code of conduct](https://github.com/nodejs/admin/blob/HEAD/CODE_OF_CONDUCT.md), and I will adhere to it
=> doc: add atlowChemi to triagers

tools/v8_gypfiles/v8.gyp
Avoid repetition by defining a new GYP target.
=> tools: refactor v8_pch config

doc/abi_version_registry.json
This PR reserves NMV 117 for Electron 26
=> doc: reserve 117 for Electron 26

CHANGELOG.md
=> doc: mark Node.js 19 as End-of-Life

doc/api/events.md
=> doc: fix typo in events.md

doc/api/inspector.md
=> doc: improve inspector.close() description

doc/contributing/releases.md
=> doc: mention git node release prepare

SECURITY.md
Refs: https://github.com/nodejs-private/node-private/issues/420
=> doc: include experimental features assessment

test/parallel/test-whatwg-url-custom-searchparams.js
/cc @nodejs/url 
Refs: https://github.com/nodejs/node/pull/48891
Refs: https://github.com/nodejs/node/issues/48886
=> url: ensure getter access do not mutate observable symbols

doc/api/n-api.md
=> doc: add ver of 18.x where Node-api 9 is supported

doc/api/http.md
improved requireHostHeader documentation (daje)
=> doc: improve requireHostHeader

test/parallel/test-fs-whatwg-url.js, test/parallel/test-module-create-require.js
=> test: use `fixtures.fileURL` when appropriate

doc/api/readline.md
Detailed description of keystrokes Ctrl-Y and Meta-Y.
=> doc: detailed description of keystrokes Ctrl-Y and Meta-Y

doc/api/policy.md
=> doc: add missing period

test/sequential/test-inspector-open-dispose.mjs
Ref: https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes\=osx11/12543/console, https://github.com/nodejs/reliability/issues/631
=> test: stabilize the inspector-open-dispose test

README.md
Fixes: https://github.com/nodejs/node/issues/49049
=> doc: add rluvaton to collaborators

.github/CODEOWNERS
=> meta: add test/reporters to codeowners

benchmark/esm/esm-loader-import.js, test/es-module/test-esm-dynamic-import-mutating-fs.js, test/es-module/test-esm-dynamic-import-mutating-fs.mjs, test/node-api/test_policy/test_policy.js
Refs: https://github.com/nodejs/node/pull/49040
=> test,benchmark: use `tmpdir.fileURL()`

doc/api/crypto.md
Compromised algorithms will never again be recommended, so remove the qualifier "currently".
=> doc: avoid "not currently recommended"

lib/fs.js
Refs: https://github.com/nodejs/node/blob/main/doc/api/fs.md#fsopenasblobpath-options
=> fs: add the options param description in openAsBlob()

.github/workflows/close-stale-feature-requests.yml
Feature requests are issues, not PRs.
=> tools: configure never-stale label correctly

doc/api/module.md
Refs: https://github.com/nodejs/node/pull/48842
Refs: https://github.com/nodejs/node/pull/47999
=> doc: update outdated history info

doc/api/process.md
doc: updated documentation for `node:process` `warning`
Refs: https://github.com/nodejs/node/issues/46862
=> doc: update documentation for node:process warning

src/node.cc
To prepare for https://chromium-review.googlesource.com/c/v8/v8/+/4839486
=> src: set --rehash-snapshot explicitly

tools/dep_updaters/update-uvwasi.sh
- fix uvwasi updater to update the right dep in the documentation for maintaining dependencies.
=> tools: fix uvwasi updater

test/es-module/test-vm-contextified-script-leak.js
Similar to the test-vm-source-text-module-leak fix, use a snapshot to force a thorough GC in order to prevent false positives.
Refs: https://github.com/nodejs/reliability/issues/669
=> test: deflake test-vm-contextified-script-leak

doc/changelogs/CHANGELOG_V20.md
Jest users might need additional changes (probably https://github.com/nodejs/node/pull/49950) to unblock upgrade from v16.
=> doc: update CHANGELOG_V20 about vm fixes

README.md
This updates my pronouns which have been out of date for quite some time. Apologies for the tiny PR, but feels important for me personally <3
=> doc: update Collaborator pronouns

lib/internal/vm.js, test/es-module/test-vm-compile-function-lineoffset.js
Fixes: https://github.com/nodejs/node/issues/49848
=> lib: fix compileFunction throws range error for negative numbers

lib/internal/vm/module.js
Refs: https://github.com/nodejs/node/pull/38434#issuecomment-832299506
=> vm: freeze `dependencySpecifiers` array

doc/contributing/releases.md
=> doc: add command to get patch minors and majors

doc/api/permissions.md
Following-up https://github.com/nodejs/node/pull/48890#pullrequestreview-1580589455
=> doc: mention files read before env setup

doc/contributing/security-release-process.md
Refs: https://github.com/nodejs-private/node-private/issues/485
=> doc: update release-stewards with last sec-release

README.md
Fixes https://github.com/nodejs/node/pull/50217#discussion_r1362638697
=> doc: fix H4ad collaborator sort

doc/api/dgram.md
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this project and the contribution
are public and …
=> doc: fix typo in dgram docs

test/sequential/sequential.status
Ref: https://github.com/nodejs/node/issues/49630
cc @nodejs/single-executable
=> test: set sea snapshot tests as flaky

lib/internal/streams/writable.js
=> stream: simplify prefinish

.github/workflows/comment-labeled.yml
=> meta: mention other notable changes section

benchmark/streams/readable-from.js
I'm planning to improve the from perf...
=> benchmark: add more cases to Readable.from

doc/contributing/releases.md
Fixes: https://github.com/nodejs/node/issues/50368
=> doc: fixed 7.1 anchor in releases.md's toc

test/parallel/test-fs-timestamp-parsing-error.js
=> test: replace forEach with for [...] of

test/parallel/test-http2-single-headers.js
Replace forEach() with for ... of in test-http2-single-headers.js.
=> test: replace forEach() with for ... of in test-http2-single-headers.js

README.md
This is the only entry with double space, let's align it with the other ones.
=> meta: fix spacing in collaborator list

test/parallel/test-readline-keys.js
=> test: replace forEach() with for ... of in test-readline-keys.js

test/parallel/test-async-wrap-constructor.js
- replace `forEach()` with `for .. of` loop in `test-async-wrap-constructor.js`
=> Replace forEach() with for .. of

.github/CODEOWNERS
Self explanatory title.
cc @nodejs/web-standards
=> meta: add web-standards as WPTs owner

src/js_native_api_v8.cc, src/js_native_api_v8.h, src/node_api.cc
* Create macro for checking new string arguments.
* Create macro for combining env check and inside-gc check.
=> node-api: factor out common code into macros

deps/base64/unofficial.gni
https://github.com/nodejs/node/pull/50629 was merged right after we merged GN files.
/cc @lpinca
=> build: fix GN configuration for deps/base64

test/parallel/test-webcrypto-sign-verify-ecdsa.js
=> test: replace forEach to for at test-webcrypto-sign-verify-ecdsa.js

doc/abi_version_registry.json
This PR reserves NMV 121 for Electron 29.
=> doc: reserve 121 for Electron 29

lib/diagnostics_channel.js
Use validateFunction to remove duplicate implementation.
=> lib: refactor to use validateFunction in diagnostics_channel

doc/contributing/maintaining/maintaining-dependencies.md
=> doc: fix simdjson wrong link

doc/api/crypto.md
=> doc: remove ambiguous 'considered'

.github/workflows/build-tarball.yml, .github/workflows/daily-wpt-fyi.yml, .github/workflows/doc.yml, .github/workflows/scorecard.yml
Refs: https://github.com/actions/upload-artifact/releases/tag/v4.0.0
Refs: https://github.com/actions/download-artifact/releases/tag/v4.1.0
=> meta: update artifact actions to v4

test/parallel/test-webcrypto-export-import-ec.js
test: replace forEach with for-of in test-webcrypto-export-import-ec
@marco-ippolito
=> test: replace forEach with for-of in test-webcrypto-export-import-ec

test/parallel/test-stream2-transform.js
=> test: replace foreach with for of

README.md, doc/contributing/strategic-initiatives.md
=> meta: move RaisinTen to emeritus and remove from strategic initiatives

doc/api/module.md
=> doc: fix spelling mistake

doc/api/net.md
Ref https://github.com/nodejs/node/pull/51045/files/159f874f1f01529510754c1124523cd8ba7dcb8e#r1452516815
=> doc: fix type of connectionAttempt parameter

test/internet/test-inspector-help-page.js
The webpage at the URL referenced by `node --inspect` was retitled when it was recently moved.
Update the test to match the new title "Debugging Node.js" (formerly "Debugging Guide").
Refs: https://github.com/nodejs/nodejs.org/pull/6265
---
Internet tests are not run on regular PR CI's -- they are run daily both on:
- Jenkins, as part of the `node-daily-*` CI jobs
- GitHub Actions, via the [Test internet workflow](https://github.com/nodejs/node/actions/workflows/test-internet.yml).
Without this PR, the [test currently fails](https://github.com/nodejs/node/actions/runs/7807973917/job/21297377230#step:6:92):
```console
=== release test-inspector-help-page ===
Path: internet/test-inspector-help-page
node:assert:1035
throw err;
^
AssertionError [ERR_ASSERTION]: The input did not match the …
```
=> test: fix `internet/test-inspector-help-page`

doc/contributing/security-release-process.md
Refs: https://github.com/nodejs-private/node-private/issues/514
=> doc: add entry to stewards

doc/api/single-executable-applications.md
The design is relatively stable now and it's more suitable to describe it as being "in active developement".
=> sea: update stability index

test/parallel/test-zlib-brotli-16GB.js
Ref: https://github.com/nodejs/node/issues/51772#issuecomment-1950284879
=> test: increase platform timeout zlib-brotli-16gb

doc/contributing/releases.md
=> doc: add mention to GPG_TTY

test/parallel/parallel.status
Refs: https://github.com/nodejs/node/issues/31727#issuecomment-985589968
=> test: remove test-fs-stat-bigint flaky designation

doc/contributing/sharing-project-news.md
Ref: https://github.com/nodejs/abi-stable-node/issues/446#issuecomment-1963630103
=> doc: update node-api/node-addon-api team link to sharing project news

doc/api/deprecations.md, doc/api/fs.md
Refs: https://github.com/nodejs/node/pull/51681
More reference: https://github.com/nodejs/node/pull/51681#issuecomment-1963048465
=> doc: doc-deprecate fs.Stats public constructor

benchmark/util/style-text.js
As titled. It seems doable to add a benchmark for it as it can be a hot-path for end-users.
=> benchmark: add style-text benchmark

README.md
=> doc: mention NodeSource in RafaelGSS steward list

tools/dep_updaters/update-gyp-next.sh
remove unnecessary .github folder
=> tools: remove gyp-next .github folder

benchmark/path/toNamespacedPath-posix.js, benchmark/path/toNamespacedPath-win32.js
Attempt to support https://github.com/nodejs/node/pull/52135
=> benchmark: add toNamespacedPath bench

doc/contributing/api-documentation.md
=> doc: add missing space

doc/contributing/security-release-process.md
Part of security release process.
=> doc: add Rafael to sec release stewards

doc/api/cli.md
=> doc: fix typo in cli.md

doc/abi_version_registry.json
This PR reserves NMV 125 for Electron 31.
=> doc: reserve 125 for Electron 31

src/node_revert.h
=> src: update branch name in node_revert.h

BUILDING.md
=> doc: remove Internet Explorer mention in BUILDING.md

lib/test/reporters.js
Fixes: https://github.com/nodejs/node/issues/52385
Ref: https://github.com/nodejs/node/pull/49184
=> test_runner: expose lcov reporter as newable function

tools/osx-entitlements.plist
=> tools: fix heading spaces for osx-entitlements.plist

doc/contributing/feature-request-management.md
Refs: https://github.com/nodejs/remark-preset-lint-node/pull/535
=> doc: fix issue detected in markdown lint update

tools/lint-md/lint-md.mjs, tools/lint-md/package-lock.json, tools/lint-md/package.json
remark-preset-lint-node@5.0.2
rollup@4.14.3
I know we have tooling that does this once a week or whatever, but I'm eager to get the new remark-preset-lint-node deployed. It shouldn't have any breaking changes, but there were a lot of dependency updates,  so I want to make sure CI doesn't hold any surprises.
=> tools: update lint-md-dependencies

README.md
(Fixes #52504's merge conflicts)
> My motivation is to help give back to the NodeJS community, the same way that NodeJS has helped me, and all JS devs throughout the world.
CC previous participants:
CC @lpinca 
CC @gireeshpunathil 
CC @benjamingr
=> doc: add RedYetiDev to triage team

.github/workflows/license-builder.yml, .github/workflows/tools.yml, .github/workflows/update-v8.yml
Refs: https://github.com/gr2m/create-or-update-pull-request-action/releases/tag/v1.9.4
=> tools: update `gr2m/create-or-update-pull-request-action`

test/parallel/test-http-client-default-headers-exist.js
- Updated `forEach` to `for ... of` in `test-http-client-default-headers-exist.js` file
=> test: updated for each to for of in test file

README.md
Refs: https://github.com/nodejs/TSC/issues/1550
cc/ @marco-ippolito
=> doc: add Marco Ippolito to TSC

SECURITY.md
=> doc: fix minor grammar and style issues in SECURITY.md

doc/abi_version_registry.json
This PR reserves NMV 128 for Electron 32.
=> doc: reserve 128 for Electron 32

benchmark/napi/ref/addon.c
Refs: https://github.com/nodejs/node/pull/53212#issuecomment-2142566866
=> benchmark: fix napi/ref addon

doc/node.1
Our community communication channels come and go, whether that's Freenode or Libera or Slack or whatever other community channels there were at some point, and I simply do not believe that folks regularly see this information at the end of the `man` page and benefit from it more than from going to our GitHub repository or website (both of which contain references to GitHub, discussions, issues, IRC, Slack, ...).
More importantly, if someone looks at the `man` page of an outdated version of the Node.js, this way they won't be directed at a potentially outdated or non-existing resource. (Assuming GitHub is here to stay.)
=> doc: remove IRC from man page

doc/api/cli.md, doc/api/test.md
Spelling fix for two words inside the API documentation.
=> doc: API doc typo fixes

Makefile
Also enable running `make corepack-update` when `node`/`npm` is not available globally.
=> tools: do not run Corepack code before it's reviewed

.github/workflows/tools.yml
Fixes a small typo in the workflow for dependency updates.
=> meta: fix typo in dependency updates

doc/api/test.md
This PR documents the addition of the `testSkipPatterns` option.
=> doc: document `testSkipPatterns` testing option

lib/internal/perf/usertiming.js, test/parallel/test-performance-measure-detail.js
Refs: https://github.com/nodejs/node/issues/53570
=> lib: add toJSON to PerformanceMeasure

doc/contributing/sharing-project-news.md
=> doc: add issue for news from ambassadors

doc/contributing/sharing-project-news.md
=> doc: remove some news issues that are no longer

test/parallel/parallel.status
There was a commit that got merged that should have fixed the issue
ref: https://github.com/nodejs/node/issues/50222#issuecomment-1962680957
CC 
@mhdawson
@richardlau
=> test: un-set inspector-async-hook-setup-at-inspect-brk as flaky

doc/contributing/security-release-process.md
Refs: https://github.com/nodejs-private/security-release/pull/29
=> doc: add Rafael to the last security release

.mailmap, README.md
Changes my email to personal one.
=> meta: change email of @anonrig

test/fixtures/wpt/README.md, test/fixtures/wpt/url/resources/toascii.json, test/fixtures/wpt/versions.json
=> test: update wpt test for url

README.md
It's been a great run but I simply don't have time anymore.
So long, and Thanks for All the Packages
=> doc: move MylesBorins to emeritus

README.md
=> meta: move anonrig to tsc voting members

README.md
=> doc: add MattiasBuelens to collaborators

tools/bootstrap/README.md
This PR replaces 'this script' with 'boxstarter'.
=> doc: update boxstarter README

test/fixtures/spawn-worker-with-copied-env.js
Similar to SmartOS, IBM i does not return the process.title
Fixes: https://github.com/nodejs/node/issues/53852
CC
@richardlau
=> test: skip --title check on IBM i

README.md
Fixes: https://github.com/nodejs/node/issues/53777
=> meta: add jake to collaborators

README.md
=> meta: move tsc member to emeritus

README.md
=> doc: move GeoffreyBooth to TSC regular member

test/parallel/test-timers-immediate-queue.js
The `console.log` is redundant here as we have an assertion on line 55:
```
assert.strictEqual(hit, QUEUE);
```
That checks `hit` is `10`.
=> test: remove unnecessary console log

.github/label-pr-config.yml
=> meta: add sqlite to js subsystems

lib/internal/test_runner/runner.js
Switched to using internal interface after
=> test_runner: switched to internal readline interface

doc/contributing/diagnostic-tooling-support-tiers.md
=> doc: fix typo in diagnostic tooling support tiers document

typings/globals.d.ts, typings/internalBinding/fs_dir.d.ts
Applied a lint: Removed an unused import and changed it to single quotation.
=> typings: apply lint

README.md
Extracted from https://github.com/nodejs/node/pull/53901.
=> doc: update list of Triagers on the `README.md`

test/parallel/test-pipe-file-to-http.js
=> test: fix timeout not being cleared

typings/internalBinding/util.d.ts
=> typings: add util.styleText type definition

benchmark/fs/bench-chownSync.js, benchmark/fs/bench-linkSync.js, benchmark/fs/bench-readlinkSync.js, benchmark/fs/bench-readvSync.js, benchmark/fs/bench-renameSync.js, benchmark/fs/bench-symlinkSync.js, benchmark/fs/bench-writevSync.js, benchmark/fs/read-stream-throughput.js
Follow up https://github.com/nodejs/node/pull/54176
=> benchmark: change assert() to assert.ok()

.github/CODEOWNERS
=> meta: add test-permission-* CODEOWNERS

tools/msvs/find_python.cmd
This helps a lot pyenv users on windows. (like myself)
=> tools: add find pyenv path on windows

benchmark/url/url-searchparams-update.js
Cherry-picked from https://github.com/nodejs/node/pull/54333
=> benchmark: use assert.ok searchparams

README.md
=> doc: replace v19 mention in Current release

README.md
Let me be the first one to add `Support me` link to the readme.
Ref: https://github.com/nodejs/node/blob/4f14eb15454b9f6ae7f0145947debd2c79a2a84f/doc/contributing/recognizing-contributors.md?plain=1#L23
cc @nodejs/tsc fyi
=> doc: add support me link for anonrig

lib/internal/crypto/util.js
=> crypto: remove unused `kHashTypes` internal

node.gyp
Refs: https://github.com/nodejs/node/issues/54736
=> build: turn off -Wrestrict

lib/sys.js
I was about to remove this module and luckily I found #49520 before that. So, I think adding this note might prevent this year after year :)
=> lib: add note about removing sys module

benchmark/diagnostics_channel/publish.js
=> benchmark: enhance dc publish benchmark

README.md
=> doc: add support link for marco-ippolito

doc/contributing/recognizing-contributors.md
=> doc: fix typo in recognizing-contributors

README.md
=> doc: add support link for mcollina

test/parallel/test-esm-loader-hooks-inspect-wait.js
Refs: https://github.com/nodejs/node/pull/51560
=> test: reduce test-esm-loader-hooks-inspect-wait flakiness

test/parallel/test-dns.js
Prevent responses from being cached.
Fixes: https://github.com/nodejs/node/issues/54124
=> test: deflake test-dns

benchmark/module/module-loader.js
=> benchmark: --no-warnings to avoid DEP/ExpWarn log

benchmark/fs/readFileSync.js, benchmark/fs/readfile.js
=> benchmark: include ascii to fs/readfile

lib/internal/modules/run_main.js
`getCWDURL` is already imported at the beginning of the file.
=> module: remove duplicated import

.github/workflows/linters.yml
Fixes: https://github.com/nodejs/node/pull/53901#issuecomment-2375174421
=> tools: only check teams on the default branch

benchmark/permission/permission-processhas-fs-read.js
=> benchmark: add no-warnings to process.has bench

.mailmap
Refs: https://github.com/nodejs/node/pull/55167#issuecomment-2382467842
=> meta: add mailmap entry for abmusse

doc/api/fs.md
All other stability statuses use `-`, this one uses `–`. This PR removes the inconsistency.
=> doc: use correct dash in stability status

.github/workflows/coverage-linux-without-intl.yml, .github/workflows/coverage-linux.yml, .github/workflows/coverage-windows.yml
Refs: https://github.com/nodejs/node/pull/55179#issuecomment-2383627350
=> build: include `.nycrc` in coverage workflows

.github/workflows/notify-on-review-wanted.yml
=> build: fix notify-on-review-wanted action

README.md
Fixes: https://github.com/nodejs/node/issues/55053
=> doc: add pmarchini to collaborators

doc/abi_version_registry.json
This PR reserves NMV 132 for Electron 34
=> doc: reserve 132 for Electron 34

doc/contributing/advocacy-ambasador-program.md
=> doc: fix ambasador markdown list

lib/dns.js, test/parallel/test-dns-default-order-verbatim.js
Fixes: https://github.com/nodejs/node/issues/55391
=> dns: honor the order option

doc/api/url.md
Fixes: https://github.com/nodejs/node/issues/55806
Refs: https://github.com/nodejs/node/pull/11236
Refs: https://github.com/nodejs/node/pull/17365
=> doc: fix history info for `URL.prototype.toJSON`

doc/contributing/releases.md
Refs: https://github.com/nodejs/changelog-maker/pull/167 & https://github.com/nodejs-private/security-release/issues/38
=> doc: add notable-change mention to sec release

README.md
For the foreseeable future, I will be focusing my efforts solely on the website and improving the documentation generator. I believe that I have a greater, and more helpful, impact there than I do here.
Thank you for the opportunity.
=> meta: remove @RedYetiDev from issue triage

.github/workflows/update-wpt.yml
Update the workflow to support subsystems that contains non alphanumeric char. Remove the Jenkins token as it is unused. Update external actions.
=> tools: update WPT updater

.github/CODEOWNERS
=> meta: add releasers as CODEOWNERS to proposal action

eslint.config.mjs
Refs: https://github.com/nodejs/node/pull/55618#issuecomment-2464222278
=> tools: enable linter for `tools/icu/**`

SECURITY.md
=> doc: update blog link to /vulnerability

.github/workflows/tools.yml
This reverts commit a492646ff1ec5ee14d31bb977de01abc3779ada5.
Refs: https://github.com/nodejs/node/commit/d6175b35ad3ad5c8bf0a
Refs: https://github.com/nodejs/node/commit/f97865fab436fba24b46
=> Revert "tools: disable automated libuv updates"

BUILDING.md
=> doc: fix winget config path

test/parallel/test-permission-sqlite-load-extension.js, test/sqlite/test-sqlite-extensions.mjs
=> test: use --permission over --experimental-permission

.github/workflows/lint-release-proposal.yml
Enables updating placeholders in documents
#56249
=> tools: add REPLACEME check to workflow

doc/eslint.config_partial.mjs
Refs: https://github.com/nodejs/node/pull/56185
=> tools: fix `node:` enforcement for docs

doc/api/util.md
This PR upgrades util.styleText from 1.1 (Active Development) to 2 (Stable)
=> doc: stabilize util.styleText

test/parallel/test-permission-sqlite-load-extension.js
Necessary for https://github.com/nodejs/node/pull/48409
=> test: make `test-permission-sqlite-load-extension` more robust

tools/actions/create-release.sh
I had to add it manually in https://github.com/nodejs/node/pull/56310#event-15708312401, let's have the automation do it for us.
=> tools: add release line label when opening release proposal

test/parallel/parallel.status
Refs: https://github.com/nodejs/node/pull/55006
Refs: https://github.com/nodejs/node/issues/54807#issuecomment-2550896871
=> test: remove test-runner-watch-mode-complex flaky designation

test/parallel/parallel.status
Fixes: https://github.com/nodejs/node/issues/54811
Refs: https://github.com/nodejs/node/issues/54811#issuecomment-2334463112
=> test: remove test-macos-app-sandbox flaky designation

doc/api/cli.md, doc/api/deprecations.md
=> doc: fix faulty YAML metadata

doc/contributing/security-release-process.md
Refs: https://github.com/nodejs/security-wg/issues/1401
cc: @nodejs/security-release
=> doc: include CVE to EOL lines as sec release process

doc/contributing/advocacy-ambassador-program.md
=> doc: tweak info on reposts in ambassador program

doc/api/permissions.md
=> doc: add history info for Permission Model

README.md
=> doc: move anatoli to emeritus

test/parallel/parallel.status
Refs: https://github.com/nodejs/node/issues/56794
=> test: set `test-fs-cp` as flaky

.github/workflows/build-tarball.yml, .github/workflows/coverage-linux-without-intl.yml, .github/workflows/coverage-linux.yml, .github/workflows/test-asan.yml, .github/workflows/test-linux.yml, .github/workflows/test-macos.yml, .github/workflows/test-ubsan.yml
Respectively to v0.9.1 and v0.0.7.
=> tools: update sccache and sccache-action

node.gyp
Handle cases where the path to the Python executable contains spaces.
Refs: https://github.com/nodejs/node/pull/56791
=> build: add double quotes around <(python)

doc/api/cli.md, doc/api/module.md
Backport of https://github.com/nodejs/node/pull/56706
=> [22.x backport] doc: add note for features using `InternalWorker` with permission model

src/node_os.cc
=> src: improve error handling in node_os by removing ToLocalChecked

.github/workflows/update-wpt.yml
=> test: automatically sync wpt urlpattern tests

.mailmap, README.md
Also adds current work email to mailmap.
Caught this in the latest release proposal (https://github.com/nodejs/node/pull/57005).
=> meta: update last name for jkrems

doc/api/buffer.md
=> doc: buffer: fix typo on `Buffer.copyBytesFrom(` `offset` option

.github/workflows/major-release.yml
Prevent issues like https://github.com/Trott/io.js/issues/8 from opening on forks like that.
=> tools: do not run major-release workflow on forks

doc/api/modules.md
=> doc: fix wrong verb form

benchmark/fs/bench-openSync.js
@RafaelGSS could you review this PR? thx
=> benchmark: add a warmup on bench-openSync

BUILDING.md
=> doc: update Xcode version used for arm64 and pkg

.github/CODEOWNERS
=> meta: add CODEOWNERS for SQLite

doc/api/fs.md
Add clarification based on discussion with security researcher.
=> doc: add additional caveat for fs.watch

doc/abi_version_registry.json
Reserving NMV 135 for Electron 36.
=> doc: reserve NMV 135 for Electron 36

test/parallel/test-without-async-context-frame.mjs
Allows Electron to run this suite as part of its smoke tests - otherwise we see these errors:
<details><summary>Details</summary>
<p>
```
ValueError: Could not find executable. Should be out/Release/node
Traceback (most recent call last):
File "/Users/codebytere/Developer/electron-gn/src/third_party/electron_node/tools/test.py", line 1831, in <module>
sys.exit(Main())
File "/Users/codebytere/Developer/electron-gn/src/third_party/electron_node/tools/test.py", line 1698, in Main
vm = context.GetVm(arch, mode)
File "/Users/codebytere/Developer/electron-gn/src/third_party/electron_node/tools/test.py", line 978, in GetVm
raise ValueError('Could not find executable. Should be ' + name)
ValueError: Could not find executable. Should be out/Release/node
Traceback (most recent call last):
File …
```
=> test: allow embedder running async context frame test

README.md
My motivation is to help give back to the NodeJS community, the same way that NodeJS has helped me, and all JS devs throughout the world. (like RedYetiDev 👀 )
Without Node.js, I wouldn't have become a programmer.
I recently started [contributing](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3A1ilsang) to the node project.
I have read node's [code of conduct](https://github.com/nodejs/admin/blob/HEAD/CODE_OF_CONDUCT.md), and I will adhere to it
Thank you!
=> doc: add 1ilsang to triage team

.github/CODEOWNERS
If you are interested in joining @nodejs/config please add yourself to the team.
@anonrig if you see files missing please commit into
=> meta: set nodejs/config as codeowner

test/fixtures/wpt/README.md, test/fixtures/wpt/compression/idlharness-shadowrealm.window.js, test/fixtures/wpt/compression/idlharness.https.any.js, test/fixtures/wpt/versions.json
Updates compression web-platform tests
=> test: update compression wpt

src/api/environment.cc, src/node.h
As in title. Similar to other embedder customization in this area, allowing embedders to use their own OOM handling.
=> src: allow embedder customization of `OOMErrorHandler`

README.md, doc/contributing/strategic-initiatives.md
Refs: https://github.com/nodejs/TSC/issues/1690
=> meta: move RaisinTen back to collaborators, triagers and SEA champion

test/parallel/test-tls-connect-abort-controller.js
Following up on @jasnell's recommendation on https://github.com/cloudflare/workerd/pull/3594
=> test: simplify test-tls-connect-abort-controller.js

.github/label-pr-config.yml, .github/workflows/tools.yml
=> tools: add config subspace

README.md
=> doc: add Darshan back as voting TSC member

onboarding.md
It might be easy to miss this repo. For example, I forgot rewatching this repo when I rejoined. So it would be a good idea to mention this in the collaborator onboarding guide.
=> doc: recommend watching the collaborators repo in the onboarding doc

doc/api/child_process.md
Refs: https://github.com/nodejs/node/pull/57389
=> doc: remove deprecated pattern in `child_process.md`

doc/api/child_process.md
I forgot to do that in the original PR
Refs: https://github.com/nodejs/node/pull/57389
=> doc: add history entry for DEP0190 in `child_process.md`

test/parallel/test-sqlite-statement-sync.js, tools/eslint/package-lock.json
Not sure why Dependabot is not picking it up 🤷‍♂️
=> tools: update ESLint to 9.23

.github/workflows/codeql.yml
Refs: https://github.com/nodejs/node/pull/57535
=> tools: add codeql nightly

doc/api/module.md
Reopening of https://github.com/nodejs/node/pull/57875
=> doc: fix typo in `module.md`

doc/api/zlib.md
=> doc: fix typo of file `zlib.md`

README.md
I would like to apply to be a triager for this project.
With the help of the community, I’ve been able to contribute to Node.js in various ways.
Now, I want to give back to the community that has supported me.
I’ll do my best to help more people and, through that, contribute to the growth of our community.
As part of this journey, I will continue to deepen my understanding of Node.js and stay actively involved.
I have read and agree to abide by the Code of Conduct.
=> doc: add HBSPS as triager

doc/api/http.md
=> doc: fix typo of file `http.md`, `outgoingMessage.setTimeout` section

doc/api/test.md
Document the change made in https://github.com/nodejs/node/pull/54548
Fixes: https://github.com/nodejs/node/issues/58301
Refs: https://github.com/nodejs/node/pull/54548
=> doc: document default test-reporter change

doc/contributing/security-release-process.md
=> doc: add latest security release steward

tools/v8_gypfiles/v8.gyp
This was added for AIX but should have included IBM i as well.
=> tools: add missing highway defines for IBM i

typings/globals.d.ts, typings/internalBinding/inspector.d.ts
=> typings: add inspector internalBinding typing

doc/api/diagnostics_channel.md, lib/internal/http2/core.js, test/parallel/test-diagnostics-channel-http2-server-stream-error.js
=> http2: add diagnostics channel 'http2.server.stream.error'

src/node_dotenv.cc
I've changed env_vars to variable for caching and tried to improve local variable coverage
=> src: env_vars caching and local variable scope optimization

README.md
=> doc: add support link for panva

doc/api/module.md
Refs: https://github.com/nodejs/node/pull/56350
=> doc: add history entry for TS support in hooks

doc/abi_version_registry.json
Reserves NMV 139 for Electron 38.
Thanks! 😄
=> doc: reserve NMV 139 for Electron 38

README.md
Fixes: https://github.com/nodejs/node/issues/58766
=> meta: add IlyasShabi to collaborators

.mailmap, README.md
Refs: https://github.com/nodejs/TSC/issues/1699
Refs: https://www.redhat.com/en/blog/evolving-our-middleware-strategy
=> doc: update email address for Richard Lau

README.md
I'd like to join the security release stewards
Fixes: https://github.com/nodejs/TSC/issues/1764
=> meta: add marco-ippolito to security release stewards

README.md
=> doc: add sponsorship link to RafaelGSS

doc/api/cli.md
For context: https://github.com/nodejs/node/pull/58719#issuecomment-3049879179
=> doc: add stability index to the `--watch-kill-signal` flag

doc/api/zlib.md
Removed unused import `process` form example.
=> docs: zlib: rm unused process from example

doc/contributing/security-release-process.md
=> doc: add RafaelGSS as steward July 25

doc/contributing/writing-tests.md
Corrects the misspelling of "optimial" to "optimal".
=> doc: fix typo in writing-test.md

README.md
Fixes: https://github.com/nodejs/node/issues/59064
=> doc: add Aditi-1400 to collaborators

benchmark/_cli.js
=> benchmark: small lint fix on _cli.js

src/stream_pipe.cc
Fixes: https://github.com/nodejs/node/issues/57612
Do it like here:
https://github.com/nodejs/node/blob/b4280ef72c9a05aef118406c23fd90dc4a237510/src/stream_base.cc#L628
https://github.com/nodejs/node/blob/b4280ef72c9a05aef118406c23fd90dc4a237510/src/node_http_parser.cc#L717
https://github.com/nodejs/node/blob/b4280ef72c9a05aef118406c23fd90dc4a237510/src/crypto/crypto_tls.cc#L545
=> src: add nullptr checks in `StreamPipe::New`

lib/internal/locks.js
Those were missed in https://github.com/nodejs/node/pull/58666, it shouldn't have much runtime effect, it's mainly to make the code more consistent with the rest of the codebase.
=> worker: implements nits in Web Locks code

.github/CODEOWNERS
=> meta: add nodejs/path to path files

src/node_modules.cc
=> src: use simdjson::pad

doc/api/process.md
Fixes: https://github.com/nodejs/node/issues/59508
References: https://simple.wikipedia.org/wiki/Kilobyte
=> doc: clarify maxRSS unit in `process.resourceUsage()`

doc/api/cli.md
The changelog was added in a separate PR, so it needs manual updating on v22.x after the backport
Refs: https://github.com/nodejs/node/pull/57432
=> [v22.x] doc: update --use-system-ca changelog on 22.x

tools/actions/review_backport.sh
It's quite limited but better than nothing
=> tools: add script to make reviewing backport PRs easier

doc/abi_version_registry.json
Reserving NMV 140 for Electron 39.
=> doc: reserve NMV 140 for Electron 39

doc/api/quic.md
=> doc: fix quic session instance typo

src/node_sqlite.cc
Refs: https://github.com/v8/v8/commit/5e139e98d1e4d8bbcccf7b15cd8e7d08b28e4a81
=> src: use non-deprecated Get/SetPrototype methods

.github/workflows/build-tarball.yml
Refs: https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size
=> tools: do not attempt to compress tgz archive

src/node_messaging.cc
=> src: fixup node_messaging error handling

test/parallel/test-inspector-network-websocket.js
In undici this tests fails if undici is used as shared-library
@mcollina 
@KhafraDev
=> fix: undici as shared-library should pass test-inspector-network-websocket.js test

README.md
I won't have enough time to contribute to Node.js to stay as a TSC member for a while so moving myself to emeritus.
=> meta: move Michael to emeritus

BUILDING.md
Refs: https://github.com/nodejs/build/issues/4083
=> doc: update macOS version used to build releases

lib/internal/quic/quic.js, lib/internal/quic/symbols.js, lib/quic.js, test/parallel/test-quic-exports.mjs, test/parallel/test-quic-handshake-ipv6-only.mjs, test/parallel/test-quic-internal-endpoint-listen-defaults.mjs, test/parallel/test-quic-internal-endpoint-stats-state.mjs
Re: https://github.com/nodejs/node/issues/60122
=> quic: continue working on quic api bits
