nodejs/node

lib/internal/v8/startup_snapshot.js
test/parallel/test-snapshot-argv1.js

In applications with entry points deserialized from snapshots, they don't need an additional CLI argument for the entry point script so process.argv[1] is going to be other user-defiend arguments. We could consider copying process.argv[0] as process.argv[1] like what we do for single executable applications, but for now just don't exapnd it so it's easier to backport to previous releases.

bootstrap: do not expand process.argv[1] for snapshot entry points

---

test/parallel/test-wrap-js-stream-exceptions.js

Non used variables were removed from stream-exception test

test: unused callback variables removed

---

test/parallel/parallel.status

a mitigation for https://github.com/nodejs/node/issues/47420

test: mark test/parallel/test-file-write-stream4 as flaky

---

lib/internal/main/mksnapshot.js
test/parallel/test-snapshot-namespaced-builtin.js

This enables e.g. `require('node:fs')` in the snapshot scripts (which is done by our doc example, but didn't actually work without this patch).

bootstrap: support namespaced builtins in snapshot scripts

---

.mailmap

This will make `git log` entries for KhafraDev show up using the name in the README, which is required so that find-inactive-collaborators.mjs doesn't incorrectly flag him for removal.

meta: add mailmap entry for KhafraDev

---

doc/api/util.md

This is a small fix for my recent PR that fixes a typo in the realm example.

doc: fix typo in util.types.isNativeError()

---

lib/diagnostics_channel.js
test/parallel/test-diagnostics-channel-pub-sub.js

I discovered a bug in some of the changes I landed with TracingChannel. Technically the bug existed before, but we've been discouraging use of `channel.subscribe(...)` and `channel.unsubscribe(...)`. With the TracingChannel changes I included a fix for the GC issue that allows `channel.subscribe(...)` and `channel.unsubscribe(...)` to work as they were originally intended, and some simplifications were made to make the top-level functions delegate to those. Unfortunately, there was an unnoticed issue where if the subscriber count ever dropped to zero the weakref would be deleted from the channels map but channel objects could still be held and therefore could still have subscribers added which would attempt an incRef on a weakref that's not there anymore. To handle that safely the delete …

diagnostics_channel: fix ref counting bug when reaching zero subscribers

---

.github/workflows/daily-wpt-fyi.yml
.github/workflows/notify-on-push.yml
.github/workflows/update-openssl.yml
deps/openssl/config/Dockerfile

This MR aims to increase the score of OpenSSF by pinning some missing dependencies.
Pinned dependencies:
- actions/checkout
- gr2m/create-or-update-pull-request-action
- ubuntu
To get the `10` score on the **Pinned-Dependencies** scorecard section, some other application dependencies (_npm_ and _pip_) would have to be pinned. But on this, I decided to investigate the correct way to pin them before creating a PR.

tools: add missing pinned dependencies

---

.github/workflows/tools.yml
doc/contributing/maintaining-web-assembly.md
tools/dep_updaters/update-uvwasi.sh

tools: automate uvwasi dependency update

---

benchmark/esm/esm-loader-defaultResolve.js

benchmark: add a benchmark for `defaultResolve`

---

test/sequential/sequential.status
tools/test.py

mitigation for https://github.com/nodejs/node/issues/39655

test: mark test-cluster-primary-error flaky on asan

---

lib/internal/readline/interface.js
test/fixtures/repl-load-multiline-no-trailing-newline.js
test/parallel/test-readline-interface-no-trailing-newline.js
test/parallel/test-repl-load-multiline-no-trailing-newline.js

The logic for reading lines was slightly flawed, in that it assumed there would be a final new line. It handled the case where there are no new lines, but this then broke if there were some new lines.
The fix in logic is basically removing the special case where there are no new lines by changing it to always read the final line with no new lines. This works because if a file contains no new lines, the final line is the first line, and all is well.
There is some subtlety in this functioning, however. If the last line contains no new lines, then `lastIndex` will be the start of the last line, and `kInsertString` will be called from that point. If it does contain a new line, `lastIndex` will be equal to `s.length`, so the slice will be the empty string.
Fixes: …

readline: fix issue with newline-less last line

---

lib/internal/event_target.js
lib/internal/webidl.js
test/parallel/test-bootstrap-modules.js
test/parallel/test-eventtarget.js

This implements a webidl converter for converting a value to a webidl DOMString and uses it in EventTarget.

lib: use webidl DOMString converter in EventTarget

---

src/node_url.cc
test/parallel/test-whatwg-url-canparse.js

Fixes the bug caught by this pull request: https://github.com/nodejs/node/pull/47541
Requesting fast-track to unblock the parent pull request.
cc @nodejs/url

url: handle URL.canParse without base parameter

---

BUILDING.md

Refs: https://github.com/nodejs/node/issues/47067

doc: update darwin-x64 toolchain used for Node.js 20 releases

---

doc/api/esm.md

Adding `setEncoding()` ensures that the example handles characters split across chunk boundaries well.

doc: add missing setEncoding call in ESM example

---

lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/resolve.js

Due to `URL.canParse`, we can avoid try/catch block and have faster validation. The previous implementation was not performant due to:
1. Unnecessary string serialization - We don't need `href`, `origin` etc. for validating if a URL is valid or not.
2. `URL.canParse` can be written with V8 Fast API - enabling more performance out of this pull request.
3. `URL.canParse` does not return anything except a boolean.
cc @nodejs/url

esm: avoid try/catch when validating urls

---

lib/internal/modules/esm/resolve.js

This pull request avoids multiple calls to the `protocol` getter of the URL. Previor to Ada version 2, `url.protocol` was always returned an already allocated string, but right now, it slices a new string for each call. Storing it in a variable and access it, would make some improvement in terms of performance.
cc @nodejs/url

esm: avoid accessing lazy getters for urls

---

src/crypto/crypto_util.cc

`CSPRNG` implicitly casts the `size_t length` argument to a signed `int` when calling `RAND_bytes()`, which leaves it up to the caller to ensure that the `length` argument actually fits into such a signed `int`. However, not all call sites explicitly ensure that, which could lead to subtle bugs.
In OpenSSL 3, use `RAND_bytes_ex()` instead, which does not require casting the `length` to a signed `int`.
In OpenSSL 1.1.1, `RAND_bytes_ex()` is not supported, thus we have to process blocks of size `INT_MAX` one by one.

src: fix CSPRNG when length exceeds INT_MAX

---

src/json_utils.cc

It is slightly better to use `static constexpr std::string_view` compared to `static const std::string_view`. See https://lemire.me/blog/2023/04/12/consider-using-constexpr-static-function-variables-for-performance/ for details.
It is a micro-optimization: you are unlikely to be able to measure the difference, but it should generate less bloat.

src: replace static const string_view by static constexpr

---

lib/internal/test_runner/runner.js
test/fixtures/test-runner/output/spec_reporter_cli.js
test/fixtures/test-runner/output/spec_reporter_cli.snapshot
test/parallel/test-runner-output.mjs

Refs: https://github.com/nodejs/node/pull/47525#issuecomment-1505391077

test_runner: fix spec skip detection

---

src/node_env_var.cc
test/parallel/test-process-env-ignore-getter-setter.js

Tiny commit to fix a missing white space in the error message "\'process.env\' does not accept anaccessor(getter/setter) descriptor".

src: fix typo in process.env accessor error message

---

src/api/environment.cc
src/crypto/crypto_context.cc
src/crypto/crypto_hmac.cc
src/crypto/crypto_random.cc
src/crypto/crypto_sig.cc
src/crypto/crypto_tls.cc
src/node_http2.cc
src/node_os.cc

Simplify existing code by using `v8::Boolean::New()` instead of equivalent expressions that contain ternary operators.

src: use v8::Boolean(b) over b ? True() : False()

---

tsconfig.json

Trailing commas are invalid in JSON files.

typings: fix syntax error in tsconfig

---

deps/v8/include/v8-version.h
deps/v8/infra/mb/mb_config.pyl
deps/v8/infra/testing/builders.pyl
deps/v8/src/builtins/builtins-error.cc
deps/v8/tools/builtins-pgo/profile_only.py
deps/v8/tools/whitespace.txt

Refs: https://github.com/v8/v8/compare/11.3.244.4...11.3.244.8

deps: patch V8 to 11.3.244.8

---

src/crypto/crypto_random.cc

This restriction was due to an implementation detail in `CSPRNG()`. Now that `CSPRNG()` properly handles lengths exceeding `INT_MAX`, remove this artificial restriction.
Refs: https://github.com/nodejs/node/pull/47515

crypto: remove INT_MAX restriction in randomBytes

---

doc/contributing/releases.md

The release-post script now is in a different location and should be called directly with `node`

doc: fix release-post script location

---

lib/internal/test_runner/reporter/spec.js
test/fixtures/test-runner/output/spec_reporter.snapshot
test/fixtures/test-runner/output/spec_reporter_cli.snapshot
test/pseudo-tty/test_runner_default_reporter.out

it is a little distracting that the summary of failures includes both failing tests and their parents

test_runner: avoid reporting parents of failing tests in summary

---

doc/api/permissions.md

This is the only instance of such a link and it is rendered incorrectly in the TOC.

doc: remove markdown link from heading

---

doc/api/test.md
lib/internal/test_runner/test.js
test/fixtures/test-runner/output/hooks.js
test/fixtures/test-runner/output/hooks.snapshot

Execute the before hook for Test as well, and execute it on root before executing any tests.
Fixes: https://github.com/nodejs/node/issues/47518

test_runner: execute before hook on test

---

lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/worker.js
test/es-module/test-esm-loader-hooks.mjs

Calling `process.exit` from the loader used to exit the process, but now that loader code is executed on a different thread, we need to pass the information across thread to avoid leaving the main thread without a loader thread.

esm: propagate `process.exit` from the loader thread to the main thread

---

.github/workflows/tools.yml
tools/dep_updaters/update-zlib.sh

tools: automate zlib update

---

.github/workflows/tools.yml

Example run: https://github.com/nodejs/node-auto-test/actions/runs/4719539591

tools: add option to run workflow with specific tool id

---

.github/workflows/tools.yml
tools/dep_updaters/update-googletest.sh

I haven't done one of these before, so please review carefully.
GoogleTest follows the Abseil Live at Head philosophy, and rarely creates tags or GitHub releases, so instead, follow Google's recommendation and update to the upstream HEAD every once in a while.
The tricky bit is properly updating googletest.gyp, and this script might fail doing so in the future.

tools: add update script for googletest

---

doc/api/cli.md
doc/api/permissions.md

Fix a small grammatical mistake and improve the surrounding wording.

doc: improve fs permissions description

---

lib/fs.js
lib/internal/encoding.js
lib/v8.js
src/aliased_buffer-inl.h
src/aliased_buffer.h
src/encoding_binding.cc
src/encoding_binding.h
src/node_file.cc
src/node_file.h
src/node_realm-inl.h
src/node_realm.h
src/node_v8.cc
src/node_v8.h

src: make AliasedBuffers in the binding data weak
The binding data holds references to the AliasedBuffers directly
from their wrappers which already ensures that the AliasedBuffers
won't be accessed when the wrappers are GC'ed. So we can just
make the global references to the AliasedBuffers weak. This way
we can simply deserialize the typed arrays when deserialize the
binding data and avoid the extra Object::Set() calls. It also
eliminates the caveat in the JS land where aliased buffers must
be dynamically read from the binding.
Refs: https://github.com/nodejs/node/issues/47353
(This doesn't fix https://github.com/nodejs/node/pull/47353, but it makes sense on its own, and at least reduces the number of unnecessary global references...)

src: make AliasedBuffers in the binding data weak

---

doc/api/fs.md
lib/internal/fs/cp/cp-sync.js
lib/internal/fs/cp/cp.js
lib/internal/fs/utils.js
test/parallel/test-fs-cp.mjs

`fs.copyFile()` supports copy-on-write operation if the underlying platform supports it by passing a mode flag. This behavior was added in https://github.com/nodejs/node/commit/a16d88d9e9a6581e463082549823189aba25ca76.
This patch adds `mode` flag to `fs.cp()`, `fs.cpSync()`, and `fsPromises.cp()` to allow to change their behaviors to copy files. This test case is based on the test case that was introduced when we add `fs.constants.COPYFILE_FICLONE`.
https://github.com/nodejs/node/commit/a16d88d9e9a6581e463082549823189aba25ca76.
This test strategy is:
- If the platform supports copy-on-write operation, check whether the destination is expected
- Otherwise, the operation will fail and check whether the failure error information is expected.
Fixes: https://github.com/nodejs/node/issues/47080

fs: `fs.cp()` should accept mode flag to specify the copy behavior

---

doc/api/buffer.md

Actual output is different from expected output if offset is 0.
Plus, removed unused importing `Buffer`.

doc: change offset of example in `Buffer.copyBytesFrom`

---

.github/label-pr-config.yml

- Update paths to the new ones.
- Remove paths that no longer exist.
- Capitalize comments and quote labels mentioned within.
- Fix syntax error in regex.
- Add missing JavaScript subsystems.

tools: update PR label config

---

doc/api/inspector.md

When using `Session`, the object outputed by the console API will not be released.
The example is as follows.
```js
const inspector = require('inspector');
class AAA {
constructor() {
const len = 10000000;
this.memory = new Array(len);
for (let i = 0; i < len; i++) {
this.memory[i] = i;
}
}
};
const session = new inspector.Session();
// comment out this and test again
session.connect();
const heapUsed = process.memoryUsage().heapUsed;
setInterval(() => {
const obj = new AAA();
console.log(obj);
gc();
console.log(process.memoryUsage().heapUsed - heapUsed);
}, 100);
```
node --expose-gc test.js

inspector: add tips for Session

---

doc/api/fs.md
lib/fs.js
lib/internal/fs/dir.js
lib/internal/fs/promises.js
lib/internal/fs/utils.js
test/sequential/test-fs-opendir-recursive.js
test/sequential/test-fs-readdir-recursive.js

Implements a recursive option for the `readdir` and `readdirSync` methods.
Closes: https://github.com/nodejs/node/issues/34992
Ref: https://github.com/nodejs/tooling/issues/130
---
Starting with tests to just get a sense for how things should behave. Will dive into the implementation next. Any feedback/concerns is welcome at any time.

fs: add recursive opendir/readdir

---

tools/dep_updaters/update-root-certs.mjs

When searching for the latest certdata.txt, check that the file exists on the remote server.
Refs: https://github.com/nodejs/node/issues/47597#issuecomment-1512506959

tools: fix updating root certificates

---

doc/api/buffer.md

According to use of `validateNumber`, error code is changed from ERR_INVALID_ARG_VALUE to ERR_OUT_OF_RANGE.
Refs: https://github.com/nodejs/node/pull/45796

doc: update error code of buffer

---

.github/workflows/find-inactive-tsc.yml
.github/workflows/timezone-update.yml
.github/workflows/tools.yml
.github/workflows/update-openssl.yml

Set the `update-pull-request-title-and-body` option when potentially updating an existing PR with a dynamic title and/or description.
Refs: https://github.com/nodejs/node/pull/47482#issuecomment-1514675158

tools: keep PR titles/description up-to-date

---

doc/api/fs.md

Hi as [mentioned](https://github.com/nodejs/node/issues/47633) in the talk, fs.stat watches the symlinks, while fs.lstat looks at the symlinks themselves. For this reason, it is recommended to use fs.lstat in cases where symlinks themselves need to be looked at. Based on this information I added that you should use fs.stat or fs.lstat depending on the type of file
Fixes: https://github.com/nodejs/node/issues/47633

doc,fs: update description of fs.stat() method

---

SECURITY.md

doc: fix typos in SECURITY.md

---

lib/internal/test_runner/harness.js
lib/internal/test_runner/test.js

This commit moves code coverage collection from the test harness exit handler to the `postRun()` function of the root test.
This is necessary preparatory work for supporting code coverage with `--test`. The reason is that `--test` is implemented on top of `run()`, and that function calls the root test's `postRun()` function, which outputs the test summary. This happens before the harness exit handler.

test_runner: move coverage collection to root.postRun()

---

lib/internal/test_runner/coverage.js
test/fixtures/test-runner/coverage.js

This commit updates the code coverage logic to skip the first function in a file (which does not correspond to an actual function) instead of skipping all functions without a name.

test_runner: support coverage of unnamed functions

---

BUILDING.md

doc: fix capitalization of ASan

---

doc/api/cli.md
doc/api/diagnostics_channel.md
doc/api/domain.md
doc/api/inspector.md
doc/api/n-api.md
doc/api/util.md
doc/api/wasi.md
doc/api/worker_threads.md
doc/contributing/adding-v8-fast-api.md
doc/contributing/api-documentation.md
doc/contributing/investigating-native-memory-leaks.md
doc/contributing/maintaining-cjs-module-lexer.md
doc/contributing/maintaining-dependencies.md
doc/contributing/maintaining-types-for-nodejs.md
doc/contributing/releases.md
doc/contributing/writing-and-running-benchmarks.md

doc: fix typos

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/hooks.js
test/fixtures/test-runner/output/name_pattern.js

Fixes: https://github.com/nodejs/node/issues/47643

test_runner: fix nested hooks

---

lib/internal/modules/esm/resolve.js

I couldn't find a benchmark or had the time to write it, but in theory, it should be a lot faster.
cc @nodejs/performance @nodejs/loaders
Refs: https://github.com/nodejs/performance/issues/39

lib: improve esm resolve performance

---

doc/api/http.md
doc/api/net.md
lib/_http_outgoing.js
lib/_http_server.js
lib/http.js
lib/net.js
test/parallel/test-http-server-options-highwatermark.js

Add `highWaterMark` option when creating a new HTTP server.
This option will override the default `(readable|writable)`
`highWaterMark` values on sockets created.
Fixes: https://github.com/nodejs/node/issues/46606

http: add highWaterMark opt in http.createServer

---

doc/api/fs.md

> a `DOMException`. error.
This removes the period between the `DOMException` and the `error`.

doc: fix a typo in `fs.openAsBlob`

---

doc/api/test.md

This is based on my understanding of how it works, but I didn't actually test this or compare it with the implementation, so please review carefully @nodejs/test_runner.
Refs: https://github.com/nodejs/node/issues/47365

doc: clarify concurrency model of test runner

---

tools/dep_updaters/update-cjs-module-lexer.sh

Refs: https://github.com/nodejs/node/pull/47446

tools: fix skip message in update-cjs-module-lexer

---

src/histogram.cc
src/node_messaging.cc

Refs https://chromium-review.googlesource.com/c/v8/v8/+/2718147
Fixes an issue where Node.js tries to call SetClassName on a FunctionTemplate twice in some cases. The above CL made it so that V8 CHECKs when this occurs. It is fixed by ensuring SetClassName is only called once.

src: prevent changing `FunctionTemplateInfo` after publish

---

lib/internal/test_runner/runner.js

The code already checks if `testNamePatterns` is an array, and converts it to an array if it is not.

test_runner: remove no-op validation

---

doc/api/async_hooks.md

`async_hooks` asynchronous content example add `mjs`  code.

doc: async_hooks asynchronous content example add mjs code

---

doc/api/tls.md
lib/_tls_wrap.js
test/parallel/test-tls-add-context.js

Do not call tls.createSecureContext() if the context provided is already an instance of tls.SecureContext.
Fixes: https://github.com/nodejs/node/issues/47408

tls: accept SecureContext object in server.addContext()

---

.github/workflows/update-v8.yml

https://github.com/nodejs/node/actions/runs/4807223999/jobs/8555708692

tools: fix update-v8-patch cache

---

doc/api/permissions.md

doc: fix a typo in `permissions.md`

---

lib/internal/streams/pipeline.js
test/parallel/test-stream-pipeline.js

In the previous implementation 
we had 
https://github.com/nodejs/node/blob/32e478d7c37a0296b2bf616ee2e39e81e4c8d694/lib/internal/streams/pipeline.js#L126
which would have called `resume()` only when the stream ended thus resolving the promise over here
https://github.com/nodejs/node/blob/32e478d7c37a0296b2bf616ee2e39e81e4c8d694/lib/internal/streams/pipeline.js#L143
but for `end: false` eos would never call resume as the stream doesn't end, hence we `wait()` only if the stream is stated to end
Fixes: https://github.com/nodejs/node/issues/47708

stream: prevent pipeline hang with generator functions

---

src/api/environment.cc
src/inspector_agent.cc
src/node.h
src/node_api.cc
src/node_errors.cc
src/node_errors.h
src/node_watchdog.cc

OnFatalError and OOMErrorHandler will not return control flow to the
calling function.
`node::FatalError` is an alias of `node::OnFatalError`. Replace all the
callsites with `node::OnFatalError` instead.

src: mark fatal error functions as noreturn

---

test/parallel/test-runner-concurrency.js

test: remove spaces from test runner test names

---

src/quic/sessionticket.cc

src: fix typo in comment in quic/sessionticket.cc

---

README.md

I want to ensure that software projects that carry my name on them make decisions and maintain a public image that I can genuinely stand behind. I am not expecting my level of involvement in Node.js to change, and that means that I'd rather communicate that fact clearly than give the impression that I have the influence over project decisions to the degree implied by the "TSC member" label.

doc: move addaleax to TSC emiriti

---

doc/api/cli.md
doc/api/test.md
lib/internal/test_runner/coverage.js
src/node_options.cc
test/fixtures/v8-coverage/combined_coverage/common.js
test/fixtures/v8-coverage/combined_coverage/first.test.js
test/fixtures/v8-coverage/combined_coverage/second.test.js
test/fixtures/v8-coverage/combined_coverage/third.test.js
test/parallel/test-runner-coverage.js

This commit adds support for combining code coverage reports in the test runner. This allows coverage to be collected for child processes, and by extension, the test runner CLI.
Fixes: https://github.com/nodejs/node/issues/47669

test_runner: support combining coverage reports

---

doc/api/test.md
test/parallel/test-runner-concurrency.js

The documentation appears to still be wrong w.r.t. the meaning of the `concurrency` option of the `test()` function. The implementation appears to default to `Infinity` when the option is set to `true`. Is that intended or a good idea? I don't know. It certainly makes more sense than what the documentation says (which is basing the number of concurrent tasks within a single thread on the number of CPU cores).
This changes the documentation to hopefully match the implementation and adds a test that rules out the (rather arbitrary) behavior described in the documentation.
Refs: https://github.com/nodejs/node/issues/47365
Refs: https://github.com/nodejs/node/pull/47642

doc,test: fix concurrency option of test()

---

lib/internal/idna.js
src/encoding_binding.cc
src/encoding_binding.h

Fixes https://github.com/nodejs/node/issues/47726
Co-authored-by: Daniel Lemire (@lemire)
cc @tniessen @nodejs/cpp-reviewers @nodejs/url

src: replace idna functions with ada::idna

---

common.gypi
deps/v8/src/codegen/tnode.h

libstdc++: fix incomplete type in v8::internal::is_subtype<T, U>
Using std::convertible with incomplete types is UB. However, till
GCC 12 it was accepted and std::convertible returned false.
This fails now for e.g. v8::internal::WasmArray. Use
std::disjunction and std::conjunction instead which are short-
circuiting, because std::is_base_of<T, T> is already true.
Bug: chromium:957519
Change-Id: Ia26643dbdf0fb00d5586c71ae6b18e8d0f3cf96e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4394663
Commit-Queue: Stephan Hartmann <stha09@googlemail.com>
Reviewed-by: Clemens Backes <clemensb@chromium.org>
Cr-Commit-Position: refs/heads/main@{#86904}
Refs: https://github.com/v8/v8/commit/c5ab3e4f0c5a3ce880941184ef8447c27cd19a93
Fixes: …

deps: V8: cherry-pick c5ab3e4f0c5a

---

doc/api/webstreams.md

doc: fix arrayBuffer alias typo
`buffer` was aliased to `arrayBuffer` in an example for `arrayBuffer`.
remake of #47762

doc: fix typo in webstreams.md

---

doc/api/assert.md
doc/api/deprecations.md
lib/assert.js

Closes: https://github.com/nodejs/node/issues/47492

assert: deprecate callTracker

---

lib/internal/v8/startup_snapshot.js
test/fixtures/snapshot/v8-startup-snapshot-api.js
test/parallel/test-v8-startup-snapshot-api.js

Adds a regression test verifying that the error is correctly constructed.

v8: fix ERR_NOT_BUILDING_SNAPSHOT is not a constructor

---

lib/internal/url.js
src/node_blob.cc
src/node_blob.h

Resolving a pending TODO. This pull request mainly reduces the C++ calls in revokeObjectURL function while removing the `try/catch` block.
cc @nodejs/url

url: reduce revokeObjectURL cpp calls

---

benchmark/events/eventtarget-creation.js

This proved to be a useful benchmark. FWIW We have a regression in creating EventTarget in Node.js v20.

benchmark: add eventtarget creation bench

---

configure.py

- Explicitly specify the encoding when opening files.
- Use f-strings to format strings.
- Use `isinstance()` for type checks instead of `type()`.
- Use the `with` keyword for resource-allocating operations.
- Avoid using multiple statements in a single line.
- Remove unnecessary `else` clauses after `return`.
- Iterate with the `items()` method of dictionaries when both the key and value are used.
- Remove unnecessary parentheses.
- Rename unused unpacked variables to `_`, `_1`, etc etc.
- Rename the `list` variable to avoid conflict with the global `list()` function.
Refs: https://github.com/nodejs/node/pull/47581#issuecomment-1518512779

build: refactor configure.py

---

test/common/README.md
test/common/tmpdir.js
test/parallel/test-fs-promises-file-handle-readFile.js
test/parallel/test-fs-readfile.js
test/pummel/test-fs-readfile-tostring-fail.js

In general, we assume that the tmpdir will provide sufficient space for most tests. Some tests, however, require hundreds of megabytes or even gigabytes of space, which often causes them to fail, especially on our macOS infrastructure. The most recent reliability report contains more than 20 related CI failures.
This change adds a new function `hasEnoughSpace()` to the `tmpdir` module that uses `statfsSync()` (thanks @SheikhSajid and @cjihrig!) to guess whether allocating a certain amount of space within the temporary directory will succeed.
This change also updates the most frequently failing tests to use the new function such that the relevant parts of the tests are skipped if tmpdir has insufficient space. Hopefully, this will significantly reduce the number of related CI failures. …

test: add and use tmpdir.hasEnoughSpace()

---

doc/api/permissions.md

As far as I can tell, the permission model implementation currently does not restrict all file system operations but only those through the fs module. WASI, for example, bypasses the permission model entirely.
That appears to be by design, see https://github.com/nodejs/node/pull/44004#issuecomment-1437361808.

doc: clarify fs permissions only affect fs module

---

doc/api/cli.md

The brackets were escaped for some reason, preventing them from being rendered as links, and the link targets were not defined.

doc: fix --allow-* CLI flag references

---

.github/dependabot.yml

This will fix the commits messages of dependabot so it complies with commit message rules : `build(deps): bump actions/checkout from 3.3.0 to 3.5.2` -> `meta: bump actions/checkout from 3.3.0 to 3.5.2`.

meta: fix dependabot commit message

---

doc/api/errors.md
lib/_http_server.js
lib/internal/errors.js
test/parallel/test-http-server-response-standalone.js

Via https://github.com/fastify/fastify-websocket/issues/249, I found out that calling `assignSocket` multiple times could lead to `ERR_INTERNAL_ASSERTION`, which is confusing for users, as this is a user mistake and not an internals bug.

http: ServerResponse.assignSocket should not throw an internal error

---

test/parallel/test-timers-immediate-promisified.js
test/parallel/test-timers-interval-promisified.js
test/parallel/test-timers-timeout-promisified.js

Use `getEventListeners` instead of `listenerCount` because #35991 was landed.
Refs: https://github.com/nodejs/node/pull/35991
Refs: https://github.com/nodejs/node/pull/36006

test: refactor to use `getEventListeners` in timers

---

test/common/wpt.js

Because `inProgress` is now a `Set<WPTTestSpec>`.
Refs: https://github.com/nodejs/node/pull/47821#issuecomment-1532015508

test: fix WPT state when process exits but workers are still running

---

doc/api/v8.md
test/fixtures/snapshot/v8-startup-snapshot-api.js
test/parallel/test-snapshot-api.js

The API is now available to user-land run-time snapshots. So update
the example. This also makes the intention of the examples a bit
clearer and test it in our test suite.
This depends on https://github.com/nodejs/node/pull/47466 and https://github.com/nodejs/node/pull/47467, otherwise the example is broken.

doc,test: update the v8.startupSnapshot doc and test the example

---

src/cares_wrap.cc
src/inspector_socket.cc
src/inspector_socket_server.cc
src/node.cc
src/node_file.cc
src/string_bytes.cc
src/util.cc
test/cctest/test_inspector_socket.cc

The pattern of getting the address of the element at index 0 of a container is generally used to materialize a pointer to the backing data of a container, however `std::string` and `std::vector` provide a `data()` accessor to retrieve the data pointer which should be preferred.
This also ensures that in the case that the container is empty, the data pointer access does not perform an errant memory access.

src: prefer data accessor of string and vector

---

README.md

Node.js 14 and 15 have both reached end-of-life.
I know that 19 is not technically current, but I think it's best not to use a future LTS release line as an example of the current release line.

doc: replace EOL versions in README

---

doc/contributing/investigating-native-memory-leaks.md

Adds details on how to generate and use Valgrind suppressions to the "Investigating memory leaks with Valgrind" documentation.

doc: add valgrind suppression details

---

src/node_worker.cc

Previously we didn't pass the snapshot data down to the isolate data of workers so workers spawned by workers won't use the snapshot. Fixes it by passing the snapshot data down.

worker: use snapshot in workers spawned by workers

---

lib/path.js

path: indicate index of wrong resolve() parameter

---

src/quic/data.h

Address coverity warning about uninitialized value

quic: address recent coverity warning

---

src/crypto/crypto_context.cc
src/crypto/crypto_tls.cc
src/node_report.cc
src/util.h

Having `Utf8Value::operator==()` without `operator!=()` is awkward in C++17, so add the negated equality operator. Then, use either instead of `strcmp()` where appropriate.

src: avoid strcmp() with Utf8Value

---

lib/internal/bootstrap/realm.js
test/parallel/test-runner-import-no-scheme.js

Fixes: https://github.com/nodejs/node/issues/47828

module: block requiring `test/reporters` without scheme

---

test/common/wpt.js
test/wpt/test-timers.js
test/wpt/testcfg.py

Refs: https://github.com/nodejs/node/pull/47657#issuecomment-1532628751
Because of the flaky wpt/test-timers and sometimes crashing wpt/test-webcrypto this PR
- moves the WPT test suite back to `SimpleTestConfiguration`
- reduces the default WPT files concurrency by 1 to save one CPU for the WPTRunner itself
- introduces an option to force a given concurrency for a WPT Runner so that timing sensitive suites can be ran sequentially
cc @targos @tniessen

test: reduce WPT concurrency

---

test/abort/test-signal-handler.js

FreeBSD uses SIGBUS after update to v12.4.
Refs: https://github.com/nodejs/build/issues/3134

test: allow SIGBUS in signal-handler abort test

---

doc/api/worker_threads.md
lib/internal/buffer.js
lib/internal/modules/esm/worker.js
lib/worker_threads.js
src/env_properties.h
src/node_messaging.cc
test/addons/worker-buffer-callback/test.js
test/node-api/test_worker_buffer_callback/test.js
test/parallel/test-buffer-pool-untransferable.js
test/parallel/test-worker-message-port-arraybuffer.js
test/parallel/test-worker-message-port-transfer-native.js
test/parallel/test-worker-message-transfer-port-mark-as-untransferable.js

The HTML [StructuredSerializeWithTransfer](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializewithtransfer) algorithm defines that when
an untransferable object is in the transfer list, a DataCloneError is
thrown.
An array buffer that is already transferred is also considered as
untransferable.
The following script throws in the browser but succeeds in Node.js:
```js
const ab = new ArrayBuffer(10)
const first = structuredClone(ab, { transfer: [ab] })
const second = structuredClone(ab, { transfer: [ab] })
```
The motivation of the PR is throwing an error prominently to avoid copy buffer
silently when it is expected to be transferred: 
```js
const buffer = Buffer.allocUnsafe(10)
// this should throw instead of falling back to copying
structuredClone(buffer, { …
```

src: throw DataCloneError on transfering untransferable objects

---

src/node_http2.cc
src/node_http2.h

The http2 implementation uses the deprecated function `nghttp2_session_callbacks_set_error_callback`, which does not supply an error code but only an error message. This so far forced node's error callback to rely on the error message in order to distinguish between different errors, which is fragile and inefficient.
Use the newer `nghttp2_session_callbacks_set_error_callback2` function instead, which is not deprecated and which provides the exact error code to node's error callback.

http2: improve nghttp2 error callback

---

test/parallel/test-node-output-console.mjs
test/parallel/test-node-output-errors.mjs
test/parallel/test-node-output-sourcemaps.mjs
test/parallel/test-node-output-vm.mjs

Refs: https://github.com/nodejs/node/pull/47498#issuecomment-1532508231
sometimes `process.cwd()` has the node version included in it - so we must first normalize `process.cwd()` and only then normalize `process.version`.

test: fix output tests when path includes node version

---

doc/api/assert.md
doc/api/stream.md

doc: Fix params names

---

src/env.cc
src/permission/child_process_permission.cc
src/permission/child_process_permission.h
src/permission/fs_permission.h
src/permission/permission.h
src/permission/permission_base.h
src/permission/worker_permission.cc
src/permission/worker_permission.h

The first parameter is to set allow-permission, but its name declaration is `deny`. This removes any confusion.
/cc @RafaelGSS 

src: clarify the parameter name in `Permission::Apply`

---

doc/api/permissions.md
doc/api/process.md

This fixes the function description and adds missing available scopes.

doc: improve `permission.has` description

---

test/parallel/test-webcrypto-wrap-unwrap.js

The wrap/unwrap promises are now properly handled.
Refs: #47864
cc @tniessen @fhanau

test: fix webcrypto wrap unwrap tests

---

lib/internal/crypto/webcrypto.js
test/parallel/test-webcrypto-export-import-cfrg.js
test/parallel/test-webcrypto-export-import-ec.js
test/parallel/test-webcrypto-export-import-rsa.js
test/parallel/test-webcrypto-export-import.js
test/parallel/test-webcrypto-sign-verify-ecdsa.js
test/parallel/test-webcrypto-sign-verify-eddsa.js
test/parallel/test-webcrypto-sign-verify-hmac.js
test/parallel/test-webcrypto-sign-verify-rsa.js

`private` and `secret` type keys are not allowed to have empty usages
Refs: #47864
cc @tniessen @fhanau

crypto: fix webcrypto private/secret import with empty usages

---

common.gypi
deps/v8/src/codegen/riscv/macro-assembler-riscv.cc
deps/v8/src/regexp/riscv/regexp-macro-assembler-riscv.cc
deps/v8/src/regexp/riscv/regexp-macro-assembler-riscv.h

[riscv] Using s8 as backtrack_stackpointer reg and optimize BranchShortHelper
1. Fix incorrect backtrack_stackpointer reg.
2. Optimize BranchShortHelper when comparing zero immediate.
3. This is a workaround CL fix v8:13836
Bug: v8:13836
Change-Id: I4cfc9df92fcd38ecd448a41ee87d1e251efd4ad9
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4394942
Auto-Submit: Yahan Lu <yahan@iscas.ac.cn>
Reviewed-by: Ji Qiu <qiuji@iscas.ac.cn>
Commit-Queue: Ji Qiu <qiuji@iscas.ac.cn>
Cr-Commit-Position: refs/heads/main@{#86889}
Refs: https://github.com/v8/v8/commit/1b471b79602235c13202b5b52eeb34603cee7a91

deps: V8: cherry-pick 1b471b796022

---

src/node.h
src/node_builtins.cc

The code cache is quite large - around 1.3 MiB. Change the code to use non-owning buffers to avoid copying it. For starting up an otherwise empty main isolate, this saves around 1.3 MiB of unique set size memory (9.9 MiB -> 8.6 MiB) and 1.1ms elapsed time (22.9 ms -> 21.8 ms).
Copying the code cache is unnecessary since:
1. for the builtin snapshot, the code cache data has static lifetime.
2. for non-builtin snapshots, we create copies of the code cache data in `SnapshotDeserializer::ReadVector`. These copies are owned by the `Environment` (through `IsolateData` -> `SnapshotData`), so they won't be deallocated.
3. a worker thread can copy a parent's isolate's code cache, but in that case we still know that the parent isolate will outlive the worker isolate.
(Admittedly point (2) feels a …

src: stop copying code cache

---

lib/internal/url.js
test/parallel/test-url-is-url.js

Previously we were checking for `protocol` and `origin` attributes, but due to the lazy-loading nature of Ada 2.0 with `url_aggregator` we shifted from checking for `origin`. This was also breaking the detection of the legacy URL parse function. This PR fixes that in the least impactful way possible, by checking if `auth` property is defined.
Fixes https://github.com/nodejs/node/issues/47624
cc @nodejs/url @Trott

url: improve `isURL` detection

---

lib/buffer.js
test/parallel/test-buffer-alloc.js
test/parallel/test-buffer-copy.js

Merging 2 checking range of sourceStart into 1. Plus, add test case to increase coverage if sourceStart is greater than length of source.

buffer: combine checking range of sourceStart in `buf.copy`

---

src/udp_wrap.cc
src/udp_wrap.h

It's not pretty either way, but a template is still preferable over a macro.

dgram: convert macro to template

---

lib/net.js
test/parallel/test-net-end-without-connect.js

Fixes: https://github.com/nodejs/node/issues/47322
`pending` potentially covers these 2 stages:
- constructed, haven't done any connection
- connecting
It is possible sockets at first stage simply want to get destroyed without any attempt of connecting.
Thus, it's more appropriate to defer the final call only when the socket has started connecting but not yet connected.

net: only defer _final call when connecting

---

lib/child_process.js
test/parallel/test-child-process-exec-abortcontroller-promisified.js
test/parallel/test-child-process-fork-abort-signal.js
test/parallel/test-child-process-spawn-controller.js

Fixes: https://github.com/nodejs/node/issues/47814

child_process: use signal.reason in child process abort

---

lib/internal/bootstrap/realm.js
lib/internal/modules/cjs/loader.js

`BuiltinModule.normalizeRequirableId()` was introduced in https://github.com/nodejs/node/pull/47779 to fix a bug in the require function of SEAs and Snapshots, so that built-in modules with the `node:` scheme could be required correctly. This change makes more use of this API instead of `BuiltinModule.canBeRequiredByUsers()` and `BuiltinModule.canBeRequiredWithoutScheme()` to reduce chances of such bugs.

module: refactor to use `normalizeRequirableId` in the CJS module loader

---

src/quic/endpoint.h

quic: fix typo in endpoint.h

---

src/node_messaging.cc
src/node_messaging.h
test/parallel/test-experimental-shared-value-conveyor.js

This adds the missing integration support for the V8 experimental shared structs feature (`--harmony-struct`). There is no observable difference to node if `--harmony-struct` is not passed. The flag is false by default.
This experimental feature is for proving out shared memory in JS. The standards side is tracked by https://github.com/tc39/proposal-structs, though the current experiment, for the sake of ease of experimentation, does not include syntax. The features in experiment is documented [here](https://github.com/tc39/proposal-structs/blob/main/CHROMIUM-DEV-TRIAL.md).
I also intentionally did not add any tests because the features are experimental and volatile. Here is an illustrative example though:
```javascript
'use strict';
const { Worker, isMainThread, parentPort } = …
```

src: support V8 experimental shared values in messaging

---

doc/api/fs.md

Fixes: https://github.com/nodejs/node/issues/40184

doc: ntfs junction points must link to directories

---

doc/api/globals.md

doc: mark global object as legacy
Fixes: https://github.com/nodejs/node/issues/47784

doc: mark global object as legacy

---

doc/contributing/using-internal-errors.md

I've spent quite a bit of time debugging why the lining was failing locally.
I thought it would be useful to document the `make lint-md-clean` job.

doc: document make lint-md-clean

---

lib/fs.js
lib/internal/fs/dir.js

This PR updates the new `readdir` recursive algorithm to be iterative. This helps avoid potential callstack issues for very large directories.

fs: make recursive readdir algorithms iterative

---

src/node_main.cc

`SKIP_CHECK_VALUE` is a string literal, so its size is the length of the string in `char`s _plus one_. The buffer `buf` is also always null-terminated, so its size should match the size of `SKIP_CHECK_VALUE`, which is _not_ `SKIP_CHECK_SIZE`.
Rename `SKIP_CHECK_SIZE` to be consistent with C/C++ terminology.

src: rename SKIP_CHECK_SIZE to SKIP_CHECK_STRLEN

---

lib/dns.js
lib/internal/dns/callback_resolver.js
lib/internal/dns/promises.js
src/cares_wrap.cc

Reduces the C++/JS bridge crosses by calling `toASCII` directly from C++.
Fixes: https://github.com/nodejs/performance/issues/77
Benchmark CI: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1335/

dns: call `ada::idna::to_ascii` directly from c++

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/hooks.js

For tests with subtests the before hook was being run after the beforeEach hook, which is the opposite to test suites and expectations.
Also, a function was being used to close over the after hooks, but at the point it was being run the after hooks were not yet set up.
Fixes #47915

test_runner: fix ordering of test hooks

---

lib/internal/process/permission.js

For other candidate permissions, such as "net" or "env", this patch will pass the given reference without resolving it to an absolute path.

permission: resolve reference to an absolute path only for fs permission

---

lib/net.js
test/parallel/test-net-autoselectfamily.js

This PR fixes timeout handling of the family autoselection.
@nodejs/net  @nodejs/tsc To ensure better user experience, I disabled the attempt timeout when connecting to the last IP address available, otherwise each connection attempt would be bound to the same (pretty low) timeout.
Do you think this is a reasonable approach? Also, is this considered a semver-major change? I think people are affected by this so we might want to include in 20.x anyway.
Fixes #47822.

net: fix family autoselection timeout handling.

---

doc/api/buffer.md

Closes: https://github.com/nodejs/node/issues/47940

doc: remove broken link

---

test/wpt/status/html/webappapis/timers.json

#47834 resolved the concurrency issues of wpt/test-timers so I believe this skip is no longer needed.

test: unskip negative-settimeout.any.js WPT

---

lib/internal/error_serdes.js
test/parallel/test-error-serdes.js

extracted from https://github.com/nodejs/node/pull/47867: 
the motivation of this change is for the test runner (which runs across multiple processes) to communicate with the main process via v8 serialization instead of TAP - so we want to better serialize a wider range of (edge?) cases

worker: support more cases when (de)serializing errors

---

doc/api/cli.md

The OpenSSL 1.1.1 version of the man page is available online and so we could update to that instead, but since we're using OpenSSL 3.0 now, I think using the 3.0 man page makes the most sense. Regardless, the current link is 404, so let's fix it.

doc: fix broken link

---

test/parallel/test-webcrypto-random.js

Added test to check the return results `getRandomValues`

test: add getRandomValues return length

---

doc/api/vm.md

The import assertion proposal has been renamed and the old URL does not redirect to the new one. So let's update our URL to point to the import attributes proposal, which is what import assertions have been renamed to.

doc: fix broken link to TC39 import attributes proposal

---

doc/api/errors.md
doc/api/http.md
lib/_http_outgoing.js
lib/_http_server.js
lib/http.js
lib/internal/errors.js
test/parallel/test-http-head-throw-on-response-body-write.js

Issue: nodejs/node#47480
An exception with the code `ERR_HTTP_BODY_NOT_ALLOWED` is thrown if an attempt is made to write to the body of a response when the HTTP spec does not allow the response to contain content.
* Request method is `HEAD`
* Response status is `204` or `304`
For release notes:
An error is thrown if when writing to an HTTP response which does not allow contents.

http: prevent writing to the body when not allowed by HTTP spec

---

doc/api/vm.md

If in case current context is unable to allocate a promise then `ERR_CONTEXT_NOT_INITIALIZED` error will be thrown (as promise rejection) in the vm measureMemory call. Though minor change but this behavior should also be notified in the docs for the API call.

vm: update measure memory rejection information

---

doc/api/globals.md

With widespread support for ES modules, the description of `global` is outdated now.

doc: update description of global

---

lib/internal/modules/esm/hooks.js
test/es-module/test-esm-loader-hooks.mjs

Fixes: https://github.com/nodejs/node/issues/47929

esm: do not use `'beforeExit'` on the main thread

---

src/base64_version.h
src/cjs_module_lexer_version.h
src/node_metadata.cc
src/node_metadata.h
test/parallel/test-process-versions.js
tools/dep_updaters/update-base64.sh
tools/dep_updaters/update-cjs-module-lexer.sh

Ref: #45260 
Added version info of `cjs_module_lexer` and `base64_version`

src: add cjs_module_lexer_version and base64_version

---

benchmark/common.js
doc/api/url.md
lib/internal/url.js
test/fixtures/wpt/README.md
test/fixtures/wpt/url/README.md
test/fixtures/wpt/url/failure.html
test/fixtures/wpt/url/historical.any.js
test/fixtures/wpt/url/resources/a-element-origin.js
test/fixtures/wpt/url/resources/a-element.js
test/fixtures/wpt/url/resources/urltestdata.json
test/fixtures/wpt/url/url-constructor.any.js
test/fixtures/wpt/url/url-origin.any.js
test/fixtures/wpt/url/urlsearchparams-delete.any.js
test/fixtures/wpt/url/urlsearchparams-has.any.js
test/fixtures/wpt/versions.json

The change aims to add value argument to two methods of URLSearchParams class i.e the has method and the delete method. For has method, if value argument is provided, then use it to check for presence. For delete method, if value argument provided, use it to delete.
Fixes: https://github.com/nodejs/node/issues/47883

url: add value argument to has and delete methods

---

tools/dep_updaters/update-nghttp3.sh

Refs: https://github.com/nodejs/node/pull/47576

tools: debug log for nghttp3

---

doc/api/cluster.md

I believe that these are required so that the respective APIs are marked as deprecated in the table of contents.

doc: add missing deprecated blocks to cluster

---

doc/api/test.md
lib/internal/test_runner/harness.js
test/fixtures/test-runner/output/only_tests.js
test/fixtures/test-runner/output/only_tests.snapshot

test_runner: add shorthands to `test`

---

src/node_contextify.cc
test/parallel/test-vm-set-proto-null-on-globalthis.js

Add `IsUndefined()` check after `GetOwnPropertyDescriptor` to avoid crash when `desc_obj->HasOwnProperty()`
fix https://github.com/nodejs/node/issues/47798

vm: fix crash when setting __proto__ on context's globalThis

---

test/es-module/es-module.status

This test has been failing occasionally for weeks.
Refs: https://github.com/nodejs/node/issues/47836
Refs: https://github.com/nodejs/reliability/issues/564

test: mark test-esm-loader-http-imports as flaky

---

src/crypto/crypto_x509.cc
src/crypto/crypto_x509.h

`X509Certificate::Fingerprint`, `X509Certificate::Fingerprint256`, and `X509Certificate::Fingerprint512` all do the same, except using different cryptographic hash functions. Move the common logic into a template helper function.

src: deduplicate X509Certificate::Fingerprint*

---

src/permission/fs_permission.h

RestrictAccess() is declared, but it's not used.

permission: remove unused function declaration

---

doc/api/errors.md

The error is not necessarily due to a client certificate engine. For example, the `privateKeyEngine` option might just as well cause this error and is independent of the client certificate.
Also mention that this is likely due to a compile-time option of OpenSSL itself and not due to any particular engine.

doc: clarify CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED

---

CHANGELOG.md

doc: mark Node.js 14 as End-of-Life

---

src/README.md

According to usage(node::util::RegisterExternalReferences) of below line, namespace has to be `util`(not `utils`).

doc: fix typo in binding functions

---

benchmark/cluster/echo.js
benchmark/http/cluster.js

`cluster.isMaster` was deprecated. So need to use `cluster.isPrimary` for benchmark.
Refs: https://github.com/nodejs/node/pull/47981

benchmark: use `cluster.isPrimary` instead of `cluster.isMaster`

---

test/common/index.js

This does not replace `_` with `-` when parsing flags.
I believe that it was added for a certain purpose, but it doesn't seem to be needed anymore. Currently, the cli options are not passed as intended in the following cases:
```js
// Flags: --diagnostic-dir=~/PATH_HAS_UNDERSCORES
```
```console
NOTE: The test started as a child_process using these flags: [ 
'--diagnostic-dir=~/PATH-HAS-UNDERSCORES' <--
]
```
```js
// Flags: --experimental-permission --allow-fs-read=~/PATH_HAS_UNDERSCORES
```
```console
The test started as a child_process using these flags: [
'--experimental-permission',
'--allow-fs-read=~/PATH-HAS-UNDERSCORES'  <--
] 
```

test: fix parsing test flags

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/abort_suite.snapshot
test/parallel/test-runner-misc.js

Fixes: https://github.com/nodejs/node/issues/47882
@MoLow that's the bug about the suite not getting the AbortSignal correctly.

test: fix suite signal

---

doc/api/process.md

Added process.versions properties in docs:
`uvwasi`
`undici`
`acorn`
`base64`
`cjs_module_lexer`
Fixes: https://github.com/nodejs/node/issues/48016

doc: updated process.versions properties

---

doc/api/globals.md
lib/internal/abort_controller.js
lib/internal/validators.js
test/common/wpt.js
test/common/wpt/worker.js
test/fixtures/wpt/README.md
test/fixtures/wpt/dom/abort/abort-signal-any.any.js
test/fixtures/wpt/dom/abort/resources/abort-signal-any-tests.js
test/fixtures/wpt/versions.json
test/parallel/test-abortsignal-any.mjs

Fixes: https://github.com/nodejs/node/issues/47811
Refs: [whatwg/dom#1152](https://github.com/whatwg/dom/pull/1152)

lib: implement AbortSignal.any()

---

.github/label-pr-config.yml

meta: remove dont-land-on-v14 auto labeling

---

node.gyp
src/crypto/crypto_context.cc
test/cctest/test_node_crypto_env.cc

NodeBIO's memory buffer structure does not support BIO_C_FILE_SEEK and B IO_C_FILE_TELL. This prevents OpenSSL PEM_read_bio_PrivateKey from readi ng some private keys. So I switched to OpenSSL's own protected memory bu ffers.
Fixes: https://github.com/nodejs/node/issues/47008

crypto: use openssl's own memory BIOs in crypto_context.cc

---

src/node_url.cc

We're planning on improving the performance of `ada::can_parse` and added this function in `2.3.1` release. This would make things a lot easier and more readable for Node.js.
cc @KhafraDev @nodejs/url

url: call `ada::can_parse` directly

---

doc/contributing/releases-node-api.md

With the change in https://github.com/nodejs/node/pull/45715 landed, there are several code sites that need to be updated with the release Node-API version when a new Node-API version is being released.
This PR adds a document to the guides of a checklist necessary for creating a Node-API release PR.
Fixes: https://github.com/nodejs/node/issues/47664

doc: document node-api version process

---

doc/api/crypto.md

doc: update broken EVP_BytesToKey link

---

doc/api/crypto.md

The examples for `generateKey()` and `generateKeySync()` generate 64-bit HMAC keys. That is inadequate for virtually any HMAC instance. As per common NIST recommendations, the minimum should be roughly 112 bits, or more commonly 128 bits.
Due to the [design of HMAC itself](https://en.wikipedia.org/wiki/HMAC), it is not unreasonable to choose the underlying hash function's block size as the key length. For many popular hash functions (SHA-256, SHA-224, SHA-1, MD5, ...) this happens to be 64 bytes (bytes, not bits!). This is consistent with the [HMAC implementation in .NET](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha256.-ctor?view=net-7.0), for example, even though it provides virtually no benefit over a 256-bit key.

doc: use secure key length for HMAC generateKey

---

BUILDING.md
README.md
doc/api/addons.md
doc/api/cli.md
doc/api/esm.md
doc/api/net.md
doc/api/process.md
doc/api/repl.md
doc/api/single-executable-applications.md
doc/api/synopsis.md
doc/api/tls.md
doc/api/wasi.md
doc/contributing/collaborator-guide.md
doc/contributing/investigating-native-memory-leaks.md
doc/contributing/maintaining/maintaining-V8.md
doc/contributing/maintaining/maintaining-openssl.md
doc/contributing/pull-requests.md
doc/contributing/releases-node-api.md
doc/contributing/releases.md
doc/contributing/writing-and-running-benchmarks.md
doc/contributing/writing-tests.md
test/wasi/README.md
test/wpt/README.md

We had a few code snippets that were using a non-descriptive tag (e.g. `console` or `text`), whereas the actual language it's using describes it better, and improves the syntax highlighting. This PR also removes non-necessary leading chars (e.g. `$`, `>`, or `%`) to make it easier for readers to copy and paste to try the command themselves.
/cc @alexsch01

doc: harmonize fenced code snippet flags

---

doc/api/single-executable-applications.md

Those were wrongly marked as `bash` (that's my bad, it's coming from https://github.com/nodejs/node/pull/48082), when the text around it was referencing PowerShell or Command Prompt.

doc: fix Windows code snippet tags

---

test/common/wpt.js

Because daily WPT report started timing out on these helper files. These are not test entrypoints so we're not losing any coverage.

test: ignore helper files in WPTs

---

doc/api/single-executable-applications.md

Windows terminals [Command Prompt and PowerShell] don't use \ for line breaks

doc: correct line break for Windows terminals

---

doc/api/tty.md

This clarifies the behavior of [tty.ReadStream.isRaw](https://nodejs.org/api/tty.html#readstreamisraw), which is not quite explicitly spelled out and is kind of surprising IMO. For more context, see the discussion in https://github.com/nodejs/node/issues/47938

doc: clarify tty.isRaw

---

tools/dep_updaters/update-zlib.sh

Use the `DEPS_DIR` variable to build the path instead of hardcoding it.
Extracted from https://github.com/nodejs/node/pull/48054.

tools: fix zconf.h path

---

doc/api/single-executable-applications.md

The code was moved in 3803b028d so the current source link is broken in our docs.

doc: update SEA source link

---

tools/dep_updaters/update-ada.sh
tools/dep_updaters/update-eslint.sh
tools/dep_updaters/update-libuv.sh
tools/dep_updaters/update-ngtcp2.sh
tools/dep_updaters/update-postject.sh
tools/dep_updaters/update-simdutf.sh

tools: add debug logs to deps update

---

test/parallel/parallel.status

Refs: https://github.com/nodejs/node/issues/48047
CC @richardlau 
CC @nodejs/platform-ibmi

test: skip test-http-pipeline-flood on IBM i

---

doc/api/test.md
lib/internal/test_runner/reporter/spec.js
lib/internal/test_runner/reporter/tap.js
lib/internal/test_runner/runner.js
lib/internal/test_runner/tests_stream.js

Introduce new `TestsStream` events `test:stderr` and `test:stdout`
to delegate `stderr` and `stdout` (e.g. `console.log()`) formatting
to the reporter. And patch existing reporters to:
- Spec: output the message as it is
- TAP: stay the same with existing `test:diagnostic`
Fixes: https://github.com/nodejs/node/issues/48011

test_runner: delegate stderr and stdout formatting to reporter

---

src/blob_serializer_deserializer-inl.h
src/blob_serializer_deserializer.h
src/debug_utils.h
src/node_main_instance.cc
src/node_sea.cc
src/node_sea.h
src/node_snapshotable.cc
test/sequential/test-single-executable-application-empty.js

src: use Blob{Des|S}erializer for SEA blobs

---

lib/internal/test_runner/reporter/v8-serializer.js
lib/internal/test_runner/runner.js
test/parallel/test-runner-v8-deserializer.mjs

Fixes: https://github.com/nodejs/node/issues/48103

test_runner: fix test deserialize edge cases

---

doc/api/deprecations.md
doc/api/stream.md
lib/internal/streams/operators.js
test/parallel/test-stream-iterator-helpers-test262-tests.mjs

Refs: https://github.com/tc39/proposal-iterator-helpers, https://github.com/tc39/proposal-iterator-helpers/commit/63567bb229e1051dfe87ed3c5a959ca77cf1f60a, https://github.com/tc39/proposal-iterator-helpers/commit/bdb48832a39a58ce4dbbe4f2031281ff61893c30, https://github.com/tc39/proposal-iterator-helpers/pull/211

stream: deprecate asIndexedPairs

---

doc/api/single-executable-applications.md
test/common/sea.js

The recent Postject upgrade, https://github.com/nodejs/node/pull/48072, included a performance improvement for the injection operation (see https://github.com/nodejs/postject/pull/86), so now it might be possible to run the SEA tests on the ppc64 architecture runners on Jenkins, which was previously getting timed out.

test,doc,sea: run SEA tests on ppc64

---

.github/CODEOWNERS

Added security-wg as codeowner of dep updaters

tools: add security-wg as dep updaters owner

---

src/crypto/crypto_keygen.cc

Now that `CSPRNG()` does not silently fail when the length exceeds `INT_MAX` anymore, there is no need for the two relevant assertions in `SecretKeyGenTraits` anymore.
Refs: https://github.com/nodejs/node/pull/47515

src: remove INT_MAX asserts in SecretKeyGenTraits

---

doc/api/crypto.md

Add a reference to potential problems with using strings as HMAC keys. Also advise against exceeding the underlying hash function's block size when generating HMAC keys from a cryptographically secure source of entropy.
Refs: https://github.com/nodejs/node/pull/48052
Refs: https://github.com/nodejs/node/pull/37248

doc: improve HMAC key recommendations

---

doc/api/tls.md

Recent OpenSSL versions support PSKs with non-SHA-256 TLSv1.3 ciphers, e.g., `TLS_AES_256_GCM_SHA384`.

doc: update outdated section on TLSv1.3-PSK

---

tools/dep_updaters/update-zlib.sh

`Zlib` rarely creates tags or releases, so now we use the latest commit on the main branch to check if an update is needed.
Refs: https://github.com/nodejs/security-wg/issues/973

tools: zlib update by checking latest commit

---

.github/CODEOWNERS

Keep each list in CODEOWNERS in alphabetical order so it is easier to find things in the longer lists.

tools: alphabetize CODEOWNERS

---

lib/internal/errors.js

**Description of change**
using an existing isWindows variable
**Checklist**

lib: use existing isWindows variable

---

doc/api/net.md

Fixes: https://github.com/nodejs/node/issues/48061
Just added in that `socket.remoteFamily` and `socket.remotePort` may be undefined as well if the socket is destroyed.

doc: update socket.remote* properties documentation

---

src/node_sea.h

Refs: https://github.com/nodejs/node/pull/47962#issuecomment-1560834347

src: include missing header in node_sea.h

---

lib/cluster.js
test/parallel/test-cluster-basic.js

This addresses: https://github.com/nodejs/node/pull/48077#discussion_r1199125760

cluster: use ObjectPrototypeHasOwnProperty

---

test/fixtures/test-runner/dependency.js
test/fixtures/test-runner/dependency.mjs
test/fixtures/test-runner/dependent.js
test/parallel/test-runner-watch-mode.mjs

I was able to reproduce the fluke with `tools/test.py -J --timeout=10 --repeat=1500 test/parallel/test-runner-watch-mode` and validate this fixes it

test: fix flaky test-runner-watch-mode

---

tools/dep_updaters/update-ada.sh
tools/dep_updaters/update-base64.sh
tools/dep_updaters/update-brotli.sh
tools/dep_updaters/update-c-ares.sh
tools/dep_updaters/update-libuv.sh
tools/dep_updaters/update-llhttp.sh
tools/dep_updaters/update-nghttp2.sh
tools/dep_updaters/update-nghttp3.sh
tools/dep_updaters/update-ngtcp2.sh
tools/dep_updaters/update-npm.sh
tools/dep_updaters/update-openssl.sh
tools/dep_updaters/update-simdutf.sh
tools/dep_updaters/update-uvwasi.sh
tools/dep_updaters/update-zlib.sh
tools/dep_updaters/utils.sh

As [discussed here](https://github.com/nodejs/node/pull/47992#pullrequestreview-1425479695), there is the need to log the  `sha256sum` for the external dependencies. With this PR in addition to log the `checksum`, we also check it's validity and eventually `exit` with an error. If the check is out of scope, of course I can just leave the log.
I started with `nghttp2` and when everything is ok I continue with the other deps
Refs: https://github.com/nodejs/security-wg/issues/973

tools: log and check shasum of archive file

---

lib/_http_outgoing.js
test/parallel/test-http-head-response-has-no-body-end-implicit-headers.js

If we respond to a HEAD request with a body, we ignore all writes. However, we must still include all implicit headers.
Fixes a regressions introduced in
https://github.com/nodejs/node/pull/47732.

http: send implicit headers on HEAD with no body

---

deps/cares/config/aix/ares_config.h
deps/cares/config/android/ares_config.h
deps/cares/config/cygwin/ares_config.h
deps/cares/config/darwin/ares_config.h
deps/cares/config/freebsd/ares_config.h
deps/cares/config/linux/ares_config.h
deps/cares/config/netbsd/ares_config.h
deps/cares/config/openbsd/ares_config.h
deps/cares/config/sunos/ares_config.h

Upstream c-ares renamed `RANDOM_FILE` to `CARES_RANDOM_FILE` some time ago in c-ares 1.17.2.
Refs: https://github.com/c-ares/c-ares/pull/397

deps: set `CARES_RANDOM_FILE` for c-ares

---

doc/api_assets/style.css

This addresses a scrolling/flickering issue in the node.js docs, as viewed by Firefox versions that have 'content-visibility' support (on by default in Firefox Nightly for several releases, opt-in in about:config in release versions).
See https://bugzilla.mozilla.org/show_bug.cgi?id=1832675 for details. Before this patch, the `content-visibility:auto` and `contain-intrinsic-size:1px 5000px` styles are telling the browser to suppress rendering of offscreen sections and behave as if they're 5000px tall, though they in fact are much shorter. This causes scrolling to behave quite bizarrely and can cause troublesome oscillating issues.
By adding `auto` to the `contain-intrinsic-size` CSS, we're asking the browser to remember the last-rendered size for the element (once it's been rendered) …

Add auto to docs' contain-intrinsic-size decl, to prevent jitter/flicker

---

doc/api/crypto.md

Remove broken link to deprecated keygen element.
Replacing the link with something to the relevant
part of the HTML spec might be OK, but I don't think it's necessary. People who need to know will find it and everyone else should be discouraged from using this.
Support for the keygen element was removed from Chrome in 2017 and removed from Firefox in 2019. We might consider deprecating and removing support ourselves, or at least marking the API as legacy.
Refs: https://caniuse.com/?search=keygen

doc: remove broken link for keygen

---

test/root.status

This test has been failing occasionally since it was introduced ~5 days ago. It was the number one failing JS test in the most recent reliability report. Mark it as flaky.
Fixes: https://github.com/nodejs/node/issues/48180
Refs: https://github.com/nodejs/node/pull/47986
Refs: https://github.com/nodejs/reliability/issues/576

test: mark test_cannot_run_js as flaky

---

lib/internal/test_runner/coverage.js

The code coverage reporting logic already filters out URLs that don't start with 'file:', so there is no need to also filter out URLs that start with 'node:'.

test_runner: remove redundant check from coverage

---

.github/workflows/tools.yml

Hi everyone,
I opened this PR to tackle the last bullet point of [this](https://github.com/nodejs/security-wg/issues/973) issue where jobs in `tools.yml` were not ordered alphabetically.
I also added the following options in `workflow_dispatch`, that were missing:
- minimatch
- zlib

tools: order dependency jobs alphabetically

---

.github/CODEOWNERS

This PR updates the CODEOWNERS file to manually ping the Website Team with changes to /tool/doc and /doc/api.

doc: update codeowners with website team

---

tools/dep_updaters/update-ada.sh
tools/dep_updaters/update-base64.sh
tools/dep_updaters/update-brotli.sh
tools/dep_updaters/update-c-ares.sh
tools/dep_updaters/update-cjs-module-lexer.sh
tools/dep_updaters/update-icu.sh
tools/dep_updaters/update-libuv.sh
tools/dep_updaters/update-llhttp.sh
tools/dep_updaters/update-nghttp2.sh
tools/dep_updaters/update-nghttp3.sh
tools/dep_updaters/update-ngtcp2.sh
tools/dep_updaters/update-simdutf.sh
tools/dep_updaters/update-uvwasi.sh

Fixes: https://github.com/nodejs/node/issues/48119
Refs: https://github.com/nodejs/security-wg/issues/973
Added `authorization` header to authenticate Github api requests in the dependency update workflow

tools: authenticate github api request to avoid rate limit

---

tools/dep_updaters/update-acorn.sh
tools/dep_updaters/update-base64.sh
tools/dep_updaters/update-cjs-module-lexer.sh
tools/dep_updaters/update-undici.sh

There were a few inconsistencies in the scripts (manual instructions were sometimes incomplete or lacking, the `_version.h` files were created differently, etc.), this PR aims to reduce that.

tools: harmonize `dep_updaters` scripts

---

tools/dep_updaters/utils.sh

By default, there is no sha256sum command in macOS.

tools: use shasum instead of sha256sum

---

test/wpt/status/html/webappapis/timers.json

This reverts commit 8244e6c35c0e9af3976511f31db2575bd2fc9d7a, PR #47946
https://github.com/nodejs/reliability/issues/577

Revert "test: unskip negative-settimeout.any.js WPT"

---

test/parallel/test-tls-dhe.js

With the default security level (SECLEVEL=2), the following error
```
40E72B52DB7F0000:error:0A00018A:SSL routines:tls_process_ske_dhe:dh key
too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2100
```
is raised on on Ubuntu 22.04 on WSL2.

test: use lower security level in s_client

---

doc/api/buffer.md

Fixes: https://github.com/nodejs/node/issues/42821

doc: update Buffer.allocUnsafe documentation

---

doc/api/cluster.md

doc: Add the links to better explain `stdio` property of `cluster.settings` in the file doc/api/cluster.md#clustersettings.
Fixes:  issue #47705
Refs: https://nodejs.org/docs/latest-v20.x/api/cluster.html#clustersettings
- doc

doc: improve the documentation of the stdio option

---

test/parallel/test-process-versions.js

Add support for subrevision in the regular expression for the zlib version.
Refs: https://github.com/madler/zlib/blob/48c3741002ac/zlib.h#L40

test: fix zlib version regex

---

.github/workflows/tools.yml
tools/dep_updaters/update-histogram.sh

More context: https://github.com/nodejs/node/pull/47742

tools: automate histogram update

---

tools/dep_updaters/update-base64.sh

The file is checked into git. Ignoring it causes a very non-obvious way of breaking tarball builds:
1. Download and unpack tarball
2. Check the sources into git with `git init; git add .; git commit -a`
3. Clean the source tree with `git clean -dfx`
4. Run `./configure && make`
5. Observe build failure because config.h is missing
Fixes: https://github.com/nodejs/node/issues/47638

tools: don't gitignore base64 config.h

---

src/README.md

Document the current `Environment`/`Realm` definitions.

src: add Realm document in the src README.md

---

lib/internal/modules/esm/hooks.js
test/es-module/test-esm-loader-hooks.mjs

Fixes: https://github.com/nodejs/node/issues/48240

esm: handle `globalPreload` hook returning a nullish value

---

configure.py

We should set v8_enable_webassembly=false when lite mode is enabled, since v8_enable_lite_mode implies v8_jitless, and wasm currently doesn't work with jitless. This is automatically handled in gn, but seems to be not the case in gyp. Enabling lite mode without setting v8_enable_webassembly=false leads to "Warning: disabling flag --expose_wasm due to conflicting flags" at runtime.

build: set v8_enable_webassembly=false when lite mode is enabled

---

lib/net.js
test/parallel/test-net-autoselectfamily.js

When `autoSelectFamily` is set to `true`, `net.connect` is supposed to try connecting to both IPv4 and IPv6, interleaving the address types. Instead, it appears that the array that holds the addresses in the order they should be attempted was never used after being populated.

net: fix address iteration with autoSelectFamily

---

doc/api/test.md

`watch` was missing. I ordered options alphabetically as well

doc: document watch option for node:test run()

---

lib/_tls_wrap.js
test/parallel/test-https-autoselectfamily.js

When establishing a TLS connection to a server with `autoSelectFamily` set to `true`, the `net.Socket` will call `[kWrapConnectedHandle]()` to reinitialize the socket (in case if it got broken during previous connect attempts). Unfortunately, prior to this patch this resulted in a brand new `TLSWrap` instance being created for the socket. While most of the configuration of `TLSWrap` is restored, the `servername` was sadly dropped and not reinitalized.
With this patch `servername` will be reinitialized if there are `tls.connect` options present on the `TLSSocket` instance, making it possible to connect with "Happy Eyeballs" to TLS servers that require the servername extension.

tls: reapply servername on happy eyeballs connect

---

doc/api/n-api.md
src/js_native_api.h
src/node_api.cc
src/node_api.h
src/node_version.h
test/js-native-api/test_error/test_error.c
test/js-native-api/test_general/test.js
test/js-native-api/test_properties/test_properties.c
test/js-native-api/test_reference/test_reference.c
test/node-api/test_general/test_general.c

Node-API version 9 promotes the following Node-API into stable:
- `node_api_throw_syntax_error`
- `node_api_create_syntax_error`
- `node_api_symbol_for`
- `node_api_get_module_file_name`
Runtime behavior changes introduced in https://github.com/nodejs/node/pull/47975 and https://github.com/nodejs/node/pull/47986 are still left experimental since they landed just in the past month and not backported to all LTS lines.
/cc @nodejs/node-api-implementer

node-api: define version 9

---

lib/internal/http2/core.js
lib/internal/webstreams/readablestream.js
lib/internal/webstreams/writablestream.js

Disabling linter for single lines is less error prone, disabling on the entire file can swallow errors that are easier to miss during code reviews, when one would assume the rule is enabled.

lib: do not disable linter for entire files

---

doc/api/buffer.md

The code for Buffer.from() treats non-Buffer and non-Uint8Array Array-likes as Arrays. This creates some confusion when passing various TypedArrays to Buffer.from(). The documentation now reflects the actual behavior.
Fixes: https://github.com/nodejs/node/issues/28725

doc: clarify array args to Buffer.from()

---

.github/FAILED_DEP_UPDATE_ISSUE_TEMPLATE.md
.github/workflows/tools.yml

This reverts commit c488558c15eb088a4b81a16fc34e5416c1d6e8d5.
the action creates an issue that dep update failed: https://github.com/nodejs/node/issues/48309 but actually worked https://github.com/nodejs/node/pull/48308, while other jobs failed

Revert "tools: open issue when update workflow fails"

---

test/parallel/parallel.status

Refs: https://github.com/nodejs/node/pull/48331#issuecomment-1575660102

test: mark test-child-process-pipe-dataflow as flaky

---

lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/utils.js
lib/internal/process/esm_loader.js

This avoids initializing arrays that we never use, and simplifies the implementation overall.
This had a purpose before https://github.com/nodejs/node/pull/43772, but now we load everything serially making the array creation superfluous.

esm: remove support for arrays in `import` internal method

---

benchmark/crypto/create-keyobject.js

Adds `crypto.createPrivateKey` and `crypto.createPublicKey` benchmarks for pem, der, and jwk inputs using rsa, ec, and ed25519 key fixtures.

benchmark: add crypto.create*Key

---

test/fixtures/wpt/README.md
test/fixtures/wpt/user-timing/idlharness-shadowrealm.window.js
test/fixtures/wpt/user-timing/mark-errors.any.js
test/fixtures/wpt/user-timing/measure-l3.any.js
test/fixtures/wpt/user-timing/measure_associated_with_navigation_timing.html
test/fixtures/wpt/user-timing/performance-measure-invalid.worker.js
test/fixtures/wpt/user-timing/resources/webperftestharness.js
test/fixtures/wpt/user-timing/structured-serialize-detail.any.js
test/fixtures/wpt/versions.json

Updates user-timing web-platform tests to latest.

test: update user-timing web-platform tests

---

test/fixtures/wpt/FileAPI/reading-data-section/filereader_readAsDataURL.any.js
test/fixtures/wpt/README.md
test/fixtures/wpt/versions.json

Updates FileAPI web-platform tests to latest.

test: update FileAPI web-platform tests

---

test/fixtures/wpt/README.md
test/fixtures/wpt/encoding/streams/stringification-crash.html
test/fixtures/wpt/encoding/unsupported-labels.window.js
test/fixtures/wpt/versions.json

Updates encoding web-platform tests to latest.

test: update encoding web-platform tests

---

doc/contributing/maintaining/maintaining-dependencies.md
tools/dep_updaters/update-acorn-walk.sh
tools/dep_updaters/update-acorn.sh
tools/dep_updaters/update-ada.sh
tools/dep_updaters/update-base64.sh
tools/dep_updaters/update-brotli.sh
tools/dep_updaters/update-c-ares.sh
tools/dep_updaters/update-cjs-module-lexer.sh
tools/dep_updaters/update-eslint.sh
tools/dep_updaters/update-googletest.sh
tools/dep_updaters/update-histogram.sh
tools/dep_updaters/update-icu.sh
tools/dep_updaters/update-libuv.sh
tools/dep_updaters/update-llhttp.sh
tools/dep_updaters/update-minimatch.sh
tools/dep_updaters/update-nghttp2.sh
tools/dep_updaters/update-nghttp3.sh
tools/dep_updaters/update-ngtcp2.sh
tools/dep_updaters/update-npm.sh
tools/dep_updaters/update-openssl.sh
tools/dep_updaters/update-postject.sh
tools/dep_updaters/update-simdutf.sh
tools/dep_updaters/update-undici.sh
tools/dep_updaters/update-uvwasi.sh
tools/dep_updaters/update-v8-patch.sh
tools/dep_updaters/update-zlib.sh
tools/dep_updaters/utils.sh

Add version to `doc/contributing/maintaining/maintaining-dependencies.md` dependencies list and automate the update
Refs: https://github.com/nodejs/security-wg/issues/973
Most of the duplicated code in all the dependencies updaters has been moved in the `utils.sh` file
This is the list of all the dependencies:

tools: add version to maintaining-dependencies.md dependencies list and automate the update

---

test/sequential/test-gc-http-client-timeout.js

Due to server response delay, all possible requests are created anyway. Instead of doing `36 * os.availableParallelism()` requests, use a fixed number.
Refs: https://github.com/nodejs/node/pull/48078#issuecomment-1568183115

test: refactor test-gc-http-client-timeout

---

test/js-native-api/.gitignore

Add `test_cannot_run_js/entry_point.c` to
`test/js-native-api/.gitignore`.

test: ignore the copied entry_point.c

---

lib/internal/modules/esm/load.js

Reduces unnecessary `new URL` call, and removes unnecessary invokes to `url.protocol`
Ref: https://github.com/nodejs/performance/issues/92

module: reduce url invocations in esm/load.js

---

lib/internal/http2/core.js
lib/internal/url.js
src/node_errors.h
src/node_url.cc
src/node_url.h

URL origin getter is quite a costly function. This pull request makes sure that there are only 1 js to C++ pass done for this operation.

lib: reduce URL invocations on http2 origins

---

lib/internal/test_runner/reporter/spec.js
lib/internal/test_runner/utils.js
lib/internal/util/colors.js
test/parallel/test-runner-coverage.js

Add a "table" parameter to getCoverageReport.
Keep the tap coverage output intact.
Change the output by adding padding and truncating the tables' cells. Add separation lines for table head/body/foot.
Group uncovered lines as ranges.
Add yellow color for coverage between 50 and 90.
Refs: https://github.com/nodejs/node/pull/46674

test_runner: refactor coverage report output for readability

---

test/parallel/test-net-autoselectfamily-commandline-option.js

If `CONFIG_IPV6` is disabled, the observed error on some platforms is `EAFNOSUPPORT` instead of `EADDRNOTAVAIL`.

test: fix `test-net-autoselectfamily` for kernel without IPv6 support

---

src/cares_wrap.cc

This is a potential alternative to PR https://github.com/nodejs/node/pull/48347 where I believe that there might be unsafe code, see comment https://github.com/nodejs/node/pull/48347#pullrequestreview-1463714114 I expect that this new code could be safer.
cc @anonrig @targos @ShogunPanda
Fixes https://github.com/nodejs/node/issues/48262

src: add missing to_ascii method in dns queries

---

test/embedding/embedtest.cc

GCC 14 drops some transitive includes within libstdc++. Explicitly include <algorithm> for std::find.
Signed-off-by: Sam James <sam@gentoo.org>

test: add missing <algorithm> include for std::find

---

lib/repl.js
test/parallel/test-repl.js

Fix for #48084 
```js
❯ ./out/Release/node
Welcome to Node.js v21.0.0-pre.
Type ".help" for more information.
> import {foo, bar} from 'mo';
import {foo, bar} from 'mo';
^^^^^^
Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import: const {foo,bar} = await import('mo');
```

repl: display dynamic import version in error message.

---

lib/internal/error_serdes.js
test/parallel/test-error-serdes.js

Fixes: https://github.com/nodejs/node/issues/48207

lib: add support for inherited custom inspection methods

---

src/quic/session.cc

quic: prevent copying ngtcp2_cid_token

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/name_pattern.js
test/fixtures/test-runner/output/name_pattern.snapshot
test/fixtures/test-runner/output/name_pattern_with_only.js
test/fixtures/test-runner/output/name_pattern_with_only.snapshot

Refs: https://github.com/nodejs/node/issues/46728#issuecomment-1581307787

test_runner: make `--test-name-pattern` recursive

---

lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/loader.js

The JSDoc here is outdated, some changes were forgotten when doing the last refactor PRs.

typings: fix JSDoc in ESM loader modules

---

lib/_http_server.js
lib/https.js
test/parallel/test-http-server-close-destroy-timeout.js
test/parallel/test-http-server-close-idle.js
test/parallel/test-https-server-close-destroy-timeout.js
test/parallel/test-https-server-close-idle.js

The connection checking interval should get cleared when `https.Server.close` is called similarly to how it gets cleared when `http.Server.close` is called. Note that this also adds a call to `closeIdleConnections()` to `https.server.close`.
Fixes https://github.com/nodejs/node/issues/48373

https: fix connection checking interval not clearing on server close

---

src/crypto/crypto_util.cc

The OPENSSL_FIPS guard is only needed for versions of OpenSSL earlier than 3.0.
Removing the guard for OpenSSL 3 fixes `parallel/test-crypto-fips` when run with a FIPS enabled OpenSSL 3 configuration.
Refs: https://github.com/nodejs/node/issues/48379
cc @nodejs/crypto 
--- 
- https://ci.nodejs.org/job/richardlau-node-test-commit-linux-containered/15/nodes=ubuntu2204_sharedlibs_openssl30fips_x64/testReport/junit/(root)/parallel/test_crypto_fips/
- https://ci.nodejs.org/job/richardlau-node-test-commit-linux-containered/15/nodes=ubuntu2204_sharedlibs_openssl30fips_x64/consoleFull
```console
13:27:29 not ok 640 parallel/test-crypto-fips
13:27:29   ---
13:27:29   duration_ms: 303.07300
13:27:29   severity: fail
13:27:29   exitcode: 1
13:27:29   stack: |-
13:27:29     Spawned child …
```

crypto: remove OPENSSL_FIPS guard for OpenSSL 3

---

doc/api/test.md
lib/internal/test_runner/test.js
lib/internal/test_runner/tests_stream.js
test/parallel/test-runner-reporters.js

Fixes https://github.com/nodejs/node/issues/46727

test_runner: add enqueue and dequeue events

---

doc/api/test.md

Follow-up for https://github.com/nodejs/node/pull/48428#discussion_r1227074474

doc: refine when file is undefined in test events

---

README.md

I have been contributing nodejs ecosystem over the last few years 
- contributions to help issues:
- through preveen-stack handle:
- https://github.com/nodejs/help/issues?q=is%3Aissue+commenter%3Apreveen-stack
- through wide4head handle:
- https://github.com/nodejs/help/issues?q=is%3Aissue+commenter%3Awide4head
- contributions to nodejs/help:
- https://github.com/nodejs/help/pulls?q=is%3Apr+author%3Apreveen-stack
- contributions to core:
- https://github.com/nodejs/node/issues?q=is%3Aissue+commenter%3Apreveen-stack
- https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Awide4head
I would like to get more involved and am looking forward to becoming a contributor
I have read through nodejs [code of conduct](https://github.com/nodejs/node/blob/HEAD/CONTRIBUTING.md) and promise to adhere to …

doc: add preveen-stack to triagers

---

lib/internal/abort_controller.js

lib: create weakRef only if any signals provided

---

doc/api/fs.md

Fixes: https://github.com/nodejs/node/issues/48452

doc: update fs flags documentation

---

lib/internal/repl/history.js

We use FileSytemWrite and FileSytemRead now.

lib: fix output message when repl is used with pm

---

src/node_http_parser.cc

This change is a fix for handling headersTimeout and requestTimeout
that causes unexpected behavior if the HTTP server is started on boot:
- the connections to the server can be closed immediately 
with the status HTTP 408
This issue usually happens in IoT or embedded devices where
the reference timestamp (returned by uv_hrtime()) is counted since boot
and can be smaller than the headersTimeout or the requestTimeout value.
Additionally added performance improvement to process the list of
connection only if one of the timers should be processed

http: fix for handling on boot timers headers and request 

---

.github/workflows/update-openssl.yml
tools/dep_updaters/update-openssl.sh

This PR allows updating openssl 1 on v16, for this to work the scripts (also utils.sh) need to be backported to v16

tools:  automate openssl update on v16

---

doc/api/packages.md

This PR would...
cc @guybedford 
follow up of #48407

Link to WinterCG Runtime Keys in export conditions docs

---

tools/dep_updaters/update-icu.sh

For cross-platform compatibility use perl instead of sed.
Fixes: https://github.com/nodejs/node/issues/48496

tools: replace sed with perl

---

src/node_report.cc
test/addons/report-api/test.js
test/common/report.js

There are no guarantees that the JS stack can be generated when no
context is entered. It is also invalid to call into JS if the current
context is missing.
Refs: https://chromium-review.googlesource.com/c/v8/v8/+/4582948
Fixes: https://github.com/nodejs/node-v8/issues/250

report: disable js stack when no context is entered

---

test/parallel/test-runner-watch-mode.mjs

Fixes https://github.com/nodejs/node/issues/48065
this skip exists in 21 other places: https://github.com/search?q=repo%3Anodejs%2Fnode+%22IBMi+does+not+support+%60fs.watch%28%29%60%22&type=code

test: skip test-runner-watch-mode on IBMi

---

lib/events.js
lib/internal/event_target.js
test/parallel/test-events-once.js
test/parallel/test-eventtarget.js

Refs: https://github.com/whatwg/dom/pull/1152#issuecomment-1534337511

lib: add option to force handling stopped events

---

test/parallel/test-http2-endafterheaders.js

The value of check depends on whether the value of headers [': method'] is equal to "GET". The first statement uses the Ternary operation to achieve this. My change uses a simple comparison expression.

http: remove useless ternary in test

---

src/node_options.cc
src/node_v8_platform-inl.h
src/permission/fs_permission.cc
src/util.cc
src/util.h

See [quick-bench.com](https://quick-bench.com/q/mhyUI8Swxu3As-RafVUSVfEZd64)
<details>
<summary>benchmark code</summary>
```cpp
#include <string_view>
#include <algorithm>
// uses string::find_first_of
std::vector<std::string>
split(const std::string& str, const std::string& delims = " ")
{
std::vector<std::string> output;
//output.reserve(str.length() / 4);
size_t first = 0;
while (first < str.size())
{
const auto second = str.find_first_of(delims, first);
if (first != second)
{
output.emplace_back(str.substr(first, second-first));
}
if (second == std::string::npos)
break;
first = second + 1;
}
return output;
}
std::vector<std::string>
splitStd(const std::string& str, const std::string& delims = " ")
{
std::vector<std::string> output;
auto first = std::cbegin(str);
while (first != …
```

src: refactor `SplitString` in util

---

lib/internal/main/check_syntax.js

Removes the duplicated require in `url` and `internal/url` as well as `internal/options`

lib: remove duplicated requires in check_syntax

---

typings/primordials.d.ts

This pull request removes unused and confusing primordials such as ArrayLength which corresponds to Array.length, and even though it is not used at all it is often get confused by Array.prototype.length.

typings: remove unused primordials

---

doc/api/module.md
lib/internal/source_map/source_map.js
test/parallel/test-source-map-api.js

This adds the `SourceMap.findOrigin(lineNumber, columnNumber)` method, for finding the origin source file and 1-indexed line and column numbers corresponding to the 1-indexed line and column numbers from a call site in generated source code.
Fix: #47770

module: Add SourceMap.findOrigin

---

doc/api/util.md

This change is needed for the correct processing `json` files generated from doc.

doc: unnest `mime` and `MIMEParams` from MIMEType constructor

---

doc/api/fs.md

[By doc](https://nodejs.org/dist/latest-v20.x/docs/api/fs.html#filename-argument):
> Providing `filename` argument in the callback is only supported on Linux,
macOS, Windows, and AIX. Even on supported platforms, `filename` is not always
guaranteed to be provided. Therefore, don't assume that `filename` argument is
always provided in the callback, and have some fallback logic if it is `null`.
So I added `null` to type to do it more clearly

doc: fix `filename` type in `watch` result

---

lib/internal/modules/helpers.js

Reduce calling getters of URL due to the lazy loading of URL.
Ref: https://github.com/nodejs/performance/issues/92

lib: reduce url getters on `makeRequireFunction`

---

lib/internal/streams/pipeline.js
test/parallel/test-stream-pipeline.js

Fixes: https://github.com/nodejs/node/issues/48406

stream: fix premature pipeline end

---

test/.eslintrc.yaml
test/parallel/test-child-process-execfile.js
test/parallel/test-fs-promises-readfile.js
test/parallel/test-fs-readfile.js
test/parallel/test-http2-client-http1-server.js
test/parallel/test-https-agent-session-injection.js
test/parallel/test-readline-interface.js
test/parallel/test-stream-filter.js
test/parallel/test-stream-flatMap.js
test/parallel/test-stream-forEach.js
test/parallel/test-stream-readable-destroy.js
test/parallel/test-stream-readable-next-no-null.js
test/parallel/test-stream-some-find-every.mjs
test/parallel/test-worker-data-url.js

test: remove unnecessary noop function args to `musNotCall()`

---

configure.py
node.gyp

Add the list of linked modules to the arguments for `js2c.py`. These were unintentionally omitted when the build was previously refactored to avoid command line length limits on Windows.
Fixes: https://github.com/nodejs/node/issues/42302
Refs: https://github.com/nodejs/node/pull/39069

build: fix `configure --link-module`

---

node.gyp
tools/js2c.cc

Incremental compilation of Node.js is slow. Currently on a powerful Linux machine, it takes about 9 seconds and 830 MB of memory to compile `gen/node_javascript.cc` with g++. This is the longest step when recompiling a small change to a Javascript file.
`gen/node_javascript.cc` contains a lot of large binary literals of our Javascript source code. It is well-known that embedding large binary literals as C/C++ arrays is slow. One workaround is to include the data as string literals instead. This is particularly nice for the Javascript included via js2c, which look better as string literals anyway.
Add a new flag `--use-string-literals` to js2c. When this flag is set, we emit string literals instead of array literals, i.e.:
```c++
// old: static const uint8_t X[] = { ... };
static const …
```

tools: speedup compilation of js2c output

---

lib/fs.js
lib/internal/fs/recursive_watch.js
lib/internal/fs/watchers.js
lib/internal/test_runner/mock/mock_timers.js
lib/internal/test_runner/runner.js
lib/internal/test_runner/test.js
lib/timers/promises.js

fs, test_runner, timers: Use `kResistStopPropagation` where applicable

---

test/cctest/test_linked_binding.cc

Include node.h first to define NAPI_VERSION that node binary is built
with. The node.h should also be included first in embedder's use case
since it is the primary header file.
Fixes https://github.com/nodejs/node/issues/48310

test: define NAPI_VERSION before including node_api.h

---

doc/api/webstreams.md

Refs: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream

doc: add description of autoAllocateChunkSize in ReadableStream

---

test/cctest/node_test_fixture.cc
test/cctest/node_test_fixture.h
test/cctest/test_environment.cc
test/cctest/test_node_api.cc
test/cctest/test_report.cc

This ensures that we only create one IsolateData for each isolate inthe cctest, since IsolateData are meant to be per-isolate. We need to make the isolate and isolate_data static in the test fixtures as a result, similar to how the event loops and array buffer allocators are managed in the
NodeZeroIsolateTestFixture but it is fine because gtest ensures that the Setup() and TearDown() of the fixtures are always run in order and would never overlap in one process.

test: make IsolateData per-isolate in cctest

---

test/parallel/parallel.status

Refs: https://github.com/nodejs/node/issues/48300#issuecomment-1604531463
Refs: https://github.com/nodejs/reliability/issues/597#issue-1772339022

test: mark test-child-process-stdio-reuse-readable-stdio flaky

---

doc/api/fs.md
doc/api/stream.md
lib/internal/fs/promises.js
lib/internal/per_context/primordials.js
lib/internal/process/pre_execution.js
lib/internal/streams/readable.js
test/parallel/test-fs-promises-file-handle-dispose.js
test/parallel/test-stream-readable-dispose.js
typings/primordials.d.ts

Both TypeScript and Bable already support `using` ([explicit resource management proposal](https://github.com/tc39/proposal-explicit-resource-management)),
adding this to node will be convenient
Co-authored-by: Benjamin Gruenbaum <benjamingr@gmail.com>

fs, stream: add initial `Symbol.dispose` and `Symbol.asyncDispose` support

---

src/permission/fs_permission.cc
src/permission/fs_permission.h
test/parallel/test-permission-fs-wildcard.js

When two paths overlaps, the permission model returns a false negative cause the Node* doesn't contain an empty child ("") to consider it as an end node. For instance, if you call `--allow-fs-read=/home/index.js,/home/index.json` and call process.permission.has for both paths, it will return false for the `index.js` since it will create the following radix tree:
```
Child /
Prefix: /home/index.js
Child o
Prefix: on
End of tree: on
End of tree(c): /home/index.js
End of tree(c):
```
and if you invert the parameters order: `--allow-fs-read=/home/index.json,/home/index.js` it will create an empty child for "/home/index.js" indicating "end node".
To handle it I've included a new parameter to `Node*`: `is_leaf`.

permission: handle end nodes with children cases

---

doc/api/net.md
lib/internal/cluster/child.js
lib/net.js
test/parallel/test-cluster-net-server-drop-connection.js
test/parallel/test-net-server-drop-connections.js

[server.maxConnections](https://nodejs.org/api/net.html#servermaxconnections) is an `Integer`, and so, I'd expect `0` to behave the same as `-1`; ie, drop all incoming conns.
(this is my first commit: I may have messed it up. I skimmed `contributing.md` but didn't pay much attention to it given this is a straight-forward fix... or, so I think)

server.maxConnections = 0 is treated as if its unset

---

lib/internal/fs/sync_write_stream.js
test/parallel/test-internal-fs-syncwritestream.js

The `writable._write()` implementation does not need to return anything, only call the callback.

fs: remove unneeded return statement

---

lib/internal/fs/sync_write_stream.js
test/parallel/test-internal-fs-syncwritestream.js

Fixes: https://github.com/nodejs/node/issues/47948

fix: callback with error if SyncWriteStream writeSync failed

---

lib/net.js
test/internet/test-https-autoselectfamily-slow-timeout.js
test/internet/test-net-autoselectfamily-timeout-close.js
test/internet/test-tls-autoselectfamily-backing-socket.js

This PR fixes network family autoselections in three area:
1. Moves handle swapping before trying a new connection, as suggested in https://github.com/npm/cli/issues/6409#issuecomment-1577019656
2. Avoids spawning two different connection attempts, which could happen if a `TLSSocket` with a manually set backing `Socket` was used. See: https://github.com/KararTY/dank-twitch-irc/issues/13#issuecomment-1591251579
3. Correctly handles `AbortSignal` when using network family auto selection.
Fixes: https://github.com/npm/cli/issues/6409
Fixes: https://github.com/KararTY/dank-twitch-irc/issues/13
Fixes: #47644 
CC: @tniessen @silverwind

net: improve network family autoselection handle handling

---

src/quic/session.cc

The existing code explicitly uses the `CID(const ngtcp2_cid*)` constructor that does not copy the given `ngtcp2_cid`, but the range-based for loop still unnecessarily copies the `ngtcp2_cid`. Use `auto&` to avoid copying.

quic: prevent copying ngtcp2_cid

---

benchmark/bar.R
doc/contributing/writing-and-running-benchmarks.md

I'm working on a few Node.js benchmarks and generating a barplot is quite helpful for comparisons when the standard deviation is slight. I'm using the `bar.R` in my next report and I thought would be good to have it available in the benchmark folder.
Example:

benchmark: add bar.R

---

doc/api/errors.md
doc/api/tls.md
lib/_tls_wrap.js
lib/internal/errors.js
src/crypto/crypto_tls.cc
src/crypto/crypto_tls.h
src/env_properties.h
test/parallel/test-tls-alpn-server-client.js

This is an alternate fix for #45056 (which replaces #45075).
I'd definitely appreciate careful reviewing of the native parts of this, I'm not familiar with a lot of the standard approaches and concerns there and this is definitely more complex than the other approach.
A few open questions:
* ~~I've used `serverName` as the field for the server name that's passed to the callback. Some of the existing API uses `servername` instead, but that casing seems very odd. Which do we prefer?~~ Resolved in favour of `servername`
* The implementation here throws an error if the server callback returns a string that isn't in the client's offered protocols. Reading the RFC that's _implicitly_ what you should do, but I don't think it's strictly required - it's weird but not 100% invalid as far as I can …

tls: add ALPNCallback server option for dynamic ALPN negotiation

---

src/node_v8_platform-inl.h

This commit fixes the latest Coverity scan mentioning unnecessary copy in for loop.

src: fix Coverity issue regarding unnecessary copy

---

doc/api/test.md

Fixes: https://github.com/nodejs/node/issues/48571

doc: update return type for describe

---

doc/api/test.md
lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers.js

Support Symbol.dispose in mock timers. Letting users of TS/Babel (and everyone else as soon as v8 ships) use `using` with the mock timers.
cc @ErickWendel @nodejs/test_runner

test: add Symbol.dispose support to mocktimers

---

lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/package_config.js
lib/internal/modules/esm/resolve.js
lib/internal/modules/package_json_reader.js
lib/internal/url.js
lib/url.js
src/node_file.cc
test/fixtures/errors/force_colors.snapshot
test/parallel/test-bootstrap-modules.js
test/parallel/test-module-binding.js
test/parallel/test-module-loading-error.js

This PR contains a refactor to merge package.json reader caches in both CJS and ESM.
I extracted the relevant parts from https://github.com/nodejs/node/pull/47991.
cc @nodejs/loaders @nodejs/modules 
PS: This PR has no effect on execution speed.
```
hyperfine './out/Release/node ../fastify/fastify.js' 'node ../fastify/fastify.js' 'bun ../fastify/fastify.js' -i --warmup 10
Benchmark 1: ./out/Release/node ../fastify/fastify.js
Time (mean ± σ):      88.3 ms ±   1.8 ms    [User: 85.5 ms, System: 20.3 ms]
Range (min … max):    84.7 ms …  94.8 ms    33 runs
Benchmark 2: node ../fastify/fastify.js
Time (mean ± σ):      88.8 ms ±   2.1 ms    [User: 83.2 ms, System: 21.8 ms]
Range (min … max):    84.0 ms …  95.0 ms    33 runs
Benchmark 3: bun ../fastify/fastify.js
Time (mean ± σ):      99.6 ms ± …
```

lib: merge cjs and esm package json reader caches

---

doc/contributing/security-release-process.md

@bengl Would you mind if I take over the next sec release too? I'm working in parallel on https://github.com/nodejs/security-wg/issues/860 and I need to test if that's working.

doc: update security release stewards

---

test/parallel/test-runner-cli.js

Seen these were added at https://github.com/nodejs/node/pull/48584

test: add missing assertions to test-runner-cli

---

lib/_http_common.js
test/parallel/test-http-parser-memory-retention.js

Null the `joinDuplicateHeaders` property when the parser is freed.
Refs: https://github.com/nodejs/node/pull/45982

http: null the joinDuplicateHeaders property on cleanup

---

doc/api/http.md

Move the `joinDuplicateHeaders` option to the correct alphabetical order.

doc: fix options order

---

lib/internal/test_runner/harness.js
test/parallel/test-runner-typechecking.js

`todo`, `only` and `skip` are shorthands for `test`, so all of them should return the same type.
Currently `todo()` returns `undefined` while `test({ todo: true })` returns a `Promise` that resolves to `undefined`.

test_runner: todo, only, skip are expected to return a Promise

---

src/env.cc
src/env.h

This fixes an issue that was surfaced by an address sanitizer (asan) run:
```
.../cxx_atomic_impl.h:387:12: runtime error: load of value 171, which is not a valid value for type 'bool'
#0 0x56532ea65fab in can_call_into_js src/env-inl.h:614
#1 0x56532ea65fab in node::AsyncHooks::clear_async_id_stack() src/env.cc:171:14
#2 0x56532eab1aed in node::AsyncHooks::AsyncHooks(v8::Isolate*, node::AsyncHooks::SerializeInfo const*) src/env.cc:1393:5
#3 0x56532eaa8ea0 in node::Environment::Environment(node::IsolateData*, v8::Isolate*, std::__u::vector<std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char>>, std::__u::allocator<std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char>>>> const&, std::__u::vector<std::__u::basic_string<char, …
```

src: Initialize fields accessed by AsyncHooks before AsyncHooks

---

src/crypto/crypto_common.cc
src/crypto/crypto_common.h
src/crypto/crypto_x509.cc

Reorder arguments of internal helper functions such that their order is consistent across X509 property getters. Add `ReturnPropertyThroughBIO()` and `ReturnProperty()`. Use these new helpers to deduplicate code across various X509 property getters.
As usual, a lot of the diff is just to appease the `format-cpp` job.

src: deduplicate X509 getter implementations

---

src/quic/session.cc

Value of the `nwrite` variable will always be less than 0 when it reaches the `switch` statement because of the previous check, which causes `case 0` to never be executed, change the check to allow 0 or less.

src: fix logically dead code reported by Coverity

---

lib/internal/modules/package_json_reader.js
test/sequential/test-module-loading.js

module: harmonize error code between ESM and CJS

---

lib/internal/process/report.js
src/heap_utils.cc
src/node_report.cc
test/parallel/test-permission-fs-write-report.js
test/parallel/test-permission-fs-write-v8.js

Even though the permission model, for now, doesn't handle other scopes than the node:fs module. Adding this validation on common write operations seems reasonable.
Co-Authored-By: @haxatron

permission: v8.writeHeapSnapshot and process.report

---

.eslintrc.js
doc/api/globals.md
lib/.eslintrc.yaml
lib/internal/bootstrap/web/exposed-window-or-worker.js
lib/internal/navigator.js
test/common/index.js
test/parallel/test-bootstrap-modules.js
test/parallel/test-global.js
test/parallel/test-navigator.js

I'm following up on an abandoned pull request, and adding authors as the co-author to this pull request. 
I've simplified and only added `navigator.hardwareConcurrency` right now, to receive feedback, understand any blockers before investing more time on it.
Referencing issue: https://github.com/nodejs/node/issues/39540
Follow up of the pull request: https://github.com/nodejs/node/pull/39581

lib: add `navigator.hardwareConcurrency`

---

doc/api/cli.md
doc/api/test.md
doc/node.1
lib/internal/main/test_runner.js
lib/internal/test_runner/runner.js
src/node_options.cc
src/node_options.h
test/fixtures/test-runner/shards/a.cjs
test/fixtures/test-runner/shards/b.cjs
test/fixtures/test-runner/shards/c.cjs
test/fixtures/test-runner/shards/d.cjs
test/fixtures/test-runner/shards/e.cjs
test/fixtures/test-runner/shards/f.cjs
test/fixtures/test-runner/shards/g.cjs
test/fixtures/test-runner/shards/h.cjs
test/fixtures/test-runner/shards/i.cjs
test/fixtures/test-runner/shards/j.cjs
test/parallel/test-runner-cli.js
test/parallel/test-runner-run.mjs

test_runner: add shards support

---

lib/internal/process/pre_execution.js
src/node_options.cc
test/cctest/test_environment.cc

Do not install experimental web globals when the environment is
initialized with embedder flag
`node::EnvironmentFlags::kNoBrowserGlobals`.

bootstrap: hide experimental web globals with flag kNoBrowserGlobals

---

doc/api/timers.md
lib/internal/per_context/primordials.js
lib/timers.js
test/parallel/test-timers-dispose.js

this does not change the behavior of `node:timers/promises`.

timers: support `Symbol.dispose`

---

doc/api/globals.md

doc: fix 'partial' typo

---

test/parallel/parallel.status

This reverts commit 893c000046998a6337977ac03158bffc560478b0.
Refs: https://github.com/nodejs/node/pull/48575#issuecomment-1620267554

Revert "test: remove test-crypto-keygen flaky designation"

---

doc/api/events.md
lib/events.js
test/parallel/test-events-add-abort-listener.mjs
tools/doc/type-parser.mjs

I am not sure this is the correct way to expose such a util, ~and I still need to add docs and UT~, just wanted to get some feedback first 🙂 
Refs: https://github.com/nodejs/node/pull/48550#issuecomment-1612702494
@mcollina @benjamingr CC

events: allow safely adding listener to abortSignal

---

lib/internal/http2/core.js
test/parallel/test-http2-client-destroy.js

http2: send RST code 8 on AbortController signal

---

lib/internal/modules/package_json_reader.js
src/node_file.cc
test/parallel/test-module-binding.js
test/parallel/test-module-loading-error.js

Follow up on https://github.com/nodejs/node/pull/48477. This is a semver-major change.

lib: remove aix directory case for package reader

---

doc/api/stream.md

Edited / fixed version of https://github.com/nodejs/node/pull/48653
Clarified that `stream.Transform` callback second argument is passed only if the first argument is `null`, i.e. no error occured processing the chunk.
From the way the documentation is written right now, I expected the second argument to be forwarded to `transform.push()`, even if the first argument is an `Error`. I was implementing a truncation stream, and passed both an `Error` ("stream exceeded maximum size"; could be optionally caught and ignored), and the last (truncated) chunk. Only after digging through [the relevant implementaton](https://github.com/nodejs/node/blob/b40f0c30743aaecd57071f7be305df43e1083817/lib/internal/streams/transform.js#L176) I could confirm for sure that the second argument is entirely ignored …

doc: clarify transform._transform() callback argument logic

---

lib/events.js
test/parallel/test-events-listener-count-with-listener.js

When add listener by once, it will be wrapped into another function. And when pass listener and there is just one event listener added by once, it will return 0 even if passed listener equal wrapped event listener.
This bug is included in https://github.com/nodejs/node/pull/46523
Refs: https://github.com/nodejs/node/pull/46523
```javascript
const ee = new EventEmitter()
const listener = () => undefined
ee.once('event', listener)
console.log('ee.listenerCount("event",listener)', ee.listenerCount('event', listener))
```
And it will output like this:

events: fix bug listenerCount don't compare wrapped listener

---

lib/internal/process/pre_execution.js

Followup to #48518; fixes #48699
Happy to add a test if needed - but I both wasn't sure where it would go, and I also wasn't sure if this was worth testing since node rarely polyfills JS builtins and v8 will supply it soon enough anyways (backed by test262)

bootstrap: polyfill Symbol.dispose/Symbol.asyncDispose with correct descriptor

---

lib/internal/streams/readable.js
test/parallel/test-stream-pipe-deadlock.js

When piping a paused Readable to a full Writable we didn't  register a drain listener which cause the src to never resume.
Refs: https://github.com/nodejs/node/issues/48666

stream: fix deadlock when pipeing to full sink 

---

common.gypi

Fixes target toolchain arguments being passed to the host toolchain when cross-compiling. For example, -m64 is not available on aarch64.
See also https://github.com/NixOS/nixpkgs/pull/238377#discussion_r1245148404

build: do not pass target toolchain flags to host toolchain

---

src/cleanup_queue-inl.h
src/cleanup_queue.cc
src/cleanup_queue.h

Previously we just rely on the unordered_set order to iterate over the BaseObjects, which is not deterministic.
The iteration is only used in printing, verification, and snapshot generation. In the first two cases the performance overhead of sorting does not matter because they are only used for debugging. In the last case the determinism is more important than the trivial overhead of sorting. So this patch makes the iteration deterministic by sorting the set first, as what is already being done when we drain the queue.
Refs: https://github.com/nodejs/build/issues/3043

src: make BaseObject iteration order deterministic

---

doc/api/module.md
lib/internal/source_map/source_map.js
lib/internal/source_map/source_map_cache.js
test/parallel/test-source-map-api.js

module: add SourceMap.lineLengths

---

README.md

Fixes: https://github.com/nodejs/node/pull/48603

doc: add atlowChemi to collaborators

---

test/parallel/test-string-decoder.js

I first noticed `test-string-decoder` failing in CI [here](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/21850/). Although it failed with VS2022-produced Node.js binaries, when I tested locally I noticed it was coming up with the same failure on VS2019 too. The only constant is that it happens sometimes and only on x86.
After investigating, this is what I found: in some cases, [this error](https://github.com/nodejs/node/blob/c3468322cfc179da2ea593fe25628e8db4c18d08/deps/v8/src/builtins/builtins-arraybuffer.cc#L104) was thrown instead of the expected one. Further down the call stack, [this line](https://github.com/nodejs/node/blob/c3468322cfc179da2ea593fe25628e8db4c18d08/deps/v8/src/objects/backing-store.cc#L327) is the root of the issue. It uses …

test: fix flaky test-string-decode.js on x86

---

lib/child_process.js
test/parallel/test-child-process-prototype-tampering.mjs

Improve robustness against something like
```mjs
Object.assign(Object.prototype, {
cwd: '/etc',
uid: 82, // www-data
execFile: '/bin/rm', // using rm to "spawn" modules
execArgv: [ ... ],
shell: '...',
env: { ... },
...
});
```

child_process: harden against prototype pollution

---

src/permission/fs_permission.cc

* The first argument `node` should be a const pointer.
* The second argument `spaces` should not be a signed integer type.
* The local variable `child` should be size_t.
* The local variable `pair` in the range declaration should be a reference type to avoid copying the object.
Refs: https://github.com/nodejs/node/pull/48677

permission: fix data types in PrintTree

---

doc/contributing/collaborator-guide.md

Document the choice of squashing and rebasing when landing a pull request containing more than one subsystem commits.
Refs: https://github.com/nodejs/node/pull/47956#issuecomment-1631783652

doc: expand on squashing and rebasing to land a PR

---

lib/internal/url.js
test/wpt/status/url.json

Mark URL/URLSearchParams as uncloneable and untransferable to reject
them in `structuredClone` and `port.postMessage`.
Refs: https://github.com/nodejs/node/pull/47214
/cc @anonrig

lib: mark URL/URLSearchParams as uncloneable and untransferable

---

lib/internal/util/inspect.js

Found a part of `identicalSequenceRange` that uses a mutable method
Changed it to use the primordial instead

util: Use `primordials.ArrayPrototypeIndexOf` instead of mutable method

---

src/util.cc
src/util.h

NewFromUtf8 takes a size parameter, and replacing char* with std::string_view gives us the size of the string, without an overhead. Additionally, I've added `constexpr` qualifier to `ToStringView()` function.

src: use string_view for utf-8 string creation

---

src/util.h

This PR removes OnScopeLeaveImpl's move assignment overload as it's not valid implementation and also has not been used

src: remove OnScopeLeaveImpl's move assignment overload

---

test/parallel/test-experimental-shared-value-conveyor.js

The test test/parallel/test-experimental-shared-value-conveyor.js was added to test the --harmony-struct feature of V8. However, when used with pointer compression, the process crashes. This commit skips the test for pointer compression builds. This change uses a child process because starting a Node pointer compression build with --harmony-struct immediately crashes the process. Once this crash is addressed, this commit can be reverted.
Refs: https://github.com/nodejs/build/issues/3204#issuecomment-1550411656

test: skip experimental test with pointer compression

---

doc/api/inspector.md
lib/inspector.js
test/parallel/test-inspector-open-dispose.mjs

inspector: open add `SymbolDispose`

---

doc/contributing/security-release-process.md

nodejs/tweet is now archived. Currently, the approach is to ping nodejs social team on Slack (Kylie specifically)

doc: remove nodejs/tweet mention

---

lib/internal/url.js

My local benchmarks show the following changes:
```
url/whatwg-url-to-and-from-path.js n=1000000 method='fileURLToPath' input='file:///dev/null?key=param&bool'             ***     12.59 %       ±1.21% ±1.62% ±2.12%
url/whatwg-url-to-and-from-path.js n=1000000 method='fileURLToPath' input='file:///dev/null?key=param&bool#hash'        ***      9.72 %       ±0.70% ±0.94% ±1.22%
url/whatwg-url-to-and-from-path.js n=1000000 method='fileURLToPath' input='file:///dev/null'                            ***     18.85 %       ±1.02% ±1.36% ±1.78%
url/whatwg-url-to-and-from-path.js n=1000000 method='pathToFileURL' input='file:///dev/null?key=param&bool'             ***     11.93 %       ±0.78% ±1.04% ±1.35%
url/whatwg-url-to-and-from-path.js n=1000000 …
```

url: reduce `pathToFileURL` cpp calls

---

.github/PULL_REQUEST_TEMPLATE.md

When someone triple clicks to select the URL, they will result a 404 page because of the inclusion of the dot at the end

fix: pr template CONTRIBUTING.md url

---

lib/internal/main/eval_string.js
lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/loader.js
lib/internal/process/esm_loader.js
test/es-module/test-esm-loader-hooks.mjs
test/es-module/test-esm-loader-mock.mjs
test/fixtures/es-module-loaders/mock-loader.mjs

This started as a revert of 938341ac61333d898f9aadd17a4fc87373d97f3c.
#44710 removed `setImportMetaCallback`, removing possibility for hooks authors to modify the `import.meta` object. It also removed all hooks execution when node entry point was not a file (e.g. REPL, `--eval`, etc.) which was not a problem except for `globalPreload` which is always supposed to run. I've added some tests to ensure `globalPreload` behaves correctly in this case.
I've also added back the test that was removed in https://github.com/nodejs/node/pull/46402 because it's good test for `globalPreload` and ensures mocking works – which is a very important use case for hooks IMO.
Refs: https://github.com/nodejs/node/pull/46402
Fixes: https://github.com/nodejs/node/issues/48778
Fixes: …

esm: add back `globalPreload` tests

---

doc/api/webstreams.md
lib/internal/webstreams/readablestream.js
lib/internal/webstreams/util.js
test/fixtures/wpt/README.md
test/fixtures/wpt/streams/piping/general-addition.any.js
test/fixtures/wpt/streams/readable-streams/from.any.js
test/fixtures/wpt/streams/readable-streams/owning-type-message-port.any.js
test/fixtures/wpt/streams/readable-streams/owning-type-video-frame.any.js
test/fixtures/wpt/streams/readable-streams/owning-type.any.js
test/fixtures/wpt/streams/readable-streams/read-task-handling.window.js
test/fixtures/wpt/streams/transferable/transform-stream-members.any.js
test/fixtures/wpt/streams/transform-streams/invalid-realm.tentative.window.js
test/fixtures/wpt/versions.json
test/wpt/status/streams.json

Implements `ReadableStream.from`
Updating the WPTs add a lot of new tests, and failures that weren't relevant to this PR, I have added them to expected failures.
Please do take a look at the node errors used, I have used `ERR_INVALID_STATE.TypeError` in all the places since all the webstreams code seems to be reliant on that.
Fixes: https://github.com/nodejs/node/issues/48389

stream: implement ReadableStream.from

---

src/env.cc

Adding the per-realm binding data tracking introduced a call to a realm method when realm was potentially null. This is triggered whenever the function is called from `ContextifyContext::New` which passes `nullptr` as the `realm`.

src: fix nullptr access on realm

---

doc/api/n-api.md

- refactor table so that it does not grow for every new version of Node.js
- refer to latest version of table as the canonical reference
- add info for Node-API v9
Refs: https://github.com/nodejs/node/issues/48277

doc: refactor node-api support matrix

---

doc/api/errors.md
lib/internal/errors.js
lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/initialize_import_meta.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/module_job.js
lib/internal/modules/esm/utils.js
test/es-module/test-esm-loader-chaining.mjs
test/es-module/test-esm-loader-programmatically.mjs
test/fixtures/es-module-loaders/loader-load-dynamic-import.mjs
test/fixtures/es-module-loaders/loader-resolve-dynamic-import.mjs

Major functional changes:
- Allow `import()` to work within loaders that require other loaders,
- Unflag the use of `Module.register`.
A new interface `Customizations` has been created in order to unify `ModuleLoader` (previously `DefaultModuleLoader`), `Hooks` and `CustomizedModuleLoader` all of which now implement it:
```ts
interface LoadResult {
format: ModuleFormat;
source: ModuleSource;
}
interface ResolveResult {
format: string;
url: URL['href'];
}
interface Customizations {
allowImportMetaResolve: boolean;
load(url: string, context: object): Promise<LoadResult>
resolve(
originalSpecifier:
string, parentURL: string,
importAssertions: Record<string, string>
): Promise<ResolveResult>
resolveSync(
originalSpecifier:
string, parentURL: string,
importAssertions: Record<string, string>
) …
```

esm: unflag `Module.register` and allow nested loader `import()`

---

src/cleanup_queue-inl.h

The `emplace` already can create the `CleanupHookCallback` in place

src: remove unnecessary temporary creation

---

doc/api/single-executable-applications.md
lib/internal/main/mksnapshot.js
lib/internal/process/pre_execution.js
src/node.cc
src/node_main_instance.cc
src/node_sea.cc
src/node_sea.h
src/node_snapshotable.cc
test/sequential/test-single-executable-application-snapshot.js

Refs: https://github.com/nodejs/single-executable/discussions/57
This patch adds snapshot support to single executable applications.
To build a snapshot from the main script when preparing the
blob that will be injected into the single executable application,
add `"useSnapshot": true` to the configuration passed to
`--experimental-sea-config`. For example:
```
{
"main": "snapshot.js",
"output": "sea-prep.blob",
"useSnapshot": true
}
```
The main script used to build the snapshot must invoke
`v8.startupSnapshot.setDeserializeMainFunction()` to configure the
entry point. The generated startup snapshot would be part of the
preparation blob and get injected into the final executable.
When the single executable application is launched, instead of running
the `main` script from scratch, Node.js …

sea: snapshot support in single executable applications

---

lib/internal/perf/utils.js
lib/internal/process/pre_execution.js
src/env.cc
src/node_perf.cc
src/node_perf_common.h

Previously we cache the time origin for the milestones in the user land, and refresh it at pre-execution. As result the time origin gets serialized into the snapshot and is therefore not deterministic. Now we store it in the milestone array as an internal value and reset the milestones at serialization time instead of deserialization time. This improves the determinism of the snapshot.
Drive-by: remove the unused MarkMilestone() binding.
Refs: https://github.com/nodejs/build/issues/3043

src: save the performance milestone time origin in the AliasedArray

---

doc/api/test.md

This PR updates the documentation for the `test:fail` event as highlighted by https://github.com/nodejs/node/issues/48840

docs: fix test_runner `test:fail` event type

---

lib/internal/fs/promises.js

JSDoc update was omitted during code implementation
Refs: https://github.com/nodejs/node/pull/46933

fs: sync JSDoc with the actual implementation

---

src/cares_wrap.cc

Since error messages are also using defined values, it is more clear to use the defined value even when the operation succeeds.

src: use ARES_SUCCESS instead of 0

---

src/permission/fs_permission.cc

This function is not declared outside of `fs_permission.cc` and thus should not be visible outside the file during the linking stage.

permission: move PrintTree into unnamed namespace

---

src/js_native_api_v8.h

Even though the redefinition complies with the C standard because the second definition is "effectively the same" as the first definition, it's best to avoid any redefinition.
The first definition is here:
https://github.com/nodejs/node/blob/b68fa599607f69f2ce3b1a3104e0d5984f6bc0d8/src/js_native_api_v8.h#L183-L189
The definition that is being removed is here:
https://github.com/nodejs/node/blob/b68fa599607f69f2ce3b1a3104e0d5984f6bc0d8/src/js_native_api_v8.h#L271-L277
Refs: https://github.com/nodejs/node/pull/28237
Refs: https://github.com/nodejs/node/pull/30006

node-api: avoid macro redefinition

---

lib/_http_server.js
lib/https.js
test/parallel/test-http-server-connections-checking-leak.js
test/parallel/test-https-server-connections-checking-leak.js

This PR fixes a memory leak by checking HTTP connections only if the server is listening.
Fixes: #48604.

http: start connections checking interval on listen

---

doc/api/test.md

change duration to duration_ms in test documentation
Fixes: https://github.com/nodejs/node/issues/48887

doc: change duration to duration_ms on test documentation

---

doc/api/single-executable-applications.md
lib/internal/modules/cjs/loader.js
lib/internal/util/embedding.js
src/json_parser.cc
src/json_parser.h
src/node_contextify.cc
src/node_contextify.h
src/node_sea.cc
src/node_sea.h
src/node_snapshotable.cc
src/util.cc
src/util.h
test/fixtures/errors/force_colors.snapshot
test/fixtures/sea.js
test/parallel/test-bootstrap-modules.js
test/sequential/test-single-executable-application-use-code-cache.js

This improves the startup performance of SEAs.
For example, the comparison of the startup performance benchmarks of a Node.js SEA built using the CJS bundle of Yarn's source code shows a 24% improvement on my `x86_64` macOS:
```js
$ hyperfine -N -w 30 -L cmd 'with_code_cache/yarn help','without_code_cache/yarn help' '{cmd}'
Benchmark 1: with_code_cache/yarn help
Time (mean ± σ):     210.8 ms ±   1.3 ms    [User: 224.0 ms, System: 25.2 ms]
Range (min … max):   209.0 ms … 213.4 ms    14 runs
Benchmark 2: without_code_cache/yarn help
Time (mean ± σ):     279.1 ms ±   2.3 ms    [User: 284.9 ms, System: 30.1 ms]
Range (min … max):   276.6 ms … 284.4 ms    10 runs
Summary
'with_code_cache/yarn help' ran
1.32 ± 0.01 times faster than 'without_code_cache/yarn help'
```
Fixes: …

sea: add support for V8 bytecode-only caching

---

doc/api/fs.md
lib/fs.js
lib/internal/fs/promises.js
lib/internal/fs/utils.js
test/parallel/test-child-process-reject-null-bytes.js
test/parallel/test-fs-mkdtemp.js
test/parallel/test-fs-whatwg-url.js

`mkdtemp()` seems to be the only `fs` method that doesn't support `URL` objects yet.

fs: make `mkdtemp` accept buffers and URL

---

doc/api/test.md

fixes: https://github.com/nodejs/node/issues/48894

doc: add new TestSream events to custom reporter examples

---

src/env.cc
test/parallel/test-permission-inspector.js

It goes according to the documentation:
> When starting Node.js with --experimental-permission, the ability to access the file system through the fs module, spawn processes, use node:worker_threads and enable the runtime inspector will be restricted.

src,permission: restrict by default when pm enabled

---

benchmark/esm/esm-loader-import.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/module_job.js
lib/internal/modules/esm/module_map.js
test/es-module/test-esm-dynamic-import-mutating-fs.js
test/es-module/test-esm-dynamic-import-mutating-fs.mjs
test/es-module/test-esm-initialization.mjs
test/es-module/test-esm-loader-modulemap.js

According to https://tc39.es/ecma262/#sec-HostLoadImportedModule, if `import()` is called multiple times with the same (`referrer`, `specifier`) pair, then it must fulfil return the same object (or reject).
https://tc39.es/proposal-import-attributes/#sec-HostLoadImportedModule takes it further by adding ~assertions~ attributes to the mix.
This PR adds a cache layer for dynamic imports to ensure Node.js meets the spec.
EDIT: I should clarify here that the cache layer is also populated by static imports

module: ensure successful dynamic import returns the same result

---

benchmark/permission/permission-startup.js

This is naive benchmark to measure the impact of permission model (file system only in this case) on startup time.

benchmark: add pm startup benchmark

---

lib/internal/util/inspector.js
test/parallel/test-repl-permission-model.js

Fixes: https://github.com/nodejs/node/issues/48884
I'll add some tests for it

lib,permission: drop repl autocomplete when pm enabled

---

doc/api/events.md

Second parameter name is described as `listener`(not resource) in below line.

doc: fix second parameter name of `events.addAbortListener`

---

doc/api/http.md

Improved documentation for joinDuplicateHeaders definition

doc: improved joinDuplicateHeaders definition

---

test/es-module/test-esm-initialization.mjs

The `--experimental-import-meta-resolve` flag was not supplied, when the target file does use `import.meta.resolve`. I also cleaned up the comments.

test: fix `es-module/test-esm-initialization`

---

.eslintrc.js
lib/internal/test_runner/coverage.js
lib/internal/test_runner/harness.js
lib/internal/test_runner/mock/mock.js
lib/internal/test_runner/mock/mock_timers.js
lib/internal/test_runner/reporter/spec.js
lib/internal/test_runner/reporter/tap.js
lib/internal/test_runner/runner.js
lib/internal/test_runner/test.js
lib/internal/test_runner/tests_stream.js
lib/internal/test_runner/utils.js
tools/eslint-rules/set-proto-to-null-in-object.js

extracted from:
- #48646
TODO:
reference: https://github.com/nodejs/node/pull/48646#issuecomment-1618997778

test_runner: add `__proto__` null

---

lib/internal/test_runner/reporter/tap.js
test/fixtures/test-runner/output/hooks.snapshot

The TAP reporter unwraps errors that come from user code. It was not properly unwrapping the error message when the failure originated from a test hook. This lead to difficult to debug errors when TAP output was used. This commit updates the TAP reporter to properly unwrap the error message.
Fixes: https://github.com/nodejs/node/issues/48941

test_runner: unwrap error message in TAP reporter

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/before-and-after-each-too-many-listeners.js
test/fixtures/test-runner/output/before-and-after-each-too-many-listeners.snapshot
test/fixtures/test-runner/output/before-and-after-each-with-timeout-too-many-listeners.js
test/fixtures/test-runner/output/before-and-after-each-with-timeout-too-many-listeners.snapshot
test/parallel/test-runner-output.mjs

test_runner: cleanup test timeout abort listener

---

test/parallel/test-worker-broadcastchannel.js

This improves a test coverage in `internal/worker/io.js`
ref: https://coverage.nodejs.org/coverage-6d3920d579a3dc3a/lib/internal/worker/io.js.html#L485
This PR adds a test that validates the `BroadcastChannel.ref()` method works correctly.

test: improve internal/worker/io.js coverage

---

test/es-module/test-cjs-legacyMainResolve-permission.js
test/es-module/test-esm-dynamic-import.js
test/es-module/test-esm-loader-spawn-promisified.mjs
test/parallel/test-fs-mkdtemp.js
test/parallel/test-internal-util-decorate-error-stack.js
test/parallel/test-repl-require-context.js
test/parallel/test-stdio-pipe-stderr.js
test/parallel/test-trace-events-worker-metadata-with-name.js
test/parallel/test-trace-events-worker-metadata.js
test/sequential/test-watch-mode.mjs

Some tests are assuming they will be run from a directory that do not contain any quote or special character in its path. That assumption is not necessary, using `JSON.stringify` or `pathToFileURL` ensures the test can be run whatever the path looks like.

test: fix some assumptions in tests

---

src/node_file.cc
test/es-module/test-cjs-legacyMainResolve.js

When passing a URL that contains a `%`, the following assertion is likely to fail: https://github.com/nodejs/node/blob/1773b2ada4b2b5ce9ad9f526808360fd5faf0282/src/debug_utils-inl.h#L70

src: do not pass user input to format string

---

src/base_object-inl.h
src/module_wrap.cc
src/node_file.cc
src/node_task_queue.cc
src/node_zlib.cc
src/stream_base.cc

In preparation of https://chromium-review.googlesource.com/c/v8/v8/+/4707972 which changes the return value to v8::Data.

src: cast v8::Object::GetInternalField() return value to v8::Value

---

doc/contributing/security-release-process.md

We perform that check one week in advance, but a lot of things could happen between the announcement and the release itself, so there's no point in checking it beforehand.

doc: drop github actions check in sec release process

---

lib/internal/modules/esm/initialize_import_meta.js
lib/internal/modules/esm/loader.js

esm: fix typo `parentUrl` -> `parentURL`

---

doc/api/esm.md
doc/api/module.md
lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/utils.js
lib/internal/process/pre_execution.js
test/es-module/test-esm-loader-hooks.mjs
test/es-module/test-esm-loader-programmatically.mjs
test/fixtures/es-module-loaders/hooks-initialize-port.mjs
test/fixtures/es-module-loaders/hooks-initialize.mjs

Follows @giltayar's proposed API:
> `register` can pass any data it wants to the loader, which will be passed to the exported `initialize` function of the loader. Additionally, if the user of `register` wants to communicate with the loader, it can just create a `MessageChannel` and pass the port to the loader as data.
The `register` API is now:
```ts
interface Options {
parentUrl?: string;
data?: any;
transferList?: any[];
}
function register(loader: string, parentUrl?: string): any;
function register(loader: string, options?: Options): any;
```
This API is backwards compatible with the old one (new arguments are optional and at the end) and allows for passing data into the new `initialize` hook. If this hook returns data it is passed back to `register`:
```ts
function initialize(data: …
```

esm: add `initialize` hook, integrate with `register`

---

test/fixtures/test-runner/output/abort.js
test/fixtures/test-runner/output/abort_hooks.js
test/fixtures/test-runner/output/abort_suite.js
test/fixtures/test-runner/output/describe_it.js
test/fixtures/test-runner/output/describe_nested.js
test/fixtures/test-runner/output/dot_reporter.js
test/fixtures/test-runner/output/hooks.js
test/fixtures/test-runner/output/name_pattern.js
test/fixtures/test-runner/output/name_pattern_with_only.js
test/fixtures/test-runner/output/no_refs.js
test/fixtures/test-runner/output/no_tests.js
test/fixtures/test-runner/output/only_tests.js
test/fixtures/test-runner/output/output_cli.js
test/fixtures/test-runner/output/single.js
test/fixtures/test-runner/output/spec_reporter.js
test/fixtures/test-runner/output/spec_reporter_cli.js
test/fixtures/test-runner/output/spec_reporter_successful.js
test/fixtures/test-runner/output/unresolved_promise.js

no longer needed after #48915 fix

test: remove `--no-warnings` flag in `test_runner` fixtures

---

test/parallel/test-node-output-errors.mjs

The main reason is to not have the test fail if the CWD contains some special URL chars.

test: refactor `test-node-output-errors`

---

test/parallel/test-preload.js
test/parallel/test-timers-immediate-promisified.js
test/parallel/test-timers-interval-promisified.js
test/parallel/test-timers-timeout-promisified.js
test/parallel/test-url-parse-invalid-input.js
test/sequential/test-cli-syntax-require.js
test/sequential/test-fs-stat-sync-overflow.js

This is important in case the `node` executable path or the CLI args contains some special characters which would be interpreted by the shell.

test: use `spawn` and `spawnPromisified` instead of `exec`

---

doc/contributing/maintaining/maintaining-openssl.md

Node.js 14.x is EOL. We don't perform OpenSSL patches anymore.

doc: remove v14 mention

---

doc/api/process.md
doc/api/worker_threads.md

A worker thread uses a copy of parent thread's `process.env` by default. The current document explains differences caused by the copy, but it doesn't cover the case sensitivity difference on Windows. 
This patch updates the document in this regard.
Fixes: #48955
Alternative to #48976

doc: clarify use of process.env in worker threads on Windows

---

.github/workflows/auto-start-ci.yml

Every time the CI is locked, there is a backup of PRs to test with Jenkins, we usually disable the auto-start-ci workflow until the CI is unlocked. It sometimes causes problems when dozens of CI jobs are spawned at the same time. But actually there's no reason to send up to 100 requests at the same time, we could limit that to a more reasonable value.
5 is an arbitrary value, my hope is that is will be low enough to not cause the CI to be overwhelmed when we re-enable the workflow (5 PRs every 5 minutes), and high enough to not slow down the regular day-to-day operations.

tools: limit the number of auto start CIs

---

doc/abi_version_registry.json

This PR reserves NMV 118 for Electron 27.

doc: reserve 118 for Electron 27

---

doc/api/test.md

In [version 20.0.0 (and backported to 19.9.0 and 18.7.0)](https://github.com/nodejs/node/pull/47094) the test runner started reporting on whether a test was a suite. This was exposed to reporters in the `details` object of a `test:pass` or `test:fail` event but this hasn't been documented. This adds the `type` property to both event's `details` object.

doc: add "type" to test runner event details

---

src/callback_queue.h

`std::unique_ptr` is in the  `memory` header, this PR adds the header inclusion

src: fix callback_queue.h missing header

---

test/common/README.md
test/common/tmpdir.js
test/es-module/test-esm-extension-lookup-deprecation.mjs
test/parallel/test-child-process-cwd.js
test/parallel/test-fs-mkdtemp.js
test/parallel/test-fs-rm.js
test/parallel/test-runner-inspect.mjs

Almost every time `tmpdir.path` is used in tests, we have to import `path` to use it.
Whenever we need `URL` of something in tmpdir, we also have to import `url.pathToFileURL`.
Adding `tmpdir.url` would reduce
```mjs
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
const testFile = pathToFileURL(join(tmpdir.path, 'subdir', 'tst-file-123'));
```
to
```mjs
const testFile = tmpdir.resolve('subdir', 'tst-file-123');
```
or to native resolving
```mjs
const tmpBase = tmpdir.fileURL();
const testFile = new URL('subdir/tst-file-123', tmpBase);
```
Additionally, maybe we could add path-oriented `tmpdir.resolve(...paths)` to replace `path.join(tmpdir.path, ...paths)` in tests?

test: add `tmpdir.fileURL()`

---

lib/internal/errors.js
lib/internal/modules/esm/resolve.js
test/es-module/test-esm-main-lookup.mjs

esm: protect `ERR_UNSUPPORTED_DIR_IMPORT` against prototype pollution

---

lib/internal/test_runner/harness.js
lib/internal/test_runner/test.js
test/fixtures/test-runner/output/async-test-scheduling.mjs
test/fixtures/test-runner/output/async-test-scheduling.snapshot
test/fixtures/test-runner/output/global_after_should_fail_the_test.snapshot
test/parallel/test-runner-output.mjs
test/parallel/test-runner-root-after-with-refed-handles.js

This commit moves the global `after()` hook execution from the `'beforeExit'` event to the point where all tests have finished running. This gives the global `after()` a chance to clean up handles that would otherwise prevent the `'beforeExit'` event from being emitted.
Fixes: https://github.com/nodejs/node/issues/49056

test_runner: run global after() hook earlier

---

lib/internal/debugger/inspect.js

this is not clearly documented anywhere and is an incredibly helpful tool for CLI debugging.

doc: node inspect port 0 description when help is printed

---

src/node_builtins.cc
src/node_builtins.h

Replaces `std::vector<std::string>` with `std::vector<std::string_view>`

src: avoid string copy in BuiltinLoader::GetBuiltinIds

---

doc/api/deprecations.md

As part of the recent security release, 4aa0eff7 updated the documentation but bd7443ad did not.

doc: update process.binding deprecation text

---

test/es-module/test-esm-loader-hooks.mjs

test: reduce flakiness of `test-esm-loader-hooks`

---

lib/internal/readline/utils.js

The paste bracket mode allows REPL to have auto-indentation that is handled differently when the user copy-pastes the code from the clipboard and the code already has an indentation.
There are no unit tests because there is no way to test copy-pate. You will need to have the equivalent of Cypress or Playwright for Terminal to test (but I'm also not sure if you can easily test copy-paste in those front-end frameworks).
Fixes: https://github.com/nodejs/node/issues/45213

readline: add paste bracket mode - fixes #45213

---

lib/fs.js
test/sequential/test-fs-readdir-recursive.js

This PR fixes the broken behavior for readdir recursive sync and callback. It updates the test assertions to catch the issue in the old code, and then adds the necessary fix in the implementation.
Refs: https://github.com/nodejs/node/issues/48640
Fixes: https://github.com/nodejs/node/issues/48858

fs: fix readdir recursive sync & callback

---

src/node_util.cc

Removed redundant code for handling uv_handle_type

src: remove redundant code for uv_handle_type

---

lib/internal/errors.js
lib/internal/modules/esm/fetch_module.js
lib/internal/modules/esm/initialize_import_meta.js
lib/internal/modules/esm/resolve.js
test/es-module/test-esm-import-meta-resolve.mjs

This resolves https://github.com/nodejs/node/issues/49010, ensuring that not found errors to exact modules in `import.meta.resolve`  still return the resolved string. Package not found errors remain module not found errors.
@nodejs/modules

esm: import.meta.resolve exact module not found errors should return

---

test/common/README.md
test/common/tmpdir.js

Adds a simple method to make the usual routine of `path.join(tmpdir.path, ...)` more concise and avoid unnecessary import from `node:path` almost every time `tmpdir` is used.

test: add `tmpdir.resolve()`

---

doc/api/cli.md
doc/api/esm.md
lib/internal/modules/esm/initialize_import_meta.js
src/node_options.cc
test/es-module/test-esm-import-meta-resolve.mjs
test/es-module/test-esm-import-meta.mjs
test/es-module/test-esm-loader-hooks.mjs

Unflags `import.meta.resolve` making the second `parentURL` argument still gated behind the same `--experimental-import-meta-resolve` flag so that existing users would retain backwards compatibility, while the default behaviour becomes standards compliant.
If we can combine this approach with supporting `file:///` URLs in `fetch`, that would be a powerful new approach for cross-platform asset loading - `await (await fetch(import.meta.resolve('./asset.bin'))).arrayBuffer()` which hopefully in turn bundlers should also be able to support better too.
//cc @nodejs/modules

esm: unflag import.meta.resolve

---

lib/internal/webstreams/readablestream.js
lib/internal/webstreams/transformstream.js
lib/internal/webstreams/writablestream.js

From my local tests, this improves the `benchmark/webstreams/creation.js` by 2 to 3 times
could someone please run the benchmark in the CI

stream: improve WebStreams creation performance

---

lib/internal/modules/esm/hooks.js
test/es-module/test-esm-loader-hooks.mjs

Fixes: https://github.com/nodejs/node/issues/49026
Before:
```
(node:9201) ExperimentalWarning: `globalPreload` will be removed in a future version. Please use `initialize` instead. is an experimental feature and might change at any time
```
After:
```
(node:34642) ExperimentalWarning: It is recommended to use `initialize` instead of `globalPreload`, which is an experimental feature and might change at any time
```

esm: fix `globalPreload` warning

---

lib/internal/modules/esm/formats.js
test/es-module/test-esm-invalid-data-urls.js

This commit adds the delimiters ^ and $ to the regex that matches the MIME types for "data:URLs".
Fixes: https://github.com/nodejs/node/issues/48957
I also added a new test case that expects an `ERR_UNKNOWN_MODULE_FORMAT` message for MIME types like this: `data:WRONGtext/javascriptFORMAT`.
This is my first time contributing to node. Let me know if I did everything right :smile:.

lib: fix MIME overmatch in data URLs

---

doc/contributing/releases.md

Refs: https://github.com/nodejs/node/pull/49084#issuecomment-1672042878

doc: make the NODE_VERSION_IS_RELEASE revert clear

---

doc/api/esm.md

`--loader` is an undocumented flag, the rest of the docs uses `--experimental-loader` to design that flag (`--loader` was kept as an undocumented alias to avoid a breaking change).

doc: fix name of the flag in `initialize()` docs

---

node.gyp
src/node_snapshot_builder.h
src/node_snapshotable.cc
tools/snapshot/node_mksnapshot.cc

- Build a static table of octal strings and use it instead of building octal strings repeatedly during printing.
- Print a newline and an offset for every 64 bytes in the case of printing array literals so it's easier to locate variation in snapshot blobs.
- Rework the printing routines so that the differences are only made in a WriteByteVectorLiteral routine. We can update this for compression support in the future.
- Rename Snapshot::Generate() that write the data as C++ source instead of a blob as Snaphost::GenerateAsSource() for clarity, and move the file stream operations into it to streamline error handling.

src: refactor vector writing in snapshot builder

---

lib/internal/test_runner/harness.js
lib/internal/test_runner/test.js
test/fixtures/test-runner/output/async-test-scheduling.mjs
test/fixtures/test-runner/output/async-test-scheduling.snapshot
test/fixtures/test-runner/output/global_after_should_fail_the_test.snapshot
test/parallel/test-runner-output.mjs
test/parallel/test-runner-root-after-with-refed-handles.js

This commit reverts the revert in
bb52656fc627e4f48a0f706756873b593d81372a. It also includes the fix for the issue that required the revert
(https://github.com/nodejs/node/pull/49059#issuecomment-1675171959) and an additional `common.mustCall()` in the added test.
Refs: https://github.com/nodejs/node/pull/49059
Refs: https://github.com/nodejs/node/pull/49110

test_runner: reland run global after() hook earlier

---

src/node_sea.cc

The removed `optional_code_cache` variable is already declared with the same name in the line below.
In my opinion, it was judged to be unnecessary redundant code and was removed.
https://github.com/nodejs/node/blob/32245275b50a455713ff753de6b1be494e077464/src/node_sea.cc#L489-L494

src: remove duplicated code in `GenerateSingleExecutableBlob()`

---

doc/api/webstreams.md

Replace `type` with `Type: {Promise}`. Plus, fix incorrect verb(`creates` -> `returns`) in description.

doc: fix `Type` notation in webstreams

---

test/es-module/test-esm-loader-hooks.mjs

- Always check stderr before stdout as the former would contain error information.
- Always match the full stdout to avoid surprises.
- Use `deepStrictEqual` when appropriate to get more informative test failures.
- Remove leading slashes from relative paths/URLs to not confuse them with absolute paths.
- Remove unnecessary `--no-warnings` flag.

test: refactor `test-esm-loader-hooks` for easier debugging

---

test/node-api/test_async/test_async.c

test: fix assertion message in test_async.c

---

doc/api/webstreams.md

As with the other examples, I added something about the resulting output.(Only output results that do not change)

doc: add print results for examples in `WebStreams`

---

configure.py

build: fix typo `libray` -> `library` (configure.py)

---

lib/internal/crypto/sig.js

`getDefaultEncoding()` always returns `'buffer'` in Node.js 20. It requires some careful justification but the default encoding can be eliminated from `sig.js` entirely.
In `Sign.prototype.update`, we can safely remove the conditional assignment of `getDefaultEncoding()` to `encoding`. This is because `SignUpdate()` in `crypto_sig.cc` internally calls `node::crypto::Decode`, which returns `UTF8` for falsy `encoding` values. In other words, with the conditional assignment, `StringBytes::Write()` ultimately receives the encoding `BUFFER`, and without the conditional assignment, it receives the encoding `UTF8`. However, `StringBytes::Write()` treats both encodings identically, so there is no need to deviate from the internal default encoding `UTF8`.
In `Sign.prototype.sign`, we can also …

crypto: remove default encoding from sign/verify

---

test/node-api/test_uv_threadpool_size/binding.gyp
test/node-api/test_uv_threadpool_size/test.js
test/node-api/test_uv_threadpool_size/test_uv_threadpool_size.c

This (not particularly elegant) native addon tests the effect of `UV_THREADPOOL_SIZE` on node-api. The test fails if Node.js allows more than `UV_THREADPOOL_SIZE` async tasks to run concurrently, or if it limits the number of concurrent async tasks to anything less than `UV_THREADPOOL_SIZE`.
The test schedules `UV_THREADPOOL_SIZE + 1` async tasks and waits until `UV_THREADPOOL_SIZE` tasks are running concurrently. (If this never happens, the test times out.) All `UV_THREADPOOL_SIZE` tasks then wait for a second to see if the last task also starts running concurrently, which should not happen.
Admittedly, I hastily put this together and the code is sloppy. While having this test is good in any case, the main motivation is such that @anonrig can invoke the test from his own test in …

test: add test for effect of UV_THREADPOOL_SIZE

---

lib/internal/crypto/hash.js

`getDefaultEncoding()` always returns `'buffer'` in Node.js 20. It requires some careful justification but the default encoding can be eliminated from `hash.js` entirely. The reasoning is almost identical with that in https://github.com/nodejs/node/pull/49145 so I won't repeat it here. The main thing to note here is that `digest()` conveniently defaults to `BUFFER` for falsy encodings.
This partially addresses:
https://github.com/nodejs/node/blob/af9b48a2f17b11b66a8b81beeaba3c408b863795/lib/internal/crypto/util.js#L77-L80

crypto: remove default encoding from Hash/Hmac

---

lib/internal/crypto/diffiehellman.js

`getDefaultEncoding()` always returns `'buffer'` in Node.js 20.
In `diffiehellman.js`, this value is always used as input to either `toBuf()`, `encode()`, or `getArrayBufferOrView()`. All of these functions treat any falsy encoding just like `'buffer'`, so we can safely remove the calls to `getDefaultEncoding()`.
This partially addresses:
https://github.com/nodejs/node/blob/af9b48a2f17b11b66a8b81beeaba3c408b863795/lib/internal/crypto/util.js#L77-L80

crypto: remove default encoding from DiffieHellman

---

tools/test.py

a follow-up for https://github.com/nodejs/node/pull/49129
since `additional_flags` was shared between all tests the reporter kept being added again for each test. 
see for example https://github.com/nodejs/node/actions/runs/5870373336/job/15917272924?pr=49184

tools: fix github reporter appended multiple times

---

lib/vm.js
src/module_wrap.cc
src/node_contextify.cc
src/node_contextify.h

Previously the ContextifyContext holds a MicrotaskQueueWrap which in turns holds a MicrotaskQueue in a shared pointer. The indirection is actually unnecessary, we can directly hold the MicrotaskQueue via a unique pointer in ContextifyContext, the lifetime would still remain the same but the graph would be simpler, and this removes the additional JS -> C++ to create the wrapper object.

vm: store MicrotaskQueue in ContextifyContext directly

---

src/node_builtins.cc
src/node_builtins.h

V8 now no longer supports serializing code cache in an isolate with unfinalized read-only space. So guard the code cache regeneration with the `is_building_snapshot()` flag. When the isolate is created for snapshot generation, the code cache is going to be serialized separately anyway, so there is no need to do it in the builtin loader.

bootstrap: do not generate code cache in an unfinalized isolate

---

lib/test/reporters.js
test/parallel/test-runner-run.mjs

Fixes: https://github.com/nodejs/node/issues/48112
Ref: https://github.com/nodejs/node/pull/48208

test_runner: expose spec reporter as newable function

---

doc/api/cli.md
doc/api/permissions.md
lib/internal/process/pre_execution.js
src/env.cc
src/node_options.h
src/permission/child_process_permission.cc
src/permission/child_process_permission.h
src/permission/fs_permission.cc
src/permission/fs_permission.h
src/permission/inspector_permission.cc
src/permission/inspector_permission.h
src/permission/permission.cc
src/permission/permission.h
src/permission/permission_base.h
src/permission/worker_permission.cc
src/permission/worker_permission.h
test/es-module/test-cjs-legacyMainResolve-permission.js
test/parallel/test-cli-permission-multiple-allow.js
test/parallel/test-permission-fs-read.js
test/parallel/test-permission-fs-symlink-target-write.js
test/parallel/test-permission-fs-symlink.js
test/parallel/test-permission-fs-traversal-path.js
test/parallel/test-permission-fs-wildcard.js
test/parallel/test-permission-fs-write.js

Support for a single comma separates list for allow-fs-* flags is removed. Instead now multiple flags can be passed to allow multiple paths.
Fixes: https://github.com/nodejs/security-wg/issues/1039

src,permission: add multiple allow-fs-* flags

---

doc/api/n-api.md

Even after reading through https://github.com/nodejs/node/pull/32930, I am not quite sure what this was supposed to say, so please feel free to suggest alternatives. cc @legendecas @mhdawson

doc: fix wording in napi_async_init

---

doc/contributing/releases.md

Since https://github.com/nodejs/Release/issues/772, we are performing semver-minor releases by default. Therefore, this PR updates the commands to consider semver-minor releases by default.

doc: update to semver-minor releases by default

---

doc/contributing/security-release-process.md

This has proven quite useful to either request disclosure on H1 and create the pos release announcement.

doc: add h1 summary to security release process

---

.github/PULL_REQUEST_TEMPLATE.md

A naive attempt to remind us about the `notable-change` label usage.
cc: @nodejs/tsc

doc: add notable-change label mention to PR template

---

.github/CODEOWNERS

I noticed while creating https://github.com/nodejs/node/pull/49188 that no one is notified when a PR is created attempting to change our GitHub templates. I believe makes sense to mention nodejs/tsc in this case.

meta: mention nodejs/tsc when changing GH templates

---

src/node_snapshotable.cc

V8 now requires the code cache to be compiled with a finalized read-only space, so we need to serialize the snapshot to get a finalized read-only space first, then deserialize it to compile the code cache.
Refs: https://github.com/nodejs/node/issues/47636
Refs: https://bugs.chromium.org/p/v8/issues/detail?id=13789

bootstrap: build code cache from deserialized isolate

---

test/parallel/test-v8-serialize-leak.js

Previously this can be flaky because the there could be a delay of the deallocation after gc() is invoked. Use gcUntil() to run the GC multiple times to make the test more robust.

test: use gcUntil() in test-v8-serialize-leak

---

test/sequential/test-perf-hooks.js

Previously the test makes several assumptions about the absolute values of the nodeTiming fields, which can make the test flaky on slow machines. This patch rewrites the test to check the relative values instead. It also updates the test to make it work with workers instead of directly skipping in workers.
Refs: https://github.com/nodejs/reliability/issues/638

test: make test-perf-hooks more robust and work with workers

---

test/common/README.md
test/common/child_process.js
test/parallel/test-snapshot-api.js
test/parallel/test-snapshot-basic.js
test/parallel/test-snapshot-warning.js

Replaces expectSyncExit() and expectSyncExitWithoutError(). Since
we usually just check the child process right after its spawned,
these shorthands also takes care of the spawning. This makes the
tests more concise.
---
I just realized that these shorthands may be more handy in some cases, so added them and switched to these instead (before we start to use them everywhere)

test: add and use spawnSyncAndExit() and spawnSyncAndExitWithoutError()

---

doc/api/webstreams.md
lib/internal/webstreams/queuingstrategies.js

Since the specification and code explicitly use the name  `init`, I think it would be clearer to use `init` in error message and documentation as well.
Refs: https://streams.spec.whatwg.org/#bytelengthqueuingstrategy

doc: use same name in the doc as in the code

---

doc/api/esm.md

closes https://github.com/nodejs/node/issues/49198

doc: caveat unavailability of `import.meta.resolve` in custom loaders

---

.github/workflows/test-internet.yml

Refs: https://github.com/nodejs/node/issues/49203
Changes slipped into v18.x regressed
test/internet/test-dns-ipv6 as I assume the action did not run because no test under test/internet was changed. Add some of the common paths that include code that might introduce failures in the internet tests.

build: expand when we run internet tests

---

lib/internal/modules/esm/load.js

Refs: https://github.com/nodejs/node/pull/48272
Refs: https://github.com/nodejs/node/pull/47999

esm: align sync and async load implementations

---

src/node_url.cc

Add an empty check for the input, like `DomainToASCII` in the line below.
https://github.com/nodejs/node/blob/f1b3ade9480b43273bd66f9039118a8b842db703/src/node_url.cc#L79-L82
Refs : https://github.com/nodejs/node/pull/46410

src: add a condition if the argument of `DomainToUnicode` is empty

---

doc/api/esm.md
doc/api/module.md

In the recent PRs that created `register`, we neglected to define its signature. @nodejs/loaders

doc: add signature for `module.register`

---

src/node_perf.cc

I looked through the code, but couldn't find where `GetName()` is used.
Both test and build passed, I think it can be deleted.

src: remove unused function `GetName()` in node_perf

---

doc/api/n-api.md

`napi_get_buffer_info` always supported receiving `Uint8Array` as a `value` argument because `node::Buffer` is a subclass of `Uint8Array` and the underlying V8 APIs don't distinguish between two. With this change we mark both types as supported by the API so that the user code doesn't have to unknowingly use oficially unsupported type of the `value` argument.
---
Hello!
I think it'd be great to officially mark `Uint8Array`s as supported since it is very likely that there is existing code in the wild that relies on this. The N-API never distinguished between `node::Buffer` and `Uint8Array` so it'd be a breaking change if we started to bail on `Uint8Array` anyway. Let's mark it as supported now to signify existing code as compliant to official APIs!

doc: clarify use of Uint8Array for n-api

---

doc/api/esm.md
doc/api/module.md

This PR moves the former “Loaders” section from `esm.md` into a new “Customization Hooks” section in `module.md`.
- The content of the section **did not change.** You don’t need to review the huge red block in `esm.md` or the huge green block in `module.md`. I promise, nothing in there changed, other than some `` ```js `` to `` ```mjs `` because of the linter. The point of this PR is so that I can follow up this one with another PR that makes edits within that block, without those edits being subsumed by the diff from the move.
- I updated bookmarks in both files, and edited some mentions outside of the moved section to refer to the new name.
The reason for the move is that as of #47999, these customization hooks now support CommonJS (when the loader author has written the `load` hook to …

doc: move and rename loaders section

---

doc/api/url.md

The character code is shown in the description of percent-encoded-bytes in the `WHATWG URL` Spec.
I think it would be better for readability to show the 'character code' the same as the `WHATWG URL`.
Refs: https://url.spec.whatwg.org/#percent-encoded-bytes

doc: update description of `percent_encode` set in `WHATWG API`

---

lib/internal/worker/io.js
test/parallel/test-worker-message-channel.js

Fixes: https://github.com/nodejs/node/issues/49259

worker: protect against user mutating well-known prototypes

---

doc/api/stream.md

The colon is quite confusing as it implies the content after that section would be related, but in fact it has nothing to do with the callback version.
Refs: https://nodejs.org/api/stream.html#streamfinishedstream-options

doc: fix typo in `stream.finished` documentation

---

configure.py

Usually lsp servers needs the `compile_commands.json` file in the root directory.

build: add symlink to `compile_commands.json` file if needed

---

test/cctest/test_node_crypto_env.cc

This fixes `warning: value computed is not used` when calling `BIO_seek()`:
```
../test/cctest/test_node_crypto_env.cc: In member function ‘virtual void NodeCryptoEnv_LoadBIO_Test::TestBody()’:
../deps/openssl/openssl/include/openssl/../../../config/././archs/linux-x86_64/asm/include/openssl/bio.h:495:26: warning: value computed is not used [-Wunused-value]
495 | # define BIO_seek(b,ofs) (int)BIO_ctrl(b,BIO_C_FILE_SEEK,ofs,NULL)
|                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../test/cctest/test_node_crypto_env.cc:26:3: note: in expansion of macro ‘BIO_seek’
26 |   BIO_seek(bio.get(), 2);
|   ^~~~~~~~
```
Refs: https://github.com/nodejs/node/pull/47160

test: fix compiler warning in NodeCryptoEnv

---

doc/api/cli.md
doc/api/esm.md
doc/api/module.md

This PR builds on and follows up https://github.com/nodejs/node/pull/49261.
The aim here was to implement most of [this to-do list](https://github.com/nodejs/loaders/issues/154#issuecomment-1678068573). In particular:
- I hopefully removed all references to the “Loaders API” and similar nomenclature, in favor of “module customization hooks” or “hooks” or similar.
- I moved most of the “how to use this API” text out of the `module.register()` section and into a new section “Enabling” under the “Customization Hooks” heading.
- I removed all references to `--experimental-loader` except in `cli.md`, rewriting to recommend `--import` with `register()` instead. We’re considering removing the `--experimental-loader` flag, but for now at least we want to discourage its use. (We anticipate that …

doc: update module customization hooks docs

---

doc/api/fs.md
lib/internal/fs/promises.js

Remove redundant code by moving it to outside of `if/else`. Plus, make `options` optional in doc.
Below code is duplicated because it exists on both `if` and `else`.
```
const {
readableStreamCancel,
} = require('internal/webstreams/readablestream');
this[kRef]();
this.once('close', () => {
readableStreamCancel(readable);
});
```
And `options` param is optional like below.
```
/**
* @typedef {import('../webstreams/readablestream').ReadableStream
* } ReadableStream
* @param {{
*   type?: string;
*   }} [options]
* @returns {ReadableStream}
*/
readableWebStream(options = kEmptyObject) {
```

fs: remove redundant code in readableWebStream()

---

lib/internal/process/pre_execution.js
test/parallel/test-policy-manifest.js

policy: fix path to URL conversion

---

doc/api/os.md
doc/api/process.md

Simple doc change to add riscv64 to list of things that `os.arch()` and `process.arch` can return.
Fixes: https://github.com/nodejs/node/issues/49278

doc: add riscv64 to list of architectures

---

doc/api/fs.md

Updating doc for `fs.cp`, `fsPromises.cp` and `fs.cpSync`.
Added the caveat that filter will be applied to both files and dirs. 
Fixes: https://github.com/nodejs/node/issues/49092

update fs doc for filter

---

doc/api/test.md

Use `cjs` instead of `js` to show toggle button between CJS and ESM because corresponding example using `mjs` exists.

doc: use `cjs` as block code's type in `MockTimers`

---

doc/api/crypto.md

NIST SP 800-131A Rev. 1 has been withdrawn. Replace the reference with a link to NIST SP 800-131A Rev. 2.

doc: update outdated reference to NIST SP 800-131A

---

lib/internal/streams/lazy_transform.js
test/parallel/test-crypto.js

This only affects the writable side of `LazyTransform` and should not change the behavior of any `LazyTransform` streams (`Cipher`, `Decipher`, `Cipheriv`, `Decipheriv`, `Hash`, `Hmac`).
If the user does not set `defaultEncoding` when creating a transform stream, `WritableState` uses `'utf8'` by default. Only `LazyTransform` overwrites this with `'buffer'` for strict backward compatibility. This was necessary when `crypto.DEFAULT_ENCODING` still existed. Now that `DEFAULT_ENCODING` has been removed, `defaultEncoding` is always `'buffer'`. The writable side of `LazyTransform` appears to treat `'utf8'` and `'buffer'` in exactly the same way. Therefore, there seems to be no need to overwrite `_writableState.defaultEncoding` at this point.
Nevertheless, because Node.js has failed to hide …

crypto: do not overwrite _writableState.defaultEncoding

---

doc/api/string_decoder.md

As with the other examples, I added result about the output.
Refs: #49143

doc: add print results for examples in `StringDecoder`

---

tools/v8_gypfiles/v8.gyp

The `deps/v8/tools/testrunner/utils/dump_build_config_gyp.py` script that this action relies on had been deleted in #44741, it is mysterious that gyp build does not report any error.

tools: remove v8_dump_build_config action

---

doc/api/permissions.md

https://github.com/nodejs-private/node-private/issues/448

doc: clarify policy expectations

---

src/crypto/crypto_aes.cc
src/crypto/crypto_ec.cc
src/crypto/crypto_hkdf.cc
src/crypto/crypto_keys.cc
src/crypto/crypto_random.cc
src/crypto/crypto_rsa.cc
src/crypto/crypto_timing.cc
src/crypto/crypto_util.cc
src/crypto/crypto_util.h

The current name is somewhat confusing. There is an internal `ByteSource` class, which is entirely unrelated to what `IsAnyByteSource()` does, even though both exist in the crypto subsystem of the C++ code. `ByteSource` objects can also be constructed from strings, for example, for which `IsAnyByteSource()` returns false.
Web IDL calls the types for which this function returns true `BufferSource`. This type is commonly used across Web Crypto, for example. Thus, rename the function to match the Web IDL naming.
Because the function also appears to accept `BufferSource` objects backed by `SharedArrayBuffer` instances, the exact Web IDL name would be `AllowSharedBufferSource`, but that seems unnecessarily long, so I decided to stick with "any".

src: rename IsAnyByteSource to IsAnyBufferSource

---

src/node_api.h

Fix `-Wstrict-prototypes` warning from AppleClang 14.0.3.14030022, compiling C.
My team tests our C addon with `-Werror` and recent changes to node_api.h [broke our build](https://github.com/awslabs/aws-crt-nodejs/actions/runs/5826936867/job/15801950085?pr=487#step:3:443).
```
/Users/runner/.cmake-js/node-arm64/v18.17.0/include/node/node_api.h:33:65: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
typedef int32_t(NAPI_CDECL* node_api_addon_get_api_version_func)();
^
void
typedef int32_t(NAPI_CDECL* node_api_addon_get_api_version_func)();
^
void
```
The break started when the build machines started using [node v18.17.0](https://github.com/awslabs/aws-crt-nodejs/actions/runs/5826936867/job/15801950085?pr=487#step:3:22). Builds from a week ago, using [node …

node-api: fix compiler warning in node_api.h

---

benchmark/esm/cjs-parse.js
benchmark/esm/esm-legacyMainResolve.js
benchmark/esm/esm-loader-defaultResolve.js
benchmark/fs/read-stream-throughput.js
benchmark/fs/readfile-permission-enabled.js
benchmark/fs/readfile-promises.js
benchmark/fs/readfile.js
benchmark/fs/write-stream-throughput.js
benchmark/fs/writefile-promises.js
benchmark/module/module-loader-circular.js
benchmark/module/module-loader-deep.js
benchmark/module/module-loader.js
benchmark/module/module-require.js
benchmark/process/coverage.js

Refs: https://github.com/nodejs/node/pull/49079

benchmark: use `tmpdir.resolve()`

---

doc/api/test.md
lib/internal/test_runner/coverage.js
lib/internal/test_runner/utils.js
test/fixtures/test-runner/custom_reporters/coverage.mjs
test/parallel/test-runner-coverage.js

Fixes #49303.
This is a breaking change for the format of `test:coverage` events. But the test coverage is still experimental, so I don't believe it requires a semver-major bump.

test_runner: report covered lines, functions and branches to reporters

---

doc/api/test.md
lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers.js

This PR adds support for
This PR makes sure that `setImmediate` has priority higher than `setTimeout` and follows the spec defined in the docs about:
_When multiple calls to setImmediate() are made, the callback functions are queued for execution in the order in which they are created_
cc: @nodejs/test_runner

test_runner: add support for mocking setImmediate timer

---

doc/api/permissions.md
test/known_issues/test-permission-model-path-resolution.js

As a side effect of 205f1e643e25648173239b2de885fec430268492, Node.js now resolves some paths differently when the permission model is enabled. While these are mostly edge cases, they are worth mentioning in the documentation. This commit also adds a known_issues test that demonstrates one such difference.

doc,test: add known path resolution issue in permission model

---

src/node_url.cc
test/parallel/test-url-format-whatwg.js

The original PR by @Xstoudi seems abandoned (ref: https://github.com/nodejs/node/pull/49087)
Fixes: https://github.com/nodejs/node/issues/48759

url: handle unicode hostname if empty

---

lib/internal/url.js
lib/url.js
test/parallel/test-url-pathtofileurl.js

Since `url.pathToFileURL()` is exposed as a part of public API, it should validate input value.
Before this change, non-strings were rejected in `path.resolve()` with confusing `The "paths[0]" argument must be of type string.` message.
On Windows, input was directly passed into `StringPrototypeStartsWith()`, causing either confusing errors or implicit coercion to string.

url: validate `pathToFileURL(path)` argument as string

---

common.gypi
deps/v8/src/codegen/s390/macro-assembler-s390.cc
deps/v8/src/compiler/backend/s390/code-generator-s390.cc

Fix usage of MulHighS64 on <= z13
mgrk is only available with MISC_INSTR_EXT2 installed.
A runtime call needs to be made if it's unavailable.
We also need to make sure caller saved registers are saved
accordingly before making a call.
Change-Id: If7ac06eef57cc3db059c2640b77c80de3b16fced
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4521297
Reviewed-by: Junliang Yan <junyan@redhat.com>
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Cr-Commit-Position: refs/heads/main@{#87675}
Fixes: https://github.com/nodejs/node/issues/47064

deps: V8: cherry-pick eadaef581c29

---

doc/api/n-api.md

The `return` statement should not be enclosed in a nested conditional
branch.
Also, the `NAPI_CALL` macro is renamed to `NODE_API_CALL` in aligning
with the `n-api` to `node-api` transition.
Fixes https://github.com/nodejs/node/issues/49311

doc: fix node-api call example

---

test/es-module/test-esm-dynamic-import.js

Add a test case that verifies that the dynamic import call can resolve absolute path strings without a scheme as the specifier.
Refs: https://github.com/nodejs/node/pull/48655

test: verify dynamic import call with absolute path strings

---

test/parallel/test-crypto-dh-group-setters.js

I can't tell why the test was written that way in the first place, even after reading through https://github.com/nodejs/node-v0.x-archive/pull/2638 and https://github.com/nodejs/node/pull/11253, but it seems sufficient to check that `setPrivateKey` and `setPublicKey` are both undefined.

test: simplify test-crypto-dh-group-setters

---

lib/_tls_wrap.js
test/parallel/test-http2-socket-close.js
test/parallel/test-tls-socket-close.js

This fixes a potential HTTP/2 segfault (https://github.com/nodejs/node/issues/49307, https://github.com/nodejs/node/issues/48567) caused by underlying TLS behaviour, and likely fixes various other apparently related issues (https://github.com/nodejs/node/issues/46094, https://github.com/nodejs/node/issues/35695).
I found this while investigating https://github.com/nodejs/node/issues/48519, which this doesn't _directly_ fix, but definitely relates to, as the JS Stream Sockets there have all sorts of issues directly caused by TLS interactions after the JSS is closed.
The underlying problem here is that TLS sockets which are created by passing an existing socket (either `tlsServer.emit('connection', socket)` or `tls.createConnection({ ..., socket })`) do not listen to whether the underlying …

Fix a segfault by ensuring TLS Sockets are closed if the underlying stream closes

---

doc/api/webcrypto.md
lib/internal/crypto/cfrg.js
lib/internal/crypto/webcrypto.js
test/parallel/test-webcrypto-export-import-cfrg.js

As per https://github.com/WICG/webcrypto-secure-curves/pull/24 this removes the check for EdDSA `alg` during JWK importKey and removes the `alg` for Ed25519 and Ed448 keys during JWK exportKey.
The algorithms from https://github.com/WICG/webcrypto-secure-curves/ are marked as experimental  in our implementation which is why this can forgo semver-major and also be easily backported.

crypto: remove webcrypto EdDSA key checks and properties

---

src/node_task_queue.cc

PromiseWrap has been removed in
https://github.com/nodejs/node/pull/39135 and we do not have any internal object setting the internal field at 0 as a promise (we always set the first field as an aligned pointer to the embedder ID). As result GetAssignedPromiseWrapAsyncId() always just returns AsyncWrap::kInvalidAsyncId and turn the removed block into noops. So the block just can be removed.

src: remove unused PromiseWrap-related code

---

deps/uv/uv.gyp

This should fix https://github.com/nodejs/node/issues/49409

deps: add missing thread-common.c in uv.gyp

---

.github/CODEOWNERS

Currently the modules team is inactive and the loaders team functions as the team in charge of these files/areas.
cc @nodejs/modules in case anyone wants to join the @nodejs/loaders team since the modules may be removed.

meta: remove modules team from CODEOWNERS

---

test/embedding/embedtest.cc

- Build log(Ubuntu 20.04)
```shell
...
../test/embedding/embedtest.cc:67:3: warning: multi-line comment [-Wcomment]
67 |   // embedtest js_code_to_eval arg1 arg2... \
|   ^
../test/embedding/embedtest.cc:72:3: warning: multi-line comment [-Wcomment]
72 |   // embedtest --embedder-snapshot-blob blob-path \
...
```
Warning messages are occurring due to a comments on the following line.
https://github.com/nodejs/node/blob/3a6a80a4e1ad3fc3f1b181e1c94ecfd0b17e6dd1/test/embedding/embedtest.cc#L65-L76
A line of comment starting with `//` is supposed to end at the newline character. 
However, if a backslash(`\`) is placed at the end of the line, the comment is extended to the next line. This is because the backslash at the end of a line is a line-continuation character, which tells the compiler …

test: fix warning for comment in embedtest

---

lib/_tls_wrap.js

Use validateFunction to remove duplicate implementation. Plus, remove `assert()` statement because validateFunction has the same purpose.

tls: refactor to use validateFunction

---

lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers.js

In this comment, https://github.com/nodejs/node/pull/49397#discussion_r1309308550 @ljharb suggested preserving the behavior and attributes of properties as they were before the modification

test_runner: preserve original property descriptor when mutating objects

---

lib/_tls_wrap.js

Remove redundant code by moving it to outside of `if/else`.
Below code is duplicated because it exists on both if and else.
```
this.secureConnecting = false;
this.emit('secureConnect');
```

tls: remove redundant code in onConnectSecure()

---

lib/internal/test_runner/coverage.js
lib/internal/test_runner/test.js
test/fixtures/test-runner/output/coverage_failure.js
test/fixtures/test-runner/output/coverage_failure.snapshot
test/parallel/test-runner-output.mjs

Fixes: https://github.com/nodejs/node/issues/49398
not sure how to test this, any help appreciated

test_runner: fix typescript coverage

---

test/sequential/test-worker-prof.js

Use a JS workload instead of repeating FS operations to make it less flaky on machines with little resources.
Refs: https://github.com/nodejs/node/issues/26401
Refs: https://github.com/nodejs/reliability/issues/640

test: make test-worker-prof more robust

---

doc/api/esm.md

- add missing history entry.
- fix the return value description:
- The return value doesn't have to be a `file:` URL, it can be of any scheme.
- The return value doesn't have to correspond to a module, it can be a directory or something that doesn't exist.
- merge the two code examples, remove the use of the non-standard second argument.
- merge the two caveats.
- do not mention the old implementation, the history section is already there for that.
Refs: https://github.com/nodejs/node/pull/49028

doc: edit `import.meta.resolve` documentation

---

test/es-module/test-esm-loader-mock.mjs
test/fixtures/es-module-loaders/mock-loader.mjs
test/fixtures/es-module-loaders/mock.mjs

This PR refactors `test/es-module/test-esm-loader-mock.mjs` to use the new `register` and `initialize` APIs instead of `globalPreload` and `setImportMetaCallback`. I tried to preserve as much of the previous test as possible; all of the assertions from the earlier version are unchanged. This test passes both here, on `main`, and within #49144.
The largest addition to `test-esm-loader-mock.mjs` was code that just moved there from within the `insideAppContext` function in `mock-loader.mjs`.
@nodejs/loaders

esm: refactor mocking test

---

lib/internal/test_runner/mock/mock_timers.js

Add JSDocs for all public functions on MockTimers

test_runner: add jsdocs to MockTimers

---

doc/contributing/releases.md

This PR updates the instructions for Node.js Releasers when publishing a new Blog Post for the Node.js Website

doc: updated releasers instructions for node.js website

---

lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers.js

fix missing call to reset node timer call

test_runner: fix invalid timer call

---

lib/internal/process/pre_execution.js
test/sequential/test-heapdump-flag-custom-dir.js

process: add custom dir support for heapsnapshot-signal

---

doc/api/fs.md

Updated the documentation for the fs.createWriteStream function to clarify the usage of the highWaterMark option. The highWaterMark option was missing from the API docs but is a valid option that can be used with the function. This commit adds a description of the highWaterMark option to the API documentation to improve clarity for developers, especially those using TypeScript.
issue:#49420

doc: fix documentation for fs.createWriteStream highWaterMark option

---

lib/internal/modules/esm/translators.js
test/es-module/test-esm-recursive-cjs-dependencies.mjs
test/fixtures/recursive-a.cjs
test/fixtures/recursive-b.cjs

Fixes: https://github.com/nodejs/node/issues/49497

esm: fix loading of (recursive) CJS modules from ESM

---

doc/api/test.md

Fixes: https://github.com/nodejs/node/issues/49488
The script was missing necessary imports for the 'run' function and the 'path' module, causing it to fail. This commit adds the missing imports and resolves the issue.
- Import 'run' from the appropriate module.
- Import 'path' to resolve file paths.
The script should now run without errors.

doc: Fix missing imports in script

---

doc/api/child_process.md

Updated the documentation for the `input` option in child_process file, at execFile, execFileSync, spawnSync functions.
This update now clarify that supplying value to the `input` option will override `stdio[0]`, only if `stdio[0]` is set to `'pipe'`.
This will help avoid confusion when using the `input` option in any of the functions above.
Also updated the default value for the `stdio` option in the docs for the child_process.spawnSync function, to complete the picture.
Fixes: https://github.com/nodejs/node/issues/49417

doc: fix documentation for input option in child_process methods [execFile, execFileSync, spawnSync]

---

test/parallel/test-dotenv-node-options.js

Note: I've tried to add `LANG=C` or `LC_ALL=C` to [`test/fixtures/dotenv/node-options.env`](https://github.com/nodejs/node/blob/HEAD/test/fixtures/dotenv/node-options.env) and it didn't help. Setting `process.env.LANG = 'C'` in main process helps. Not sure if it's bug or feature.

test: make `test-dotenv-node-options` locale-independent

---

src/node_file.cc

It's an undocumented V8 behavior that is subject to change. Instead just check if the internal field is set to a promise. There is also no need to check IsEmpty() since the object is guaranteed to be constructed by the FileHandle constructor with enough internal fields.
Refs: https://chromium-review.googlesource.com/c/v8/v8/+/4707972/comment/be9285cc_a49aad88/

src: do not rely on the internal field being default to undefined

---

tools/js2c.cc

This PR makes js2c accept `"/path/to/config.gypi"` instead of forcing a `"config.gypi"` string, which is needed when building Node.js with alternative build systems.
/cc @joyeecheung
Refs https://github.com/nodejs/node/pull/47637 and https://github.com/nodejs/node/pull/46997.

tools: allow passing absolute path of config.gypi in js2c

---

doc/api/packages.md

Close parenthesis in [_Package entry points_](https://nodejs.org/api/packages.html#package-entry-points) chapter:
> Existing packages introducing the [`"exports"`](https://nodejs.org/api/packages.html#exports) field will prevent consumers of the package from using any entry points that are not defined, including the [`package.json`](https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions) (e.g. `require('your-package/package.json')`. **This will likely be a breaking change.**

doc: close a parenthesis

---

README.md

Refs: https://github.com/nodejs/Release/issues/892

doc: add release key for Ulises Gascon

---

test/parallel/test-crypto-dh-errors.js
test/parallel/test-crypto-dh-generate-keys.js
test/parallel/test-crypto-dh.js

Locally this speeds up running test-crypto-dh* from 7s to 2s. This was previously timing out in CI (took more than 2 minutes) so should see a bigger gap in the CI.
Refs: https://github.com/nodejs/node/issues/49202
Refs: https://github.com/nodejs/reliability/issues/655

test: split test-crypto-dh to avoid timeout on slow machines in the CI

---

src/node_dir.cc
src/node_file.cc

https://github.com/nodejs/node/issues/49293

src: fix fs_type_to_name default value

---

src/module_wrap.cc
src/module_wrap.h

There is no need to initialize the internal fields to undefined and then initialize them to something else in the caller. Simply pass the internal fields into the constructor to initialize them just once.

src: set ModuleWrap internal fields only once

---

node.gyp

This is a followup to https://github.com/nodejs/node/pull/46965, which will be very helpful for https://github.com/nodejs/node/pull/47637.

gyp: put cctest filenames in variables

---

doc/api_assets/api.js
doc/api_assets/style.css
test/doctool/test-doctool-html.mjs
tools/doc/buildCSSForFlavoredJS.mjs
tools/doc/html.mjs

A "selector" usually refers to a CSS selector, when here it refers to a checkbox.

doc: rename possibly confusing variable

---

doc/api/module.md
lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/loader.js
test/es-module/test-esm-loader-hooks.mjs
test/fixtures/es-module-loaders/hooks-initialize-port.mjs
test/fixtures/es-module-loaders/hooks-initialize.mjs

The current API shape is not great because it's too limited and redundant with the use of `MessagePort`.

esm: remove return value for `Module.register`

---

lib/internal/modules/esm/hooks.js

typings: fix missing property in `ExportedHooks`

---

doc/api_assets/api.js

Fixes: https://github.com/nodejs/node/issues/49508

doc: toggle all flavor selectors sticky on click

---

test/es-module/test-esm-loader-globalpreload-hook.mjs
test/es-module/test-esm-loader-hooks.mjs
test/fixtures/es-module-loaders/loader-this-value-inside-hook-functions.mjs

From https://github.com/nodejs/node/pull/49144#issuecomment-1710835214, this PR minimizes the changes in #49144 so that if an extended period goes by before it gets backported, the potential for conflicts is as reduced as possible. The idea is that this can be merged now, without breaking anyone; and #49144 can be merged on `main` but not backported for a while, which might cause difficulties backporting later PRs but hopefully such conflicts will be fewer because of the changes in _this_ PR. @nodejs/loaders 
I left one test in `test-esm-loader-hooks.mjs` because I expect that to remain (but change) after #49144, because presumably we’ll want to emit some kind of warning or error indefinitely when this hook is defined.

esm: isolate globalPreload

---

test/es-module/test-esm-loader-hooks.mjs

I recommend reviewing with whitespaces turned off.

test: increase coverage of `Module.register` and `initialize` hook

---

doc/api/cli.md
src/node.cc
src/node_dotenv.cc
src/node_dotenv.h
test/fixtures/dotenv/node-options.env
test/parallel/test-dotenv-edge-cases.js

From now on, you can pass multiple `--env-file` arguments. Each valid config file will
override any pre-existing declarations made in previous config file.
Example:
```bash
node --env-file=.env --env-file=.development.env index.js
```
Ref: https://github.com/nodejs/node/issues/49148

src: support multiple `--env-file` declarations

---

deps/zlib/zlib.gyp

It seems that the optimization causes memory corruption. Disable it until the issue is fixed upstream.
Fixes: https://github.com/nodejs/node/issues/45268

zlib: disable CRC32 SIMD optimization

---

lib/internal/process/execution.js
lib/repl.js

For internal usage, `internal/url` version should be used instead of re-exported `url`.

lib: use internal `pathToFileURL`

---

lib/internal/test_runner/coverage.js
lib/internal/watch_mode/files_watcher.js

For internal usage, `internal/url` should be used.
Refs: https://github.com/nodejs/node/pull/49553

lib: use internal `fileURLToPath`

---

common.gypi
deps/v8/include/v8-object.h
deps/v8/samples/process.cc
deps/v8/src/api/api.cc
deps/v8/test/cctest/test-api.cc
deps/v8/test/cctest/test-api.h
deps/v8/test/cctest/test-serialize.cc
deps/v8/test/unittests/objects/value-serializer-unittest.cc

[api] allow v8::Data as internal field
Previously only v8::Value can be stored as internal fields.
In some cases, however, it's necessary for the embedder to
tie the lifetime of a v8::Data with the lifetime of a
JS object, and that v8::Data may not be a v8::Value, as
it can be something returned from the V8 API. One way to
keep the v8::Data alive may be to use a v8::Persistent<v8::Data>
but that can easily lead to leaks.
This patch changes v8::Object::GetInternalField() and
v8::Object::SetInernalField() to accept v8::Data instead of just
v8::Value, so that v8::Data can kept alive by a JS object in
a way that the GC can be aware of to address this problem.
This is a breaking change for embedders
using v8::Object::GetInternalField() as it changes the return
type. …

deps: V8: backport 0aa622e12893

---

test/parallel/parallel.status

This is constantly failing on Windows now that the CI is never green there. To give CI at least some green space, mark it as SKIP, because we've been practically ignoring the failure for months anyway, and will probably just continue doing that.
Refs: https://github.com/nodejs/node/issues/48300

test: skip test-child-process-pipe-dataflow.js on Windows

---

test/pummel/test-heapdump-shadow-realm.js

With a tight loop the GC may not have enough time to kick in. Try setImmediate() instead.
Refs: https://github.com/nodejs/node/issues/49572

test: use setImmediate() in test-heapdump-shadowrealm.js

---

test/sequential/sequential.status

It has been flaky for more than a year. Mark it as flaky to avoid blocking the CI.
Refs: https://github.com/nodejs/reliability/issues/658

test: mark test-http-regr-gh-2928 as flaky

---

lib/internal/fs/dir.js
lib/internal/fs/utils.js
test/sequential/test-fs-opendir-recursive.js
test/sequential/test-fs-readdir-recursive.js

If the libuv operations invoked by `readdir`/`opendir` return `uv_dirent_t` values where the `type` is `UV_DIRENT_UNKNOWN` then a further `lstat` is issued to fully construct the `Dirent` values. In the recursive versions of these functions, the `path` parameter was incorrectly assumed to be the path to the entry when it should be the path to the directory containing the entry.
Fixes #49499.

fs: fix readdir and opendir recursive with unknown file types

---

lib/internal/errors.js

Before it would have say something like `Expected a … to be returned for the "…" from the function but got an instance of String.`, and with this PR it would say the more useful and more correct `Expected a … to be returned for the "…" from the function but got type string ('the input string')`.
Fixes: https://github.com/nodejs/node/issues/49576

errors: use `determineSpecificType` in more error messages

---

common.gypi
deps/v8/include/v8-script.h

[api] mark v8::Script and v8::UnboundScript as v8::Data
v8::UnboundModuleScript and v8::Module are already v8::Data.
Mark v8::Script and v8::UnboundScript as v8::Data so that they
can be used in other V8 APIs that takes v8::Data.
Refs: https://github.com/nodejs/node/pull/48510
Bug: v8:14120
Change-Id: I2dd5648528c1b0030292872441758d4fb2cfcc1c
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4827307
Reviewed-by: Camillo Bruni <cbruni@chromium.org>
Commit-Queue: Joyee Cheung <joyee@igalia.com>
Cr-Commit-Position: refs/heads/main@{#89727}
Refs: https://github.com/v8/v8/commit/b60a03df4cebafb4c92ee644d11617ad73889e5e

deps: V8: cherry-pick b60a03df4ceb

---

test/sequential/test-cli-syntax-require.js

Use spawnSyncAndExit() to show more info when the tes fails.

test: show more info on failure in test-cli-syntax-require.js

---

doc/api/module.md

With #49144, we have completed the [loaders roadmap Milestone 2](https://github.com/nodejs/loaders#milestone-2-stability). That milestone included everything that we thought needed to be done before potentially calling the module customization hooks stable. The hooks API as currently described in the documentation is hopefully the final design. It can get additions in the future, like any Node API, but we hope that there will be no more breaking changes to what’s there now.
This PR changes the stability levels for `register`, `initialize` and the hooks generally to stability index 1.2, release candidate. Once they have been at this level for a while with no reported bugs or issues, another PR will move them to stable. @nodejs/loaders 
The [module customization …

esm: set all module customization hooks as release candidate

---

test/parallel/test-tls-socket-close.js

Move the check for the destroyed state of the remote socket to the inner `setImmediate()`.
Refs: https://github.com/nodejs/node/pull/49327#issuecomment-1712525257

test: deflake test-tls-socket-close

---

benchmark/net/net-is-ip-v4.js
benchmark/net/net-is-ip-v6.js
lib/internal/net.js

Basically making the a capturing group to be non capturing.
I dont know how to bench the performance on nodejs
This is my benchmark:
```js
'use strict'
const { isIPv4: isIPv4builtIn } = require('net')
const benchmark = require('benchmark')
const suite = new benchmark.Suite()
const ipMax = '255.255.255.255'
const ipMin = '0.0.0.0'
const invalid = '0.0.0.0.0'
const isIPv4RE = /^(?:(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])[.]){3}(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$/
suite.add('RE', function () {
isIPv4RE.test(ipMin)
isIPv4RE.test(ipMax)
isIPv4RE.test(invalid)
})
suite.add('builtIn', function () {
isIPv4builtIn(ipMin)
isIPv4builtIn(ipMax)
isIPv4builtIn(invalid)
})
suite.on('cycle', function onCycle(event) {
console.log(String(event.target))
})
suite.run({ async: …
```

net: improve performance of isIPv4 and isIPv6

---

lib/internal/test_runner/mock/mock.js

Add JSDocs for all public functions of MockFunctionContext

test_runner: add jsdocs to MockFunctionContext and MockTracker

---

doc/api/test.md
lib/internal/test_runner/reporter/junit.js
lib/internal/test_runner/utils.js
lib/test/reporters.js
test/fixtures/test-runner/output/junit_reporter.js
test/fixtures/test-runner/output/junit_reporter.snapshot
test/parallel/test-runner-output.mjs

as per @cjihrig 's ask I have ported https://github.com/MoLow/reporters/tree/main/packages/junit into core

test_runner: add junit reporter

---

src/node_options.cc
test/parallel/test-runner-watch-mode.mjs

Fixes: https://github.com/nodejs/node/issues/49617
I cannot reproduce the original error reported in https://github.com/nodejs/node/issues/49544
but this fixes the issue in the [comment](https://github.com/nodejs/node/issues/49544#issuecomment-1711595665)

test_runner: fix test runner watch mode when no positional arguments

---

test/parallel/parallel.status

Refs: https://github.com/nodejs/node/issues/49605

test: mark test-runner-watch-mode as flaky

---

CHANGELOG.md

Refs: https://nodejs.org/en/blog/announcements/nodejs16-eol

doc: mark Node.js 16 as End-of-Life

---

test/parallel/parallel.status
test/parallel/test-child-process-pipe-dataflow.js
test/parallel/test-child-process-stdio-reuse-readable-stdio.js

It is flaky due to the same cause of test-child-process-pipe-dataflow being flaky - cygwin quirks - so skip it on Windows too.
Drive-by: remove the skip mark of test-child-process-pipe-dataflow in the status file and directly skip it in the test with a comment.

test: skip test-child-process-stdio-reuse-readable-stdio on Windows

---

lib/internal/errors.js
test/es-module/test-cjs-esm-warn.js

In #39175, better ESM errors were introduced. This commit tweaks the language in the error slightly to make it clear that there are three different options to resolve the error.
I find the current message more difficult to parse, because you only realise that you need to pick one of the three options after reading most of the (very long) sentence. Putting "either" at the start of the message should signpost that these are three options and you can pick any of them.
Before
```
[Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/Developer/company/repo/app/src/tracer.js not supported.
tracer.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename …
```

esm: clarify ERR_REQUIRE_ESM errors

---

.eslintrc.js
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/create_dynamic_module.js
lib/internal/modules/esm/formats.js
lib/internal/modules/esm/get_format.js
lib/internal/modules/esm/hooks.js
lib/internal/modules/esm/module_job.js
lib/internal/modules/esm/resolve.js
lib/internal/modules/esm/translators.js
lib/internal/modules/esm/worker.js
lib/internal/modules/run_main.js
test/fixtures/errors/force_colors.snapshot
test/fixtures/source-map/output/source_map_sourcemapping_url_string.snapshot

> Split out from https://github.com/nodejs/node/pull/49523 per https://github.com/nodejs/node/pull/49523#discussion_r1326244760.
This PR adds a lint rule to formalize our informal rule for modules code, where we try to always use braces to enclose blocks (so no implicit blocks after things like `if` conditions).

esm: require braces for modules code

---

benchmark/error/error-class-reg-exp.js
lib/internal/errors.js

This PR simplifies the RegExp for detecting class names
Main:
error/error-class-reg-exp.js n=100000: 9,114.045930023383
PR:
error/error-class-reg-exp.js n=100000: 11,002.079862772853

errors: improve performance of classRegExp in errors.js

---

doc/api/corepack.md

Refs: https://github.com/nodejs/corepack/pull/291

doc: update `corepack.md` to account for 0.20.0 changes

---

doc/api/deprecations.md
doc/api/util.md

The plan is to have it throw a runtime warning in the next major, so it will help catch cases like https://github.com/nodejs/node/issues/49607, and will likely never be EOL.

doc: deprecate calling `promisify` on a function that returns a promise

---

deps/llhttp/.gitignore
deps/llhttp/CMakeLists.txt
deps/llhttp/README.md
deps/llhttp/include/llhttp.h
deps/llhttp/src/api.c
deps/llhttp/src/http.c
deps/llhttp/src/llhttp.c
doc/api/cli.md
doc/api/http.md
doc/contributing/maintaining/maintaining-dependencies.md
src/node_http_parser.cc
test/parallel/test-http-client-error-rawbytes.js
test/parallel/test-http-client-reject-chunked-with-content-length.js
test/parallel/test-http-dummy-characters-smuggling.js
test/parallel/test-http-invalid-te.js
test/parallel/test-http-response-splitting.js
test/parallel/test-http-server-reject-chunked-with-content-length.js
test/parallel/test-https-foafssl.js
test/parallel/test-stream-destroy.js

This PR updates llhttp to version 9.1.2, which drops strict mode in favor of specific leniency flags.

deps: update llhttp to 9.1.2

---

doc/api/module.md
lib/internal/modules/esm/loader.js
test/es-module/test-esm-loader-hooks.mjs

Refs: https://github.com/nodejs/node/pull/49633#discussion_r1326349733

esm: fix support for `URL` instances in `register`

---

test/common/assertSnapshot.js
test/fixtures/errors/force_colors.snapshot
test/fixtures/source-map/output/source_map_sourcemapping_url_string.snapshot
test/parallel/test-node-output-errors.mjs
test/parallel/test-node-output-sourcemaps.mjs

Working on https://github.com/nodejs/node/pull/49657, I discovered that some of the more unusual snapshot tests had stack traces that include specifics of the module loader internals. (See https://github.com/nodejs/node/actions/runs/6191368639/job/16809521748?pr=49657.) Refactoring the modules code shouldn’t break these unrelated tests; these snapshots should be like the others that exclude detailed stack traces of modules internals. These two specific cases probably slipped through because they’re edge cases, having to do with source maps and colored stack trace output. This PR updates the tests and snapshots so that future modules changes don’t break these tests. @nodejs/test_runner @nodejs/testing

test: fix edge snapshot stack traces

---

doc/api/cli.md

Over the years `cli.md` has had a few sections get out of alphabetical order. @nodejs/documentation @Trott 
There is zero content changed here other than sections moving. I didn’t edit a single character _within_ any sections that moved.

doc: alphabetize cli.md sections

---

src/pipe_wrap.cc
test/parallel/test-pipe-abstract-socket-http.js

This PR moves `PipeWrap` from the classic `uv_pipe_bind` and `uv_pipe_connect` methods to their newer `uv_pipe_bind2` and `uv_pipe_connect2` counterparts. This restores support for connecting to abstract unix domain sockets. Support was lost due to the refactor in libuv/libuv#4030 where `uv_pipe_bind` and `uv_pipe_connect` now infer the length of the `pathname` using `strlen()`. For an abstract unix socket, this was producing `0`. Moving to `uv_pipe_bind2` and `uv_pipe_connect2` allows us to pass an explicit `size_t` for the socket path based on the length of the v8 string.
Fixes: https://github.com/nodejs/node/issues/49656

Update PipeWrap to use uv_pipe_bind2 and uv_pipe_connect2 to restore ability to connect to abstract domain sockets

---

doc/api/deprecations.md
lib/internal/util.js
test/parallel/test-util-promisify.js

My goal would be for this deprecation to never reach EOL, and stay as runtime deprecated forever. The warning it produces should help folks who run into the linked issue figure out what's happening.
```js
// file.js
const promisified = promisify(async () => {});
promisified();
```
`node --trace-warnings file.js` will show `at file.js:5:1` – so not where the `promisify` call happened, but where the promisified function was called. Hopefully that will give enough info to debug it.
Fixes: https://github.com/nodejs/node/issues/49607

util: runtime deprecate `promisify`-ing a function returning a `Promise`

---

lib/internal/webstreams/readablestream.js

140% Improvement
```
webstreams/creation.js kind='ReadableStream.tee' n=50000                              -0.96 %       ±3.01%  ±4.01%  ±5.22%
webstreams/creation.js kind='ReadableStream' n=50000                                  -0.15 %       ±3.60%  ±4.79%  ±6.24%
webstreams/creation.js kind='ReadableStreamBYOBReader' n=50000                        -0.26 %       ±4.59%  ±6.11%  ±7.95%
webstreams/creation.js kind='ReadableStreamDefaultReader' n=50000                      6.40 %      ±10.81% ±14.40% ±18.76%
webstreams/creation.js kind='TransformStream' n=50000                                 -1.70 %       ±2.61%  ±3.48%  ±4.52%
webstreams/creation.js kind='WritableStream' n=50000                                   0.50 %       ±4.24% …
```

stream: improve webstream readable async iterator performance

---

lib/internal/dns/promises.js
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/create_dynamic_module.js
lib/internal/modules/esm/fetch_module.js
lib/internal/modules/esm/handle_process_exit.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/package_config.js
lib/internal/modules/esm/resolve.js
lib/internal/modules/esm/translators.js
lib/internal/modules/esm/utils.js
lib/internal/modules/esm/worker.js
lib/internal/modules/helpers.js
lib/internal/modules/run_main.js

This PR adds JSDoc annotations for all the files in `lib/internal/modules/*` as well as a lint rule to enforce keeping that code annotated.

esm: jsdoc for modules code

---

lib/internal/modules/esm/loader.js
test/es-module/test-esm-experimental-warnings.mjs

Following up https://github.com/nodejs/node/pull/49597, this PR edits the warning when `--experimental-loader` / `--loader` is used to tell people to use `--import` / `register()` instead, which has no warning. The separate warning about `globalPreload` remains.

esm: update loaders warning

---

benchmark/webstreams/readable-read.js

While looking at https://github.com/nodejs/performance/issues/82 and trying to find a way to optimise read() realised that there is no specific benchmark for the read() function and the byob variant of read too
Refs: https://github.com/nodejs/performance/issues/82

benchmark: add a benchmark for read() of ReadableStreams

---

doc/api/events.md

In the `mjs` example, when printing `this`, it is displayed as `undefined`.
Refs: https://github.com/nodejs/node/issues/49537

doc: fix print results in `events`

---

doc/contributing/pull-requests.md

doc: link maintaining deps to pull-request.md

---

lib/internal/webstreams/readablestream.js

improvement of ~60%
```
webstreams/creation.js kind='ReadableStream.tee' n=50000                        *     -3.14 %       ±2.61%  ±3.49%  ±4.56%
webstreams/creation.js kind='ReadableStream' n=50000                                   0.82 %       ±3.54%  ±4.71%  ±6.13%
webstreams/creation.js kind='ReadableStreamBYOBReader' n=50000                        -0.03 %       ±4.17%  ±5.55%  ±7.23%
webstreams/creation.js kind='ReadableStreamDefaultReader' n=50000                      3.01 %      ±10.03% ±13.40% ±17.56%
webstreams/creation.js kind='TransformStream' n=50000                                  1.19 %       ±2.14%  ±2.84%  ±3.70%
webstreams/creation.js kind='WritableStream' n=50000                                  -1.15 %       ±3.61% …
```

stream: improve readable webstream `pipeTo`

---

lib/internal/errors.js
lib/internal/modules/esm/initialize_import_meta.js
test/es-module/test-esm-import-meta-resolve.mjs

Fixes: https://github.com/nodejs/node/issues/49695

esm: fix return type of `import.meta.resolve`

---

doc/api/esm.md

doc: add missing history info for `import.meta.resolve`

---

doc/api/errors.md
doc/api/url.md

doc: fix history comments

---

doc/api/util.md

In exmple of `util.inspect` with numericSeparator option, calling `util.inspect` is missed. So actual result is different from expected result.
Expected result:
```
1_000 1_000_000 123_456_789n 1_234.123_45 
```
Actual result:
```
1000 1000000 123456789n 1234.12345
```

doc: add missed `inspect` with numericSeparator to example

---

lib/repl.js
test/parallel/test-repl-save-load.js

When using .load the REPL would accumulate indentation with each line
including the indentation from all previous lines. Now it keeps the
indentation at the correct level.
Fixes: https://github.com/nodejs/node/issues/47673

repl: Don't accumulate excess indentation in .load

---

doc/api/util.md

Actual output of example in `mimeParams.set()` is mismatched.
So update output of example in `mimeParams.set()`.
Expected output:
```
foo=def&bar=1&baz=xyz
```
Actual output:
```
foo=def;bar=1;baz=xyz
```

doc: update output of example in `mimeParams.set()`

---

doc/api/util.md

The function call was missed from the example of the `async function` in `util.promisify`, so it was added.

doc: add missing function call to example for `util.promisify`

---

benchmark/fs/bench-opendirSync.js
lib/internal/fs/dir.js
src/node_dir.cc

```
fs/bench-opendirSync.js n=10000 bufferSize=128 type='existing'                    -0.15 %       ±1.56%  ±2.08%  ±2.71%
fs/bench-opendirSync.js n=10000 bufferSize=128 type='non-existing'        ***    109.56 %       ±3.93%  ±5.23%  ±6.81%
fs/bench-opendirSync.js n=10000 bufferSize=32 type='existing'                     -0.34 %       ±1.95%  ±2.60%  ±3.39%
fs/bench-opendirSync.js n=10000 bufferSize=32 type='non-existing'         ***    111.68 %       ±3.03%  ±4.03%  ±5.25%
fs/bench-opendirSync.js n=10000 bufferSize=4 type='existing'                      -1.19 %       ±1.44%  ±1.92%  ±2.51%
fs/bench-opendirSync.js n=10000 bufferSize=4 type='non-existing'          ***    104.85 %       ±8.18% ±11.01% ±14.59%
```

fs: improve error performance of `opendirSync`

---

doc/contributing/strategic-initiatives.md

This is a pull request to add the strategic initiative outlined in https://github.com/nodejs/TSC/issues/1439 there is a list of tasks here https://github.com/nodejs/TSC/issues/1439#issuecomment-1717016394
Please do not fast-track this as I'd like to give https://github.com/nodejs/TSC/issues/1439#issuecomment-1717016394 a week to make sure everyone had time to see it for lazy consensus

meta: add primordials strategic initiative 

---

lib/internal/test_runner/harness.js
lib/internal/test_runner/utils.js
test/fixtures/test-runner/custom_reporters/throwing-async.js
test/fixtures/test-runner/custom_reporters/throwing.js
test/parallel/test-runner-reporters.js

Fixes: https://github.com/nodejs/node/issues/49733

test_runner: accept `testOnly` in `run`

---

doc/api/deprecations.md

`StringPrototypeToWellFormed` can be disabled with a harmony flag. Therefore, we can't use it in core, but this doesn't mean that we can't doc-only deprecate it for developers.
In favor of `String.prototype.toWellFormed` doc-only deprecate `util.toUSVString`.
https://chromestatus.com/feature/5200195346759680
Ref: https://github.com/nodejs/node/pull/47342
cc @nodejs/tsc

doc: deprecate `util.toUSVString`

---

src/node_file.cc

src: remove unnecessary todo

---

doc/contributing/strategic-initiatives.md

meta: fix linter error

---

lib/internal/blob.js
test/parallel/test-blob.js
test/wpt/status/FileAPI/blob.json

Fixes: https://github.com/nodejs/node/issues/47993

lib: allow byob reader for 'blob.stream()'

---

lib/internal/modules/esm/resolve.js
test/es-module/test-esm-loader-default-resolver.mjs
test/fixtures/es-modules/invalid-posix-host.mjs

New output:
```
TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on darwin
at new NodeError (node:internal/errors:406:5)
at getPathFromURLPosix (node:internal/url:1385:11)
at fileURLToPath (node:internal/url:1408:50)
at finalizeResolution (node:internal/modules/esm/resolve:210:16)
…
code: 'ERR_INVALID_FILE_URL_HOST',
input: 'file://hmm.js/',
module: 'file:///…/test.mjs'
```
fixes https://github.com/nodejs/node/issues/49571

esm: identify parent importing a url with invalid host

---

deps/uv/uv.gyp

The file was removed in the latest libuv upgrade. Remove it from the build recipe as well.
Fixes: https://github.com/nodejs/node/issues/49739

deps: remove pthread-fixes.c from uv.gyp

---

benchmark/readline/readline-iterable.js
test/parallel/test-readline-async-iterators.js

Refactor test-readline-async-iterators into a benchmark
Fixes: https://github.com/nodejs/node/issues/49224 
Added old way of readline async iterator to benchmark.

Refactor test-readline-async-iterators into a benchmark

---

doc/contributing/backporting-to-release-lines.md

also updated 10.x to 20.x in backporting examples

doc: add `git node backport` way to the backporting guide

---

lib/internal/streams/readable.js

cc @ronag @anonrig this should save (worst case) 17 bytes per stream

stream: use bitmap in readable state

---

doc/api/test.md
lib/internal/test_runner/runner.js
test/fixtures/test-runner/test_only.js
test/parallel/test-runner-run.mjs

Fixes: https://github.com/nodejs/node/issues/49733
I mistakinaly pushed a commit to https://github.com/nodejs/node/pull/49743 that caused it to close. will need a approval again

test_runner: accept `only` in `run`

---

lib/fs.js

Ref https://github.com/nodejs/node/pull/49691#issuecomment-1723120461 by @bnoordhuis

fs: fix file descriptor validator

---

doc/api/n-api.md
src/node_api.cc
test/js-native-api/test_reference/binding.gyp
test/js-native-api/test_reference/test_finalizer.c
test/js-native-api/test_reference/test_finalizer.js
test/js-native-api/test_reference/test_reference.c
test/node-api/test_buffer/binding.gyp
test/node-api/test_buffer/test_buffer.c
test/node-api/test_buffer/test_finalizer.c
test/node-api/test_buffer/test_finalizer.js
test/node-api/test_threadsafe_function/binding.gyp
test/node-api/test_threadsafe_function/test_legacy_uncaught_exception.js
test/node-api/test_threadsafe_function/test_uncaught_exception.c
test/node-api/test_threadsafe_function/test_uncaught_exception.js
test/node-api/test_threadsafe_function/test_uncaught_exception_v9.js
test/node-api/test_threadsafe_function/uncaught_exception.js

This enables the option `--force-node-api-uncaught-exceptions-policy`
for a specific Node-API addon when it is compiled with 
`NAPI_EXPERIMENTAL` (and this would be the default behavior when 
`NAPI_VERSION` 10 releases). This would not break existing Node-API
addons.
Refs: https://github.com/nodejs/node/pull/36510

node-api: enable uncaught exceptions policy by default

---

test/parallel/test-trace-events-bootstrap.js

This pull request is for the Issue provided in the Open Source Day of GHC
Issue guideline - "Replace mustCall((err, data) ...) with mustSucceed((data) ...) in test-trace-events-bootstrap.js"

test: use mustSucceed instead of mustCall

---

doc/api/deprecations.md
doc/api/fs.md

These constants were soft deprecated since [v6.3.0](https://nodejs.org/api/fs.html#fsaccesspath-mode-callback) in favour of `fs.constants`.
Nowadays we also have `fs.promises.constants` without re-exposing those directly on `fs.promises`, so perhaps it's time to get rid of them.
cc @nodejs/fs

doc: deprecate `fs.F_OK`, `fs.R_OK`, `fs.W_OK`, `fs.X_OK`

---

test/parallel/parallel.status

This has been flaky on many platforms for months. Mark it as flaky for now to avoid blocking the CI.
Refs: https://github.com/nodejs/node/issues/49853
Refs: https://github.com/nodejs/reliability/issues/673

test: mark test-runner-output as flaky

---

benchmark/fs/readFileSync.js
lib/fs.js
lib/internal/fs/sync.js
src/node_file.cc

This particular change applies to: `fs.readFileSync(fs.openSync(__filename), 'utf8')`
My local benchmarks are as follows:
```
fs/readFileSync.js n=10000 hasFileDescriptor='false' path='existing' encoding='undefined'                     0.73 %       ±1.65% ±2.20% ±2.86%
fs/readFileSync.js n=10000 hasFileDescriptor='false' path='existing' encoding='utf8'                          0.05 %       ±1.74% ±2.32% ±3.02%
fs/readFileSync.js n=10000 hasFileDescriptor='false' path='non-existing' encoding='undefined'        ***     62.27 %       ±2.82% ±3.77% ±4.95%
fs/readFileSync.js n=10000 hasFileDescriptor='false' path='non-existing' encoding='utf8'             ***     60.93 %       ±2.72% ±3.64% ±4.78%
fs/readFileSync.js n=10000 hasFileDescriptor='true' path='existing' encoding='undefined' …
```

fs: improve `readFileSync` with file descriptors

---

.github/workflows/tools.yml

refs: https://github.com/nodejs/node/pull/49869/commits/fbe28e2f1da0a66a78164201048c0c60615bd0c8
https://github.com/nodejs/node/pull/49869 requires the [latest release of @reporters/github ](https://github.com/MoLow/reporters/releases/tag/github-v1.5.3) wich cannot be manually updated

tools: support updating @reporters/github manually

---

benchmark/url/whatwg-url-validity.js
lib/internal/errors.js
lib/internal/url.js
src/env_properties.h
src/node_url.cc
src/node_url.h
test/parallel/test-url-null-char.js
test/parallel/test-whatwg-url-custom-parsing.js

Some easy wins for `Invalid URL` path.
```
url/whatwg-url-validity.js e=100000 type='invalid'        ***    120.33 %       ±2.06% ±2.74% ±3.56%
url/whatwg-url-validity.js e=100000 type='valid'                   1.35 %       ±2.21% ±2.96% ±3.91%
In this case, there are 2 comparisons, you can thus expect the following amount of false-positive results:
```
cc @nodejs/url @nodejs/performance

url: improve invalid url performance

---

lib/internal/streams/writable.js

same as the following PR but for writable:
- https://github.com/nodejs/node/pull/49745
**Benchmark CI output:**
```
streams/creation.js kind='duplex' n=50000000                                                     ***     10.15 %       ±1.04%  ±1.39%  ±1.81%
streams/creation.js kind='readable' n=50000000                                                   ***     -1.59 %       ±0.64%  ±0.85%  ±1.11%
streams/creation.js kind='transform' n=50000000                                                           3.94 %       ±4.16%  ±5.58%  ±7.37%
streams/creation.js kind='writable' n=50000000                                                   ***     14.64 %       ±1.57%  ±2.09%  ±2.73%
streams/destroy.js kind='duplex' n=1000000 …
```

stream: use bitmap in writable state

---

test/fixtures/test-runner/output/abort.snapshot
test/fixtures/test-runner/output/abort_hooks.snapshot
test/fixtures/test-runner/output/abort_suite.snapshot
test/fixtures/test-runner/output/arbitrary-output.snapshot
test/fixtures/test-runner/output/describe_it.snapshot
test/fixtures/test-runner/output/hooks.snapshot
test/fixtures/test-runner/output/unresolved_promise.snapshot
test/parallel/test-runner-output.mjs

Fixes: https://github.com/nodejs/node/issues/49853

test: deflake test-runner-output

---

benchmark/perf_hooks/timerfied.js
lib/internal/perf/performance_entry.js

Continuing the work started on https://github.com/nodejs/performance/issues/109
Removed two references for `ReflectConstruct`, the improvements for `createPerformanceNodeEntry` can be seen using the `timerfied` function:
```
perf_hooks/timerfied.js observe='function' n=100000        ***    872.44 %      ±22.56% ±30.40% ±40.36%
result increases. In this case, there are 1 comparisons, you can thus
0.05 false positives, when considering a   5% risk acceptance (*, **, ***),
0.01 false positives, when considering a   1% risk acceptance (**, ***),
``` …

perf_hooks: reduce overhead of new performance_entries

---

src/node_file.cc

All FS methods should not use it since FS operations will have side effects (suggested by @anonrig)

fs: replace `SetMethodNoSideEffect` in `node_file.cc`

---

test/parallel/test-os.js

adding more `os.setPriority` & `os.getPriority` test coverage

test: add os setPriority, getPriority test coverage

---

common.gypi
deps/v8/src/snapshot/embedded/platform-embedded-file-writer-base.cc

fix: EmbeddedTargetOs on IBM i with Python 3.9
For some context, Python 3.9 on IBM i returns "os400" for sys.platform
instead of "aix". We used to build with Python 3.6 which returned "aix"
as the platform
When attempting to build Node.js with python 3.9 on IBM i we run into a
build error.
Ref: https://github.com/nodejs/node/pull/48056
Ref: https://github.com/nodejs/node/pull/48056#issuecomment-1553719508
I'm not quite sure where target_os is being passed down to the function ToEmbeddedTargetOs.
It seems as though target_os is being generated from sys.platform or
similar call from python as we started running into this issue after
building with Python 3.9.
This PR supersedes initial changes proposed in:
https://chromium-review.googlesource.com/c/v8/v8/+/4259330 …

deps: V8: cherry-pick 8ec2651fbdd8

---

.eslintrc.js
doc/api/cli.md
doc/api/globals.md
doc/node.1
lib/internal/process/pre_execution.js
src/node_options.cc
src/node_options.h
test/common/globals.js
test/common/index.js
test/parallel/test-websocket.js

lib: add WebSocket

---

doc/template.html
tools/doc/allhtml.mjs
tools/doc/html.mjs

As an a11y enhancement, supply ARIA landmarks for all content.

doc, tools: add ARIA landmarks to API docs

---

.github/CODEOWNERS

Pings for the website team aren't working because the team name changed but it did not get updated in CODEOWNERS.

meta: update website team with new name

---

lib/internal/modules/esm/translators.js
test/es-module/test-esm-json.mjs
test/es-module/test-esm-virtual-json.mjs

Fixes: https://github.com/nodejs/node/issues/49724

esm: fix cache collision on JSON files using file: URL

---

doc/api/fs.md
lib/fs.js
lib/internal/fs/promises.js
lib/internal/fs/utils.js
test/parallel/test-fs-read-position-validation.mjs
test/parallel/test-fs-read-promises-position-validation.mjs
test/parallel/test-fs-readSync-position-validation.mjs

This PR:
- Adds validation of `position` argument to `filehandle.read()`, same as in cousin methods
- Allows bigint position for `filehandle.read()`
- Adjusts min number position from `Number.MIN_SAFE_INTEGER` to `-1`
- Adjusts min bigint position from `-2⁶³` to `-1`
- Adjusts max bigint position from `2⁶³ - 1` to `2⁶³ - 1 - length`
- Makes docs a bit more pedantic
Tests are still passing and documented features are still working, but there are potentially breaking changes:
- When user passes an unsafe number or not a number in `filehandle.read()`, an exception is thrown.
- Previously: silently read from current position.
- When user passes a safe bigint in `filehandle.read()`, it works.
- Previously: silently read from current position.
- When user passes a negative integer (except for …

fs: adjust `position` validation in reading methods

---

lib/events.js
test/parallel/test-events-on-async-iterator.js
test/parallel/test-events-once.js

Check whether options is object or not to avoid passing invalid type as options to `on` and `once`.
Refs: https://nodejs.org/dist/latest-v19.x/docs/api/events.html#eventsonceemitter-name-options

events: validate options of `on` and `once`

---

benchmark/error/format-list.js
lib/internal/errors.js
test/parallel/test-error-format-list.js

This PR improves formatLIst in errors.js
The benchmarks:
main: 
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/node$ ./node benchmark/error/format-list.js 
error/format-list.js input="" n=10000000: 19,674,229.0009035
error/format-list.js input="a" n=10000000: 17,898,703.51886578
error/format-list.js input="a,b" n=10000000: 8,773,227.708163619
error/format-list.js input="a,b,c" n=10000000: 5,988,210.708969075
```
PR:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/node$ ./node benchmark/error/format-list.js 
error/format-list.js input="" n=10000000: 544,845,141.1173433
error/format-list.js input="a" n=10000000: 543,086,471.205501
error/format-list.js input="a,b" n=10000000: 37,940,629.811950795
error/format-list.js input="a,b,c" n=10000000: 6,147,421.564903789
```

errors: improve formatList in errors.js

---

src/node_file.cc
src/node_file.h

After checking the comments in the reference, it seems that there is no need to define a 'const' variable in the header.
It seems efficient to handle this by defining it as `constexpr` in the source file so that it can be evaluated at compile time. For this purpose, it would be better to change it to `std::string_view` rather than handling it as `std::string`.
Refs: #48325

src: move const variable in `node_file.h` to `node_file.cc`

---

lib/internal/test_runner/test.js

There is an `if` statement that likely should have been an `else` in the original PR.
Refs: https://github.com/nodejs/node/pull/48915

test_runner: replace spurious if with else

---

lib/http.js
lib/https.js

A missing parameter was added to the jsdoc of `HTTPRequestOptions`.
- `joinDuplicateHeaders`
- `uniqueHeaders`
https://github.com/nodejs/node/blob/main/doc/api/http.md#httprequesturl-options-callback

lib: update params in jsdoc for `HTTPRequestOptions`

---

doc/api/permissions.md

Much earlier, a design decision was made that the permission model should not prevent following symbolic links to presumably inaccessible locations. Recently, after some back and forth, it had been decided that it is indeed a vulnerability that symbolic links, which currently point to an accessible location, can potentially be re-targeted to point to a presumably inaccessible location. Nevertheless, months later, no solution has been found and the issue is deemed unfixable in the context of the current permission model implementation, so it was decided to disclose the ~vulnerability~ _peculiarity_ and to shift responsibiliy onto users who are now responsible for ensuring that no potentially dangerous symlinks exist in any directories that they grant access to.
I believe that this design …

doc: document dangerous symlink behavior

---

typings/primordials.d.ts

Hey 👋 
I noticed that in the [`primordials.js`, SymbolDispose and SymbolAsyncDispose](https://github.com/nodejs/node/blob/main/lib/internal/per_context/primordials.js#L234-L235) are defined as
```ts
primordials.SymbolDispose ??= primordials.SymbolFor('nodejs.dispose');
primordials.SymbolAsyncDispose ??= primordials.SymbolFor('nodejs.asyncDispose');
```
The result of `primordials.SymbolFor` is a `symbol`. Currently these two properties are defined as `SymbolConstructor` (`typeof Symbol`). I think this is incorrect and should be updated to `symbol` instead.

lib: fix `primordials` typings

---

benchmark/streams/writable-manywrites.js
lib/internal/streams/writable.js

Just some ideas. Not sure I will have time to finish this. Feel free to take over.

stream: writable state bitmap

---

src/inspector/node_string.cc
src/inspector/node_string.h
src/inspector_agent.cc
tools/inspector_protocol/lib/base_string_adapter_cc.template
tools/inspector_protocol/lib/base_string_adapter_h.template

This is in relation with bug https://github.com/nodejs/node/issues/47457 where we found that under Windows, there seems to be a problem when converting from UTF-8 to UTF-16 a JSON message generated by key presses in the REPL.
Tracing it back, I found evidence that in common cases, each time you hit a key in the Node REPL, a call to `dispatchProtocolMessage` is made, passing an UTF-16 JSON message. The message is converted to UTF-8 into the local variable `raw_message`, and then we call `parseMessage` which converts back `raw_message` into UTF-16 and calls `parseJSON` on it.
This PR avoids the conversion from UTF-8 back into UTF-16. This should save some processing that is currently done with each key press.
It is possible that it is a [Chesterton's …

inspector: simplify dispatchProtocolMessage

---

lib/internal/modules/cjs/loader.js
lib/internal/modules/helpers.js
lib/internal/modules/package_json_reader.js
lib/internal/modules/run_main.js

Following up #49869, supporting #49432, this PR moves some methods that are used by both the CommonJS and ESM startup flows out of `cjs/loader.js` and into shared common files. This is a precursor for the next PR that refactors how the initial entry point is handled in ESM-first mode.
All this PR does is move the code; nothing is changed other than references to variables. @nodejs/loaders

module: move helpers out of CommonJS loader

---

test/parallel/parallel.status

This reverts commit 717e233cd95602f79256c5b70c49703fa699174b.
Refs: https://github.com/nodejs/node/commit/fef7927cc3a7

Revert "test: mark test-runner-output as flaky"

---

test/es-module/es-module.status
test/parallel/parallel.status

`test-wasm-web-api` was moved from `test/parallel` to `test/es-modules`. Update the status files for parallel and es-modules accordingly.
Refs: https://github.com/nodejs/node/pull/49869
Refs: https://github.com/nodejs/node/pull/47299
Refs: https://github.com/nodejs/node/issues/47297
---
Started seeing `test-wasm-web-api` failing for arm64 debug builds again today. 
e.g. https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2004_debug-arm64/9557/ seems to be the earliest build that it happened in. 
According to the [reliability repo](https://github.com/search?q=repo%3Anodejs%2Freliability+test-wasm-web-api&type=issues&s=created&o=desc), we saw this test flaking at the beginning of the year. We started skipping it on arm in https://github.com/nodejs/node/pull/47299. …

test: update skip for moved `test-wasm-web-api`

---

lib/internal/process/pre_execution.js
test/parallel/test-fetch.mjs

I haven't tracked down exactly where the webidl spec says this, but every other platform I've tested matches this behavior. This has been nagging at me for a while 😅

lib: make fetch sync and return a Promise

---

src/node_credentials.cc

`uv_os_getenv` returns `0` for happy path.
- [Windows implementation ref](https://github.com/libuv/libuv/blob/2f8275009854599ec7de68dbef795e82b6b5fb30/src/win/util.c#L1463)
- [Unix implementation ref](https://github.com/libuv/libuv/blob/2f8275009854599ec7de68dbef795e82b6b5fb30/src/unix/core.c#L1452)

src: use exact return value for `uv_os_getenv`

---

benchmark/error/determine-specific-type.js
lib/internal/errors.js
test/common/index.js
test/parallel/test-error-value-type-detection.mjs
test/parallel/test-fs-readfile-error.js

This PR improves the function determineSpecificType in errors.js.  
Also fixes a bug, where a string would be sliced without the single tick at the end of the string. 
Added unit tests. Added benchmarks based on unit tests.
main:
```sh
error/determine-specific-type.js v="() => 1n" n=1000000: 6,843,920.840090735
error/determine-specific-type.js v="() => true" n=1000000: 9,456,016.191725645
error/determine-specific-type.js v="() => false" n=1000000: 8,851,588.609212818
error/determine-specific-type.js v="() => 2" n=1000000: 9,901,905.486054687
error/determine-specific-type.js v="() => +0" n=1000000: 8,973,347.793105612
error/determine-specific-type.js v="() => -0" n=1000000: 10,751,000.496169424
error/determine-specific-type.js v="() => NaN" n=1000000: 10,215,963.841045486 …
```

errors: improve performance of determineSpecificType

---

benchmark/perf_hooks/resourcetiming.js
lib/internal/perf/performance_entry.js
lib/internal/perf/resource_timing.js

Continuing the work started on https://github.com/nodejs/performance/issues/109.
This PR should be landed after #49803.
```
perf_hooks/resourcetiming.js observe='resource' n=100000        ***   1086.23 %      ±40.80% ±54.98% ±72.99%
result increases. In this case, there are 1 comparisons, you can thus
0.05 false positives, when considering a   5% risk acceptance (*, **, ***),
0.01 false positives, when considering a   1% risk acceptance (**, ***),
```
~I want to use the symbol `kSkipThrow` in other classes around the NodeJS codebase, someone had …

perf_hooks: reduce overhead of new resource timings

---

lib/_tls_wrap.js
test/parallel/test-tls-basic-validations.js

If user uses invalid type for `options.checkServerIdentity` in tls.connect(), it's not internal issue of Node.js. So validateFunction() is more proper than assert().
Fixes: https://github.com/nodejs/node/issues/49839
Before
```
node:internal/assert:14
throw new ERR_INTERNAL_ASSERTION(message);
^
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues
```
After
```
node:internal/validators:440
throw new ERR_INVALID_ARG_TYPE(name, 'Function', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "options.checkServerIdentity" property must be of type function. Received undefined
```

tls: use validateFunction for `options.checkServerIdentity`

---

lib/internal/modules/run_main.js
lib/internal/process/pre_execution.js

Extracted from https://github.com/nodejs/node/pull/49918

esm: improve JSDoc annotation of internal functions

---

BUILDING.md
tools/bootstrap/windows_boxstarter

This PR updates the Windows Building Instructions and the Boxstarter Automated Installation Script due to the following:
- The `vcbuild.bat` will require Python3 to be installed, but on Windows, if Python 2 is installed, it will take precedence over the `$PATH`; also, Python2 is not needed for Node.js builds anymore.
- If installed on ARM64, the recommended packages are incompatible. ARM64 compatibility was added with Visual Studio 2022 (17.4.0 or higher)
- Updated the scripts to use VS2022 Chocolatey Packages
- Updated the Building docs to use the newest Visual Studio Packages (which are compatible with Windows 10 and Windows 11)
- Updated Docs to clarify that folks should first clone the repository and head to the cloned directory. A bunch of newcomers on Grace Hopper were confused …

doc: updated building docs for windows

---

doc/api/vm.md

The current link in the docs go to a page that does not have the Abstract Module Records information. Update the link to an official source that does.

doc: update link to Abstract Modules Records spec

---

lib/internal/streams/writable.js

```
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='no' n=100000            ***      4.11 %       ±1.32% ±1.76% ±2.31%
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='yes' n=100000           ***     -2.82 %       ±1.32% ±1.77% ±2.34%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='no' n=100000           ***      4.15 %       ±1.63% ±2.18% ±2.85%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='yes' n=100000          ***      2.74 %       ±1.17% ±1.57% ±2.06%
streams/writable-manywrites.js len=1024 callback='yes' writev='no' sync='no' n=100000           ***      4.59 %       ±1.55% ±2.06% ±2.68%
streams/writable-manywrites.js len=1024 callback='yes' writev='no' sync='yes' n=100000          *** …
```

stream: avoid tick in writable hot path

---

deps/ngtcp2/ngtcp2.gyp

I don't think it's the right method but this solves these errors when compiling for Android arm64:
```
../deps/ngtcp2/nghttp3/lib/nghttp3_conv.c:49:21: error: call to undeclared function 'ntohs'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
return (int64_t)ntohs(n.n16);
^
../deps/ngtcp2/nghttp3/lib/nghttp3_conv.c:53:21: error: call to undeclared function 'ntohl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
return (int64_t)ntohl(n.n32);
^
../deps/ngtcp2/nghttp3/lib/nghttp3_conv.c:69:7: error: call to undeclared function 'ntohl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
n = nghttp3_htonl64(n);
^ …
```

nghttp3_conv: fix call to undeclared functions 'ntohl' and 'htons'

---

benchmark/validators/validate-object.js
lib/fs.js
lib/internal/abort_controller.js
lib/internal/encoding.js
lib/internal/event_target.js
lib/internal/fs/promises.js
lib/internal/util/inspect.js
lib/internal/validators.js
lib/internal/vm.js
lib/internal/webstreams/readablestream.js
test/benchmark/test-benchmark-validators.js
test/parallel/test-validators.js

Reducing the number of comparisons and allocations when using `validateObject`.
```
confidence improvement accuracy (*)      (**)     (***)
validators/validate-object.js objectToTest='array' n=100000           ***  28696.95 %    ±1448.43% ±1952.07% ±2591.59%
validators/validate-object.js objectToTest='function' n=100000        ***  28553.34 %    ±1501.99% ±2024.25% ±2687.42%
validators/validate-object.js objectToTest='null' n=100000            ***  25157.86 %    ±1483.43% ±1999.24% ±2654.21%
validators/validate-object.js objectToTest='object' n=100000          ***     60.87 %      ±10.64%   ±14.24%   ±18.70%
result increases. In this case, there are 4 comparisons, you can thus
expect the following amount of …
```

lib: reduce overhead of validateObject

---

doc/abi_version_registry.json

This PR reserves NMV 119 for Electron 28.

doc: reserve 119 for Electron 28

---

lib/internal/test_runner/runner.js
test/parallel/test-runner-filetest-location.js

This commit adds the previously missing test location for `FileTest` tests.
Fixes: https://github.com/nodejs/node/issues/49926
Fixes: https://github.com/nodejs/node/issues/49927

test_runner: add test location for FileTests

---

benchmark/fs/bench_fdatasyncSync.js
lib/fs.js
src/node_file.cc
typings/internalBinding/fs.d.ts

```
fs/bench_fdatasyncSync.js n=10000 type='existing'            ***      6.39 %       ±1.85% ±2.48%  ±3.25%
fs/bench_fdatasyncSync.js n=10000 type='non-existing'        ***    116.11 %       ±6.89% ±9.21% ±12.08%
In this case, there are 2 comparisons, you can thus expect the following amount of false-positive results:
```
Refs: https://github.com/nodejs/performance/issues/106

fs: improve error performance for `fdatasyncSync`

---

benchmark/perf_hooks/performance-observer.js
lib/internal/perf/observe.js

Continuing the work started on https://github.com/nodejs/performance/issues/109.
```
perf_hooks/performance-observer.js pending=1 n=100000         ***    147.63 %       ±3.89% ±5.23% ±6.89%
perf_hooks/performance-observer.js pending=10 n=100000        ***    104.54 %       ±5.69% ±7.60% ±9.92%
result increases. In this case, there are 2 comparisons, you can thus
```
cc @nodejs/performance

perf_hooks: reducing overhead of performance observer entry list

---

src/node_messaging.cc

Name a scoped lock to be consistent with all the others.

src: name scoped lock

---

lib/internal/streams/writable.js

Try to inline condition checks and try to avoid read state properties in hot paths.
```
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='no' n=100000            ***      8.14 %       ±4.15% ±5.56% ±7.29%
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='yes' n=100000           ***     11.35 %       ±2.60% ±3.46% ±4.50%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='no' n=100000             *      2.04 %       ±2.03% ±2.71% ±3.54%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='yes' n=100000          ***     17.89 %       ±2.05% ±2.73% ±3.56%
streams/writable-manywrites.js len=1024 callback='yes' writev='no' sync='no' n=100000           *** …
```

perf: optimize Writable

---

doc/api/fs.md
lib/fs.js
lib/internal/fs/promises.js
test/parallel/test-fs-write-file-flush.js

This commit adds a `'flush'` option to the `fs.writeFile` family of functions.
Refs: https://github.com/nodejs/node/issues/49886
Notable change summary: When writing to files, it is possible that data is not immediately flushed to permanent storage. This allows subsequent read operations to see stale data. This PR adds a `'flush'` option to the `fs.writeFile` family of functions which forces the data to be flushed at the end of a successful write operation.

fs: add flush option to writeFile() functions

---

lib/_tls_wrap.js
test/parallel/test-tls-socket-close.js

Ensure that the `'close'` event is emitted on a `TLSSocket` when it is
created from an existing raw `net.Socket` and the raw socket is not
closed cleanly (destroyed).
Refs: https://github.com/nodejs/node/commit/048e0bec5147
Refs: https://github.com/nodejs/node/issues/49902#issuecomment-1741203813
Fixes: https://github.com/nodejs/node/issues/49902

tls: handle cases where the raw socket is destroyed

---

src/crypto/crypto_tls.cc

Retrieve the TLSWrap from the SSL object, not SSL_CTX.
A SSL_CTX object is the parent of zero or more SSL objects. TLSWrap is a wrapper around SSL, SecureContext around SSL_CTX.
Node.js normally uses a SecureContext per TLSWrap but it is possible to use a SecureContext object more than once.
It was therefore possible for an ALPN callback to use the wrong (possibly already freed) TLSWrap object.
Having said that, while the bug is clear once you see it, I'm not able to trigger it (and hence no test, not for lack of trying.)
None of the bug reporters were able to reliably reproduce it either so the stars probably need to align just right in order to hit it.
Fixes: https://github.com/nodejs/node/issues/47207

src: fix TLSWrap lifetime bug in ALPN callback

---

benchmark/vm/compile-script-in-isolate-cache.js
lib/internal/modules/esm/utils.js
lib/vm.js
src/env_properties.h
src/node_contextify.cc
test/parallel/test-vm-no-dynamic-import-callback.js

This makes it possile to hit the in-isolate compilation cache when host-defined options are not necessary.
Local benchmark numbers: huge variance because when the cache is missed (in the main branch) it is just toooooo slow, I think we can keep n fairly small for now until we no longer need to compare the cache-miss cases, but the speed up is very visible if you just run the benchmark locally - with cache hit it finishes in a blink of an eye and without cache it gets stuck for a few seconds.
```
confidence improvement accuracy (*)     (**)    (***)
vm/compile-script-in-isolate-cache.js n=100 type='with-dynamic-import-callback'                   -0.33 %       ±0.81%   ±1.08%   ±1.41%
vm/compile-script-in-isolate-cache.js n=100 type='without-dynamic-import-callback'        ***   9132.25 % …
```

vm: use default host-defined options when importModuleDynamically is not set

---

lib/internal/perf/performance_entry.js
lib/internal/perf/usertiming.js

Continuing the work started on https://github.com/nodejs/performance/issues/109.
This PR should be landed after https://github.com/nodejs/node/pull/49837.
```
perf_hooks/usertiming.js observe='all' n=100000            ***    351.28 %       ±9.79% ±13.17% ±17.46%
perf_hooks/usertiming.js observe='measure' n=100000        ***    436.41 %       ±8.94% ±12.03% ±15.93%
result increases. In this case, there are 2 comparisons, you can thus
0.00 false positives, when …
```

perf_hooks: reduce overhead of new user timings

---

src/js_native_api.h
src/node_api.h

Hi, Node-API team @nodejs/node-api 
I'm wondering if [emnapi](https://github.com/toyobayashi/emnapi) could use [node-api-headers](https://github.com/nodejs/node-api-headers) package instead of maintaining [a modified version of headers](https://github.com/toyobayashi/emnapi/tree/be127f0cc5c6b8d4e186b20f4620ed00078cd57d/packages/emnapi/include).
Just a little modification:
- change `__wasm32__` to `__wasm__` for building `wasm64-unknown-emscripten`
- expand `NAPI_MODULE_EXPORT` to `__attribute__((used))` (`EMSCRIPTEN_KEEPALIVE`) to export `napi_register_wasm_v1` and `node_api_module_get_api_version_v1` if build with Emscripten
- ~~expand `NAPI_EXTERN` to `__attribute__((__import_module__("env")))` if build with Emscripten. Not sure if this should.~~ Currently [there is no way to specify a …

node-api: update headers for better wasm support

---

lib/internal/streams/writable.js

```
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='no' n=100000              *      7.48 %       ±6.60%  ±8.78% ±11.43%
streams/writable-manywrites.js len=1024 callback='no' writev='no' sync='yes' n=100000           ***      8.19 %       ±3.39%  ±4.51%  ±5.87%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='no' n=100000                   -1.00 %       ±3.29%  ±4.43%  ±5.86%
streams/writable-manywrites.js len=1024 callback='no' writev='yes' sync='yes' n=100000          ***     12.17 %       ±2.83%  ±3.76%  ±4.90%
streams/writable-manywrites.js len=1024 callback='yes' writev='no' sync='no' n=100000             *      3.61 %       ±3.15%  ±4.24%  ±5.60%
streams/writable-manywrites.js len=1024 callback='yes' writev='no' sync='yes' n=100000 …
```

stream: lazy allocate back pressure buffer

---

lib/internal/crypto/webidl.js

Xref https://github.com/electron/electron/pull/40070
It's possible for `SharedArrayBuffer`s to be disabled with `--no-harmony-sharedarraybuffer`. If they _are_ disabled and a user goes to use for example `webcrypto.subtle.importKey`, they will see the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')
at isSharedArrayBuffer (node:internal/crypto/webidl:187:57)
at Object.BufferSource (node:internal/crypto/webidl:208:9)
at SubtleCrypto.importKey (node:internal/crypto/webcrypto:585:36)
at worker.js:6:18
```
This handles that case similarly to how it's handled [elsewhere in the codebase](https://github.com/nodejs/node/blob/7df27582bbb896ebb72697da58209976a0b4daf6/lib/internal/worker.js#L103-L112).

crypto: account for disabled `SharedArrayBuffer`

---

lib/_tls_wrap.js
test/parallel/test-tls-client-mindhsize.js

If user sets invalid type for options.minDHSize in tls.connect(), it's not internal issue of Node.js. So validateNumber() is more proper than assert(). Plus, set min of validateNumber() as 1 to check minDHSize is positive.
Refs: https://github.com/nodejs/node/pull/49896
Before
```
node:internal/assert:14
throw new ERR_INTERNAL_ASSERTION(message);
^
Error [ERR_INTERNAL_ASSERTION]: options.minDHSize is not a number: undefined
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues
```
After
```
// case#1: undefined is used as minDHSize.
node:internal/validators:177
throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "options.minDHSize" …
```

tls: use `validateNumber` for `options.minDHSize`

---

doc/api/synopsis.md

I found the explanation for the example to be lacking a bit of clarity so cleared it up. Changed:
Save the file, go back to the terminal window, and enter the following command:
```
$ node hello-world.js
```
to:
Save the file and go back to the terminal. Entering the following commands run the file named `hello-world.js`:
```
$ node hello-world.js
```

docs: explained what node keyword does in terminal

---

test/parallel/test-assert.js

Changed for each loop to for of loop in test-assert.js

test: change forEach to for...of

---

test/parallel/test-net-perf_hooks.js

Removes the use of `forEach()` in `test-net-perf_hooks.js` by replacing it with `for ... of`
(Part of Open Source Day at GHC 2023)

test: replace forEach() in test-net-perf_hooks with for of

---

lib/internal/test_runner/runner.js
test/parallel/test-runner-run.mjs

is this a major change (on the surface it looks like it does)?
did this as I accidentally passed array of files as the run argument instead of inside the `files` option

test_runner: disallow array in `run` options

---

lib/internal/bootstrap/realm.js

Refs: https://github.com/nodejs/node/pull/50025#issuecomment-1746107751

lib: let deps require `node` prefixed modules

---

test/parallel/test-process-env-ignore-getter-setter.js

Replaced forEach with for..of in test-process-env-ignore-getter-setter.js

test: replace forEach with for..of in test-process-env-ignore

---

doc/api/test.md

We currently use `resolve` which is incorrect from a technical point of view in several places in the test runner docs.
Most of the docs contain correct terminology.
For anyone wondering "resolves" means the promise's fate is known by either settling (becoming fulfilled or rejected) or because it's assimilating the status of another promise (that may be unfulfilled).

doc: use precise terminology in test runner

---

doc/api/fs.md

See https://github.com/nodejs/node/pull/50028 for context - this also has the added benefit of reducing the amount of times we use resolving a promise vs resolving a path.
Note this document already used `fulfills` in many cases and I kept resolves (for promises) in some cases where it made sense to me from a technical point of view

doc: use precise promise terminology in fs

---

doc/api/errors.md
src/env_properties.h
src/node_errors.h
src/node_messaging.cc
test/parallel/test-whatwg-webstreams-transfer.js
test/parallel/test-worker-message-port-transfer-filehandle.js
test/parallel/test-worker-workerdata-messageport.js

Instead of TypeError, throwing DOMException in accordance to the HTML
structured serialize algorithms.
Fixes: https://github.com/nodejs/node/issues/40841

src: throw DOMException on cloning non-serializable objects
