nodejs/node

doc/contributing/primordials.md
lib/eslint.config_partial.mjs
lib/zlib.js

As a result of the primordials work done by @aduh95 and others, let's remove the prototypal primordials from `node:zlib`

zlib: remove prototype primordials usage

---

common.gypi
deps/v8/src/builtins/set-difference.tq
deps/v8/src/builtins/set-intersection.tq
deps/v8/src/builtins/set-is-disjoint-from.tq
deps/v8/src/builtins/set-is-subset-of.tq
deps/v8/src/builtins/set-is-superset-of.tq
deps/v8/test/mjsunit/harmony/set-difference.js
deps/v8/test/mjsunit/harmony/set-intersection.js
deps/v8/test/mjsunit/harmony/set-is-disjoint-from.js
deps/v8/test/mjsunit/harmony/set-is-subset-of.js
deps/v8/test/mjsunit/harmony/set-is-superset-of.js

Fixes a bug in set methods.
This commit is already on `main` with V8 12.8.
Thanks @ljharb for reporting on Slack.
[set-methods] Handle SetLike with infinite size
This CL adds a check for identifying SetLikes with infinite sizes in
methods dependent on the size of `other`s.
Bug: 351332634
Change-Id: I5c6d9c0cc7f3f5fae5cedc72a44bc21c917c84b8
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5684652
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Commit-Queue: Rezvan Mahdavi Hezaveh <rezvan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#94897}
Refs: https://github.com/v8/v8/commit/217457d0a560990b5ed41da9a5bfc0d224a0f060

[v22.x] deps: V8: cherry-pick 217457d0a560

---

lib/internal/main/worker_thread.js
test/parallel/test-worker-cli-options.js

Fixes: https://github.com/nodejs/node/issues/30682#issuecomment-2352453961

worker: handle `--input-type` more consistently

---

lib/internal/modules/cjs/loader.js
test/es-module/test-esm-detect-ambiguous.mjs
test/fixtures/es-modules/tla/unresolved.js

Fixes: https://github.com/nodejs/node/issues/54931

module: report unfinished TLA in ambiguous modules

---

lib/internal/modules/esm/translators.js
lib/internal/test_runner/mock/loader.js
lib/internal/test_runner/mock/mock.js
test/es-module/test-typescript.mjs
test/fixtures/typescript/ts/commonjs-logger.ts
test/fixtures/typescript/ts/module-logger.ts
test/fixtures/typescript/ts/test-mock-module.ts

Ugh I named the branch with ò character and GitHub complains :(
Fixes: https://github.com/nodejs/node/issues/54428

test_runner: support typescript module mocking

---

.github/workflows/label-flaky-test-issue.yml

Because this workflow checks `github.event.label`, the `opened` trigger will *always* be skipped, so this PR removes it entirely.

meta: remove never-used workflow trigger

---

CHANGELOG.md

IIUC, v21 reached EoL on April 1st, so shouldn't this document be updated to reflect that?

doc: mark v21 as End-of-Life

---

test/parallel/test-whatwg-webstreams-encoding.js

Use a `forEach` loop for `assert.throws` statements, improving code readability.

test: refactor `test-whatwg-webstreams-encoding` to be shorter

---

tools/js2c.cc

Refactors js2c.cc to use modern syntax.

tools: refactor js2c.cc to use c++20

---

deps/ngtcp2/nghttp3/lib/nghttp3_ringbuf.c
deps/ngtcp2/ngtcp2/lib/ngtcp2_ringbuf.c

Floats dependency patch from https://github.com/ngtcp2/nghttp3/pull/252 to enable updating VS to the latest version (17.11) in the CI.
Fixes: https://github.com/nodejs/node/issues/54898

build,win: float VS 17.11 compilation patch

---

BUILDING.md

Update the list of toolchains used to build the official Node.js binaries for Node.js 23 onwards.
Refs: https://github.com/nodejs/build/issues/3806
Refs: https://github.com/nodejs/node/pull/54081
Refs: https://github.com/nodejs/node/pull/53184#discussion_r1617496804

doc: reflect toolchains used for official binaries

---

test/sequential/sequential.status

There is no recent trace of failure for this test.
Fixes: https://github.com/nodejs/node/issues/47116

test: remove test-http-max-sockets flaky designation

---

test/parallel/test-http-max-sockets.js

test: move test-http-max-sockets to parallel

---

test/es-module/test-esm-extensionless-esm-and-wasm.mjs

The test setup is incorrect:
```js
it('should error on import', async () => {
try {
await import(fixtures.fileURL('es-modules/noext-wasm'));
mustNotCall();
} catch (err) {
ok(err instanceof SyntaxError);
}
});
```
In the correct setup, `mustNotCall()` should be invoked as `mustNotCall()();`. However, the test fails in this case, indicating that the import is actually successful. This PR fixes the invalid test.

test: fix invalid test

---

doc/api/cli.md
doc/api/globals.md

doc: add more details for localStorage and sessionStorage
Releated #53871

doc: add more details for localStorage and sessionStorage

---

doc/api/test.md
lib/internal/test_runner/runner.js
test/parallel/test-runner-run-coverage.mjs

Fixes: #53867
Refs: https://github.com/nodejs/node/issues/53924

test_runner: add coverage support to run function

---

test/parallel/test-runner-watch-mode.mjs

This PR extends the existing tests for the Node.js test runner's `--watch` mode by adding support for the `--experimental-test-isolation` option.
@cjihrig I was unable to find a test that covers this combination.  
I also noticed that the `should run new tests when a new file is created in the watched directory` test behaves differently depending on the isolation modes.  
What do you think?

test: add runner watch mode isolation tests

---

src/compile_cache.cc

Fixes https://github.com/nodejs/node/issues/54519

src: add unistd.h import if node posix credentials is defined

---

doc/api/errors.md
doc/api/tls.md
src/crypto/crypto_tls.cc
src/node_errors.h
test/parallel/test-tls-psk-errors.js

Refs: https://github.com/nodejs/node/pull/23188
Fixes: https://github.com/nodejs/node/issues/52448

tls: fix 'ERR_TLS_PSK_SET_IDENTIY_HINT_FAILED' typo

---

src/env-inl.h
src/env.cc
src/env.h

Environment handles are deterministic and can be cleaned up directly
without saving the references in a list and iterate the list.

src: cleanup per env handles directly without a list

---

Makefile

CC @jazelly 
Fixes https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1726321766408959

build: fix eslint makefile target

---

test/fixtures/test-runner/coverage/index.test.js

Can this be fast-tracked? it shouldn't cause any breakages.

test: fix `soucre` to `source`

---

src/compile_cache.cc
src/compile_cache.h
src/env.cc
src/inspector_profiler.cc
src/node_file.cc
src/node_modules.cc
src/node_report.cc
src/path.cc
src/path.h
src/permission/fs_permission.cc
src/permission/fs_permission.h
src/util.h

Reverts https://github.com/nodejs/node/pull/53063. There are still some `filesystem::path` references left, since they're added in multiple different PRs. Depending on whether we need them or not, we can remove them.
We're reverting because it fixes multiple different regressions due to Windows UTF-16 path requirements.
Fixes https://github.com/nodejs/node/issues/54991
Fixes https://github.com/nodejs/node/issues/54476

src: revert filesystem::path changes

---

doc/api/test.md
lib/internal/main/test_runner.js
lib/internal/test_runner/harness.js
lib/internal/test_runner/test.js
lib/internal/test_runner/tests_stream.js
lib/internal/test_runner/utils.js
test/parallel/test-runner-reporters.js

This commit adds a new 'test:summary' event to the test runner's reporting interface. This new event serves two purposes:
- In the future, the test runner internals will no longer need to change the process exit code. This may be important to run() users. Unfortunately, this is a breaking change, so it needs to be changed in a major version.
- The reporting interface now has a single event that can identify passing or failing test runs.
Refs: https://github.com/nodejs/node/issues/53867
Refs: https://github.com/nodejs/node/issues/54812
~~(Still need to add docs)~~

test_runner: add 'test:summary' event

---

test/parallel/test-tls-set-ciphers.js

The test failed as it was using AES128 which is not supported in OpenSSL32 due to default security level and because some error messages have changed.
Adjusted to use AES256 where it made sense and not run tests on OpenSSL32 where test was specific to AES128.
Adjust to use the expected error messages based on version.

test: adjust tls-set-ciphers for OpenSSL32

---

doc/api/test.md

As I discovered answering [this Stack Overflow question](https://stackoverflow.com/q/79004444/3001761), `node:test`'s [`mock.module`](https://nodejs.org/api/test.html#mockmodulespecifier-options) is currently hidden behind the `--experimental-test-module-mocks` flag. This was covered on the CLI page, but **not** the test runner page.

doc: cover --experimental-test-module-mocks flag

---

doc/api/globals.md

Refs: https://github.com/nodejs/node/pull/51575

doc: add missing EventSource docs to globals

---

doc/contributing/collaborator-guide.md

The *linux* label **does** exist, so this PR updates the docs accordingly. (+ add `etc` to the end of the lists).

meta: add `linux` to OS labels in collaborator guide

---

test/parallel/test-vm-context-dont-contextify.js

Because of the double encoding, the test would fail as soon as the path contains a space or any other char that's already encoded by `pathToFileURL`.

test: fix `test-vm-context-dont-contextify` when path contains a space

---

test/parallel/test-child-process-exec-abortcontroller-promisified.js
test/parallel/test-child-process-exec-maxbuf.js
test/parallel/test-child-process-promisified.js
test/parallel/test-child-process-spawn-shell.js
test/parallel/test-child-process-spawnsync-shell.js
test/parallel/test-cli-node-print-help.js
test/parallel/test-cli-syntax-eval.js
test/parallel/test-http-chunk-problem.js
test/parallel/test-npm-install.js
test/parallel/test-permission-allow-child-process-cli.js
test/parallel/test-permission-child-process-cli.js
test/parallel/test-pipe-head.js
test/parallel/test-stdin-from-file-spawn.js
test/sequential/test-child-process-execsync.js
test/sequential/test-cli-syntax-file-not-found.js
test/sequential/test-cli-syntax-good.js

We had a bunch of tests that would fail if run from an executable that contains any char that should be escaped when run from a shell.

test: do not assume `process.execPath` contains no spaces

---

test/parallel/test-tls-client-getephemeralkeyinfo.js

OpenSSL32 does not support AES128 and DH 1024 to
update test to use newer algorithms.

test: update tls test to support OpenSSL32

---

doc/api/repl.md

As of v15.0.0, this function no longer exists (see DEP0075)

doc: remove `parseREPLKeyword` from REPL documentation

---

test/parallel/test-runner-assert.js

Refs: https://github.com/nodejs/node/pull/54630#issuecomment-2358197506

test: make `test-runner-assert` more robust

---

doc/api/errors.md
lib/internal/errors.js
lib/internal/test_runner/coverage.js
test/fixtures/test-runner/source-map-missing-sources/index.js
test/fixtures/test-runner/source-map-missing-sources/index.js.map
test/parallel/test-runner-coverage.js

Fixes #54756
`ERR_SOURCE_MAP_MISSING_SOURCE` is now thrown when a sourcemap contains a reference to a non-existent file.
---
@jaydenseric provided the test fixture, and @cjihrig provided the initial patch.

test_runner: report error on missing sourcemap source

---

benchmark/webstorage/getItem.js
benchmark/webstorage/removeItem.js
benchmark/webstorage/setItem.js

This PR adds benchmarks to web storage feature.
There are 3 main categories covered by this PR:
| Storage Type | Method | Performance (n=100000) |
|--------------|--------|------------------------|
| localStorage | setItem | 32,226.011329779365 |
| localStorage | property setter | 31,983.078822509164 |
| sessionStorage | setItem | 99,525.92487767464 |
| sessionStorage | property setter | 96,256.61628876119 |
| Storage Type | Method | Performance (n=100000) |
|--------------|--------|------------------------|
| localStorage | getItem | 339,745.7512670393 |
| localStorage | property getter | 318,879.11897832097 |
| sessionStorage | getItem | 546,089.0025795224 |
| sessionStorage | property getter | 605,112.5963263614 |
| Storage Type | Method | Performance (n=100000) | …

benchmark: add webstorage benchmark

---

lib/internal/crypto/aes.js
lib/internal/crypto/cfrg.js
lib/internal/crypto/ec.js
lib/internal/crypto/mac.js
lib/internal/crypto/rsa.js
test/parallel/test-webcrypto-export-import-cfrg.js
test/parallel/test-webcrypto-export-import-ec.js
test/parallel/test-webcrypto-export-import-rsa.js

All invalid data during import is supposed to return `DataError` `DOMException`. See https://w3c.github.io/webcrypto/
The WPTs for this are coming in https://github.com/web-platform-tests/wpt/pull/48243 but I'm opening this separately to be able to backport this easily.

crypto: ensure invalid SubtleCrypto JWK data import results in DataError

---

lib/internal/idna.js
lib/url.js
test/parallel/test-bootstrap-modules.js

We don't need this extra file. Let's remove it.

lib: remove lib/internal/idna.js

---

lib/internal/README.md

This PR adds a note about `--expose-internals`, as the flag allows the `internal/` directory to be `require()`ed.

doc: add note about `--expose-internals`

---

tools/eslint-rules/no-duplicate-requires.js

**Review note**:
I'm not a fan of the `@author` syntax. I edited the file, so I added my entry, but I'd prefer to remove it entirely.

tools: remove redudant code from eslint require rule

---

lib/internal/util.js
lib/string_decoder.js

As far as I can tell, I couldn't find a valid reason to call normalizeEncoding and isEncoding for the same input. Normalize encoding function returns undefined if the encoding is not valid.
Benchmark ci: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1640/

string_decoder: refactor encoding validation

---

test/parallel/test-inspector-strip-types.js

Use the `NodeRuntime.waitingForDebugger` event.
Refs: https://github.com/nodejs/node/pull/51560

test: deflake test-inspector-strip-types

---

test/parallel/test-runner-watch-mode-complex.mjs

This PR should address #54807.
I'm leaving this in Draft while testing more extensively 🚀

test: remove interval and give more time to unsync

---

Makefile
tools/v8-json-to-junit.py

This PR updates `ruff` to 0.6.5, and adds two new makefile targets:
`lint-py-fix`
`lint-py-fix-unsafe`

build: update ruff and add `lint-py-fix`

---

lib/internal/perf/performance.js
test/parallel/test-performance-timeline.mjs

Fixes: https://github.com/nodejs/node/issues/54766
This change adds an optional `type` argument to `performance.getEntriesByName`, aligning with both the documented node.js method signature and the performance timing spec.

perf_hooks: add missing type argument to getEntriesByName

---

lib/internal/tty.js

This PR updates the links for TTY's terminal colors.
For **Terminator**, according to author of the original link (The bolded `Here` is the new link):
> For [Terminator](http://gnometerminator.blogspot.com/p/introduction.html) users, there is a branch for GTK+3 version, which supports true colors and much more, but it's not yet merged in the master and not yet released as well. **[Here](https://bugs.launchpad.net/terminator/+bug/1030562)** is the bug for pushing it upstream. So if you want to help this - you can test it more, write patches and ping developers. Looks like this one is almost ready, I see no big stoppers against merging this branch in the master and releasing a new version of Terminator.
For **rxvt-unicode-24bit**, the link was changed to that mentioned by …

tty: fix links for terminal colors

---

tools/eslint/package-lock.json
tools/eslint/package.json

This essentially reverts e0e0b1a70ebf2b7c6c384771e3f746e9236c4737.
We don't bundle ESLint anymore, so the change is no longer needed.

tools: unlock versions of irrelevant DB deps

---

lib/internal/webstreams/readablestream.js
lib/internal/webstreams/transformstream.js
lib/internal/webstreams/writablestream.js
test/parallel/test-structuredClone-global.js

The latest WPT test requires this behaviour. The `ReflectConstruct` way did this well, but there was [an attempt to reduce the `ReflectConstruct` overhead](https://github.com/nodejs/node/pull/50107) breaking this, since it introduced a "closer" superclass under `Readable` (or `Writable` etc.). 
Fixes: https://github.com/nodejs/node/issues/54603
Refs: https://github.com/nodejs/node/pull/50107

stream: set stream prototype to closest transferable superclass

---

src/path.cc

Fix a crash when running tests with the GN build of node:
```
../out/Debug/node test/parallel/test-cli-permission-multiple-allow.js
```
Crash trace:
```
$ lldb ../out/Debug/node
(lldb) target create "../out/Debug/node"
Current executable set to '/Users/zcbenz/codes/node_with_gn/out/Debug/node' (arm64).
(lldb) run --experimental-permission --allow-fs-write /Users/zcbenz/codes/node_with_gn/node/tmp --allow-fs-write /Users/zcbenz/codes/node_with_gn/node/other-path -e 'console.log(process.permission.has("fs.write"));'
Process 28010 launched: '/Users/zcbenz/codes/node_with_gn/out/Debug/node' (arm64)
../../third_party/gn/third_party/libc++/src/include/string:1364: assertion !empty() failed: string::back(): string is empty
Process 28010 stopped
* thread #1, queue = 'com.apple.main-thread', stop …
```

src: do not call path.back() when it is empty

---

lib/internal/repl/utils.js
test/parallel/test-repl-preview-newlines.js

Fixes #54504 
Uses `RegExpPrototypeExec` (with `\n`, `\r`, and `\v`) rather than `StringPrototypeIndexOf` with `\n`.

repl: catch `\v` and `\r` in new-line detection

---

test/pummel/pummel.status

This reverts commit 2a871df3dfb8ea663ef5e1f8f62701ec51384ecb.
It has been almost three years since the test was marked flaky. Remove the unstable designation to see if the problem persists on Windows.

Revert "test: mark test-fs-watch-non-recursive flaky on Windows"

---

benchmark/fixtures/strip-types-benchmark.js
benchmark/fixtures/strip-types-benchmark.ts
benchmark/fixtures/transform-types-benchmark.js
benchmark/fixtures/transform-types-benchmark.ts
benchmark/ts/strip-typescript.js
benchmark/ts/transform-typescript.js

Some benchmarks for `--experimental-strip-types` and `--experimental-transform-types`.
First time writing a benchmark so open to suggestions

benchmark: create benchmark for typescript

---

test/common/inspector-helper.js
test/es-module/test-esm-import-meta-resolve.mjs
test/es-module/test-esm-loader-hooks.mjs

We should escape URL-significant chars such as `%` so the test works even if the repo is cloned on a path that contains such char.

test: fix some tests when path contains `%`

---

lib/internal/test_runner/mock/loader.js
test/fixtures/module-mocking/don't-open.mjs
test/parallel/test-runner-module-mocking.js

test_runner: fix mocking modules with quote in their URL

---

README.md

The directory / file names contain more than just the date commit SHA. They also contain the version.
Additionally, this change gives examples of each value, and places them in the correct order.

meta: add more information about nightly releases

---

test/common/assertSnapshot.js

When the repo is cloned on a path that contains a `'`, the quote is escaped in the stack trace, which makes the assertSnapshot test fails.

test: fix `assertSnapshot` when path contains a quote

---

test/parallel/test-child-process-execfile.js
test/parallel/test-cli-node-options.js
test/parallel/test-startup-large-pages.js
test/pseudo-tty/test-repl-external-module.js

There were some more failures that were left out of https://github.com/nodejs/node/pull/55028.

test: fix more tests that fail when path contains a space

---

test/parallel/test-tls-junk-closes-server.js

Refs: https://github.com/nodejs/node/issues/52482
TLS spec seems to indicate there should should be a response sent when TLS handshake fails. See
https://datatracker.ietf.org/doc/html/rfc8446#page-85
When compiled with OpenSSL32 we see the
the following response '15 03 03 00 02 02 16' which decodes as a fatal (0x02) TLS error alert number 22 (0x16). which corresponds to TLS1_AD_RECORD_OVERFLOW which matches the error we see if NODE_DEBUG is turned on once you get through the define aliases.
If there is a response from the server the test used to hang because the end event will not be emitted until after the response is consumed. This PR fixes the test so it consumes the response.
Some earlier OpenSSL versions did not seem to send a …

test: fix test-tls-junk-closes-server

---

src/node_errors.h

The native error messages can sometimes contain e.g. path content that are typically passed in as chars with UTF8-encoded code points. The native error throwing code previously always decode the chars as Latin-1, which would be incorrect.

src: decode native error messages as UTF-8

---

doc/api/deprecations.md
lib/crypto.js

Let's runtime deprecate `crypto.fips` attribute.
cc @nodejs/crypto

crypto: runtime deprecate crypto.fips

---

test/parallel/test-http-remove-header-stays-removed.js

Instead of relying on a timer, verify that `socket.end()` is called when the `'finish'` event is emitted on the `ServerResponse` object.

test: deflake test-http-remove-header-stays-removed

---

lib/internal/blob.js
test/parallel/test-blob.js

- Extracts Blob.prototype.arrayBuffer so it cannot be overridden in .text(), etc.
- Make .bytes() enumerable. I guess the WPT runner is not running the idlharness tests?
- Make .text() return a Promise, rather than being explicitly async. This is a non-documented part of the webidl spec. Refs: #49936

buffer: extract Blob's .arrayBuffer() & webidl changes

---

doc/api/buffer.md
lib/internal/blob.js
lib/internal/file.js
test/parallel/test-file.js
test/wpt/status/html/webappapis/structured-clone.json

Fixes: https://github.com/nodejs/node/issues/47612

buffer: make File cloneable

---

doc/api/test.md

I was looking over the documentation while working on adding `run()` coverage to https://github.com/nodejs/nodejs.org/pull/7006, and I noticed that there is a missing `:`, so this quick PR fixes that.
Fast-tracking, as this change is a one character change to the documentation, and shouldn't have any negative side effects.

doc: add missing `:` to `run()`'s `globPatterns`

---

doc/README.md

This pull request brings the style guide up to date with the latest information (and formatting).
Over the past two years since the guide was updated, significant changes have occurred in the documentation process. For instance, additional languages have been incorporated into Node.js's remark extension, and line lengths have been extended from 80 to 120 characters.
In addition to updating the content, this pull request reorganizes the guide into sections for better readability, replacing the previous list format.

doc: update style guide

---

test/pummel/test-timers.js

This PR fixes: https://github.com/nodejs/node/issues/55092
Timers are not guaranteed to fire exactly when specified, the flakiness of the test comes from the assumption that the timer will always fire **_at_** or **_after_** the `timeout`, however this is not always the case. For instance, a 1000ms `timeout` could be fired at anytime roughly between `98x ~ 100x` due to the CPU load, platform etc.
This could be easily verified by:
```js
let currentTime = Date.now();
setInterval(() => {
const timeElapsed = Date.now();
console.log(timeElapsed - currentTime);
currentTime = Date.now();
}, 1000);
```
on my macOS nightly build here is the result:
```
1003
983
1000
1001
999
1001
1001
1000
1001
997
1000
1000
```
Here is a more precise timing mechanism by using `process.hrtime` version:
```js
let …
```

test: deflake test/pummel/test-timers.js

---

benchmark/fs/bench-glob.js
lib/fs.js
typings/primordials.d.ts

The following applies to this PR:
- Replaced the `for await...of` loop with `ArrayFromAsync()`.
- Removed the need for manual array pushing using `ArrayPrototypePush`.
- Added `ArrayFromAsync` type to `primordials.d.ts` file
- Simplified the overall structure of the async function.
`Array.fromAsync` was defined relatively recently, but I used it because I knew it was officially adopted in Node.js v22. ([MDN Document](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fromAsync))

fs: refactoring declaratively with the Array.fromAsync function

---

lib/internal/modules/cjs/loader.js
test/es-module/test-typescript-eval.mjs
test/es-module/test-typescript.mjs

Some unit tests had duplicate names. Please review these small changes.
Thanks
Christos

Fix duplicated test descriptions

---

lib/internal/modules/esm/resolve.js
src/node_file.cc
test/es-module/test-cjs-legacyMainResolve.js

As documented, its value is a path.
https://github.com/nodejs/node/blob/c42d8461b061136da2b3c04bd976d2e15b81969d/doc/api/packages.md#L1210-L1211

esm: do not interpret `"main"` as a URL

---

lib/internal/webstreams/util.js
test/wpt/status/streams.json

According to the spec, getIterator should normalize incoming method to
undefined if it is either undefined or null. This PR enforces that spec
compliance with passed WPT.

stream: treat null asyncIterator as undefined

---

doc/api/modules.md

Before the fix, the pseudocode means an infinite loop.

doc: fix the require resolve algorithm in modules.md

---

.github/workflows/notify-on-review-wanted.yml

I have noticed we don't have a usual workflow for
review-wanted PRs. So, in other words the label
is not useful as it should be. This commit notify
via Slack (#node-core) whenever this label is placed either on an issue or in a PR.

build: notify via slack when review-wanted

---

doc/api/cli.md

doc: put --env-file-if-exists=config right under --env-file=config

---

doc/api/cli.md
doc/api/permissions.md
doc/contributing/adding-v8-fast-api.md
lib/fs.js
lib/internal/fs/promises.js
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/resolve.js
src/histogram.cc
src/histogram.h
src/node_external_reference.h
src/node_file.cc
src/node_process.h
src/node_wasi.cc
src/node_wasi.h
src/timers.cc
src/timers.h
test/parallel/test-permission-fs-internal-module-stat.js
typings/internalBinding/fs.d.ts

When creating an fast api the callback might use the receiver. In that case if the internal binding is destructured the method won't have access to the reciver and it will throw. Passing the receiver as second argument ensures the receiver is available.

src: add receiver to fast api callback methods

---

doc/api/process.md

They don't seem to have any meaning (the sections it separates are not more different than any other pair of two sections) and I don't think we use those anywhere else in our docs, I suspect they were added by mistake.

doc: remove random horizontal separators in `process.md`

---

tools/msvs/install_tools/install_tools.bat

This PR improves the readability of the chocolatey install script by splitting the long command into multiple lines.

tools: make choco install script readable

---

lib/internal/console/constructor.js
test/parallel/test-repl.js
test/pseudo-tty/test-tty-color-support-warning-2.out
test/pseudo-tty/test-tty-color-support-warning.out
test/pseudo-tty/test-tty-color-support.out

Fixes #53661
This PR reverts #51629.
**Why was this change made?**
IMO The original PR introduces more issues than it resolves, negatively impacting the intended use of standard streams in several ways, such as:
**Misuse of Standard Streams:** The primary purpose of `stdout` is to handle program output, whereas `stderr` is designated for diagnostics, status updates, and runtime user messages. Showing this output red may confuse users, as this content isn't always an error. (For example, run `ncu-ci` with no args...)
**Inconsistency in Color Handling:** If the input passed to `console.error` or `console.warn` already includes color formatting, the additional internal coloring introduced by the original PR can result in a clash of styles.
---
CC @MrJithil

Revert "console: colorize console error and warn"

---

src/node_file.cc
test/parallel/test-fs-cp.mjs

Fixes: https://github.com/nodejs/node/issues/54285

fs: check subdir correctly in cpSync

---

doc/api/net.md

moved YAML changes element regarding to `onread` option from `socket.connect(options[, connectListener])`
to `new net.Socket([options])`
Fixes: https://github.com/nodejs/node/pull/54194#issuecomment-2372583454
Refs: https://github.com/nodejs/node/pull/25436

doc: move the YAML changes element regarding to https://github.com/nodejs/node/pull/54194

---

lib/internal/test_runner/test.js
lib/internal/test_runner/utils.js
test/parallel/test-runner-force-exit-flush.js

This commit updates the test runner to explicitly close and flush all destination file streams when the `--test-force-exit` flag is used.
Fixes: https://github.com/nodejs/node/issues/54327

test_runner: close and flush destinations on forced exit

---

doc/api/module.md

Refs: https://github.com/nodejs/node/pull/53822
Fixes: https://github.com/nodejs/node/issues/55091

doc: remove outdated https import reference

---

doc/api/net.md

This PR adds the `ESM` counterparts of the `CJS` examples for [the Net documentation](https://nodejs.org/api/net.html).
I've also updated the `port` used in the [`net.createConnection(options[, connectListener])`](https://nodejs.org/api/net.html#netcreateconnectionoptions-connectlistener) (`onread` section) so it's the same port across examples, that way new users can follow the documentation to _create_ a server and then _connect_ to it using the provided examples.
Best regards!

doc: add esm examples to `node:net`

---

deps/ncrypto/ncrypto.cc
deps/ncrypto/ncrypto.h
src/crypto/crypto_keys.cc

More incremental moving of evp key handlnig to ncrypto

src: move more key handling to ncrypto

---

lib/internal/blob.js
lib/internal/file.js
test/parallel/test-structuredClone-global.js

Followup #47613 
Reference #55067
---
The prototype of the transferred File / Blob should be equal to it's closest transferable superclass. This PR applies the same change as #55067 did to Streams to Files and Blobs.

buffer: correctly apply prototype to cloned `File` / `Blob`

---

doc/api/test.md
lib/internal/test_runner/utils.js
test/fixtures/test-runner/matching-patterns/typescript-test.cts
test/fixtures/test-runner/matching-patterns/typescript-test.mts
test/fixtures/test-runner/matching-patterns/typescript-test.ts
test/parallel/test-runner-cli.js

~~This is a draft. I haven't added tests for this change yet.~~
Ready for review
Fixes #55078
Fixes https://github.com/nodejs/help/issues/3902

test_runner: support typescript files in default glob

---

lib/internal/blob.js
test/parallel/test-blob.js

Fixes: https://github.com/nodejs/node/issues/55139

buffer: coerce extrema to int in `blob.slice`

---

test/sequential/test-watch-mode.mjs

No need to await for the function `writeFileSync`.

test: remove unnecessary `await` in test-watch-mode

---

lib/internal/test_runner/runner.js
lib/internal/test_runner/test.js

test_runner: avoid spread operator on arrays

---

.configurations/configuration.dsc.yaml
.configurations/configuration.vsEnterprise.dsc.yaml
.configurations/configuration.vsProfessional.dsc.yaml
.gitignore

This PR contains 3 configuration files for each version of Visual Studio.
These configuration files can be used to set up the Node.js development environment for developers via Dev Home. 
The user can choose the configuration file from Dev Home and easily install the tools required to build Node.js. In addition, this configuration file can be run directly via `winget configure <configuration file>` command.

build,win: add winget config to set up env

---

lib/internal/webstreams/encoding.js
test/wpt/status/encoding.json

Align TextDecoderStream behavior with WPT requirements by treating undefined chunks as errors. This change ensures that TextDecoderStream properly handles unexpected chunk types and throws an error when receiving undefined input.
This update addresses the failing WPT for decode stream error handling.

stream: handle undefined chunks correctly in decode stream

---

.nycrc

Fixes https://github.com/nodejs/node/actions/runs/11107498508/job/30858220494 and on current main
```
Unexpected token ']', ..."ps/**",
],
"repo"... is not valid JSON
```
Refs: https://github.com/nodejs/node/pull/53256#discussion_r1781121119

build: fix not valid json in coverage

---

doc/api/cli.md

doc: mention addons to experimental permission

---

test/es-module/test-typescript.mjs
test/fixtures/typescript/ts/test-parameter-properties.ts
test/fixtures/typescript/ts/test-union-types.ts

In this MR I'm adding more tests created in this [PR](https://github.com/nodejs/node/pull/53725/files), testing generics and Utility Types.
This PR makes part of typescript iniciative on Node.
cc: @RedYetiDev @marco-ippolito @ErickWendel

test: adding more tests for strip-types

---

doc/api/errors.md

doc: fix unordered error anchors

---

doc/api/modules.md

doc: update `require(ESM)` history and stability status

---

typings/internalBinding/modules.d.ts

Adding a type def for the util from https://github.com/nodejs/node/pull/54971

module: add internal type def for `flushCompileCache`

---

lib/internal/worker/io.js
test/wpt/status/webmessaging/broadcastchannel.json

Align BroadcastChannel behavior with spec by throwing an InvalidStateError when postMessage is called after the channel is closed. This ensures that the BroadcastChannel properly handles closed states and throws the appropriate error for postMessage attempts.
This update addresses expected failures for invalid postMessage after close in WPT.

worker: handle invalid BroadcastChannel postMessage after close

---

doc/api/fs.md
test/parallel/test-fs-read-stream-file-handle.js

`filehandle.createReadStream({ signal })` is supported but it was not documented nor tested.

fs: acknowledge `signal` option in `filehandle.createReadStream()`

---

doc/api/test.md

This PR updates test runner `test context.assert` documentation.

test_runner: update test context.assert

---

onboarding.md

Add some additional guidance based on something we missed in a recent onboarding step.

doc: tweak onboarding instructions

---

common.gypi
deps/v8/src/flags/flag-definitions.h
deps/v8/src/init/bootstrapper.cc
deps/v8/test/mjsunit/harmony/promise-withresolvers.js
deps/v8/test/test262/testcfg.py

Remove `--js-promise-withresolvers` runtime flag
Co-authored-by: Antoine du Hamel <duhamelantoine1995@gmail.com>
Bug: 42204122
Change-Id: I017a0d1ae0f8225513206ffb7806a4250be75d4c
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5843972
Reviewed-by: Igor Sheludko <ishell@chromium.org>
Commit-Queue: Erik Corry <erikcorry@chromium.org>
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Cr-Commit-Position: refs/heads/main@{#96215}
Refs: https://github.com/v8/v8/commit/0d5d6e71bbb0d2b0a12567fffa7e3375c427bc92

deps: V8: backport 0d5d6e71bbb0

---

doc/api/worker_threads.md
lib/internal/worker/io.js
lib/worker_threads.js
test/parallel/test-worker-message-mark-as-uncloneable.js

External modules need a way to decorate their objects so that node can
recognize it as a host object for serialization process. Exposing a way
for turning off instead of turning on is much safer.
Refs: https://github.com/nodejs/node/pull/55178

worker: add `markAsUncloneable` api

---

lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/load.js
lib/internal/modules/helpers.js
lib/internal/util.js

This is faster and more consistent with other places using the regular expression to detect node_modules.

module: use kNodeModulesRE to detect node_modules

---

doc/api/net.md

Specify the initial default value of `autoSelectFamily` in description of [net.setDefaultAutoSelectFamily()](https://github.com/nodejs/node/blob/main/doc/api/net.md#netsetdefaultautoselectfamilyvalue) as specified in description of [net.getDefaultAutoSelectFamily()](https://github.com/nodejs/node/blob/main/doc/api/net.md#netgetdefaultautoselectfamily).

doc: fix initial default value of autoSelectFamily

---

doc/api/process.md
lib/internal/bootstrap/node.js
test/es-module/test-typescript.mjs
test/parallel/test-process-features.js

process: add `process.features.typescript`

---

doc/api/errors.md

It was added in https://github.com/nodejs/node/pull/17887/files#diff-2057dbe503dbb37a65a74cf86e056d50c27ba828070577e0f7f07e734365c9bcR3782 and removed in https://github.com/nodejs/node/pull/32997/files#diff-2057dbe503dbb37a65a74cf86e056d50c27ba828070577e0f7f07e734365c9bcL355, but the removal was never reflected in docs.
Refs: https://github.com/nodejs/node/pull/17887
Refs: https://github.com/nodejs/node/pull/32997

doc: move `ERR_NAPI_TSFN_START/STOP_IDLE_LOOP` to legacy errors

---

doc/api/sqlite.md
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-database-sync.js

For historical reasons and to maintain compatibility with legacy database schemas, [SQLite does not enable foreign key constraints by default.](https://www.sqlite.org/quirks.html#foreign_key_enforcement_is_off_by_default) For new applications, however, this behavior is undesirable. Currently, any application that wishes to use foreign keys must use
```sql
PRAGMA foreign_keys = ON;
```
to explicitly enable enforcement of such constraints.
This commit changes the behavior of the SQLite API built into Node.js to enable foreign key constraints by default. This behavior can be overridden by users to maintain compatibility with legacy database schemas.
I decided against using the compile-time option to set the default behavior to avoid limiting compatibility with third-party code that links …

sqlite: enable foreign key constraints by default

---

doc/api/sqlite.md
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-statement-sync.js

Change `sourceSQL` and `expandedSQL` from being methods to being string-valued properties. These fields
- are conceptually properties (and not actions),
- are derived deterministically from the current state of the object,
- require no parameters, and
- are inexpensive to compute.
Also, following the naming conventions of ECMAScript for new features, most function names should usually contain a verb, whereas names of (dynamically computed) properties generally should not, so the current names also seem more appropriate for properties than for functions.

sqlite: make sourceSQL and expandedSQL string-valued properties

---

doc/api/crypto.md
lib/internal/crypto/aes.js
lib/internal/crypto/cfrg.js
lib/internal/crypto/ec.js
lib/internal/crypto/keys.js
lib/internal/crypto/mac.js
lib/internal/crypto/rsa.js
lib/internal/crypto/webcrypto.js
test/parallel/test-crypto-key-objects-to-crypto-key.js
test/parallel/test-webcrypto-export-import.js

For universal libraries executed in Node.js it would be useful to have an efficient way of accepting a `KeyObject` instance and transforming it to `CryptoKey` so that the actual crypto implementation doesn't have to depend on importing `node:crypto` but instead just use global SubtleCrypto.
To that end the application can check for key's Symbol.toStringTag being `KeyObject` and then having it wrapped around with a CryptoKey structure.
```ts
let publicKey!: crypto.KeyObject
let privateKey!: crypto.KeyObject
publicKey.toCryptoKey('Ed25519', true, ['verify']) // CryptoKey
privateKey.toCryptoKey('Ed25519', true, ['sign']) // CryptoKey
```
This PR adds the prototype methods and then utilizes the WebCryptoAPI implementation internals to run all the same routines as if SubtleCrypto.importKey was …

crypto: add KeyObject.prototype.toCryptoKey

---

lib/internal/test_runner/test.js
test/parallel/test-runner-coverage.js
test/parallel/test-runner-enable-source-maps-issue.js

test_runner: fix TypeError exception when --enable-source-maps is passed

---

doc/api/errors.md
lib/internal/errors.js
lib/internal/test_runner/coverage.js
test/fixtures/test-runner/source-maps/invalid-json/index.js
test/fixtures/test-runner/source-maps/invalid-json/index.js.map
test/fixtures/test-runner/source-maps/missing-map.js
test/parallel/test-runner-coverage-source-map.js

This PR changes the code coverage test runner to throw `ERR_SOURCE_MAP_CORRUPT` when a sourcemap is not a valid JSON file, or does not exist.

test_runner: throw on invalid source map

---

lib/v8.js
test/parallel/test-v8-deserialize-buffer.js

Fixes: https://github.com/nodejs/node/issues/54573

v8: out of bounds copy

---

doc/api/modules.md
doc/api/process.md
lib/internal/bootstrap/node.js
test/es-module/test-require-module-feature-detect.js
test/parallel/test-process-features.js

For detecting whether `require(esm)` is supported without triggering the experimental warning.

process: add process.features.require_module

---

lib/buffer.js
lib/internal/util.js
src/node_util.cc
test/fixtures/warning_node_modules/new-buffer-cjs.js
test/fixtures/warning_node_modules/new-buffer-esm.mjs
test/fixtures/warning_node_modules/node_modules/new-buffer-cjs/index.js
test/fixtures/warning_node_modules/node_modules/new-buffer-cjs/package.json
test/fixtures/warning_node_modules/node_modules/new-buffer-esm/index.js
test/fixtures/warning_node_modules/node_modules/new-buffer-esm/package.json
test/parallel/test-buffer-constructor-node-modules.js

This previously compiles a script and run it in a new context to avoid global pollution, which is more complex than necessary and can be too slow for it to be reused in other cases. The new implementation just checks the frames in C++ which is safe from global pollution, faster and simpler.
The previous implementation also had a bug when the call site is in a ESM, because ESM have URLs as their script names, which don't start with '/' or '\\' and will be skipped. The new implementation removes the skipping to fix it for ESM.

src: implement IsInsideNodeModules() in C++

---

common.gypi
deps/v8/src/flags/flag-definitions.h
deps/v8/src/init/bootstrapper.cc
deps/v8/test/mjsunit/harmony/promise-withresolvers.js
deps/v8/test/test262/testcfg.py

Backport of https://github.com/nodejs/node/pull/55115.

[v22.x backport] deps: V8: backport 0d5d6e71bbb0

---

doc/api/modules.md

Backport of https://github.com/nodejs/node/pull/55199

[v22.x backport] doc: update `require(ESM)` history and stability status

---

test/es-module/test-loaders-workers-spawned.mjs

I've seen it fail on CI (e.g. https://github.com/nodejs/node/actions/runs/11084447570/job/30799766200), cannot reproduce locally. Calling `console.log` from both a worker and the main thread is always going to result in uncertain output, IMO it makes sense to considered the test passed as long as we got all of them, regardless of the order.

test: make `test-loaders-workers-spawned` less flaky

---

doc/contributing/advocacy-ambasador-program.md

Actually I noticed there is not @nodejs/ambassadors team, so I'll create one and give access only to the the nodejs/ambassadors repo (which is private). This way will be easier to offboard

doc: add onboarding details for ambassador program

---

lib/internal/util/debuglog.js
test/parallel/test-module-print-timing.mjs

Currently, we generate invalid JSON if the specifier contains `"`, this can be addressed by escaping all double quotes like this PR is doing.

lib: fix module print timing when specifier includes `"`

---

lib/internal/test_runner/coverage.js
test/parallel/test-runner-coverage-source-map.js

test_runner: fix coverage report when --enable-source-maps is provided

---

lib/internal/modules/cjs/loader.js
test/es-module/test-disable-require-module-with-detection.js
test/fixtures/es-modules/loose.js

Previously we assumed if `--experimental-detect-module` is true, then `--experimental-require-module` is true, which isn't the case, as the two can be enabled/disabled separately. This patch fixes the checks so `--no-experimental-require-module` is still effective when `--experimental-detect-module` is enabled.
Drive-by: make the assertion messages more informative and remove obsolete TODO about allowing TLA in entrypoints handled by require(esm).

module: check --experimental-require-module separately from detection

---

doc/api/sqlite.md
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-database-sync.js

Double-quoted string (DQS) literals are not allowed by the SQL standard, which defines that text enclosed in double quotes is to be interpreted as an identifier only and never as a string literal. Nevertheless, for historical reasons, SQLite allows double-quoted string literals in some cases, which leads to inconsistent behavior and subtle bugs.
This commit changes the behavior of the built-in Node.js API for SQLite such that the DQS misfeature is disabled by default. This is recommended by the developers of SQLite. Users can explicitly enable DQS for compatibility with legacy database schemas if necessary.

sqlite: disable DQS misfeature by default

---

doc/api/events.md

Upon trying out [the example listed in the docs](https://nodejs.org/api/events.html#eventsonceemitter-name-options) on how to use `once()` with an `AbortSignal`, I noticed that it does not work the way the example demonstrates.
When running the example below, calling `ac.abort()` prints `Waiting for the event was canceled!`, while the next line (`ee.emit('foo')`) seems to do nothing.
```
import { EventEmitter, once } from 'node:events';
const ee = new EventEmitter();
const ac = new AbortController();
async function foo(emitter, event, signal) {
try {
await once(emitter, event, { signal });
console.log('event emitted!');
} catch (error) {
if (error.name === 'AbortError') {
console.error('Waiting for the event was canceled!');
} else {
console.error('There was an error', error.message);
}
} …
```

doc: fix `events.once()` example with `AbortSignal`

---

benchmark/esm/detect-esm-syntax.js

Syntax detection has been unflagged so it's no longer meaningful to toggle the detection based on CLI flags. It was also previously benchmarking cached module imports which isn't very meaningful for subsequent loads. This patch updates the benchmark to toggle the detection based on the presence of type field in the package.json, and generates fixtures to benchmark fresh module loads.
Note: in local testing, loading a ESM graph with detection is about 45% slower than loading it without detection (by adding a type field to the pacakge.json)
```
$ out/Release/node benchmark/esm/detect-esm-syntax.js
esm/detect-esm-syntax.js n=10000 type="with-package-json": 9,132.158577994036
esm/detect-esm-syntax.js n=10000 type="without-package-json": 5,065.756862407826
```

benchmark: rewrite detect-esm-syntax benchmark

---

doc/api/errors.md
lib/internal/errors.js
lib/internal/modules/helpers.js
test/es-module/test-typescript-eval.mjs

This PR wraps swc errors in a Node error to provide a more consistent error handling.
Before this PR
```bash
marcoippolito@marcos-MacBook-Pro node % node --experimental-strip-types -p "enum Foo{}"
node:internal/deps/amaro/dist/index:226
throw takeObject(r1);
^
x TypeScript enum is not supported in strip-only mode
,----
1 | enum Foo{}
: ^^^^^^^^^^
`----
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Node.js v22.8.0
```
After this PR
```bash
marcoippolito@marcos-MacBook-Pro node % ./node --experimental-strip-types -p "enum Foo{}"                      
node:internal/modules/helpers:390
throw new ERR_INVALID_TYPESCRIPT_SYNTAX(error);
^
SyntaxError [ERR_INVALID_TYPESCRIPT_SYNTAX]:   x TypeScript enum is not supported in strip-only mode
,----
1 | enum Foo{}
: …
```

module: wrap swc error in ERR_INVALID_TYPESCRIPT_SYNTAX

---

doc/api/errors.md

The error was added in https://github.com/nodejs/node/pull/14680/files#diff-670bf55805b781d9a3579f8bca9104c04d94af87cc33220149fd7d37b095ca1cR237, and removed in https://github.com/nodejs/node/pull/39297/files#diff-670bf55805b781d9a3579f8bca9104c04d94af87cc33220149fd7d37b095ca1cL1269-L1270, but it was still documented as a valid error code.
Refs: https://github.com/nodejs/node/pull/14680
Refs: https://github.com/nodejs/node/pull/39297

doc: move `ERR_INVALID_PERFORMANCE_MARK` to legacy errors

---

lib/fs.js
lib/internal/fs/promises.js
lib/internal/fs/streams.js
lib/internal/fs/utils.js
test/sequential/test-fs-path-dir.js

This PR fixes the inconsistency across platforms by throwing the same exception on Windows as on Linux.
I've taken the logic and the code in the referenced PR and modified it slightly to allow it to run with the current implementation of Node. Thanks @lundibundi.
Fixes: https://github.com/nodejs/node/issues/17801
Refs: https://github.com/nodejs/node/pull/33831

fs,win: fix bug in paths with trailing slashes

---

README.md

Refs: https://github.com/nodejs/Release/issues/999

doc: add release key for aduh95

---

doc/api/buffer.md
doc/api/diagnostics_channel.md
doc/api/test.md

A few lint errors have slipped through on the staging branch, it seems easier to push an additional commit than to try to force push a fix.

[v22.x] Fix doc linter

---

test/parallel/test-runner-cli.js

The `1 is not equal to 0` errors give very little info on what's actually going wrong when the test fails. Checking stdout and stderr first almost always gives more informative errors.

test: use more informative errors in `test-runner-cli`

---

doc/api/errors.md
tools/eslint-rules/documented-errors.js

It seems to be the right time to do so, just when 20.x is about to reach maintenance, so it's unlikely to cause backporting nightmares.

tools: enforce ordering of error codes in `errors.md`

---

lib/internal/fs/utils.js
test/sequential/test-fs-path-dir.js

Linter is failing on `main`, it seems https://github.com/nodejs/node/pull/54160 landed with an outdated CI.

fs: fix linter issue

---

test/es-module/test-esm-loader-entry-url.mjs
test/parallel/test-runner-cli.js

Fix two tests that fail when `node` is configured `--without-amaro`.

test: fix tests when Amaro is unavailable

---

node.gypi
tools/gyp/pylib/gyp/generator/msvs.py
tools/v8_gypfiles/v8.gyp

This change improves ClangCL compilation time drastically by enabling PCH to be used.
Fixes: https://github.com/nodejs/node/issues/55208
P.S. Since one of the changes is in the `gyp-next` I'll open a PR for it there as well.

build,win: enable pch for clang-cl

---

lib/internal/bootstrap/node.js
test/es-module/test-typescript.mjs
test/fixtures/typescript/echo-process-features-typescript.cjs

Fixes: https://github.com/nodejs/node/pull/55320#issuecomment-2400184367

process: fix `process.features.typescript` when Amaro is unavailable

---

lib/internal/test_runner/coverage.js
test/parallel/test-runner-coverage-source-map.js

Reverts nodejs/node#55228
This reverts a PR that was intended to fix #54753, however, the tests that it added where not accurate, and it actually does not pass the tests that it should pass. 
Once this lands, I'll open a follow up with tests for this behavior so that this doesn't happen again.

Revert "test_runner: ignore unmapped lines for coverage"

---

doc/api/http.md

The actual implementation returns `outgoingMessage` itself, but not
exactly `http.ServerResponse`.
Refs: https://github.com/nodejs/node/blob/20d8b85d3493bec944de541a896e0165dd356345/lib/_http_outgoing.js#L712-L751

doc: fix the return type of outgoingMessage.setHeaders()

---

onboarding.md

As pointed out in https://github.com/nodejs/node/pull/55331#discussion_r1793473803, adding a mailmap entry is not always necessary, we might as well put instructions regarding how to check whether adding such entry is necessary or not.

doc: edit onboarding guide to clarify when mailmap addition is needed

---

benchmark/assert/deepequal-object.js

This should make it easier to read on benchmark/compare and when generating graphs

benchmark: adjust config for deepEqual object

---

doc/api/esm.md
lib/internal/modules/esm/translators.js
test/es-module/test-esm-json.mjs

The two proposals reached stage 4 yesterday, at the October 2024 meeting. The Node.js implementation already matches exactly the semantics required by the proposals. This PR can/should be backported to 22 and 20 (and 18?).

esm: mark import attributes and JSON module as stable

---

lib/internal/util/comparisons.js
lib/internal/util/inspect.js
test/parallel/test-assert-deep.js

Fixes: https://github.com/nodejs/node/issues/50836

assert: fix deepEqual always return true on URL

---

lib/internal/bootstrap/web/exposed-window-or-worker.js
lib/internal/perf/usertiming.js
lib/internal/webidl.js
lib/internal/webstreams/readablestream.js
lib/internal/worker/js_transferable.js
src/node_messaging.cc
test/parallel/test-structuredClone-global.js

This PR utilizes the webidl sequence converter to convert `transfer` in JS layer. Although this is kind of like undoing some efforts [made to move the entire `strucutredClone` to C++](https://github.com/nodejs/node/pull/50330), it fixes the inconsistency of `structuredClone` with other runtimes with webidl compliance.
Additionally, this reduces the C++ to JS overhead, as the iterator function is no longer invoked at C++ layer, when `transfer` is an iterator object.
Fixes: https://github.com/nodejs/node/issues/55280
Refs: https://github.com/nodejs/node/pull/50330

lib: convert transfer sequence to array in js

---

doc/api/buffer.md

Small PR to fix the missing `Returns: <Buffer>` annotations on some methods.

doc: add missing return values in buffer docs

---

Makefile

fix make errors that occur in coverage-clean case and coverage-test case in Makefile 
AS-IS
To-BE

build: fix make errors that occur in Makefile

---

test/cctest/test_util.cc

- src/util-inl.h
- T* ListHead<T, M>::PopFront()

test: update test_util.cc for coverage

---

benchmark/events/eventtarget-add-remove-abort.js
lib/internal/event_target.js

```
events/eventtarget-add-remove-abort.js nListener=1 n=100000         ***    223.45 %      ±12.03% ±16.12% ±21.21%
events/eventtarget-add-remove-abort.js nListener=10 n=100000        ***    199.33 %       ±9.42% ±12.63% ±16.65%
events/eventtarget-add-remove-abort.js nListener=5 n=100000         ***    221.94 %       ±8.80% ±11.78% ±15.47%
```
Fixes: https://github.com/nodejs/node/issues/55311

events: optimize EventTarget.addEventListener

---

lib/diagnostics_channel.js
test/parallel/test-diagnostics-channel-sync-unsubscribe.js

When unsubscribing a publisher that has already been published to, while inside a subscriber, the next subscriber will not be called. Example:
```javascript
const dc = require('diagnostics_channel')
const testChannel = dc.channel('test')
function subscriberA () {
console.log('A called')
testChannel.unsubscribe(subscriberA)
}
function subscriberB () {
console.log('B called')
}
function subscriberC () {
console.log('C called')
}
testChannel.subscribe(subscriberA)
testChannel.subscribe(subscriberB)
testChannel.subscribe(subscriberC)
testChannel.publish()
/*
Expected:
A called
B called
C called
Actual:
A called
C called
*/
```
This is due to the `publish()` method iterating over the array with incrementing index:
```javascript
publish(data) {
for (let i = 0; i < this._subscribers.length; i++) …
```

diagnostics_channel: fix unsubscribe during publish

---

benchmark/buffers/buffer-copy.js

Using bytes 0 doesn't make much sense for this benchmark. Using `32768` also makes it indeterministic.

benchmark: adjust byte size for buffer-copy

---

lib/internal/test_runner/coverage.js
test/parallel/test-runner-coverage-source-map.js

Ref: https://github.com/nodejs/node/issues/54753#issuecomment-2351142258 / https://github.com/nodejs/node/issues/54753#issuecomment-2351584729
This is not semver-major, as both code coverage and source maps experimental features.
The coverage constructer was changed to accept a `globalOptions` because of how cluttered it got from all the additional features.
Previously, there were some issues with coverage (See #55039), however, other test runner changes have resolved those issues.

test_runner: require `--enable-source-maps` for sourcemap coverage

---

lib/internal/abort_controller.js
test/parallel/test-abortsignal-drop-settled-signals.mjs

Refs #55351
Using this [commit's description](https://github.com/chromium/chromium/commit/d5b7539036199ad653125222f061f39c66e91a86) as a reference, this PR adds a `SafeFinalizationRegistry` to remove GCed dependant signals' references since they will no longer abort.

lib: clean up references to GCed abort signals

---

src/api/exceptions.cc
test/parallel/test-debug-process.js

This fixes the bug in printing the error messages when an exception is thrown on Windows.
Fixes: https://github.com/nodejs/node/issues/23191

src: fix winapi_strerror error string

---

lib/buffer.js
test/parallel/test-buffer-resizable.js

For release notes:
When a `Buffer` is created using a resizable `ArrayBuffer`, the `Buffer` length will now correctly change as the underlying `ArrayBuffer` size is changed.
```js
const ab = new ArrayBuffer(10, { maxByteLength: 20 });
const buffer = Buffer.from(ab);
console.log(buffer.byteLength); 10
ab.resize(15);
console.log(buffer.byteLength); 15
ab.resize(5);
console.log(buffer.byteLength); 5
```
Fixes: https://github.com/nodejs/node/issues/52195

buffer: make Buffer work with resizable ArrayBuffer

---

lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers.js

add mock timers for nodeTimers.promises.scheduler.wait

test_runner: add mock timers for nodeTimers.promises.scheduler.wait

---

doc/api/deprecations.md
lib/buffer.js
test/parallel/test-buffer-slow.js

SlowBuffer has been doc-deprecated for a while and I couldn't find why we didn't want to proceed with the deprecation cycle on this feature. Therefore, this PR runtime deprecates SlowBuffer.

lib: runtime deprecate SlowBuffer

---

test/parallel/test-eslint-prefer-primordials.js
tools/eslint-rules/prefer-primordials.js

Mostly relevant for the v22.x branch now that https://github.com/nodejs/node/pull/55276 has landed on `main` and won't land on v22.x. With this change, it's going to make backporting changes to v22.x easier, helping backporters pin point which commits need fixing when backporting to the v22.x staging branch without needing to run the whole test suite.

tools: add `polyfilled` option to `prefer-primordials` rule

---

configure.py

- The `Path` class does not support concatenation with the `+` operator, so use the `/` operator instead.
- When concatenating paths, if the operand is an absolute path the previous path is ignored, so change `/include` to `include`.

build: fix path concatenation

---

doc/api/net.md
lib/internal/cluster/child.js
test/parallel/test-net-server-drop-connections-in-cluster.js

Refs: https://github.com/nodejs/node/issues/54882

lib: add flag to drop connection when running in cluster mode

---

.github/CODEOWNERS

AS per the title, noticed in #55425 where the team was not pinged

meta: assign CODEOWNERS for /deps/ncrypto/*

---

test/fixtures/wpt/README.md
test/fixtures/wpt/console/console-countReset-logging-manual.html
test/fixtures/wpt/console/console-log-large-array.any.js
test/fixtures/wpt/console/console-log-symbol.any.js
test/fixtures/wpt/versions.json

test: update `console` wpt

---

src/node_file.cc
test/parallel/test-fs-cp.mjs

Without this patch, here's the crash:
````
$ tools/test.py test/parallel/test-fs-cp.mjs
=== release test-fs-cp ===                   
Path: parallel/test-fs-cp
----- Native stack trace -----
1: 0x100476754 node::DumpNativeBacktrace(__sFILE*) [/Users/duhamean/Documents/node/out/Release/node]
2: 0x1005d7b6c node::Assert(node::AssertionInfo const&) [/Users/duhamean/Documents/node/out/Release/node]
3: 0x1003b0e94 node::SPrintFImpl(char const*) [/Users/duhamean/Documents/node/out/Release/node]
4: 0x1026c940c std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> node::SPrintF<>(char const*) [/Users/duhamean/Documents/node/out/Release/node]
5: 0x100604c50 v8::Local<v8::Object> node::ERR_FS_CP_EINVAL<>(v8::Isolate*, char const*) …
```

fs: fix crash when path contains `%`

---

lib/internal/process/execution.js
lib/internal/url.js
test/parallel/test-url-pathtofileurl.js

Fixes: https://github.com/nodejs/node/issues/54515
Given the number of characters to cover, I leaning towards using one regex to deal with them all rather than adding more special cases. Let's check what the benchmark says.
> FWIW According to [RFC1738](https://www.ietf.org/rfc/rfc1738.txt), they should be encoded (see the bold):
>
> > Characters can be unsafe for a number of reasons.  **The space
> > character is unsafe** because significant spaces may disappear and
> > insignificant spaces may be introduced when URLs are transcribed or
> > typeset or subjected to the treatment of word-processing programs.
> > **The characters "<" and ">" are unsafe** because they are used as the
> > delimiters around URLs in free text; the quote mark (""") is used to
> > delimit URLs in some systems. …

url: handle "unsafe" characters properly in `pathToFileURL`

---

benchmark/run.js
doc/contributing/writing-and-running-benchmarks.md

This PR adds a new flag to benchmark/run.js. You can pass the `--runs` to define the amount of benchmark suite runs.

benchmark: add --runs support to run.js

---

lib/child_process.js
lib/internal/abort_controller.js
lib/internal/blob.js
lib/internal/fs/watchers.js
lib/internal/per_context/primordials.js
lib/internal/streams/duplexify.js
lib/internal/test_runner/harness.js
lib/internal/test_runner/runner.js
lib/internal/test_runner/test.js
lib/internal/test_runner/utils.js
lib/internal/util.js
lib/internal/webstreams/adapters.js
lib/internal/webstreams/readablestream.js
lib/internal/webstreams/transfer.js
lib/internal/webstreams/transformstream.js
lib/internal/webstreams/writablestream.js
test/parallel/test-runner-run-watch.mjs
test/parallel/test-runner-watch-mode-complex.mjs
test/parallel/test-runner-watch-mode.mjs
typings/primordials.d.ts

Node.js v22+ supports `Promise.withResolvers()`. Let's use them!

lib: refactor project to use `Promise.withResolvers`

---

lib/_http_agent.js
lib/internal/main/watch_mode.js
lib/internal/modules/esm/fetch_module.js
lib/internal/modules/esm/resolve.js
lib/internal/modules/helpers.js
lib/internal/process/per_thread.js
lib/internal/process/pre_execution.js
lib/internal/repl/utils.js
lib/internal/url.js
lib/internal/util/inspect.js
lib/repl.js
test/fixtures/wpt/resources/webidl2/lib/webidl2.js

Removes primordials when we're only checking for one character and leans on JavaScript syntax as much as possible for performance

lib: remove startsWith/endsWith primordials for char checks

---

deps/ncrypto/ncrypto.cc

IWYU `#include` fix that also rectifies the following errors in Electron during build:
```
../../third_party/electron_node/deps/ncrypto/ncrypto.cc:308:14: error: use of undeclared identifier 'RAND_status'
308 |     if (1 == RAND_status()) {
|              ^
../../third_party/electron_node/deps/ncrypto/ncrypto.cc:314:39: error: use of undeclared identifier 'RAND_bytes'
314 |       while (length > INT_MAX && 1 == RAND_bytes(buf, INT_MAX)) {
|                                       ^
../../third_party/electron_node/deps/ncrypto/ncrypto.cc:318:37: error: use of undeclared identifier 'RAND_bytes'
318 |       if (length <= INT_MAX && 1 == RAND_bytes(buf, static_cast<int>(length)))
|                                     ^
../../third_party/electron_node/deps/ncrypto/ncrypto.cc:336:17: error: use …
```

crypto: include `openssl/rand.h` explicitly

---

doc/api/util.md
lib/internal/util.js
lib/util.js
src/uv.cc
test/parallel/test-uv-errno.js

This patch adds a new utility function which provides human-readable string description of the given system error code.

src,lib: introduce `util.getSystemErrorMessage(err)`

---

lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/load.js
lib/internal/modules/helpers.js

Moves the check from random places in loaders to `stripTypeScriptTypes `

module: simplify ts under node_modules check

---

doc/api/deprecations.md
lib/url.js
test/parallel/test-url-parse-invalid-input.js
typings/internalBinding/util.d.ts

We documentation-only deprecated URL.parse on v18, almost 2 years ago. Without a runtime deprecation people will continue to use it and be exposed to security flaws. This is a nudge on the direction for a possible EOL in 3-5 years?
cc @nodejs/tsc

url: runtime deprecate url.parse

---

test/sequential/test-fs-path-dir.js

Trying to build a URL by concatenating `file://` and a path will always fail as soon as the path contains some URL-significant char (e.g. `%`, `?`, `#`)

test: fix invalid `file:` URL in `test-fs-path-dir`

---

doc/api/dgram.md
lib/dgram.js
src/udp_wrap.cc
test/common/udp.js
test/parallel/test-child-process-dgram-reuseport.js
test/parallel/test-cluster-dgram-reuseport.js
test/parallel/test-dgram-reuseport.js

`UV_UDP_REUSEPORT` allows users to bind a port to multiple sockets.
Refs: https://github.com/libuv/libuv/pull/4419

dgram: add UV_UDP_REUSEPORT for udp

---

doc/api/net.md
lib/net.js
src/tcp_wrap.cc
test/common/net.js
test/parallel/test-child-process-net-reuseport.js
test/parallel/test-cluster-net-reuseport.js
test/parallel/test-net-reuseport.js

`SO_REUSEPORT` allows users bind a port to multiple sockets, and incoming connections are distributed by OS across the listener sockets. It will improve the performance of server.
Refs: https://github.com/libuv/libuv/pull/4407

net: add UV_TCP_REUSEPORT for tcp

---

node.gyp

Only compile the bundled sqlite in `deps/sqlite` if Node.js was not configured with `--shared-sqlite`.
`node.gypi` is already correctly adding the sqlite dependency if `node_shared_sqlite=="false"` so the unconditional entries in `node.gyp` are not necessary.
---
It looks like there are other dependencies that would need a similar change, but I'm not including those here because the sqlite dependency is much easier to check (deleting the `deps/sqlite` directory and linking against (with `--shared-sqlite`) `libsqlite3-dev` on Ubuntu or `sqlite-devel` on Fedora).

build: conditionally compile bundled sqlite

---

tools/install.py

This PR will fix #55437 , please have a look!

fix(build): uninstall support AIX 7.1

---

doc/api/fs.md

`Readable`'s `highWaterMark` has in fact been 64KiB since #52037.

doc: remove outdated remarks about `highWaterMark` in fs

---

test/parallel/test-cluster-shared-handle-bind-privileged-port.js

On some Linux systems (not reproducible in CI, but reproducible locally), this test will fail because the port 42 is not priviledged. For example, on my Kali Linux installation:
```console
└─$ out/Release/node test/parallel/test-cluster-shared-handle-bind-privileged-port.js
node:assert:137
throw err;
^
AssertionError [ERR_ASSERTION]: listen should have failed at test/parallel/test-cluster-shared-handle-bind-privileged-port.js:51
at Server.mustNotCall (test/common/index.js:557:12)
at Object.onceWrapper (node:events:621:28)
at Server.emit (node:events:519:35)
at emitListeningNT (node:net:1948:10)
at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
generatedMessage: false,
code: 'ERR_ASSERTION',
actual: undefined,
expected: undefined,
operator: 'fail'
}
Node.js …
```

test: deflake `test-cluster-shared-handle-bind-privileged-port`

---

doc/api/util.md

Refs: https://github.com/nodejs/node/pull/19989
Fixes: https://github.com/nodejs/node/issues/55446

doc: add isBigIntObject to documentation

---

doc/api/child_process.md

This is a PR for a old issue in hope for it to be resolved and closed. This will be my first contribution to node 😊
Fixes: https://github.com/nodejs/node/issues/15714

doc: add note about stdio streams in child_process

---

src/api/environment.cc
src/internal_only_v8.cc
src/js_native_api_v8.cc
src/node_buffer.cc
src/node_constants.cc
src/node_options.cc
src/node_webstorage.cc

Ref #55452
`GetPrototype` has been deprecated in favor of `GetPrototypeV2`. See https://issues.chromium.org/issues/333672197

src: switch from `Get/SetPrototype` to `Get/SetPrototypeV2`

---

test/fixtures/wpt/README.md
test/fixtures/wpt/versions.json
test/fixtures/wpt/webmessaging/broadcastchannel/WEB_FEATURES.yml
test/fixtures/wpt/webmessaging/broadcastchannel/basics.any.js
test/fixtures/wpt/webmessaging/broadcastchannel/workers.html

Updating the web platform tests for the webmessaging/broadcastchannel.

test: update wpt test for webmessaging/broadcastchannel

---

test/addons/repl-domain-abort/test.js
test/node-api/test_instance_data/test.js
test/node-api/test_uv_threadpool_size/node-options.js

Some test was making assumptions about the path no containing `'` char, we can simplify it by relying on `JSON.stringify` to escape chars.

test: fix addons and node-api test assumptions

---

typings/primordials.d.ts

The type of `ArrayBufferPrototypeGetByteLength` was missing in `primordials.d.ts`.

typings: add missing type of `ArrayBufferPrototypeGetByteLength`

---

lib/internal/fs/glob.js
test/parallel/test-fs-glob.mjs

Fixes #55060
Passes the dirname as parentPath, rather than the full file path.

fs: pass correct path to `DirentFromStats` during `glob`

---

test/parallel/test-node-output-v8-warning.mjs

This PR makes snapshot testing slightly more flexible so that embedders can run smoke tests against it.
Previous similar PRs:
* https://github.com/nodejs/node/pull/36489
* https://github.com/nodejs/node/pull/54375

test: make `test-node-output-v8-warning` more flexible

---

lib/internal/modules/esm/resolve.js
test/es-module/test-esm-main-lookup.mjs

There's this assumption in the code that the importing module (which I called the `importer` in the PR title) URL would be under the `file:`  scheme, but there's no reason this is the case, even without loader it could be under the `data:` scheme. TBH I'm not sure why we bother converting it to a path instead of exposing the URL and let the user decides if they want to convert it to a path, but for the sake of not introducing a breaking change, I'm simply wrapping the `fileURLToPath` in a `try`/`catch` block.

esm: add a fall back when importer in not a file

---

lib/internal/streams/pipeline.js
test/parallel/test-stream-pipeline.js

This PR propagates the reason of the `AbortSignal` passed to the `pipeline` function (`node:stream/promises`) to the `cause` of the thrown `AbortError`.
The vast majority of `AbortError`s created by the standard library already propagates the reason, so this should bring more consistency.

stream: propagate AbortSignal reason

---

lib/internal/util/colors.js
test/fixtures/test-runner/output/assertion-color-tty.mjs
test/fixtures/test-runner/output/assertion-color-tty.snapshot
test/fixtures/test-runner/output/non-tty-forced-color-output.js
test/fixtures/test-runner/output/non-tty-forced-color-output.snapshot
test/parallel/test-runner-output.mjs

This PR should address #55383.

lib: ensure FORCE_COLOR forces color output in non-TTY environments

---

test/parallel/test-crypto-dh-errors.js
test/parallel/test-crypto-private-decrypt-gh32240.js
test/parallel/test-tls-getcertificate-x509.js

This PR tweaks crypto tests a bit to make them work for both OpenSSL and BoringSSL. This allows Electron to reduce relevant patch surface area.

test,crypto: make crypto tests work with BoringSSL

---

doc/api/module.md
lib/internal/main/eval_string.js
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/get_format.js
lib/internal/modules/esm/translators.js
lib/internal/modules/helpers.js
lib/internal/modules/typescript.js
lib/module.js
test/parallel/test-bootstrap-modules.js
test/parallel/test-module-strip-types.js

This PR introduces a new api in `node:module`.
Fixes: https://github.com/nodejs/node/issues/54300

module: add module.stripTypeScriptTypes

---

src/node_sqlite.cc
src/node_sqlite.h

Move options that are only relevant for opening the database into a self-contained class.
Refs: https://github.com/nodejs/node/pull/54777#discussion_r1745988310

sqlite: refactor open options

---

test/parallel/test-buffer-includes.js
test/parallel/test-buffer-indexof.js

These tests are segfaulting in `ulimit -s 512` environment.

test: avoid `apply()` calls with large amount of elements

---

doc/api/string_decoder.md

This PR adds the ESM counterparts of the CJS examples for [the String decoder documentation](https://nodejs.org/api/string_decoder.html).
Best regards!

doc: add esm examples to `node:string_decoder`

---

test/parallel/test-url-pathtofileurl.js

In https://github.com/nodejs/node/pull/55476, we're changing the implementation of `pathToFileURL` to something more performant. In an early implementation, I realized some char were swallowed, but we didn't have a test to catch that. This PR is adding some additional test cases to catch this kind of bug.

test: increase coverage of `pathToFileURL`

---

deps/nghttp2/unofficial.gni
deps/sqlite/unofficial.gni

As in title - fixes build failures resultant of recent updates to `sqlite` and `nghttp2`.

build: fix GN build for sqlite and nghttp2

---

doc/api/cli.md
doc/api/module.md
doc/api/process.md
doc/api/typescript.md

`--experimental-strip-types` has been released for almost ~3 months.
There is only one issue open and TypeScript has created a [flag for compatibility](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/) with our implementation.

doc: move typescript support to active development

---

doc/api/fs.md
lib/internal/fs/utils.js
test/parallel/test-fs-utils-get-dirents.js

Refs: https://github.com/nodejs/node/issues/55538

fs: make `dirent.path` writable

---

tools/generate_config_gypi.py

Fixes the following failure on Windows:
<details><summary>Details</summary>
<p>
```
NORTHAMERICA+cavohr@CODEBYTERE-WIN-WORK CLANGARM64 ~/Developer/node_gn/node ((001728f...))
$ ninja -C out/Release node
ninja: Entering directory `out/Release'
[0/1] Regenerating ninja files
[1/5950] ACTION //node:generat...toolchain/win:win_clang_arm64) 
FAILED: gen/node/config.gypi
C:/Users/cavohr/AppData/Local/.vpython-root/store/python_venv-8iu8g3np8f7r76gphtcf7o1v1s/contents/Scripts/python3.exe ../../node/tools/generate_config_gypi.py gen/node/config.gypi --out-dir . --dep-file gen/node/generate_config_gypi.d --node-gn-path //node
Traceback (most recent call last):
File "../../node/tools/generate_config_gypi.py", line 116, in <module>
main()
File "../../node/tools/generate_config_gypi.py", line 103, in …
```

build: fix GN arg used in `generate_config_gypi.py`

---

lib/_http_outgoing.js
test/parallel/test-http-outgoing-destroyed.js

Enforce stream invariant. No new errors can occur after `.destroy(err)`

http: don't emit error after destroy

---

src/inspector_js_api.cc
src/node_buffer.cc
src/string_bytes.cc

Fixes #54417
Ref: #55452
`v8::String::Value` is deprecated, so this PR replaces it with `v8::String::ValueView`

src: migrate `String::Value` to `String::ValueView`

---

src/process_wrap.cc
src/spawn_sync.cc
src/util-inl.h

Let's not run `IsWindowsBatchFile` on non-windows environments.

src: do not run IsWindowsBatchFile on non-windows

---

lib/internal/modules/cjs/loader.js
lib/internal/util.js
test/es-module/test-require-module-warning.js
test/fixtures/es-modules/require-module.js

Trim off irrelevant internal stack frames for require(esm) warnings so it's easier to locate where the call comes from when --trace-warnings is used.
Previously, running `npm install` in `tools/doc` with `--trace-warning` leads to the following stack trace - none of the top 10 frames are useful in finding where the `require()` call comes from:
```
at emitExperimentalWarning (node:internal/util:273:11)
at loadESMFromCJS (node:internal/modules/cjs/loader:1388:5)
at Module._compile (node:internal/modules/cjs/loader:1525:5)
at Object..js (node:internal/modules/cjs/loader:1680:16)
at Module.load (node:internal/modules/cjs/loader:1328:32)
at Function._load (node:internal/modules/cjs/loader:1138:12)
at TracingChannel.traceSync (node:diagnostics_channel:315:14)
at wrapModuleLoad …
```

module: trim off internal stack frames for require(esm) warnings

---

lib/internal/errors.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/module_job.js
src/module_wrap.cc
test/es-module/test-require-module-tla-retry-require.js

This tracks the asynchronicity in the ModuleWraps when they turn out to contain TLA after instantiation, and throw the right error (ERR_REQUIRE_ASYNC_MODULE) when it's required again. It removes the freezing of ModuleWraps since it's not meaningful to freeze this when the rest of the module loader is mutable, and we can record the asynchronicity in the ModuleWrap right after compilation after we get a V8 upgrade that contains v8::Module::HasTopLevelAwait() instead of searching through the module graph repeatedly which can be slow.
Fixes: https://github.com/nodejs/node/issues/55516
Refs: https://github.com/nodejs/node/issues/52697

module: fix error thrown from require(esm) hitting TLA repeatedly

---

test/parallel/test-child-process-dgram-reuseport.js
test/parallel/test-child-process-net-reuseport.js
test/parallel/test-cluster-dgram-reuseport.js
test/parallel/test-cluster-net-reuseport.js
test/parallel/test-dgram-reuseport.js
test/parallel/test-net-reuseport.js

Unhandled `'error'` events will make the process exit with an unclean exit code anyway.

test: remove unneeded listeners

---

configure.py

ICU 76 decided to reduce overlinking[^1] thus `icu-i18n` will no longer add `icu-uc` when linking to shared libraries. This results in undefined symbols/references when trying to build with system ICU 76.
[^1]: unicode-org/icu@199bc82
---
Example of build error (seen on v22.10.0 and v23.1.0) is:
```
.../out/Release/obj.target/gen-regexp-special-case/deps/v8/src/regexp/gen-regexp-special-case.o: in function `v8::internal::PrintSet(std::basic_ofstream<char, std::char_traits<char> >&, char const*, icu_76::UnicodeSet const&)':
gen-regexp-special-case.cc:(.text._ZN2v88internal8PrintSetERSt14basic_ofstreamIcSt11char_traitsIcEEPKcRKN6icu_7610UnicodeSetE+0x9c): undefined reference to `icu_76::UnicodeSet::getRangeStart(int) const'
/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: …
```

build: fix building with system icu 76

---

README.md

According to the MIT Technology Licensing Office, "MIT License" appears to have a capital **L** in 'License', per the following statement:
> The MIT Open Source License, often referred to as the "MIT License,"

doc: capitalize "MIT License"

---

src/cares_wrap.cc
src/cares_wrap.h

Ref: #52464 
`ares_query` has been deprecated in favor of `ares_query_dnsrec`, so this PR switches our implementation to use it.

dns: stop using deprecated `ares_query`

---

src/node.h

Small efficiency improvement to `NODE_DEFINE_CONSTANT`: use [`v8::String::NewFromUtf8Literal()`](https://chromium.googlesource.com/v8/v8/+/branch-heads/12.9/include/v8-primitive.h#425) instead of `NewFromUtf8()`. 
This way, the string literal's length is known at compile time, so V8 doesn't have to call strlen() or ToLocalChecked().

src: use NewFromUtf8Literal in NODE_DEFINE_CONSTANT

---

doc/api/sqlite.md
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-database-sync.js

Allow opening existing SQLite databases with `SQLITE_OPEN_READONLY` set.

sqlite: add readOnly option

---

doc/api/diagnostics_channel.md
lib/_http_client.js
test/parallel/test-diagnostic-channel-http-request-created.js
test/parallel/test-diagnostics-channel-http.js

Fixes: https://github.com/nodejs/node/issues/55352

http: add diagnostic channel `http.client.request.created`

---

lib/internal/modules/cjs/loader.js

This refactors the CommonJS loading a bit to create a center point that handles source loading (`loadSource`) and make format detection more consistent to pave the way for future synchronous hooks.
- Handle .mjs in the .js handler, similar to how .cjs has been handled.
- Generate the legacy ERR_REQUIRE_ESM in a getRequireESMError() for both .mts and require(esm) handling (when it's disabled).
Refs: https://github.com/nodejs/loaders/pull/198

module: unify TypeScript and .mjs handling in CommonJS

---

lib/internal/http2/core.js
test/parallel/test-http2-async-local-storage.js

Create and store an AsyncResource for each stream, following a similar approach as used in HttpAgent.
Fixes #55376

http2: fix client async storage persistence

---

lib/internal/url.js
src/node_url.cc
src/node_url.h

As suggested in https://github.com/nodejs/node/pull/54545#discussion_r1733768385, let's see if it's faster.

url: refactor `pathToFileURL` to native

---

src/cares_wrap.cc

Fixes: https://github.com/nodejs/node/issues/52439
1. the `channel->task_list()` maybe empty when failed to create `NodeAresTask` in `ares_sockstate_cb`. So we can not assert the list is not empty in timeout callback.
2. We should check if the task is `nullptr` in `ares_sockstate_cb`.

src: fix dns crash when failed to create NodeAresTask

---

doc/api/embedding.md

normalise the headers, fixup bullet points and expand `node::IsolateData` scope for clarity.

doc: improve c++ embedder API doc

---

lib/internal/test_runner/coverage.js

This should make future modifications to the `TestCoverage` class simpler, as additional options don't need to be added to the constructor.

test_runner: pass `options` directly to `TestCoverage`

---

.github/workflows/notify-on-review-wanted.yml

Ref: https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1730308054959239?thread_ts=1730296053.898089&cid=C019Y2T6STH
There is already a message stating that the PR/issue needs reviews, the title should (IMO) correspond to the issue/PR.

meta: show PR/issue title on review-wanted

---

Makefile
tools/release.sh
vcbuild.bat

Use rclone to upload assets to Cloudflare as it is more reliable.
Refs: https://github.com/nodejs/build/issues/3508

build: use rclone instead of aws CLI

---

lib/internal/crypto/diffiehellman.js
src/crypto/crypto_ec.cc
src/crypto/crypto_ec.h
src/crypto/crypto_keys.cc
src/crypto/crypto_keys.h

removes use of `GetOKPCurveFromName` in `ECDHBitsJob` and moves `GetOKPCurveFromName` closer to its only remaining invocation.

src: refactor ECDHBitsJob signature

---

doc/api/crypto.md

EC, X448 and X25519 are all ECDH, `ECDH-ES` in here might have been a reference to the JWA algorithm identifier 🤷

doc: remove mention of ECDH-ES in crypto.diffieHellman

---

doc/api/console.md

Many user reported issues show poor awareness of the nature of console streams. explicitly document that.

doc: add a note on console stream behavior

---

doc/api/diagnostics_channel.md
lib/_http_server.js
test/parallel/test-diagnostic-channel-http-response-created.js
test/parallel/test-diagnostics-channel-http.js

Followup of https://github.com/nodejs/node/pull/55586

http: add diagnostic channel `http.server.response.created`

---

README.md
tools/lint-readme-lists.mjs

Having small variations can be hard to spot for human reviewers, and can affect the tooling in a way that's not always obvious.

tools: lint README lists more strictly

---

deps/ncrypto/ncrypto.cc
deps/ncrypto/ncrypto.h
src/crypto/crypto_keygen.cc
src/crypto/crypto_keygen.h
src/crypto/crypto_keys.cc
src/crypto/crypto_keys.h
src/crypto/crypto_util.h

src: move more key related stuff to ncrypto

---

lib/os.js

Replaced String.prototype.endsWith with manual string length and index checks for performance improvements.

os: improve path check with direct index access

---

lib/internal/assert/assertion_error.js
test/parallel/test-assert-deep.js
test/parallel/test-assert.js

Fixes a small issue introduced in https://github.com/nodejs/node/pull/54862
The check that was comparing the total string length to decide if the comparison was long enough to pick between the "stacked" diff or the "simple" one, was not considering the double quotes surrounding `actual` and `expected` when they are strings

assert: fix the string length check for printing the simple diff

---

lib/internal/modules/package_json_reader.js

Fixes: https://github.com/nodejs/node/pull/55412#discussion_r1816314305

module: simplify `findPackageJSON` implementation

---

doc/api/cli.md
lib/internal/async_context_frame.js
src/node_options.cc
test/parallel/test-without-async-context-frame.mjs

I've marked AsyncContextFrame as stable and made it the default. With this we should see the substantial performance improvements to AsyncLocalStorage as the default case for users on future versions of Node.js. Getting more users on this will also help to identify if there are any perf outliers to tweak further.
I hope to land this in v24. I _assume_ we would generally consider this change as major, but I'm happy to downgrade it to minor if we think it's safe to do so.
(Pushing from the train somewhere between Valencia and Barcelona! 🚅💨)
cc @nodejs/diagnostics APMs have had some time to try this out and there have been no further issues after the initial iteration. I'm taking this to mean it seems to be stable. If you disagree, please speak up.
cc @nodejs/electron-installer Note that …

lib: make ALS default to AsyncContextFrame

---

.github/workflows/notify-on-review-wanted.yml

When the `review-wanted` message is sent, the ref will consistently be `refs/heads/main`, the event type will be `pull_request_target`, and I believe the most recent commit to main will likely not be relevant to the review request.
The `actions URL` is significant here, as it distinguishes this process from the force-push workflow.

meta: make review-wanted message minimal

---

benchmark/util/get-callsite.js
doc/api/deprecations.md
doc/api/util.md
lib/util.js
src/node_util.cc
test/common/index.js
test/fixtures/get-call-site.js
test/fixtures/get-call-sites.js
test/parallel/test-util-getcallsite.js
test/parallel/test-util-getcallsites.js

`util.getCallSite` returns an array of call site objects. Rename the
function to reflect that it returns a given count of frames captured
as an array of call site object.
Renames the first parameter `frames` to be `frameCount` to indicate
that it specifies the count of returned call sites.
Given that this function is marked as "active development", I believe it is better to rename it early.

util: fix util.getCallSites plurality

---

typings/internalBinding/modules.d.ts

Refs: https://github.com/nodejs/node/pull/55412/files#r1817708918

typings: fix `ModulesBinding` types

---

doc/api/perf_hooks.md

The code sample at the top of the "Performance measurements API" section of the docs does not run.
The code in question:
```js
const { PerformanceObserver, performance } = require('node:perf_hooks');
const obs = new PerformanceObserver((items) => {
console.log(items.getEntries()[0].duration);
performance.clearMarks();
});
obs.observe({ type: 'measure' });
performance.measure('Start to Now');
performance.mark('A');
doSomeLongRunningProcess(() => {
performance.measure('A to Now', 'A');
performance.mark('B');
performance.measure('A to B', 'A', 'B');
});
```
If you replace `doSomeLongRunningProcess` with an IIFE with a sleep() at the top of it, you get this:
```js
const { PerformanceObserver, performance } = require('node:perf_hooks');
const obs = new PerformanceObserver((items) => { …
```

doc: broken `PerformanceObserver` code sample

---

.github/workflows/daily-wpt-fyi.yml

This updates the [Daily WPT report](https://github.com/nodejs/node/actions/workflows/daily-wpt-fyi.yml) job to always test on all releases that are not EOL + latest nightly and it uses the [schedule](https://raw.githubusercontent.com/nodejs/Release/refs/heads/main/schedule.json) from https://github.com/nodejs/Release/ to collect the versions.
Example output from the processed schedule given $now is `2024-10-31`
```
[
18,
20,
22,
23,
"latest-nightly"
]
```
---
This resolves an issue with the delay coming from https://github.com/actions/node-versions manifest that `actions/setup-node` uses as well as actually not cutting off reporting on lts/-2 so long as it's still not EOL presented in the recent run - https://github.com/nodejs/node/actions/runs/11604060841 - where 18 is tested but 22 is …

tools: run daily WPT.fyi report on all supported releases

---

.github/workflows/daily-wpt-fyi.yml

A quick followup to #55619, makes the jq output compact so that it can be processed by the actions runner properly.
Fixes https://github.com/nodejs/node/actions/runs/11645595593

tools: compact jq output in daily-wpt-fyi.yml action

---

src/crypto/crypto_cipher.cc

The ability to revert the fix for CVE-2023-46809 was only added to Node.js 18.x, 20.x and 21.x as, per policy, security reverts are only added to the existing supported release lines at the time of the fix.
The error message thrown when `RSA_PKCS1_PADDING` is used on `main` and subsequent major versions (i.e. Node.js 22 and 23) when OpenSSL does not support implicit rejections should not have suggested that it is possible to revert the fix.
Fixes: https://github.com/nodejs/node/issues/55628

crypto: fix `RSA_PKCS1_PADDING` error message

---

lib/internal/modules/cjs/loader.js

Previously in the CommonJS loader, --inspect-brk is implemented checking whether the module points to the result of re-resolving process.argv[1] to determine whether the module is the entry point. This is unnecessarily complex, especially now that we store that information in the module as kIsMainSymbol. This patch updates it to simply check that symbol property instead.

module: simplify --inspect-brk handling

---

src/node_sqlite.cc

As per @jasnell's [suggestion](https://github.com/nodejs/node/pull/54687#discussion_r1745992906), consistently use `MaybeLocal` and avoid `Check()` and `ToLocalChecked()` entirely.

sqlite: improve error handling using MaybeLocal

---

doc/api/deprecations.md
doc/api/util.md
lib/util.js
test/fixtures/typescript/ts/test-get-callsite-explicit.ts
test/fixtures/typescript/ts/test-get-callsite.ts
test/parallel/test-util-getcallsites.js

Fixes: https://github.com/nodejs/node/issues/55109

 util: add sourcemap support to getCallSites

---

tools/lint-md/lint-md.mjs

`node:util` provides a `parseArgs` export, so this PR switches `lint-md` to use it, as it's (IMO) a cleaner way to read arguments.

tools: use `util.parseArgs` in `lint-md`

---

src/node.h
typings/internalBinding/options.d.ts

Delete deprecated an never used enum options `kAllowedInEnvironment` and `kDisallowedInEnvironment` in `OptionEnvvarSettings`
-------
I'm not too sure if this is gonna be ok in CITGM, but, lets give it a try!

src: nuke deprecated and un-used enum members in `OptionEnvvarSettings`

---

lib/internal/webidl.js
lib/internal/worker/js_transferable.js
test/parallel/test-structuredClone-global.js

The first commit optimizes `type(V)` in `webidl.js` to return enum
instead of string.
The second commit provides a factory to generate `dictionaryConverter`
compliant with the spec. The implemented factory function is used for
the `structuredClone` algorithm, along with updated test cases.

lib: implement webidl dictionary converter and use it in structuredClone

---

doc/api/cli.md

doc: update --max-semi-space-size description in cli.md

---

lib/path.js
src/path.cc
test/cctest/test_path.cc
test/parallel/test-path-makelong.js
test/parallel/test-path-normalize.js
test/parallel/test-path-resolve.js

This PR fixes resolving device paths like `\\.\PHYSICALDRIVE`.
The `resolve` and `normalize` functions were adding a trailing backslash, considering that this device path was a UNC path. However, device paths are different than UNC paths.
In addition to fixing this issue, the previous attempt also fixed other inconsistencies. So, this PR only fixes the issue itself.
Previous PR: https://github.com/nodejs/node/pull/54224
Fixes: https://github.com/nodejs/node/issues/54025

path,win: fix bug in resolve and normalize

---

test/es-module/test-esm-import-meta-resolve.mjs
test/es-module/test-esm-pkgname.mjs

Those tests were using unusual patterns, making them a bit hard to read.

test: refactor some esm tests

---

lib/internal/assert/assertion_error.js
test/parallel/test-assert-deep-with-error.js

Refs #55310
Fixes #55310
This PR fixes AssertionError reporting when [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) is present.

assert: fix deepStrictEqual on errors when cause is present

---

test/parallel/test-fs-watch-recursive-add-file-to-existing-subfolder.js
test/parallel/test-fs-watch-recursive-add-file-to-new-folder.js
test/parallel/test-fs-watch-recursive-add-file-with-url.js
test/parallel/test-fs-watch-recursive-add-file.js
test/parallel/test-fs-watch-recursive-add-folder.js

change assertions on test-fs-watch-recursive-add-* tests to only take into account change events that match the file
Fixes #55592

test: ignore unrelated events in FS watch tests

---

src/node_modules.cc

In issue https://github.com/nodejs/node/issues/55584, @codebytere reported a sanitizer error 'container-overflow'. This error happens only on systems where the standard library has been annotated to warn about reads between the std::string's end and the end of the its allocated memory (std::string:capacity). This reads are memory safe but they can also be a sign that there is a real bug. In the instance of issue 55584, it is not a bug, it is a false positive.
In some instances, it is possible to indicate to the compiler that we want to disallow these checks to avoid the false positive, but I could not find documentation on this topic. With some glue code, this PR should work around this issue. It somewhat ugly code. In a future release of simdjson, we will provide a more convenient …

src: provide workaround for container-overflow (issue 55584)

---

doc/api/addons.md

bullet pointed addon optons; wording clarity; fixes typo

doc: clarity to available addon options

---

lib/internal/util/inspect.js
test/parallel/test-util-inspect.js

Fixes #55539 by only supressing an error from a circular `inspectRaw` if it is a max-call-stack-exceeded error, otherwise, throw the error.

util: don't catch on circular toStringTag error

---

doc/api/child_process.md

reword `child` to `child process` wherever possible. this helps in maintaining clarity and precision,
consistency while avoiding misinterpretation.

doc: consistent use of word child process

---

tools/dep_updaters/update-c-ares.mjs

GitHub Actions is by default running the tools updater workflow with Node.js 18. Avoid use of `import.meta.dirname`, which wasn't backported to Node.js 18.
Refs: https://github.com/nodejs/node/pull/55445
---
Example error, https://github.com/nodejs/node/actions/runs/11647004207/job/32431749696
```
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:405:5)
at validateString (node:internal/validators:162:11)
at join (node:path:1171:7)
at file:///home/runner/work/node/node/tools/dep_updaters/update-c-ares.mjs:5:17
at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
at async …
```

tools: fix c-ares updater script for Node.js 18

---

lib/timers/promises.js

Let's use `Promise.withResolvers()` instead of creating a promise directly.
Benchmark CI: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1652/console

lib: use `Promise.withResolvers()` in timers

---

.github/workflows/doc.yml

To save time, the `.github/workflows/doc.yml` workflow runs with a pre-built Node.js. The switch of `lts/*` to Node.js 22 has broken this workflow for Node.js 20 and 18 due to a mismatch in globals. Pin the version of Node.js back to 20.
Fixes: https://github.com/nodejs/node/issues/55754
---
cc @nodejs/releasers The workflow is broken for both `v18.x-staging` and `v20.x-staging`. I think if we land this on `v20.x-staging` we can cherry-pick this to `v18.x-staging` to fix the workflow there, but if you prefer I can open a `v18.x-staging` targeted PR that pins to Node.js 18 instead.

[v20.x] build: pin doc workflow to Node.js 20

---

lib/events.js
lib/fs.js
lib/internal/fs/promises.js
lib/internal/fs/read/context.js
lib/internal/fs/watchers.js
lib/timers/promises.js

From the [V8 blog](https://v8.dev/features/optional-chaining):
> Still, be considerate about using more than one optional chaining operator in a single chain. If a value is guaranteed to not be nullish, then using ?. to access properties on it is discouraged.
It adds more bytecode to each property access, in all these cases we know that the variables are not nullish

lib: remove unnecessary optional chaining

---

doc/contributing/releases.md

Refs: https://github.com/nodejs/Release/issues/1054
This needs to be discussed first by the @nodejs/releasers. However, since the next session (https://github.com/nodejs/TSC/issues/1648) might not happen due to NodeConf/Collab Summit I thought would be better to discuss it async.
cc: @nodejs/releasers @BethGriggs

doc: enforce strict policy to semver-major releases

---

test/fixtures/permission/fs-read.js
test/fixtures/permission/fs-write.js

Increasing the permission model coverage by including Buffer in fs tests.

test: add buffer to fs_permission tests

---

lib/internal/webidl.js

lib: prefer symbol to number in webidl `type` function

---

lib/internal/assert/assertion_error.js
lib/internal/util/comparisons.js
test/parallel/test-assert-deep-with-error.js

assert: differentiate cases where `cause` is `undefined` or missing

---

doc/api/path.md

Fast-tracking because this is a relatively simple change to implement, and IMO it doesn't need much deliberation

doc: add esm path import

---

doc/api/typescript.md

Adding path aliases not supported documentation and alternative to TypeScript documentation

doc: add path aliases typescript doc

---

test/parallel/test-os.js

This test fails if parent's (e.g. `sshd`) niceness is already lower than `10` and we're not root.

test: ensure that test priority is not higher than current priority

---

doc/api/documentation.md

As suggested in https://github.com/nodejs/node/pull/55740#pullrequestreview-2417943643.
IMO there's value in keeping the deprecated stability status for APIs that are stable. Users are already discouraged from using experimental APIs in production (because of the lack of stability), so applying a deprecated status on top of experimental only muddies the water, and I don't think it would be a stretch to imagine users starting to expect experimental APIs to follow semver until it's deprecated.
I'm not against emitting warnings when an experimental API is being modified and/or removed, I'm saying we should refrain from using the word deprecated in those cases.

doc: clarify removal of experimental API does not require a deprecation

---

lib/internal/fs/dir.js
test/sequential/test-fs-opendir-recursive.js

The bufferSize option was not respected in recursive mode. This PR
implements a naive solution to fix this issue until a better
implementation can be designed.
Fixes: https://github.com/nodejs/node/issues/48820

fs: fix bufferSize option for opendir recursive

---

doc/api/deprecations.md
doc/api/util.md
lib/internal/util.js
lib/util.js
test/parallel/test-util-getcallsite.js

A deprecated API has stability guarantees that an experimental API does not. I don't think we should mark an experimental API as deprecated without first graduating it to stable. Instead we can emit an experimental warning which would tell the user the API was renamed.

util: do not mark experimental feature as deprecated

---

test/parallel/test-child-process-send-type-error.js

This patch will include this uncovered fraction of code: https://app.codecov.io/gh/nodejs/node/blob/main/lib%2Finternal%2Fchild_process.js#L807

test: improve test coverage for child process message sending

---

doc/api/cli.md
doc/api/process.md
doc/api/report.md
lib/internal/process/report.js
src/env-inl.h
src/env.h
src/node_options.cc
src/node_options.h
src/node_report.cc
src/node_report_module.cc
test/common/report.js
test/report/test-report-writereport-exclude-env.js
test/report/test-report-writereport-preserve-env.js

This PR introduces a new cli flag `--report-exclude-env` to avoid writing env vars on diagnostic reports.
Some context: https://x.com/arthurfiorette/status/1848372069198614664

src: add cli option to exclude env vars on dr

---

lib/os.js
src/node_os.cc

Improve `node:os` userInfo performance by reducing the cost of creating a v8::Object.

src: improve `node:os` userInfo performance

---

doc/api/events.md
doc/api/globals.md

Refs: #55733
Fixes: #55733
This PR fixes inconsistencies in the `CustomEvent` docs by consolidating the history table in `globals` and `events`

doc: consolidate history table of CustomEvent

---

doc/api/cli.md

Refs: https://github.com/nodejs/node/pull/55697#discussion_r1834454585

doc: sort --report-exclude alphabetically

---

eslint.config.mjs

This file no longer exists. It hasn't existed since 02de40246f261355ece1cc044e282db4db60d59b.

tools: remove non-existent file from eslint config

---

.github/workflows/commit-queue.yml

Having prs not landing if they are label as `blocked` would be nice

tools: make commit-queue check blocked label

---

Makefile
deps/ncrypto/dh-primes.h
deps/ncrypto/engine.cc
deps/ncrypto/ncrypto.cc
deps/ncrypto/ncrypto.h

CC @jasnell (who appears to have contributed most of this work)
If these files are maintained in this repository, should they not follow the same linting / formatting rules? This PR has `clang-format` and `cpplint` apply to these files.

build: apply cpp linting and formatting to ncrypto

---

Makefile

The `out/Makefile` target in `Makefile` has an incomplete list of `.gyp` files for Node.js dependencies in `deps`, but also the ones that are listed are unconditional. If using any of the `--shared-*` configure options, it should be possible to still build Node.js if the corresponding directory under `deps` is removed.
Convert the explicit list of dependency `*.gyp` files for the `out/Makefile` target to a glob. This will pick up any toplevel `.gyp` files for dependencies present in `deps`.

build: use glob for dependencies of out/Makefile

---

doc/contributing/issues.md

highlight additional points around triager role

doc: clarify triager role

---

node.gni
tools/generate_config_gypi.py
unofficial.gni

Implement the `node_use_amaro` flag in GN build, which was added to GYP build in https://github.com/nodejs/node/pull/54136.
Refs: https://github.com/nodejs/node/pull/54136

build: implement node_use_amaro flag in GN build

---

src/node_modules.cc
test/es-module/test-esm-import-meta-resolve.mjs

Fixes: https://github.com/nodejs/node/issues/55518

esm: fix import.meta.resolve crash

---

benchmark/test_runner/mock-fn.js

Ref: #55723
This PR benchmarks the function-mocking of the test runner

benchmark: add `test_runner/mock-fn`

---

doc/api/report.md
src/node_report.cc
src/node_report.h
src/node_report_utils.cc
test/common/report.js
test/report/test-report-exclude-network.js

Fixes #55576 #46060 
I also added in the endpoint's report info the keys `ip4` or `ip6` which contain the ip address of the endpoint (as well as information on which stack it was via the key)
Example of a tcp uv with network (default) (note that the reverse hostname resolving is up to the system dns resolver and some implementation may not resolve 127.0.0.1 to localhost for example on one of the ci server it resolves to `test-ibm-rhel9-x64-1.nodejs.cloud`) 
```js
[
{
type: 'tcp',
is_active: true,
is_referenced: true,
address: '0x000055e70fcb85d8',
localEndpoint: { host: 'localhost', ip4: '127.0.0.1', port: 48986 },
remoteEndpoint: { host: 'localhost', ip4: '127.0.0.1', port: 38573 },
sendBufferSize: 2626560,
recvBufferSize: 131072,
fd: 24,
writeQueueSize: 0,
readable: true,
writable: true …
```

report: fix network queries in getReport libuv with exclude-network

---

doc/api/esm.md

same as title, to align with other features

doc: update unflag info of `import.meta.resolve`

---

doc/api/cli.md

Corrects #55495 re. the `--max-semi-space-size` default behavior change after Node 18
This relates to Node 19+ so please label [dont-land-on-v18.x](https://github.com/nodejs/node/labels/dont-land-on-v18.x)
Correction: The default `max-semi-space-size` doesn't reach 16MiB until the memory limit _exceeds_ 2GiB:
```shell
docker run -it -m 2048m \
-e NODE_OPTIONS="--max-old-space-size=1536" \
node:20 node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'
```
=> 1560 - 1536 = 24MB = 3x max-semi-space = 8MB
```shell
docker run -it -m 2049m \
-e NODE_OPTIONS="--max-old-space-size=1536" \
node:20 node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'
```
=> 1584 - 1536 = 48MB = 3x max-semi-space = 16MB
(Relates #55487 - Please excuse the churn!)

doc: correct max-semi-space-size statement

---

lib/internal/modules/package_json_reader.js

I'm already git blamed for these lines. The changes are code hygiene.

module: tidy code string concat → string templates

---

benchmark/fs/bench-opendirSync.js
doc/api/deprecations.md
doc/api/fs.md
lib/internal/fs/utils.js
test/parallel/test-fs-opendir.js
test/parallel/test-fs-utils-get-dirents.js
test/sequential/test-fs-opendir-recursive.js
test/sequential/test-fs-readdir-recursive.js

Marking as https://github.com/nodejs/node/labels/blocked because it should land after https://github.com/nodejs/node/pull/55547
Fixes: https://github.com/nodejs/node/issues/55538

fs: remove `dirent.path`

---

lib/events.js

There was some repetitive logics that validated the existence of eventlisteners.  
We now replace this with a single line of, `hasEventListener(self, type)`.  
- `self` is the object(e.g. EventEmitter) to be checked whether eventlisteners exists or not.  
- `type` is the type of eventlisteners, which can be `undefined`

events: extract event listener validation as a function

---

doc/api/cli.md

Setting of UV_THREADPOOL_SIZE from within javascript using process.env.UV_THREADPOOL_SIZE is not guaranteed to work as the thread pool would have been created as part of the runtime initialisation much before user code is run.
update doc/api/cli.md
Addresses [nodejs/help#1429](https://github.com/nodejs/help/issues/1429)

doc: clarify UV_THREADPOOL_SIZE env var usage

---

doc/contributing/releases.md

Adding the `-S` flag will pass it along to `git`, producing signed commits, which is something we want to encourage on our staging branches.

doc: add `-S` flag release preparation example

---

benchmark/fixtures/basic-test-runner.js
benchmark/test_runner/test-reporters.js

Refs: https://github.com/nodejs/node/issues/55723
This PR benchmarks the reporters currently included in the `node:test/reporters` module.

benchmark: add `test-reporters`

---

doc/api/modules.md

Added `node:sqlite` to mandatory `node:` prefix list.

doc: add `node:sqlite` to mandatory `node:` prefix list

---

doc/api/esm.md

Refs: https://github.com/nodejs/node/pull/55333

doc: add history entries for JSON modules stabilization

---

lib/internal/fs/utils.js
test/parallel/test-fs-utils-get-dirents.js

The `parentPath` must be a path to the parent directory rather than path to the file itself.
/cc @Ethan-Arrowood @nodejs/fs

fs: fix parentPath returned from getDirent() when type is `UV_DIRENT_UNKNOWN`

---

src/inspector_js_api.cc
src/node_buffer.cc
src/string_bytes.cc

This reverts commit 45c6a9e1f6e165eb0ab2f7b5635662aa1875c171.
Closes: https://github.com/nodejs/node/issues/55826

Revert "src: migrate `String::Value` to `String::ValueView`"

---

lib/internal/test_runner/mock/mock_timers.js
test/parallel/test-runner-mock-timers-date.js

Fixes #55849
Previously, the properties from the global `Date`, including the not-writable `isMock` and `[kMock]` values, would be copied if the global `Date` was already mocked. This became an issue because the mock setup would attempt overwrite these properties.
Now, `ERR_INVALID_STATE` is thrown, as `Date is already being mocked!`.
```js
import { test } from 'node:test'
test((outer) => {
outer.mock.timers.enable()
test((inner) => inner.mock.timers.enable())
});
```
```
✖ <anonymous> (0.536701ms)
TypeError: Cannot redefine property: Symbol(MockTimers)
at defineProperties (<anonymous>)
at #createDate (node:internal/test_runner/mock/mock_timers:396:5)
at Object.Date (node:internal/test_runner/mock/mock_timers:635:45)
at node:internal/test_runner/mock/mock_timers:659:74
at Array.forEach …
```

test_runner: error on mocking an already mocked date

---

lib/internal/watch_mode/files_watcher.js
test/parallel/test-runner-complex-dependencies.mjs
test/parallel/test-watch-file-shared-dependency.mjs

remove file from watcher dependencyOwners on file change only if it has no other owners.
Closes #55095

test: prevent unwanted dependencyOwners removal

---

lib/internal/crypto/hkdf.js
lib/internal/crypto/pbkdf2.js
test/fixtures/wpt/README.md
test/fixtures/wpt/WebCryptoAPI/cryptokey_algorithm_returns_cached_object.https.any.js
test/fixtures/wpt/WebCryptoAPI/derive_bits_keys/derived_bits_length_testcases.js
test/fixtures/wpt/WebCryptoAPI/derive_bits_keys/hkdf.js
test/fixtures/wpt/WebCryptoAPI/derive_bits_keys/pbkdf2.js
test/fixtures/wpt/versions.json
test/parallel/test-webcrypto-derivebits-hkdf.js
test/pummel/test-webcrypto-derivebits-pbkdf2.js

This PR updates the WPTs and implementation to reflect the upstream spec change from https://github.com/w3c/webcrypto/pull/380
The change is done entirely in javascript so that we don't have to change the underlying c++ code which would also affect its corresponding `node:crypto` methods.

crypto: allow length=0 for HKDF and PBKDF2 in SubtleCrypto.deriveBits

---

tools/v8_gypfiles/v8.gyp

fix https://github.com/nodejs/node/issues/52678

tools: fix riscv64 build failed

---

doc/api/cli.md
doc/api/sqlite.md
doc/node.1
lib/internal/process/pre_execution.js
src/node_options.cc
src/node_options.h
test/parallel/test-sqlite-data-types.js
test/parallel/test-sqlite-database-sync.js
test/parallel/test-sqlite-named-parameters.js
test/parallel/test-sqlite-statement-sync.js
test/parallel/test-sqlite-transactions.js
test/parallel/test-sqlite.js

As requested in #55854...
This commit allows the node:sqlite module to be used without starting Node with a CLI flag. The module is still experimental.
Fixes: https://github.com/nodejs/node/issues/55854

doc,lib,src,test: unflag sqlite module

---

doc/api/test.md

This function does not require a CLI flag, does not emit a warning, and is a fairly simple API that is already being used heavily in the ecosystem. This commit marks `context.plan()` as stable.

test_runner: mark context.plan() as stable

---

doc/contributing/releases.md

Refs: https://github.com/nodejs/node-core-utils/pull/835

doc: include git node release --promote to steps

---

doc/api/cli.md

I missed this when fixing relative paths https://github.com/nodejs/node/pull/50758

doc: fix relative path mention in --allow-fs

---

test/parallel/test-os.js

Follow-up to https://github.com/nodejs/node/pull/55739, making it actually work.
`priority` means `niceness` here, so the comparison should be other way around. 😅
Fixes: https://github.com/NixOS/nixpkgs/issues/355919 (should be applied on top of https://github.com/nodejs/node/pull/55739 until both get into release)
Alternative to: https://github.com/nodejs/node/pull/55863 (/cc @aduh95)

test: fix determining lower priority

---

doc/api/timers.md

The two examples for [Cancelling timers](https://nodejs.org/api/timers.html#cancelling-timers) in the Timers docs are missing their `ESM` counterparts.
This PR adds them.
Best regards :heart_hands: 
Edit: With this change all current `node:timers` examples would have their `ESM` counterparts, there are no more left

doc: add esm examples to `node:timers`

---

deps/sqlite/unofficial.gni

Fix the GN build failure after merging #54181.

build: fix GN build for sqlite

---

CHANGELOG.md

The column for Node.js 23 in `CHANGELOG.md` is missing an opening `<td>` tag so was not correctly rendering.
---
* Before
* After

doc: fix Node.js 23 column in CHANGELOG.md

---

.github/workflows/lint-release-proposal.yml

Currently, it's way too simple to forget about the `PR-URL: TODO` trailer – in fact, it has slipped through in some releases. Another thing that has happened to me is when postponing a release, I would remember to amend the date in the commit message but not in the CHANGELOG.
Let's add some automation that ensure we catch those kind of mistakes early.

tools: add linter for release commit proposals

---

doc/contributing/maintaining/maintaining-dependencies.md

Refs: https://github.com/nodejs/security-wg/issues/1236

doc: document approach for building wasm in deps

---

deps/ncrypto/unofficial.gni
node.gni
unofficial.gni

Allow customizing the path to Node.js crypto in the GN build
For Electron it'd be e.g. `/third_party/boringssl`.

build: use variable for OpenSSL dep path

---

doc/api/zlib.md

This PR add esm example for zlib module

doc: add esm example for zlib

---

.github/workflows/create-release-proposal.yml
tools/actions/create-release.sh

Blocked until the following PR lands
* https://github.com/nodejs/node-core-utils/pull/862
* https://github.com/nodejs/node-core-utils/pull/863
* https://github.com/nodejs/node-core-utils/pull/864
Refs: https://github.com/nodejs/security-wg/issues/860
---
The purpose is to have an action that will generate the release proposal (assuming the vN.x-staging is up to date). After that, I'll create a second action the keep the staging branches up-to-date.

build: add create release proposal action

---

doc/api/assert.md
lib/assert.js
lib/internal/test_runner/test.js
test/parallel/test-assert-objects.js

Fixes: https://github.com/nodejs/node/issues/50399
Took heavy inspiration from https://github.com/nodejs/node/pull/53415 , trying to push it to the finish line 🚀 
On top of it, I took the liberty of:
1. refactor the code a bit
2. wrote more documentation
3. added more tests and restructured old ones
4. implement previously reported comments / suggestions
Co-Authored-By: Cristian Barlutiu

assert: add partialDeepStrictEqual

---

test/parallel/test-fs-readdir-recursive.js

This PR is the result of a code & learn session at NodeConf EU 2024 in Waterford, Ireland.
It was part of a wider initiative to update Node.js tests to make use of the new built-in test apparatus.

test: convert readdir test to use test runner

---

test/parallel/test-http-remove-connection-header-persists-connection.js

Fixes: #47200
This is a more robust alternative to #47316

test: make HTTP/1.0 connection test more robust

---

lib/internal/test_runner/test.js
test/fixtures/test-runner/output/abort_hooks.snapshot
test/fixtures/test-runner/output/global_after_should_fail_the_test.snapshot
test/fixtures/test-runner/output/hooks.snapshot
test/fixtures/test-runner/output/hooks_spec_reporter.snapshot

This commit removes some asynchronous logic from the `runHook()` method and replaces `ArrayPrototypeReduce()` with a `for` loop.

test_runner: simplify hook running logic

---

lib/fs.js
test/parallel/test-fs-readdir-types-symlinks.js

Fixes: https://github.com/nodejs/node/issues/52663

lib: avoid excluding symlinks in recursive fs.readdir with filetypes

---

.github/workflows/coverage-linux-without-intl.yml
.github/workflows/coverage-linux.yml
.github/workflows/coverage-windows.yml

Refs: https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token
I already enabled it in the Codecov settings for the `nodejs` org.

tools: use tokenless Codecov uploads

---

doc/contributing/advocacy-ambasador-program.md

Fixes https://github.com/nodejs/nodejs.org/issues/7201

doc: add vetted courses to the ambassador benefits

---

doc/api/perf_hooks.md

The PR add missing documentation for `PerformanceObserver.prototype.takeRecords()`, which landed in v16.0.0 with `PerformanceObserver.supportedEntryTypes`
confirmed by the [release v16.0.0](https://nodejs.org/zh-cn/blog/release/v16.0.0) and impl PR https://github.com/nodejs/node/pull/37136
see also [mdn documentation](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/takeRecords) and [specification](https://w3c.github.io/performance-timeline/#dom-performanceobserver-takerecords)
Fixes: https://github.com/nodejs/node/issues/55779

doc: add missing documentation for `PerformanceObserver.prototype.takeRecords()`

---

doc/api/deprecations.md

Precursor to #55753
cc @aduh95

doc: deprecate passing invalid types in fs.existsSync

---

src/node_http2.cc
test/parallel/test-h2leak-destroy-session-on-socket-ended.js

Http2Session should always call ondone into JS to detach the handle. In some case, ondone is defered to be called by the StreamListener through WriteWrap, we should be careful of this before getting rid of the StreamListener.
The test case destroys the socket governed by http2. This is not a good practice, but nodejs internal in some case does this too (e.g. when a TCP RESET is received, nodejs internal destroys the socket without bothering it is consumed by a http2 session or not) and it is the simplest code that I can come up with to produce this issue.
I stongly believe that this fixs https://github.com/nodejs/node/issues/42710 based on the issue's description

http2: fix memory leak caused by premature listener removing

---

unofficial.gni

When building Node.js using the GN build, it would fail when cross-compiling, e.g.
```
./tools/gn-gen.py out/Release --target_cpu=arm64
```
becuase `node_arch` was being improperly set to `current_cpu` in every case and thus the startup snapshot wouldn't match:
https://github.com/nodejs/node/blob/eef303028f9f06a6c64c20e5b537fd6db6ac69a7/src/node_snapshotable.cc#L677-L684

build: set `node_arch` to `target_cpu` in GN

---

vcbuild.bat

Visual Studio v17.12 has a bug that produces a compilation error. Since ClangCL is now supported as a compiler for Node.js on Windows, and Clang 18.1.8, provided with VS 17.12, works fine, Only MSVC is disabled.
cc @nodejs/platform-windows @nodejs/build @huseyinacacak-janea 
Refs: https://github.com/nodejs/build/issues/3963
Refs: https://github.com/nodejs/node/pull/53863

build: avoid compiling with VS v17.12

---

src/node_dotenv.cc
test/fixtures/dotenv/no-final-newline-single-quotes.env
test/fixtures/dotenv/no-final-newline.env
test/parallel/test-dotenv-edge-cases.js

Refs: https://github.com/nodejs/node/issues/55925
When _GLIBCXX_ASSERTIONS is enabled, passing npos to remove_prefix triggers an assertion error. Modified to avoid calling remove_prefix when npos is encountered.
```
#0  0x0000ffffa799e020 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x0000ffffa794b140 [PAC] in raise () from /lib64/libc.so.6
#2  0x0000ffffa79359c8 [PAC] in abort () from /lib64/libc.so.6
#3  0x0000ffffa7cc20c8 [PAC] in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () from /lib64/libstdc++.so.6
#4  0x000000000195c634 [PAC] in std::basic_string_view<char, std::char_traits<char> >::remove_prefix (this=0xffffd0a72938, __n=18446744073709551615) at /usr/include/c++/14/string_view:297
#5  0x000000000195b98c [PAC] in …
```

src: safely remove the last line from dotenv

---

.github/workflows/update-wpt.yml

a WPT updater that specifically targets the url subsystem for more controlled and focused updates.

tools: add WPT updater for specific subsystems

---

doc/api/deprecations.md
doc/api/process.md

Resolves: #55537
As per the linked issue.
- `ipv6` and `uv` are unconditionally true, and have been since v0.5.x.
- Not all builds supported ALPN/OCSP/SNI prior to OpenSSL 1.0.2, hence the existence of individual `tls_*` properties. Since v11.0.0, this is no longer the case, and so these properties are now redundant.

process: deprecate `features.{ipv6,uv}` and `features.tls_*`

---

doc/api/cli.md
src/debug_utils.cc
src/debug_utils.h
src/env.cc
src/node.cc
src/node_credentials.cc
src/node_env_var.cc
src/node_internals.h
src/node_options.cc
src/node_options.h
src/path.cc
test/fixtures/process-env/define.js
test/fixtures/process-env/delete.js
test/fixtures/process-env/enumerate.js
test/fixtures/process-env/get.js
test/fixtures/process-env/query.js
test/fixtures/process-env/set.js
test/parallel/test-trace-env-stack.js
test/parallel/test-trace-env.js

This implements --trace-env, --trace-env-js-stack and --trace-env-native-stack CLI options which can be used to find out what environment variables are accessed and where they are accessed.

cli: implement --trace-env and --trace-env-[js|native]-stack

---

doc/api/stream.md

Remove confusing and outdated sentence in `doc/api/stream.md`.
Fixes: https://github.com/nodejs/node/issues/55987

doc: remove confusing and outdated sentence

---

doc/api/deprecations.md

https://github.com/nodejs/node/pull/55545 introduced a duplicate deprecation code and because of it [CI is now failing](https://github.com/nodejs/node/actions/workflows/doc.yml)

doc: fix deprecation codes

---

doc/contributing/gn-build.md

As in title. With my last few commits as well as some i've made upstream to `node-ci`, the GN build now compiles on Windows:
```
NORTHAMERICA+cavohr@CODEBYTERE-WIN-WORK CLANGARM64 ~/Developer/node_gn/node ((95ad75b...))
$ ./out/Release/node.exe
Welcome to Node.js v24.0.0-pre.
Type ".help" for more information.
>
```
This adds some Windows-specific notes to documentation.

doc: improve GN build documentation a bit

---

doc/api/util.md

Refs: https://github.com/nodejs/node/pull/29524
Fixes: https://github.com/nodejs/node/issues/55938

doc: add history entry for textEncoder.encodeInto()

---

doc/api/util.md

Move the history entry for the `TextDecoder` class into the class description itself instead of its constructor.
Refs: https://github.com/nodejs/node/issues/55938

doc: move history entry to class description

---

doc/contributing/releases.md

After a short discussion on the releasers channel, I thought it wouldn't hurt to open this PR to see what the team feels about it.

doc: add FAQ to releases section

---

tools/release.sh

I might be wrong, but I think most releasers use the primary key that's listed in the README, so we can make the script autoselect it by default, reducing the need for the releaser to interact with the script when selecting the key.
/cc @nodejs/releasers

tools: filter release keys to reduce interactivity

---

doc/api/async_context.md

The `node:path` module is referenced in a code snippet that doesn't actually use it.

Remove unused import from sample code

---

lib/internal/util/colors.js

This PR addresses this suggestion:
https://github.com/nodejs/node/pull/55404#discussion_r1807957034
@jasnell

lib: refactor code to improve readability

---

doc/api/sqlite.md

Very cool to see my PR #54181 released!
I noticed that the version added line was missing because I forgot to use `REPLACEME`.
Also I fixed a typo `databsase` -> `database`.

doc: add added tag and fix typo sqlite.md

---

src/util.cc
test/parallel/test-fs-stat.js

Fixed: https://github.com/nodejs/node/issues/55983

src: fix check fd

---

.github/workflows/tools.yml

It makes sense to skip the cron job on forks, but dispatch can only happen after an action from the fork owner.

tools: allow dispatch of `tools.yml` from forks

---

tools/dep_updaters/update-undici.sh

The `build:node` npm script now expects esbuild to be installed and
bin-linked.
Closes: https://github.com/nodejs/node/issues/56061

tools: fix update-undici script

---

deps/sqlite/sqlite3ext.h
tools/dep_updaters/update-sqlite.sh

This is a pre-requirement of https://github.com/nodejs/node/pull/53900, I need this header file to build extension from source code

sqlite: deps include `sqlite3ext.h`

---

doc/api/deprecations.md
lib/zlib.js
test/parallel/test-zlib.js

Since we documentation-only deprecated the usage without `new` qualifier, we can make it runtime deprecated.

zlib: deprecate classes usage without `new`

---

.github/workflows/create-release-proposal.yml

To prevent users from executing the workflow via CLI without passing the desired inputs.

build: remove defaults for create-release-proposal

---

src/node_debug.cc

Avoids copy by calling `ToStringView()`

src: avoid copy on getV8FastApiCallCount

---

src/api/async_resource.cc
src/env-inl.h
src/env.h
src/node.h

Add member to hold the async context frame to `AsyncResource` to avoid the need for the `async_resource_context_frames_` map in `env`.
Semver major because it changes ABI.
Continuation of #54879.
Seems to be a good time now as `AsyncContextFrame` is now default for ALS (see #55552).

src: add async context frame to AsyncResource

---

src/async_wrap.cc
src/async_wrap.h

The silent option for AsyncWrap and AsyncReset is not used anywhere.
Seems like a leftover from times PromiseWrap was used.
Refs: #39135

src: remove dead code in async_wrap

---

lib/dgram.js
test/parallel/test-dgram-createSocket-type.js

```js
const udp = require('dgram');
// uncaughtException event is triggered
process.on('uncaughtException', () => {});
for (let i = 0; i < 10; i++) {
const socket = udp.createSocket({type: 'udp4', recvBufferSize: 'x'});
// error and listening events are not triggered
socket.on('error', () => {
socket.close();
});
socket.on('listening', () => {
socket.close();
});
socket.bind(0);
}
```
The process will open 10 fds.

dgram: check udp buffer size to avoid fd leak

---

src/node_process.h
src/node_process_events.cc

We should use `std::string_view` instead of `const char*` because we need the length for better creating a string in V8.

src: use std::string_view for process emit fns

---

doc/api/net.md
lib/net.js
test/parallel/test-net-server-blocklist.js

Support `blocklist` options for `net.Server`, which can be used for disabling inbound  access to specific IP addresses, IP ranges, or IP subnets.

net: support blocklist for net.Server

---

benchmark/util/text-decoder.js
lib/internal/encoding.js
src/encoding_binding.cc
src/encoding_binding.h
test/cctest/test_encoding_binding.cc

I added a fast path for Latin1 (windows-1252) decoding to improve performance. This change avoids using the slower ICU-based decoding for Latin1 and instead utilizes a direct approach, similar to the fast path implemented for UTF-8.
https://github.com/nodejs/performance/issues/178

util: add fast path for Latin1 decoding

---

doc/contributing/releases.md

After https://github.com/nodejs/node/pull/55690 it's time to suggest it's usage as a replacement of manual steps.

doc: add create-release-action to process

---

src/env.cc
src/env.h

Adds several missing `const` qualifiers and replaces `std::vector` usage with `v8::LocalVector<Value>` for a function used for testing.
FYI: `v8::LocalVector` is recommended to be used by the V8 team when storing them on heap. Ex: https://groups.google.com/g/v8-reviews/c/gM-dP-mASPI?pli=1

src: add missing qualifiers to env.cc

---

configure.py

Refs https://github.com/nodejs/node/commit/6e0a2bb5
Refs https://github.com/electron/electron/pull/44189
The above commit configures the value for `clang` usage at build time which doesn't work in Electron. It depends on the environment where the headers got generated, which doesn't always reflect the platform where the binary was built for us.
This isn't an issue for Node.js since node-gyp will use the result of `process.config` that reflects the environment in which the binary got built.
To fix this, allow overriding clang usage.

build: allow overriding clang usage

---

doc/changelogs/CHANGELOG_V22.md

doc: fix typo

---

lib/internal/crypto/keys.js
test/parallel/test-webcrypto-export-import-cfrg.js
test/parallel/test-webcrypto-export-import-ec.js
test/parallel/test-webcrypto-export-import-rsa.js
test/parallel/test-webcrypto-export-import.js
test/parallel/test-webcrypto-keygen.js

As per [the spec](https://w3c.github.io/webcrypto/#ref-for-concept-cached-object-1:~:text=When%20this%20specification%20refers%20to%20the%20cached%20ECMAScript%20object%20associated%20with%20an%20internal%20slot%20%5B%5Bslot%5D%5D%20of%20object%2C%20the%20user%20agent%20must%20run%20the%20following%20steps%3A) both the `usages` and `algorithm` are "cached", i.e. not new objects every time the getter is invoked.
This fixes the behaviour for `usages` and adds tests for both.

crypto: ensure CryptoKey usages and algorithm are cached objects

---

README.md

doc: add LJHarb to collaborators

---

doc/api/cli.md
test/parallel/test-cli-node-options-docs.js

Superseding https://github.com/nodejs/node/pull/55790

test: ensure `cli.md` is in alphabetical order

---

src/module_wrap.cc
test/es-module/test-require-module-error-catching.js
test/es-module/test-require-module-synchronous-rejection-handling.js
test/fixtures/es-modules/reference-error-esm.js
test/fixtures/es-modules/runtime-error-esm.js
test/fixtures/es-modules/synchronous-rejection-esm.js

Previously the implemention of require(esm) only converted the rejected promise from module evaluation into an error, but the rejected promise was still treated as a pending unhandled rejection by the promise rejection callback, because the promise is created by V8 internals and we don't get a chance to mark it as handled, so the rejection incorrectly marked as unhandled would still go through unhandled rejection handling (if no global listener is set, the default handling would print a warning and make the Node.js instance exit with 1).
This patch fixes it by calling into the JS promise rejection callback to mark the evalaution rejection handled so that it doesn't go through unhandled rejection handling.
Fixes: https://github.com/nodejs/node/issues/56115

module: mark evaluation rejection in require(esm) as handled

---

lib/fs.js
test/fixtures/permission/fs-read.js

Fixes: https://github.com/nodejs/node/issues/56006
cc: @aduh95 @Ethan-Arrowood

lib: fix fs.readdir recursive async

---

.github/workflows/create-release-proposal.yml
tools/actions/create-release.sh

We can remove the permission for the repo to `git push`, and instead use a `createCommitOnBranch` API call to create the release commit, which has the upside of being signed.
I've also use this PR as an opportunity to tidy things up (e.g. we don't need a JENKINS_TOKEN, or to fetch the whole repo)

tools: update `create-release-proposal` workflow

---

doc/contributing/releases.md

Mention that running `./tools/release.sh` script using the recently added `-a` option enables the previously-default interactive interface to select the correct GPG key.

doc: mention tools/release -a option

---

doc/api/errors.md
doc/api/net.md
lib/internal/errors.js
lib/net.js
test/parallel/test-net-blocklist.js

The first PR for https://github.com/nodejs/node/issues/55000

net: support blockList in net.connect

---

test/parallel/parallel.status

The issue is likely the same as other tests that time out.
Refs: https://github.com/nodejs/node/issues/54918
Refs: https://github.com/nodejs/node/pull/54844
Refs: https://github.com/nodejs/node/pull/54802

test: remove test-fs-utimes flaky designation

---

lib/vm.js
test/parallel/test-vm-basic.js

This PR adds a validation step for the options parameter in the compileFunction method within lib/vm.js. 
The validateObject function is used to ensure that options is an object, aligning with the validation approach used in other functions like measureMemory in lib/vm.js.

lib: add validation for options in compileFunction

---

node.gyp
node.gypi
src/quic/session.cc

To our [secondary C++ style guide](https://github.com/nodejs/node/blob/main/doc/contributing/cpp-style-guide.md#guides-and-references):
> Do not use CTAD with a given template unless the template's maintainers have opted into supporting use of CTAD by providing at least one explicit deduction guide (all templates in the std namespace are also presumed to have opted in). This should be enforced with a compiler warning if available.
> 
> Ref: https://google.github.io/styleguide/cppguide.html#CTAD
To use CTAD with a template, it must be defined with at least one deduction guide (`std` templates are defined with guides). Enforcing this rule with compiler checks.

src,build: add no user defined deduction guides of CTAD check

---

doc/api/report.md

It's always a pain to reference a paragraph in a large section where the paragraph is outstanding and important.
Add a section dedicated for the report version so that it can be easily referenced with URL.
Also, added a version history section to trace back the changes.
Refs: https://github.com/nodejs/node/pull/56068

doc: add report version section

---

doc/api/module.md

1. Groups compilation cache APIs together (`flushCompileCache`, `enableCompileCache`, and `getCompileCacheDir`), under a level 2 heading `Module compile cache`. 
1. Fixes that `flushCompileCache` was under the level 2 heading `Source map v3 support`.
2. Make `module.stripTypeScriptTypes` a level 3 heading to be nested under the level 2 heading `The Module object`.

doc: fix module.md headings

---

doc/contributing/releases.md

Updates the location since the file has been moved.

doc: update blog release-post link

---

doc/api/events.md
lib/internal/abort_controller.js
test/parallel/test-eventtarget-memoryleakwarning.js

This change sets the default `kMaxEventTargetListeners` property for `AbortSignal` instances to 0, disabling the check per default, to enable users to write isomorphic library code.
If desirable, the max event target listeners check can still be enabled for individual `AbortSignal` instances by calling `setMaxListeners` on them.
Refs: https://github.com/nodejs/node/issues/54758
I ran all the test I believe are relevant locally, but I can't run the full test suite as I'm working on a managed Mac and can't change firewall rules, so the test suite just explodes on me with popups.

lib: disable default memory leak warning for AbortSignal

---

src/node.cc
test/sequential/test-single-executable-application-snapshot-worker.js

Snapshot main functions are only loaded for main threads in single executable applications. Update the check to avoid asserting it in worker threads - this allows worker threads to be spawned in snapshot main functions bundled into a single executable application.
(Also noticed that worker_threads cannot be loaded in the snapshot builder script, which is to be expected currently since we haven't vetted the worker_threads module for snapshot building. I left a FIXME on how to vet the worker internals and make it loadable in the snapshot builder).
Fixes: https://github.com/nodejs/node/issues/56077

sea: only assert snapshot main function for main threads

---

vcbuild.bat

This reverts commit 542f252d3672f586db07112fe2d844a5d1417e3a.
---
VS 17.12.2 and 17.12.3 work therefore no longer needed to stop build for 17.12.
fyi @nodejs/platform-windows @nodejs/build @StefanStojanovic 
Refs: https://github.com/nodejs/build/issues/3963
Refs: https://github.com/nodejs/node/pull/55930

Revert "build: avoid compiling with VS v17.12"

---

configure.py
tools/v8_gypfiles/features.gypi
tools/v8_gypfiles/v8.gyp

The wasm simd256 revectorization feature is enabled by default when v8_enable_webassembly is true on x64 target in V8. At runtime it will be enabled through flag --experimental-wasm-revectorize.
This PR adds the build configuration in Node to enable this feature and make it explicitly accessible through the same runtime flag for x64 build.

v8,tools: expose experimental wasm revectorize feature

---

lib/internal/abort_controller.js
test/parallel/test-abortsignal-drop-settled-signals.mjs

Refs #55328
Fixes #55328
This PR adds a finalizer to the non-composed signals used in `AbortSignal.any`. With that finalizer, those settled signals can be removed from `gcPersistentSignals`.
This comparison shows that settled signals are being collected.

lib: clean up persisted signals when they are settled

---

.github/workflows/create-release-proposal.yml
tools/actions/create-release.sh

Reopening of https://github.com/nodejs/node/pull/56128
- Open as draft. The releaser should review the PR and mark it as ready.
- Add the "release" label.
- Assign the releaser to the PR so it's clearer who's in charge and they can find it more easily. This will also notify and subscribe them to the PR.

tools: improve release proposal PR opening

---

lib/assert.js
test/parallel/test-assert-objects.js
test/parallel/test-assert-typedarray-deepequal.js

Fixes: https://github.com/nodejs/node/issues/56097
Added handling for ArrayBuffers, SharedArrayBuffers and Int16Arrays , which were not properly considered in the new method `assert.partialDeepStrictEqual` .  
This PR should move the feature one step closer to a stable version

assert: partialDeepStrictEqual now handles comparisons of ArrayBuffers, SharedArrayBuffers and Int16Arrays

---

unofficial.gni

use_gold is not defined on macOS.

build: fix GN build on macOS

---

test/common/index.js
test/parallel/test-https-agent-session-eviction.js
test/parallel/test-tls-alert.js
test/parallel/test-tls-empty-sni-context.js
test/parallel/test-tls-getprotocol.js
test/parallel/test-tls-min-max-version.js
test/parallel/test-tls-psk-circuit.js
test/parallel/test-tls-session-cache.js

In favor of `hasOpenSSL`.
> When I added `hasOpenSSL()` in https://github.com/nodejs/node/pull/53456, the idea was to stop adding new functions for every OpenSSL version to `common`, and instead directly call, e.g.`hasOpenSSL(3, 4)` in the test.
_Originally posted by @richardlau in https://github.com/nodejs/node/pull/56160#discussion_r1874118863_
Let's remove those before the list grows larger.
Refs: https://github.com/nodejs/node/pull/56160/files#r1874118863

test: remove `hasOpenSSL3x` utils

---

tools/actions/create-release.sh

Looking at list of release proposals from before we introduced the automation, we usually used wither the commit title, or the name of the branch, but never the line in the CHANGELOG AFAICT. The difference is that it doesn't contain the GH handle of the releaser (which to me looks weird on a PR title).

tools: use commit title as PR title when creating release proposal

---

doc/api/addons.md

Fixes #56173
Refs: #56173
This PR updates the sample provided at https://nodejs.org/api/addons.html#hello-world so it builds successfully with `node-gyp` [1]. 
[1]: https://v8docs.nodesource.com/node-4.8/d2/db3/classv8_1_1_string.html

doc: fix c++ addon hello world sample

---

tools/v8_gypfiles/v8.gyp

File was removed in https://github.com/nodejs/node/pull/54536

tools: remove has_absl_stringify from gyp file

---

src/node_file.cc
test/parallel/test-fs-readdir-pipe.js

This PR fixes the issue by giving the user the responsibility to add/remove trailing slashes for `fs.readdir`. Examples:
```
> require('fs').readdirSync('\\\\.\\pipe').length
Uncaught Error: ENOTDIR: not a directory, scandir '\\.\pipe'
at Object.readdirSync (node:fs:1503:26) {
errno: -4052,
code: 'ENOTDIR',
syscall: 'scandir',
path: '\\\\.\\pipe'
}
> require('fs').readdirSync('\\\\.\\pipe\\').length
243
```
For additional context, most of the paths are resolved in [resolve()](https://github.com/nodejs/node/blob/61e4ad535281fca6418e1417175253560253deca/lib/path.js#L189) in Node.js. This relies on [normalizeString()](https://github.com/nodejs/node/blob/61e4ad535281fca6418e1417175253560253deca/lib/path.js#L77) which removes the trailing slashes. Since `resolve()` is widely used, any change …

fs,win: fix readdir for named pipe

---

doc/contributing/pull-requests.md

The link to the style guide in [the Code section of pull-requests.md](https://github.com/nodejs/node/blob/main/doc/contributing/pull-requests.md#step-3-code) was incorrectly pointing to the main `README.md` using `../../README.md` instead of `doc/README.md`.
Replaced `../../README.md` with `../../doc/README.md`.
Note that `../../doc/README.md` is equivalent to `../README.md` in this context, but I think the former will be better for readability, emphasizing that this `README.md` is the one under `doc/`.
Refs: #41119

doc: fix incorrect link to style guide

---

doc/api/module.md
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/resolve.js
lib/internal/modules/package_json_reader.js
lib/module.js
test/fixtures/packages/cjs-main-no-index/main.js
test/fixtures/packages/cjs-main-no-index/other.js
test/fixtures/packages/cjs-main-no-index/package.json
test/fixtures/packages/nested/package.json
test/fixtures/packages/nested/sub-pkg-cjs/index.js
test/fixtures/packages/nested/sub-pkg-cjs/package.json
test/fixtures/packages/nested/sub-pkg-esm/index.js
test/fixtures/packages/nested/sub-pkg-esm/package.json
test/fixtures/packages/root-types-field/package.json
test/parallel/test-find-package-json.js
typings/internalBinding/modules.d.ts

PR-URL: https://github.com/nodejs/node/pull/55412
Reviewed-By: Matteo Collina <matteo.collina@gmail.com>
Reviewed-By: Antoine du Hamel <duhamelantoine1995@gmail.com>

[v22.x backport] module: add `findPackageJSON` util

---

doc/api/cli.md
doc/api/process.md
doc/api/report.md
lib/internal/process/report.js
src/env-inl.h
src/env.h
src/node_options.cc
src/node_options.h
src/node_report.cc
src/node_report_module.cc
test/common/report.js
test/report/test-report-writereport-exclude-env.js

PR-URL: https://github.com/nodejs/node/pull/55697
Reviewed-By: James M Snell <jasnell@gmail.com>
Reviewed-By: Richard Lau <rlau@redhat.com>

[v22.x backport] src: add cli option to exclude env vars on dr 

---

Makefile

Backport of https://github.com/nodejs/node/pull/55789.
---
cc @ruyadorno (FWIW https://github.com/nodejs/node/pull/55789 went out in Node.js 23.3.0 so would usually need to wait another week before landing on LTS to satisfy the 2 weeks in current guide.)

[v22.x backport] build: use glob for dependencies of out/Makefile

---

doc/api/cli.md
doc/api/permissions.md
lib/internal/modules/cjs/loader.js
src/node_file.cc
test/fixtures/permission/fs-read.js
test/fixtures/permission/main-module.js
test/fixtures/permission/main-module.mjs
test/fixtures/permission/required-module.js
test/fixtures/permission/required-module.mjs
test/parallel/test-permission-fs-internal-module-stat.js
test/parallel/test-permission-fs-require.js

This improves Permission Model usage when allowing read access to specific modules. To achieve that, the permission model check on internalModuleStat has been removed meaning that on module loading, uv_fs_stat is performed on files and folders even when the permission model is enabled. Although a uv_fs_stat is performed, reading/executing the module will still pass by the permission model check.
Without this PR when an app tries to --allow-fs-read=./a.js --allow-fs-read=./b.js where `a` attempt to load b, it will fails as it reads $pwd and no permission has been given to this path.
PR-URL: https://github.com/nodejs/node/pull/55797
Reviewed-By: Yagiz Nizipli <yagiz@nizipli.com>
Reviewed-By: Ulises Gascón <ulisesgascongonzalez@gmail.com>

[v22.x backport] permission: ignore internalModuleStat on module loading

---

lib/internal/modules/esm/worker.js
test/es-module/test-esm-loader-spawn-promisified.mjs
test/fixtures/es-module-loaders/hooks-custom.mjs

This fix ensures the main thread does not terminate before an ESM worker's `handleMessage` function completes by moving the atomic lock release to the end of the function. As far as I can see, there doesn’t seem to be any necessary processing after the lock release.
The `test-esm-loader-spawn-promisified.mjs` test occasionally fails in debug builds. If processing after the lock release exceeds the stack limit, it results in a fatal error:
```
✖ can predetermine the format in the custom loader resolve hook (162.586375ms)
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ '\n' +
+   '\n' +
+   '#\n' +
+   '# Fatal error in ../../deps/v8/src/api/api.cc, line 5021\n' +
+   '# Debug check failed: !i_isolate->is_execution_terminating().\n' +
... 
``` …

module: prevent main thread exiting before esm worker ends

---

doc/api/esm.md

**Problem**: It is called out that dynamic import is supported in both CJS and ES modules. Nothing is mentioned for leading `import.meta`. This can lead to an incorrect assumption that one can use `import.meta.resolve` to resolve a file path to dynamically import from a CJS module. Using `import.meta` in CJS currently throws an error.
**Solution**: Explicitly call out the environments in which `import.meta` is supported.

doc: call out import.meta is only supported in ES modules

---

lib/internal/util/inspect.js
test/parallel/test-util-inspect.js

Fixes: https://github.com/nodejs/node/issues/55924

util: do not rely on mutable `Object` and `Function`' `constructor` prop

---

lib/internal/http2/core.js
test/parallel/test-http2-alpn.js

Fixes: https://github.com/nodejs/node/issues/55994
Refs: https://github.com/nodejs/node/pull/45190

http2: createSecureServer support ALPNCallback option

---

src/node_worker.cc

If a worker has not already joined before running to completion it will join in a SetImmediateThreadsafe which could occur after the worker has already ended by other means. Mutating a JS object at that point would fail because the isolate is already disposed.
Fixes #56020 (Note that this issue is not reproducible on 22+, but is likely still technically present on later versions as it appears to be a race condition which just happened to be reproducible in the specific conditions described in the issue. The originating code has not been changed in a long time, so it's likely just a very rare condition.)
cc @addaleax I would greatly appreciate a review from you as you're the last person to touch this code...even if it's been many years now. 😅

worker: fix crash when a worker joins after exit

---

node.gni
unofficial.gni

Similar to https://github.com/nodejs/node/pull/55928 - as of https://chromium-review.googlesource.com/c/chromium/src/+/6054817 Chromium includes simdutf and so there's a conflict if both are used. This allows customizing the one Node.js uses so Electron can use Chromium's in Node.js

build: use variable for simdutf path

---

doc/contributing/releases.md

This updates the announce section to match the current process of announcing releases on Node.js. This also mentions the latest Bluesky automation.
cc: @nodejs/releasers @nodejs/social

doc: update announce documentation for releases

---

lib/internal/streams/duplexify.js
test/parallel/test-stream-duplex-from.js

Allow manipulating the generator in Duplex.from()

---

.github/workflows/lint-release-proposal.yml

When the person preparing the release is not the person promoting it, there are more than 1 `@` char and the linter should account for that.
in this case, it's a matter of using `%%` instead of `%` bash parameter expansion. I'm also changing the test syntax to align with how our `.sh` files linter is set even though it's not running on shell script written inside YAML files.

tools: fix release proposal linter to support more than 1 folk preparing

---

doc/api/single-executable-applications.md

`sea.getRawAsset(key)` always returns ArrayBuffer, not string. The return type in the documentation is wrong.
https://github.com/nodejs/node/blob/bd3c25cf31282f101196c0808cbf9267fb3f9bcd/src/node_sea.cc#L600
https://github.com/nodejs/node/blob/bd3c25cf31282f101196c0808cbf9267fb3f9bcd/lib/sea.js#L15-L35
cc @nodejs/single-executable

doc: `sea.getRawAsset(key)` always returns an ArrayBuffer

---

src/node_http2.cc

Original bug was introduced in here: https://github.com/nodejs/node/pull/55155/files#diff-33f026e43570112875cf4c8eab6743496f3aa014329611128e348ec23d6f771cL1303-R1313
Doesn't seem like that it actually leads to any problems, except extra memcpy

fix(node_http2.cc): remove duplicate codeblock

---

doc/api/http.md
lib/_http_client.js
test/parallel/test-http-dont-set-default-headers-with-set-header.js
test/parallel/test-http-dont-set-default-headers-with-setHost.js
test/parallel/test-http-dont-set-default-headers.js

When sending an HTTP request, for some use cases you want _full_ control of the request headers: controlling the raw format directly and setting only the headers provided, with no other headers automatically included whatsoever.
That is not currently possible, because:
* The only way to disable various default headers like Connection & Transfer-Encoding is to call `req.removeHeader` for each of them individually on a request instance, before the headers are sent. Otherwise these are set automatically, even if you pass a raw header array.
* The only way to set raw headers (i.e. passing a header array instead of an object, to directly control order, casing & duplicate handling etc) is by passing them upfront in the `http.request()` method, and when you do so the headers are passed to …

http: add setDefaultHeaders option to http.request

---

doc/api/sqlite.md
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-custom-functions.js

This commit adds support to node:sqlite for defining custom functions that can be invoked from SQL.
Fixes: https://github.com/nodejs/node/issues/54349

sqlite: add support for custom functions

---

test/parallel/test-abortsignal-drop-settled-signals.mjs

test: fix test-abortsignal-drop-settled-signals flakiness

---

doc/api/perf_hooks.md

This PR adds the `ESM` counterparts of the `CJS` examples for [the Performance measurement APIs documentation](https://nodejs.org/api/perf_hooks.html).
There is one particular example in which I'd like to get a more in depth feedback, it's the [`Measuring how long it takes to load dependencies`](https://nodejs.org/api/perf_hooks.html#measuring-how-long-it-takes-to-load-dependencies) example.
I've done it this way:
```js
import { performance, PerformanceObserver } from 'node:perf_hooks';
// Activate the observer
const obs = new PerformanceObserver((list) => {
const entries = list.getEntries();
entries.forEach((entry) => {
console.log(`import('${entry[0]}')`, entry.duration);
});
performance.clearMarks();
performance.clearMeasures();
obs.disconnect();
});
obs.observe({ entryTypes: …
```

doc: add esm examples to `node:perf_hooks`

---

test/sequential/sequential.status

The referenced issue is closed as having been
fixed, so the tests should run ok. Unexclude them.

test: remove exludes for sea tests on PPC

---

doc/api/report.md
src/node_report.cc
test/common/report.js

Replace typos "kbytes" with "bytes" in `PrintSystemInformation()` in `src/node_report.cc` for `"data_seg_size_kbytes"`, `"max_memory_size_kbytes"` and `"virtual_memory_kbytes"`, as `RLIMIT_DATA`, `RLIMIT_RSS` and `RLIMIT_AS` from `<sys/resource.h>` are given in bytes. ([ref](https://www.ibm.com/docs/en/aix/7.3?topic=k-kgetrlimit64-kernel-service))
I found this problem when I was testing the limit of virtual memory. When I set it to 32GB, the report showed
```
"virtual_memory_kbytes": {
"soft": 34359738368,
"hard": 34359738368
}
```
After checking the source codes, I think that it should be in `bytes`, not `kbytes`.
Refs: https://www.ibm.com/docs/en/aix/7.3?topic=k-kgetrlimit64-kernel-service
**The keys with `*_kbytes` are replaced by `*_bytes`, and the report version is bumped from 4 to …

report: fix typos in memory limit units

---

src/js_native_api_v8.cc
test/js-native-api/6_object_wrap/6_object_wrap.cc
test/js-native-api/6_object_wrap/binding.gyp
test/js-native-api/6_object_wrap/myobject.h
test/js-native-api/6_object_wrap/test-basic-finalizer.js

`napi_delete_reference` must be called immediately for a
`napi_reference` returned from `napi_wrap` in the corresponding
finalizer, in order to clean up the `napi_reference` timely.
`napi_delete_reference` is safe to be invoked during GC.

node-api: allow napi_delete_reference in basic finalizers

---

doc/api/tls.md

This PR adds the missing `ESM` counterparts of the `CJS` examples for [the TLS (SSL) documentation](https://nodejs.org/api/tls.html).
While I normally try not to touch the current `CJS` examples, this time I went ahead and destructured the (`require`)  imports following a feedback I had received in [a previous PR](https://github.com/nodejs/node/pull/55335) so that examples from both `CJS` and `ESM` are as similar as possible so new users don't get confused.
I've also taken the liberty to add a snippet to explain how to generate the necessary files for both [the client](https://nodejs.org/api/tls.html#tlsconnectoptions-callback) and [the echo server](https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener) examples similar to what I had done for the …

doc: add esm examples to `node:tls`

---

.github/workflows/create-release-proposal.yml

This will put the GH handle of the user who started the workflow in the CHANGELOG, rather than the bot handle.
N.B.: The release commit itself will still be attributed to the bot, but we established that release commit authorship does not matter for the release, only release tag does. Releasers can either keep the bot as the author, or overwrite it, up to them.

tools: use `github.actor` instead of bot username for release proposals

---

doc/api/module.md
doc/api/modules.md
lib/internal/bootstrap/realm.js
lib/internal/modules/cjs/loader.js
lib/repl.js
test/parallel/test-internal-module-require.js
test/parallel/test-process-get-builtin.mjs
test/parallel/test-repl-tab-complete-import.js
test/parallel/test-repl-tab-complete.js
test/parallel/test-require-resolve.js

Fixes: https://github.com/nodejs/node/issues/42785
I haven't added tests yet; I wanted to get some feedback first.

module: add prefix-only modules to `module.builtinModules`

---

doc/contributing/technical-priorities.md

Replaced 'which' with 'that' and added comma for clarity.

doc: fix 'which' to 'that' and added comma

---

src/encoding_binding.cc
test/cctest/test_encoding_binding.cc
test/parallel/test-util-text-decoder.js

returned a string instead of a buffer
Fixes: https://github.com/nodejs/node/issues/56219

util: fix Latin1 decoding to return string output

---

doc/api/readline.md

This PR adds the missing `ESM` counterparts of the `CJS` examples for [the Readline documentation](https://nodejs.org/api/readline.html).
Best regards!

doc: add esm examples to `node:readline`

---

doc/api/repl.md

This PR adds the ESM counterparts of the CJS examples for [the REPL documentation](https://nodejs.org/api/repl.html).
Best regards!

doc: add esm examples to `node:repl`

---

doc/api/dgram.md
lib/dgram.js
test/parallel/test-dgram-blocklist.js

dgram: support blocklist in udp

---

doc/api/buffer.md

`Buffer.concat` will zero-fill the tail of the destination buffer. This behavior is specified in `test/parallel/test-buffer-concat.js` but it is not yet documented in `doc/api/buffer.md`. This pull request updates the docs.
The zero-fill behavior is already implemented here.
https://github.com/duncpro/node/blob/6e59723fbf380950fa901fd33326a00346ead607/lib/buffer.js#L607-L616
There is already a test for it here.
https://github.com/duncpro/node/blob/6e59723fbf380950fa901fd33326a00346ead607/test/parallel/test-buffer-concat.js#L91-L93

Document `Buffer.concat` zero-fill behavior

---

doc/api/util.md

fixes: #55340 
This PR Highlights both the clarification of the `resource` parameter and the added context around memory management.

doc: clarify util.aborted `resource` parameter usage

---

common.gypi
deps/v8/include/v8config.h

When compiling with ClangCL, it's causing linker errors with node.lib in node-gyp and potentially breaks other 3rd party tools.
This was already reviewed in another PR where it was grouped with other changes. Here is the part of the description from that PR regarding this change:
_Disable V8_PRESERVE_MOST on Windows. We already have something similar for V8_NODISCARD as a floating patch, so it should not be a problem as I see it. If left, this results in functions that use it having `__swift_2` calling conventions rather than the expected `__cdecl`. This was noticed in `cppgc-object` native suites test. This change, if agreed upon, would be come one of our V8 floating patches we use on each V8 update._
Refs: https://github.com/nodejs/node/pull/55784

deps: define V8_PRESERVE_MOST as no-op on Windows

---

lib/buffer.js
lib/internal/util/inspect.js
test/parallel/test-util-inspect.js

For an arbitrary list of classes, we can protect against userland mutation of the `constructor` prototype property, and speed up the `inspect` call by avoiding a `ObjectGetOwnPropertyDescriptor` call. I tried to come up with a list of classes that are the most likely to be often inspected, though I haven't used any rigorous method, I just came up with it, and I'm certainly open to add/remove some.
Refs: https://github.com/nodejs/node/pull/56188#discussion_r1876800640

util: harden more built-in classes against prototype pollution

---

.github/workflows/major-release.yml

This action reminds collaborators of the upcoming
major release date. In the future, this action can
also update and create the branches (that's why the
action name is generic).
Refs: https://github.com/nodejs/node/pull/55732

build: add major release action

---

doc/api/cli.md
doc/api/test.md
lib/internal/fs/glob.js
lib/internal/test_runner/coverage.js
lib/internal/test_runner/utils.js
lib/path.js
test/fixtures/test-runner/coverage-default-exclusion/file-test.js
test/fixtures/test-runner/coverage-default-exclusion/file.test.mjs
test/fixtures/test-runner/coverage-default-exclusion/file.test.ts
test/fixtures/test-runner/coverage-default-exclusion/logic-file.js
test/fixtures/test-runner/coverage-default-exclusion/test.cjs
test/fixtures/test-runner/coverage-default-exclusion/test/not-matching-test-name.js
test/fixtures/test-runner/output/lcov_reporter.js
test/parallel/test-runner-coverage-default-exclusion.mjs
test/parallel/test-runner-coverage-source-map.js
test/parallel/test-runner-coverage-thresholds.js
test/parallel/test-runner-coverage.js
test/parallel/test-runner-output.mjs

This should address #53508.
I'm opening this PR since #55633 seems to be stale.
This PR contains the feature and some changes to reduce its footprint.
Note: The reason behind `lazyMinimatch` is to avoid experimental warnings related to `matchesGlob`.
I'm not entirely convinced about the change I introduced to the `--test-coverage-exclude` and `--test-coverage-include` flags.
Regarding: 
@cjihrig 
https://github.com/nodejs/node/pull/55633#pullrequestreview-2410163982
> Another thing that is not clear to me: what happens if someone runs a test file, but that test file imports another file that also includes tests? Should we exclude that imported file from the coverage report, or should we only exclude the files that the user specified?
I think we should just exclude the files specified by …

test_runner: exclude test files from coverage by default

---

test/parallel/parallel.status

The issue is likely the same as other tests that time out.
Refs: https://github.com/nodejs/node/issues/54918
Refs: https://github.com/nodejs/node/pull/54802

test: remove test-sqlite-statement-sync flaky designation

---

doc/api/sqlite.md
src/node_sqlite.cc
test/parallel/test-sqlite-session.js
test/parallel/test-sqlite.js
typings/internalBinding/constants.d.ts

sqlite: aggregate constants in a single property

---

tools/v8_gypfiles/d8.gyp

build: fix missing fp16 dependency in d8 builds

---

Makefile

- https://github.com/nodejs/unofficial-builds/pull/157
When running on `loongarch64`, `DESTCPU` in the `Makefile` does not seem to be set correctly, so I get the following error when building the openssl `make -j8 binary `
```bash
make -j8 binary V= VARIATION=musl DISTTYPE=release CUSTOMTAG= DATESTRING= COMMIT= RELEASE_URLBASE=https://unofficial-builds.nodejs.org/download/release/ CONFIG_FLAGS=--openssl-no-asm
/bin/sh: git: not found
rm -f -r node-v23.3.0-linux-x86-musl
rm -f -r out/deps out/Release
python3 ./configure \
--prefix=/ \
--dest-cpu=x86 \
--tag= \
--release-urlbase=https://unofficial-builds.nodejs.org/download/release/ \
--openssl-no-asm --download=all --with-intl=full-icu
Node.js configure: Found Python 3.12.8...
WARNING: --openssl-no-asm will result in binaries that do not …
```

build: set DESTCPU correctly for 'make binary' on loongarch64

---

doc/api_assets/hljs.css

Attributes are being highlighted as #f00 on a background of #f2f2f2 in light mode. That's a color contrast of 3.98:1, failing to meet the 4.5:1 requirement of WCAG 2.1 AA. This changes the attribute color to #d00, which has a color contrast of 5.09:1 meeting the 4.5:1 requirement.
By the way, I'm not sure if we document it anywhere, but it would probably be useful to document that we strive for WCAG 2.1 AA compliance (and not AAA compliance which might not even be possible, or some other WCAG version compliance). 
Before:
After:

doc: fix color contrast issue in light mode

---

tools/v8_gypfiles/v8.gyp

V8 should be built with -fvisibility=hidden, otherwise the resulting binary would contain unnecessary symbols. In particular, on macOS, this leads to 5000+ weak symbols resolved at runtime, leading to a startup regression.
On macOS this also reduces the binary size about ~10MB.  On Linux the size reduction is around 8MB.
```
$ DYLD_PRINT_BINDINGS=1 ./node-c4aa34aa --version 2>&1 | grep "looking for weak-def symbol" | wc -l
7317
$ DYLD_PRINT_BINDINGS=1 out/Release/node --version 2>&1 | grep "looking for weak-def symbol" | wc -l
1755
$ hyperfine "./node-c4aa34aa --version" "out/Release/node --version" --warmup 10
Benchmark 1: ./node-c4aa34aa --version
Time (mean ± σ):      28.9 ms ±   1.0 ms    [User: 26.5 ms, System: 1.9 ms]
Range (min … max):    28.1 ms …  32.2 ms    89 runs
Benchmark 2: …
```

build: build v8 with -fvisibility=hidden on macOS

---

doc/api/module.md

Let's use the auto-link that the rest of the docs are using so it's consistent.

doc: fix links in `module.md`

---

lib/internal/streams/readable.js
test/parallel/test-stream-pipe-objectmode-to-non-objectmode.js

Fixes: https://github.com/nodejs/node/issues/54945
Wanted to give a quick mention why [checking object modes at the start of the pipe function](https://github.com/nodejs/node/issues/54945#issuecomment-2351385474) wouldn't work (even though I liked the idea). Because if the chunk from the source stream is not object while source stream is in object mode and destination stream is not in object mode, it should still work.
Consider the following example:
```js
const { Readable, Writable } = require("node:stream");
const write = new Writable({
write(data, enc, cb) {
// do something with the data
cb();
},
});
write.on("error", (err) => {
console.log(err);
});
Readable.from("hello hello").pipe(write);
```

stream: catch and forward error from dest.write

---

test/parallel/test-esm-loader-hooks-inspect-brk.js

Refs: https://github.com/nodejs/node/pull/54827
Refs: https://github.com/nodejs/node/pull/51560

test: deflake test-esm-loader-hooks-inspect-brk

---

benchmark/fixtures/simple-error-stack.js
benchmark/fixtures/simple-error-stack.ts
lib/internal/source_map/prepare_stack_trace.js
lib/internal/source_map/source_map_cache.js
test/parallel/test-runner-source-maps-invalid-json.js

When the source map data are invalid json strings, skip construct
SourceMap on it. Additionally, suppress exceptions on source map lookups
and fix test runners crash on invalid source maps.
Only invalidates source map lookup cache when a new source map is found.
This improves when user codes interleave with builtin functions, like
`array.map`.
```
es/error-stack.js n=100000 method='sourcemap'                ***     78.04 %       ±1.27% ±1.70% ±2.24%
es/error-stack.js n=100000 method='without-sourcemap'                 0.27 %       ±1.09% ±1.45% ±1.89%
```
Refs: https://github.com/nodejs/node/issues/56296

lib: suppress source map lookup exceptions

---

doc/api/cli.md
doc/node.1
lib/internal/test_runner/utils.js
src/node_options.cc
test/parallel/test-runner-cli-concurrency.js
test/parallel/test-runner-cli-timeout.js
test/parallel/test-runner-cli.js
test/parallel/test-runner-coverage.js
test/parallel/test-runner-extraneous-async-activity.js
test/parallel/test-runner-force-exit-failure.js
test/parallel/test-runner-no-isolation-filtering.js
test/parallel/test-runner-no-isolation-hooks.mjs
test/parallel/test-runner-snapshot-tests.js
test/parallel/test-runner-watch-mode.mjs

This commit stabilizes test isolation configuration in the test runner.

test_runner,cli: mark test isolation as stable

---

test/async-hooks/async-hooks.status

The issue is the same as other tests that time out.
Refs: https://github.com/nodejs/node/issues/54918
Refs: https://github.com/nodejs/node/pull/54802

test: remove async-hooks/test-writewrap flaky designation

---

lib/internal/webstreams/writablestream.js

No test was added since it was covered by existing WPT, and the spec change did not introduce WPT updates
Fixes: https://github.com/nodejs/node/issues/56014
Refs: https://github.com/whatwg/streams/pull/1333

stream: validate undefined sizeAlgorithm in WritableStream

---

doc/api/cli.md
doc/api/esm.md
doc/api/module.md
doc/node.1
lib/internal/modules/esm/formats.js
lib/internal/modules/esm/load.js
lib/internal/modules/esm/translators.js
src/node_options.cc
src/node_options.h
test/addons/.gitignore
test/addons/esm/binding-export-default.cc
test/addons/esm/binding-export-primitive.cc
test/addons/esm/binding.cc
test/addons/esm/binding.gyp
test/addons/esm/node_modules/esm-package/package.json
test/addons/esm/test-esm.mjs
test/addons/esm/test-import-package.js
test/addons/esm/test-import.js
test/addons/esm/test-require-package.js
test/addons/esm/test-require.js

Add experimental support to loading `.node` extension modules in ESM.
An addon exports two names `default` and `module.exports`, as same as `import(cjs)` where
its export names can not be preparsed. Addon export names can not be inferred until it is evaluated.
Fixes: https://github.com/nodejs/node/issues/40541
Fixes: https://github.com/nodejs/node/issues/55821

esm: add experimental support for addon modules

---

src/node_api.h

This PR targets to addresses the issue #56153 by removing the `[[deprecated]]` attribute from the `napi_module_register` function.
The code described in the issue does not use the `napi_module_register`  function as it was intended from a module shared library. Instead, it uses it to register modules for embedding scenarios. While it was never the intended use, we currently do not have a better approach to register modules before `Environment` is created until we complete the new embedding API  - PR #54660. 
We discussed the issue in the Node-API meeting on Dec 6th 2024, and decided that the quickest and the least intrusive way to address it is to remove the `[[deprecated]]` attribute from the `napi_module_register` function for now.

node-api: remove deprecated attribute from napi_module_register

---

.github/workflows/test-macos.yml

We are in the process of updating macOS to version 13 in the
Jenkins CI, but unfortunately this is taking longer than expected.
Add it to the GitHub actions test matrix so that we have some coverage.
Refs: https://github.com/nodejs/build/issues/3686

build: test macos-13 on GitHub actions

---

lib/eslint.config_partial.mjs
lib/internal/modules/typescript.js
test/parallel/test-module-strip-types.js

`btoa` only supports latin-1 charset and produces invalid source mapping urls.
This also forbids usage of `btoa` in `lib/` without particular reasons.
Refs: https://github.com/nodejs/node/issues/56296

module: use buffer.toString base64

---

doc/changelogs/CHANGELOG_V22.md
doc/changelogs/CHANGELOG_V23.md

Add note to 23.3.0 changelog. 
Some distributors were wondering why they started to get link errors. https://github.com/nodejs/node/pull/54181#issuecomment-2555519459
Even though dynamically linking when with dependencies, those dependencies are the responsibility of distributors (as per a note in `BUILDING.md`), it's good to give people a heads-up.

doc: add entry to changelog about SQLite Session Extension

---

test/es-module/test-typescript.mjs
test/fixtures/typescript/ts/hook.ts
test/fixtures/typescript/ts/test-loader.ts
test/fixtures/typescript/ts/test-simple.js

Refs: https://github.com/nodejs/node/issues/54645

test: check typescript loader

---

doc/api/cli.md
lib/internal/main/eval_string.js
lib/internal/modules/cjs/loader.js
lib/internal/modules/esm/loader.js
lib/internal/modules/esm/translators.js
lib/internal/modules/typescript.js
lib/internal/process/execution.js
src/node_options.cc
test/es-module/test-typescript-eval.mjs
test/fixtures/eval/eval_messages.snapshot

Refs: https://github.com/nodejs/typescript/issues/17
Previous attempt: https://github.com/nodejs/node/pull/56273
What is the problem?
Before this PR when `--experimental-strip-types` was enabled, `--eval` would always parse the input as typescript.
If unflagged, the typescript parser would throw different errors on invalid syntax so unflagging would become a breaking change.
With this PR when running `--eval` and `--experimental-strip-types` is enabled, if parsing the code fails we try again with typescript parser.
If it fails again we throw the original error, adding the typescript parser message.
In this way the error is the original error and it's not a breaking change.
Example:
```
With `--experimental-strip-types`:
marcoippolito@marcos-MBP node % ./node --experimental-strip-types -e …
```

module: support eval with ts syntax detection

---

test/sqlite/test-sqlite-extensions.mjs

Refs: https://github.com/nodejs/node/pull/53900#discussion_r1894702821
The `libsqlite_extension` binary won't be found in the same directory as `node` when we build with `--shared-sqlite`.

test: skip `test-sqlinte-extension` when SQLite is not built by us

---

doc/api/zlib.md

In this PR I'm adjusing the documentation of zlib. The crc32 is not a method of ZlibBase. It is a standalone function of the module.
Mentioned in [55800](https://github.com/nodejs/node/issues/55800)
@RedYetiDev @ErickWendel @aduh95

doc: fixing the crc32 function on documentation

---

src/permission/fs_permission.cc

Use `starts_with` from C++20 instead of `substr` in  fs_permission.cc

src: use starts_with in fs_permission.cc

---

BUILDING.md

This is just documenting the current state, not changing it.
Refs:
- https://ci-release.nodejs.org/job/iojs+release/10689/nodes=osx13-x64-release-tar/consoleFull
Apple clang version 16.0.0 (clang-1600.0.26.3)
- https://ci-release.nodejs.org/job/iojs+release/10689/nodes=osx13-arm64-release-tar/consoleFull
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

doc: update macOS and Xcode versions for releases

---

test/parallel/test-watch-file-shared-dependency.mjs

Delay dependency file modification on macOS.
Refs: https://github.com/nodejs/node/pull/51842

test: deflake test-watch-file-shared-dependency

---

SECURITY.md

This clarifies that WASM is trusted, too.

docs: clarify that WASM is trusted

---

SECURITY.md

The Microsoft style guide says:
> Use a numbered list for sequential items (like a procedure) or prioritized items (like a top 10 list).
> Use a bulleted list for things that have something in common but don’t need to appear in a particular order.
It seems to me those lists fit much better the latter, and therefor should be bulleted (i.e. `<ul>`).
If I'm wrong and those lists indicates a prioritization, we should make it explicit.

doc: use `<ul>` instead of `<ol>` in `SECURITY.md`

---

lib/internal/url.js

Only matters if the CWD is a UNC path, which is hard to write a test for.
Fixes: https://github.com/nodejs/node/issues/56262

url: use resolved path to convert to `fileURL`

---

test/es-module/test-typescript.mjs

This should finally work 🥳 
@nodejs/typescript

test: enable ts test on win arm64

---

test/parallel/test-abortsignal-drop-settled-signals.mjs

Refs #56190
This PR does two things in the specific `test` case that is flaky:
- Make the `composedSignal` a weak ref so the test won't hold any reference that could keep that variable from being GCed.
- Add `gcUntil` so it will make more calls to `global.gc`. Precisely, until that condition is reached or a maximum number of attempts is hit.

test: improve abort signal dropping test

---

doc/api/util.md

Per https://github.com/nodejs/node/issues/53427#issuecomment-2294885963.

doc: expand description of `parseArg`'s `default`

---

test/parallel/parallel.status

The original issue is likely the same as other tests that time out.
Refs: https://github.com/nodejs/node/issues/54918
Refs: https://github.com/nodejs/node/commit/84c2e712ebcd0f32dc0e
RefS: https://github.com/nodejs/node/pull/52959

test: remove test-net-write-fully-async-hex-string flaky designation

---

test/parallel/parallel.status

Refs: https://github.com/nodejs/node/pull/56053

test: remove test-worker-arraybuffer-zerofill flaky designation

---

doc/api/sqlite.md
src/env_properties.h
src/node_sqlite.cc
test/parallel/test-sqlite-session.js

Resolves #56210 by allowing to pass a conflict resolution handler that returns a conflict resolution type instead of just a conflict resolution type.
As @Renegade334 points out in that issue, it does not make sense to pass `SQLITE_CHANGESET_REPLACE` because this conflict resolution type is only valid for certain conflict types. Therefore an API where the conflict-resolution handler receives the conflict type makes sense, so the user can return a valid conflict resolution type for a particular conflict type.
An API where an individual (conflicting) change can be inspected ([as is possible with the SQLite C conflict handler](https://www.sqlite.org/session/sqlite3changeset_apply.html)) would be a good follow-up. This would then be added as a second argument to the conflict handler.
Note that …

sqlite: allow passing conflict resolution handler function

---

doc/api/typescript.md
lib/internal/main/eval_stdin.js
test/fixtures/eval/stdin_messages.snapshot
test/fixtures/eval/stdin_typescript.js
test/fixtures/eval/stdin_typescript.snapshot
test/parallel/test-node-output-eval.mjs

After `--eval` we can add in the same way support for STDIN

lib: add typescript support to STDIN eval

---

doc/api/module.md
lib/internal/modules/esm/hooks.js
lib/internal/modules/package_json_reader.js
test/parallel/test-find-package-json.js

Resolves https://github.com/nodejs/node/pull/55822 (that merely sweeps the problem under the rug).

module: fix async resolution error within the sync `findPackageJSON`

---

doc/api/n-api.md
doc/contributing/releases-node-api.md
src/js_native_api.h
src/js_native_api_v8.cc
src/js_native_api_v8.h
src/node_api.cc
src/node_api.h
src/node_version.h
test/js-native-api/test_cannot_run_js/binding.gyp
test/js-native-api/test_cannot_run_js/test_cannot_run_js.c
test/js-native-api/test_general/test.js
test/js-native-api/test_string/binding.gyp
test/node-api/test_buffer/binding.gyp
test/node-api/test_reference_by_node_api_version/binding.gyp

Notable runtime changes to existing APIs:
- returning `node_api_cannot_run_js` instead of `napi_pending_exception`.
- allow creating references to objects, functions, and symbols.

node-api: define version 10

---

doc/api/webstreams.md

When piping a `ReadableStream` created from an `Iterable` into a `WritableStream`, the sequence of objects in the `Iterable` must consist of either `Buffer`s, `TypedArray`s, or `DataView`s.
Re: https://github.com/nodejs/node/issues/56297

doc: add example for piping ReadableStream

---

lib/internal/main/worker_thread.js
test/parallel/test-worker-eval-typescript.js

worker: add eval ts input

---

.github/dependabot.yml

This way, we can disable all dependabot PRs from private forks – I'm fed up with the flow of useless notifications coming from our nodejs-private org.

tools: use a configurable value for number of open Dependabot PRs

---

pyproject.toml

Removing PLC1901 and RUF100 from the list of Python lint rules to ignore does not result in any errors. Keeping the ignore list as short as possible seems like a good idea, so this change removes them from the ignore list.

tools: disable unneeded rule ignoring in Python linting

---

test/parallel/test-child-process-windows-hide.js

This commit updates test/parallel/test-child-process-windows-hide.js to use node:test. This allows the test to use the built in mocking functionality instead of managing spies manually. It also prevents multiple child processes from being spawned in parallel, which can be problematic in the CI.

test: update test-child-process-windows-hide to use node:test

---

doc/api/test.md
lib/internal/test_runner/assert.js
lib/internal/test_runner/test.js
lib/test.js
test/parallel/test-runner-custom-assertions.js

This commit adds a top level `assert.register()` API to the test runner. This function allows users to define their own custom assertion functions on the TestContext.
Fixes: https://github.com/nodejs/node/issues/52033

test_runner: add assert.register() API

---

test/parallel/test-set-http-max-http-headers.js

This commit updates test/parallel/test-set-http-max-http-headers.js to use node:test. This test already implemented a test runner, so it makes sense to use the existing public API.

test: update test-set-http-max-http-headers to use node:test

---

deps/sqlite/sqlite.gyp
deps/sqlite/unofficial.gni
test/parallel/test-sqlite.js

This commit enables SQLite math functions.
Fixes: https://github.com/nodejs/node/issues/56435

sqlite: enable SQL math functions

---

doc/api/sqlite.md
src/node_sqlite.cc
test/parallel/test-sqlite-typed-array-and-data-view.js

Fixes: https://github.com/nodejs/node/issues/56384

sqlite: support TypedArray and DataView in `StatementSync`

---

lib/internal/bootstrap/switches/is_not_main_thread.js
lib/internal/worker/io.js
test/parallel/test-worker-stdio-flush-inflight.js
test/parallel/test-worker-stdio-flush.js

This fix an old problem I had since forever when using worker threads, stdout log lines being cut if the thread exited. This PR fixes it by bypassing backpressure if the thread is exiting.

worker: flush stdout and stderr on exit

---

src/node_snapshotable.cc

Drain the loop and platform tasks before creating a snapshot. This is
necessary to ensure that the no roots are held by the the platform
tasks, which may reference objects associated with a context. For
example, a WeakRef may schedule an per-isolate platform task as a GC
root, and referencing an object in a context, causing an assertion in
the snapshot creator that objects must be serialized with a context.
Refs: https://github.com/nodejs/node/pull/56292

src: drain platform tasks before taking startup snapshot

---

tools/v8_gypfiles/v8.gyp

Fix LoongArch64 build error
https://github.com/nodejs/unofficial-builds/issues/154
https://github.com/nodejs/node/issues/56280

tools: fix loong64 build failed

---

src/node_snapshotable.cc

Otherwise it can crash DCHECK when V8 expects that at least someone is locking the current thread.
Fixes: https://github.com/nodejs/node-v8/issues/294

src: lock the thread properly in snapshot builder

---

src/cares_wrap.cc

src: make some minor ToLocalChecked cleanups

---

lib/assert.js
lib/internal/assert/assertion_error.js
lib/internal/assert/myers_diff.js
test/parallel/test-assert.js
test/pseudo-tty/test-assert-colors.js
test/pseudo-tty/test-assert-no-color.js

following the same reasoning as [this PR](https://github.com/nodejs/node/pull/54759):
right now the method `assert.partialDeepStrictEqual` does not show the diff when the assertion fails.  
With this PR we go from this:
```js
const assert = require('assert');
assert.partialDeepStrictEqual([1, 2, 3, 5], [4, 5]);
```
to this
with a custom error message:
Relevant changes:
1. enabled the diff when `assert.partialDeepStrictEqual` fails
2. enabled the diff when `assert.partialDeepStrictEqual` fails with a custom error message
3. added different diff style in case `assert.partialDeepStrictEqual` fails:
- properties available in `actual` are gray
- properties in `expected` but not in `actual` are prefixed with the classic red `-`
- properties present in both `actual` and `expected` are white

assert: show diff when doing partial comparisons with a custom message

---

lib/internal/inspector/network.js
lib/internal/inspector/network_http.js
lib/internal/inspector/network_undici.js
lib/internal/inspector_network_tracking.js
src/node_builtins.cc
test/parallel/test-inspector-network-fetch.js

Add basic undici http tracking support via inspector protocol. This
allows tracking `fetch` calls with an inspector.
Refs: https://github.com/nodejs/node/issues/53946

inspector: add undici http tracking support

---

doc/contributing/collaborator-guide.md

I might be missing some context on why we’re not doing that, but IMO it would make perfect sense for semver-major PRs, as it’s basically the only time where TSC voting members reviews have a different weight. Requesting a review from the team would allow GH UI to highlight those reviews (useful for newcomers who are less likely to have all the TSC members handles in mind). It would require us to give the `@nodejs/TSC` team Triage role on the repo, which should not change anything as TSC voting members are already collaborators (which have Write role on the repo).
EDIT: from my understanding of https://github.com/nodejs/node/pull/22759, it seems the rule was put in place because of the lack of support for filtering/filtering out notifications coming from team reviews, which was problematic …

doc: allow request for TSC reviews via the GitHub UI

---

doc/api/fs.md
lib/internal/fs/glob.js
test/parallel/test-fs-glob.mjs

This patch extends the `exclude` option in glob functions (`fs.glob`, `fs.globSync`, and `fsPromises.glob`) to support glob patterns.
Resolves #56254

fs: allow `exclude` option in globs to accept glob patterns

---

src/node_errors.cc
test/fixtures/errors/throw_in_eval_anonymous.js
test/fixtures/errors/throw_in_eval_anonymous.snapshot
test/fixtures/errors/throw_in_eval_named.js
test/fixtures/errors/throw_in_eval_named.snapshot
test/parallel/test-node-output-errors.mjs

If an error is not caught, the file name and source code line where the error was thrown is printed. However, for unnamed eval scripts, a placeholder instead of `undefined` should be print:
```
undefined:3
throw new Error('error in unnamed script');
^
Error: error in unnamed script
at eval (eval at <anonymous> (/dev/nodejs/node/test/fixtures/errors/throw_in_eval_unnamed.js:5:1), <anonymous>:3:9)
```
This PR prints a placeholder `<anonymous_script>` for such errors:
```
<anonymous_script>:3
throw new Error('error in anonymous script');
```

src: fix undefined script name in error source

---

lib/assert.js
test/parallel/test-assert-objects.js
test/parallel/test-assert-typedarray-deepequal.js

this PR should close the gap between `assert.deepStrictEqual` and `assert.partialDeepStrictEqual` even more.
Found a couple more cases that were not properly working:
- URLs were not properly compared
- it was not passing when comparing `Object.getPrototypeOf(File.prototype)` and `Blob.prototype`
- `new Float32Array([+0.0])` and `new Float32Array([-0.0])` were considered equal, which is not the case

assert: make partialDeepStrictEqual work with urls and File prototypes

---

doc/api/test.md
lib/internal/test_runner/snapshot.js
lib/internal/test_runner/test.js
test/fixtures/test-runner/snapshots/file-snapshots.js
test/parallel/test-runner-assert.js
test/parallel/test-runner-snapshot-file-tests.js

This commit adds a `t.assert.fileSnapshot()` API to the test runner. This is similar to how snapshot tests work in core, as well as userland options such as `toMatchFileSnapshot()`.

test_runner: add t.assert.fileSnapshot()

---

.github/workflows/lint-release-proposal.yml
tools/actions/lint-release-proposal-commit-list.mjs

When updating manually a release proposal, it can be easy to have the commit list in the CHANGELOG and the actual list of commits in the proposal no longer in sync.
It will also double check that none of the commits being released comes from a PR with the `dont-land-onvXX.x`, in case the label was added after the commit was already backported.
I'm also switching to using `make release-only` which contains the checks we were doing and more.
You can test it locally while the v23.5.0 proposal is open:
```sh
#!/bin/bash
set -e
set -o pipefail
GITHUB_REPOSITORY=nodejs/node
MAJOR=22
GITHUB_SHA=7d849ab5e3ff707512c6d7e7031428dafe44a5aa # b0bd12384eca49202d2dd2b4971ee66d7f62f4a0
CHANGELOG_PATH="doc/changelogs/CHANGELOG_V${MAJOR}.md"
curl -L -o "$CHANGELOG_PATH" …
```

tools: validate commit list as part of `lint-release-commit`

---

doc/abi_version_registry.json

This PR reserves NMV 133 for Electron 35

chore: reserve NMV 133 for Electron 35

---

doc/api/tracing.md

This PR adds the missing `ESM` counterparts of the `CJS` examples for [the Trace events documentation](https://nodejs.org/api/tracing.html).
I also destructured the (`require`)  imports for the current `CJS` examples following a feedback I had received in previous PRs, except for [the last one](https://nodejs.org/api/tracing.html#collect-trace-events-data-by-inspector) where I didn't see it necessary, but tell me what you think and I can do it quickly!
Happy new year! :partying_face:

doc: add esm examples to `node:trace_events`

---

doc/api/process.md
lib/internal/process/per_thread.js
test/parallel/test-process-ref-unref.js

The methods landed (and were released 😞) with two shortcomings:
- The added methods were not marked as experimental.
- The symbol name they used did not follow our conventions: https://github.com/nodejs/node/blob/cd4f4b4dfac4d96316058e12aafdc2737ed43f72/doc/contributing/using-symbols.md#L67-L68
Refs: https://github.com/nodejs/node/pull/56400#discussion_r1906543664

process: fix symbol name and mark experimental new process methods

---

doc/api/cli.md

The 'coverage output' and 'source map cache' sections were appearing under the `NO_COLOR` environment variable instead of the `NODE_V8_COVERAGE` environment variable where they were intended to be. This commit fixes that issue.

doc: fix location of NO_COLOR in CLI docs

---

deps/ncrypto/ncrypto.cc

`CSPRNG` is declared with `warn_unused_result`.

crypto: fix warning of ignoring return value

---

lib/internal/assert/myers_diff.js

now that [Myers diff](https://github.com/nodejs/node/pull/54862) has landed, I took the liberty to review the code I wrote to look for improvements that would squeeze some more performance out of the comparison mechanism
- simplified some logic
- reviewed loops and introduced more breaking points to make them run for less cycles
- reduced memory allocation using `Int32Array`
Refs: https://github.com/nodejs/node/pull/54862

assert: make myers_diff function more performant

---

doc/api/cli.md
test/parallel/test-permission-allow-child-process-cli.js

This commit updates the documentation and includes a test to ensure that permission model flags
will be passed to the child process if `fork` is called

test: clarify fork inherit permission flags

---

deps/sqlite/sqlite.gyp

This commit defines `SQLITE_DEFAULT_MEMSTATUS=0` for the SQLite build. This setting disables several currently unused C APIs in SQLite, which can yield noticeable performance improvements. This setting is also used by better-sqlite, and is one of the recommended compile-time options in the SQLite docs.
The disabled APIs are used to report statistics about SQLite's memory usage. The drawback to this change is that those APIs could possibly be useful one day. I think the perf tradeoff and prior art make this change worth it.
Refs: https://sqlite.org/compile.html
<details>
I tested this code against main, this PR, and better-sqlite by changing the `require()` calls. On my machine, this PR was the fastest (6.4 seconds), followed by better-sqlite (6.7 seconds), followed by main (7.6 seconds). …

sqlite: disable memstatus APIs at build time

---

lib/internal/process/per_thread.js
test/parallel/test-process-ref-unref.js

The symbol was undocumented in https://github.com/nodejs/node/pull/56517, but left in the code to avoid a breaking change. This PR makes the breaking change, I suggest we skip landing it on 23.x and directly backport it to 22.x so that release line only receive support for the documented symbol.

process: remove support for undocumented symbol

---

doc/api/child_process.md

doc: fix parentheses in options

---

BUILDING.md

doc: update gcc-version and build for Ubuntu 22.04.5 LTS

---

benchmark/util/style-text.js

I noted that when we don't validate the stream it's reasonably faster than when it does.

benchmark: add validateStream to styleText bench

---

src/crypto/crypto_util.cc
test/parallel/test-tls-error-stack.js

The ncrypto move introduced regressions in
cryptoErrorListToException() by passing in the size of the vector unnecessarily into the vector constructor and then use push_back() (which would result in a crash on dereferencing empty handles during later iteration) and having incorrect logic for checking the presence of an exception. This patch fixes it.
Fixes: https://github.com/nodejs/node/issues/56375
Refs: https://github.com/nodejs/node/pull/53803

tls: fix error stack conversion in cryptoErrorListToException()

---

doc/api/permissions.md

doc: add section about using npx with permission model

---

doc/api/util.md
src/env_properties.h
src/node_util.cc
test/parallel/test-util-getcallsites.js

The `scriptId` is essential to construct chrome devtools protocol
structs like `Network.Initiator`, allowing inspectors to associate
a `CallSite` with a unique script.

util: expose CallSite.scriptId

---

doc/api/diagnostics_channel.md
lib/internal/console/constructor.js
test/parallel/test-console-diagnostics-channels.js
test/parallel/test-repl.js

I've added diagnostics_channel support to capture and modify inputs to the main console methods. This enables some useful things like APMs injecting tracing data into log messages to correlate log messages to the requests from which they originated. You can also replace the args list entirely, so you could apply your own custom formatting to produce JSON logs instead or things like that.
cc @nodejs/diagnostics @nodejs/console

diagnostics_channel: capture console messages

---

lib/internal/webstreams/readablestream.js

The `readIntoRequests` field was misspelled as `requestIntoRequests`. This didn't break anything of importance, but it did show up when inspecting the `ReadableStreamBYOBReader`:
```
$ node
> rs = new ReadableStream({ type: "bytes" })
> reader = rs.getReader({ mode: "byob" })
ReadableStreamBYOBReader {
stream: ReadableStream { locked: true, state: 'readable', supportsBYOB: true },
requestIntoRequests: 0,
close: Promise {
<pending>,
[Symbol(async_id_symbol)]: 192,
[Symbol(trigger_async_id_symbol)]: 6
}
}
> reader.read(new Uint8Array(1))
> reader
ReadableStreamBYOBReader {
stream: ReadableStream { locked: true, state: 'readable', supportsBYOB: true },
requestIntoRequests: 0,
close: Promise {
<pending>,
[Symbol(async_id_symbol)]: 192,
[Symbol(trigger_async_id_symbol)]: 6
}
}
```
Note that …

stream: fix typo in `ReadableStreamBYOBReader.readIntoRequests`

---

test/parallel/test-child-process-bad-stdio.js

This commit updates test/parallel/test-child-process-bad-stdio.js to use node:test. This change prevents multiple child processes from being spawned in parallel, which can be problematic in the CI.

test: update test-child-process-bad-stdio to use node:test

---

doc/contributing/releases.md

With https://github.com/nodejs/bluesky/pull/32, we now have a way to have GHA open the PR for us, as I find the manual workflow to be quite a slowdown when working on post-release stuff.
@nodejs/releasers wdyt?

doc: document CLI way to open the nodejs/bluesky PR

---

lib/internal/util/inspect.js
test/parallel/test-util-inspect.js

See #56570 - this avoids a crash when a Function name is a Symbol.

util: inspect: do not crash on Symbol function names

---

.github/CODEOWNERS

meta: add codeowners of security release document

---

lib/internal/modules/cjs/loader.js

module: fix jsdoc for `format` parameter in cjs/loader

---

test/sequential/sequential.status

This has been flaky at least [since Dec 17](https://github.com/nodejs/reliability/blob/main/reports/2024-12-17.md) and has failed [7 PRs in the last 100 CI runs](https://github.com/nodejs/reliability/blob/main/reports/2025-01-13.md). I don't think it would do us any good to keep it flaking on smartos in the CI, and I don't think anyone is looking into it, so mark it as flaky.
cc @nodejs/platform-smartos @nodejs/tsc  this is what I mentioned in https://github.com/nodejs/TSC/issues/1666 about the tier 2 platforms destablizing the CI. It's counting on volunteers, like me, to occasionally care about the overall health of the project enough to look at the reliability reports, triage the flakes, and ping the platform teams. IMO it's fine for tier 1 platforms whose user base make them worthy of …

test: mark test-worker-prof as flaky on smartos

---

doc/api/util.md
lib/util.js
src/env_properties.h
src/node_util.cc
test/parallel/test-util-getcallsites.js

Align the property names `lineNumber` and `columnNumber`.
The name should either be `line` and `column`, or `lineNumber` and `columnNumber`, but not mixing up. This leads confusing doc like https://github.com/nodejs/node/blob/db7a31e2766ae3c800f6e879ec0f3d08e0759198/lib/util.js#L337-L344

util: rename CallSite.column to columnNumber

---

src/README.md
tools/snapshot/README.md

Part of the tools/snapshot/README.md is out of date since we have made more progress on the snapshot integration, so update it accordingly with some details about the various snapshots in the snapshot blob.
Also update the section in src/README.md about external reference registration for clarification.

doc: improve internal documentation on built-in snapshot

---

lib/internal/util/inspect.js
test/parallel/test-util-inspect.js

See #56570 - this avoids a crash with a regex set as the `name` property of an Error

util: inspect: do not crash on an Error with a regex `name`

---

doc/api/test.md
lib/internal/test_runner/test.js
test/parallel/test-runner-wait-for.js

This commit adds a `waitFor()` method to the `TestContext` class in the test runner. As the name implies, this method allows tests to more easily wait for things to happen.

test_runner: add TestContext.prototype.waitFor()

---

src/permission/fs_permission.cc
test/parallel/test-permission-fs-repeat-path.js

This commit fixes a crash whenever someone tries to allow access to the same path twice

src: handle duplicate paths granted

---

doc/contributing/advocacy-ambassador-program.md

Adding type stripping to the messages we would like ambassadors.
I rushed the goals, feel free to suggest refinements.
@nodejs/tsc for visibility

doc: add type stripping to ambassadors program

---

doc/api/errors.md
lib/internal/errors.js

It seems that `ERR_TAP_PARSER_ERROR`,`ERR_TAP_LEXER_ERROR` and `ERR_TAP_VALIDATION_ERROR` are no longer used in the codebase.
Does it make sense to perform some housekeeping by removing them?

test_runner: remove unused errors

---

doc/api/cli.md
doc/api/errors.md
lib/internal/errors.js
lib/internal/modules/typescript.js
lib/internal/process/execution.js
test/es-module/test-typescript-eval.mjs
test/es-module/test-typescript.mjs
test/fixtures/typescript/ts/test-invalid-syntax.ts

This new error allows user to know if its unsupported syntax like enums in strip-types or just general invalid syntax.

module: add ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX

---

.github/workflows/lint-release-proposal.yml

The token needs permission to read PR content in order to lint the release proposal commit – mostly relevant for private forks.

tools: fix permissions in `lint-release-proposal` workflow

---

src/crypto/crypto_context.cc

Add return value check for call to SSL_CTX_add_client_CA to be consistent with other places it is called
Fixed unused warning in one of the static analysis tools we use at Red Hat even though it is not being reported by coverity in the configuration we run.

crypto: add missing return value check

---

doc/contributing/releases.md

Forgot to include this for security releases

doc: mention prepare --security

---

lib/punycode.js
test/fixtures/errors/core_line_numbers.snapshot

DEP0040 is an extremely annoying warning. Most of the people seeing it cannot do anything about it. This commit updates the warning logic to only emit outside of node_modules. This is similar to other warnings such as the Buffer() constructor warning.
Ideally, this should be backported to Node 22.
Refs: https://github.com/nodejs/node/pull/47202

punycode: limit deprecation warning

---

lib/internal/child_process/serialization.js
test/parallel/test-child-process-advanced-serialization-splitted-length-field.js

Fixes: https://github.com/nodejs/node/issues/55834

child_process: fix parsing messages with splitted length field

---

src/node_file.cc

The goal is to fix this error reported by Coverity:

src: initialize FSReqWrapSync in path that uses it

---

deps/ncrypto/ncrypto.cc

Fixes: https://github.com/nodejs/node/issues/56611

deps: fixup some minor coverity warnings

---

doc/api/assert.md

This PR updates the documentation of the comparison details of the `WeakMap` and `WeakSet` as per the current behavior. 
Fixes #56640

doc: `WeakSet` and `WeakMap` comparison details

---

doc/api/process.md

the section comparing `queueMicrotask()` and `process.nextTick()` doesn't address the different scheduling behavior that the two functions have in cjs and esm modules, the section's introductory mjs example also provides an incorrect output, the changes here address such by explaining the difference between the two module types and updating the example accordingly
Fixes: https://github.com/nodejs/node/issues/45048

doc: clarify cjs and esm scheduling difference between `queueMicrotask()` and `process.nextTick()`

---

test/parallel/test-permission-dc-worker-threads.js
test/parallel/test-runner-module-mocking.js

This PR fixes main. I've cherry-picked the v23.x security release commits into main and I forgot we've removed `--experimental-permission` in main.

test: use --permission instead of --experimental-permission

---

doc/api/cli.md
doc/api/module.md

https://github.com/nodejs/node/commit/bf59539b980cbada964bf4c0991afe55668526e8 did not include documentation for all features depending on `InternalWorker`.

doc: add note for features using `InternalWorker` with permission model

---

lib/internal/worker.js
lib/internal/worker/io.js

While I fixed https://github.com/nodejs/node/pull/56428, I've found that we could do quite a bit of refactoring and simplifying the sdtio in workers and remove code that is not really necessary anymore.
This PR also changes from `map` and `forEach` to use basic array operations because those can be hot paths, and therefore we can actually avoid a bottleneck.

workers: refactor stdio to improve performance

---

lib/internal/modules/typescript.js

In case the thrown error is not of the shape we expect, we get a `TypeError` but an `ERR_INTERNAL_ASSERTION`

module: use more defensive code when handling SWC errors

---

doc/contributing/security-release-process.md

Refs: https://github.com/nodejs-private/security-release/pull/41

doc: add RafaelGSS as latest sec release stewards

---

doc/api/assert.md

This PR fixes the inconsistencies in the comparison example added in #56648.
Part of #56640

doc: fix inconsistencies in `WeakSet` and `WeakMap` comparison details

---

.github/workflows/tools.yml

This extends PR https://github.com/nodejs/node/pull/52957 to our other automated updates.
@targos [suggested that this might be more robust](https://github.com/nodejs/node/pull/56663#issuecomment-2602910065).

tools: fix tools-deps-update

---

test/parallel/test-zlib-const.js

Instead of checking that assignments fail silently in sloppy mode, check that they throw in strict mode.

test: enforce strict mode in test-zlib-const

---

android-configure
configure
configure.py
pyproject.toml

> After next Monday ___acceptable___ versions should be py39, py310, py311, py312, py313.
_Originally posted by @cclauss in https://github.com/nodejs/node/issues/54358#issuecomment-2388762359_

build: drop support for python 3.8

---

test/parallel/test-dotenv-edge-cases.js

Adds missing test for https://github.com/nodejs/node/issues/54255
Fixes https://github.com/nodejs/node/issues/54255

test: add missing test for env file

---

lib/internal/modules/typescript.js
src/compile_cache.cc
src/compile_cache.h
src/node_modules.cc
test/parallel/test-compile-cache-typescript-commonjs.js
test/parallel/test-compile-cache-typescript-esm.js
test/parallel/test-compile-cache-typescript-strip-miss.js
test/parallel/test-compile-cache-typescript-strip-sourcemaps.js
test/parallel/test-compile-cache-typescript-transform.js

This integrates TypeScript into the compile cache by caching the transpilation (either type-stripping or transforming) output in addition to the V8 code cache that's generated from the transpilation output.
Locally this speeds up loading with type stripping of `benchmark/fixtures/strip-types-benchmark.ts` by ~65% and loading with type transforms of
`fixtures/transform-types-benchmark.ts` by ~128%.
When comparing loading .ts and loading pre-transpiled .js on-disk with the compile cache enabled, previously .ts loaded 46% slower with type-stripping and 66% slower with transforms compared to loading .js files directly.
After this patch, .ts loads 12% slower with type-stripping and 22% slower with transforms compared to .js.
(Note that the numbers are based on microbenchmark fixtures and do …

module: integrate TypeScript into compile cache

---

src/inspector/worker_inspector.h

Added `cstdint` to `worker_inspector.h `as on new version of gcc
(v15) the build was failing due to changes to **libstdc++** and
the removal of transitive includes. Build then now fails due to
the usage of uint64_t in worker_inspector.h.
**Output of build:**
`../../src/inspector/worker_inspector.h:63:7: **error: ‘uint64_t’ has not been declared**
63 |       uint64_t thread_id, const std::string& url, const std::string& name) {
|       ^~~~~~~~
../../src/inspector/worker_inspector.h:12:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
11 | #include <unordered_set>
+++ |+#include <cstdint>`
Fixes: https://github.com/nodejs/node/issues/56731

src: adding #include <cstdint> to worker_inspector. h for gcc v15

---

doc/api/util.md

Code shows how to style `errorMessage`, but then only logs out `successMessage` twice. Might trip people up :)

doc: fix typo in example code for util.styleText

---

lib/internal/main/watch_mode.js
test/sequential/test-watch-mode.mjs

While using watch mode with --env-file-if-exists, reload env correctly
ref: https://github.com/nodejs/node/issues/49148#issuecomment-2585886195

watch: reload env file for --env-file-if-exists

---

lib/internal/modules/cjs/loader.js
test/fixtures/module-require/relative/subdir/relative-subdir.js
test/parallel/test-require-resolve-opts-paths-relative.js

Fixes: https://github.com/nodejs/node/issues/47000

fix `require.resolve` not considering paths `.` and `..` relative

---

doc/contributing/pull-requests.md

doc: add note regarding commit message trailers

---

test/parallel/test-require-resolve-opts-paths-relative.js

`common.isMainThread` was removed in
https://github.com/nodejs/node/commit/8caa1dcee63b2c6fd7a9, use the
`isMainThread` export of the `worker_threads` module instead.

test: do not use common.isMainThread

---

test/parallel/test-crypto-aes-wrap.js

* Add comment explaining purpose of the test
* Eliminate duplicative/extraneous buffer allocations

test: cleanup and simplify test-crypto-aes-wrap

---

doc/api_assets/api.js
doc/api_assets/style.css
doc/template.html
tools/doc/html.mjs

- Focus the first link in the expandable list – currently the focus stays on the opening link, which can be confusing for folks using a screen reader (if you don't have a visual clue, you don't know if the clicking link did anything).
- Remove focusability on the wrapping div – I don't think focusing it any purpose, so let's remove that additional keyboard and screen reader users have to make.
- Fix the keyboard navigation when JS is disabled.

doc: improve accessibility of expandable lists

---

doc/api_assets/style.css
doc/template.html

Useful especially for folks using a screen reader.
WCAG Reference: [WCAG 2.0 Technique G1](https://www.w3.org/TR/WCAG20-TECHS/G1.html)

doc: add "Skip to content" button

---

deps/uv/unofficial.gni

The `ENODATA` macro, which is used by uv's public header`errno.h`, has been deprecated in libc++.

deps: macro ENODATA is deprecated in libc++

---

doc/api_assets/style.css

The current CSS uses `::before` to build custom list markers, which causes them to appear underlined. This PR undoes that to use plain old list marker instead.
<details open><summary>Before</summary>
</details>
<details open><summary>After</summary>
</details>

doc: fix styles of the expandable TOC

---

test/parallel/test-global-setters.js

test-global-setters.js was added in
https://github.com/nodejs/node/pull/26882 and hasn't been modified since. It appears that it avoids strict mode so that unscoped identifiers are treated as globals, but that's true in strict mode too. (In sloppy mode, an assignment to an undefined identifier will create a global, but that's not what this test does. In strict mode, those assignments will throw an error, which would seem to be what we would want.)

test: use strict mode in global setters test

---

doc/api/cli.md
doc/api/tls.md
node.gypi
src/crypto/crypto_context.cc
src/node_options.cc
src/node_options.h
test/parallel/parallel.status
test/parallel/test-cli-node-options.js
test/parallel/test-cli-node-print-help.js
test/parallel/test-native-certs-macos.mjs
test/parallel/test-process-env-allowed-flags-are-documented.js

Fixes https://github.com/nodejs/node/issues/39657
Builds on https://github.com/nodejs/node/pull/44532 but for macOS
TODO:
I can take a look at the Windows one after, resolving the conflicts and addressing the review comments as well.
----
Happy to refactor heavily, I haven't used c++ before and I wrote it initially in objective c and ported it across.
This is heavily based upon [chromium](https://github.com/chromium/chromium/blob/main/net/cert/internal/trust_store_mac.cc) and some of [OpenJDK](https://github.com/openjdk/jdk/blob/master/src/java.base/macosx/native/libosxsecurity/KeystoreImpl.m) along with a [PR](https://github.com/openjdk/jdk/pull/22911) I have open with OpenJDK
----
I'm using https://github.com/timja/openjdk-intermediate-ca-reproducer as a reproducer:
```
docker compose …
```

feat: added support for reading certificates from macOS system store

---

test/parallel/parallel.status

`test-esm-loader-hooks-inspect-wait` is occasionally crashing on more platforms than Linux. Mark the test as flaky on those platforms as well.
Refs: https://github.com/nodejs/node/issues/54346

test: mark `test-esm-loader-hooks-inspect-wait` flaky

---

lib/util.js
test/parallel/test-util-styletext.js

Fixes: https://github.com/nodejs/node/issues/56717

util: enforce shouldColorize in styleText array arg

---

test/parallel/test-https-client-renegotiation-limit.js
test/parallel/test-tls-alert-handling.js
test/parallel/test-tls-ocsp-callback.js

The following tests
- `test/parallel/test-https-client-renegotiation-limit.js`
- `test/parallel/test-tls-alert-handling.js`
- `test/parallel/test-tls-ocsp-callback.js`
no longer use the OpenSSL CLI.
Refs: https://github.com/nodejs/node/pull/56714#discussion_r1926486581

test: remove unnecessary code

---

doc/api/sqlite.md

Clarifies a couple of behaviours of `DatabaseSync#function()`:
- "A variable number of arguments" is ambiguous; makes explicit the fact that this allows SQLite to call the function with any number of arguments in the range `0 .. SQLITE_MAX_FUNCTION_ARG`.
- Sets out the conditions governing the function return value.

doc: clarify sqlite user-defined function behaviour

---

src/crypto/crypto_ec.cc

I think it's missed, cause in this file we have example of checking result of BignumPointer::new
Fixes: https://github.com/nodejs/node/issues/56692

src: add check for Bignum in GroupOrderSize

---

test/fixtures/permission/fs-read.js
test/fixtures/permission/fs-write.js

@marco-ippolito informed me some permission model tests are failing on Windows and until I get some time to find out why this is flaky on Windows (I have some guesses), let's disable those checks.
Refs: https://github.com/nodejs/node/pull/56727#issuecomment-2613834438
```
Since the last security release, the resource check has been flaky on Windows. This commit temporarily disables those checks to unblock the next regular release.
```

test: temporary remove resource check from fs read-write

---

doc/api/util.md

`errorMessage` needs to be printed instead of `successMessage` in console.error().
ESM example is only fixed in previous PR.
Refs: https://github.com/nodejs/node/pull/56720

doc: fix typo in cjs example of `util.styleText`

---

src/inspector/unofficial.gni
unofficial.gni

Fix the GN build after recent roll and movement of `inspector_protocol`.

inspector: fix GN build

---

lib/events.js
test/parallel/test-events-getmaxlisteners.js

With the removal of the max listeners warning from AbortSignal, a bug was surfaced with getMaxListeners.
```js
> events.getMaxListeners(new AbortController().signal)
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
at Function.getMaxListeners (node:events:946:9) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
This causes performance issues for undici.
Refs: https://github.com/nodejs/undici/issues/4032
Refs: https://github.com/nodejs/node/commit/c1ccade02f29fd5585601bd496d4fb615a55b682

events: getMaxListeners detects 0 listeners

---

.github/workflows/test-macos.yml

We have to remove `macos-13` as it doesn't have Xcode 16 available.
Refs: https://github.com/nodejs/node/pull/56824

tools: run macOS test workflow with Xcode 16.1

---

src/cleanup_queue-inl.h
src/cleanup_queue.cc
src/cleanup_queue.h

Getting the idea from @jasnell on https://github.com/nodejs/node/pull/56059, let's use std::ranges::sort and spaceship operator to sort with std::ranges::sort which is available on C++20.

src: modernize cleanup queue to use c++20

---

lib/_http_outgoing.js

Avoid any potential ref to Buffer in new generation from old generation. Otherwise, the lightweight Minor GC could not collect Buffer, as a result, the heavy Major GC may be invoked more frequently
Similar tricks are used in Writable and Readable
https://github.com/nodejs/node/blob/ce6a62872081d720734d82bf975653a322795288/lib/internal/streams/writable.js#L779
https://github.com/nodejs/node/blob/ce6a62872081d720734d82bf975653a322795288/lib/internal/streams/readable.js#L1598

http: be more generational GC friendly

---

test/parallel/test-tls-client-mindhsize.js

Some checks should use the sec level instead of the OpenSSL version, adjust test-tls-client-mindhsize.js

test: adjust check to use OpenSSL sec level

---

src/cleanup_queue-inl.h
src/cleanup_queue.cc
src/cleanup_queue.h

This reverts commit 581b44421ac399c0b9ed051b1779e69f5b2457df.
Refs: https://github.com/nodejs/node/pull/56063
---
Fixes [failing Test Linux workflow](https://github.com/nodejs/node/actions/runs/13073721954/job/36480723623).
```
../src/cleanup_queue.cc:18:32: error: 'greater' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
18 |   std::ranges::sort(callbacks, std::greater());
|                                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_function.h:390:12: note: add a deduction guide to suppress this warning
390 |     struct greater : public binary_function<_Tp, _Tp, bool>
|            ^
```

Revert "src: modernize cleanup queue to use c++20"

---

BUILDING.md

This is the same version as required by the Chromium/V8 project.
Refs: https://chromium-review.googlesource.com/c/chromium/src/+/5973484

build: increase minimum Xcode version to 16.1

---

doc/api/sqlite.md
src/node_sqlite.cc
test/parallel/test-sqlite-custom-functions.js

#56385 widened the valid "blob-equivalent" type from `Uint8Array` to `ArrayBufferView` for bound parameters. This isn't currently reflected in the valid return types for user-defined functions, and it seems sensible to keep things consistent.

sqlite: allow returning `ArrayBufferView`s from user-defined functions

---

test/parallel/test-child-process-bad-stdio.js

test-child-process-bad-stdio.js contains a race condition between a timeout in the test process and a timeout in the spawned child process. This commit addresses the race condition by having the child process wait indefinitely to be killed.
I was unable to reproduce the race condition locally using the test as it was originally written (I ran a 1,000 iteration stress test). I was able to reproduce it by tweaking the timeout duration in the parent process, which leads me to believe this was due to some slowness in the CI.

test: fix race condition in test-child-process-bad-stdio

---

lib/internal/util/colors.js
test/fixtures/test-runner/output/assertion-color-tty.mjs
test/fixtures/test-runner/output/assertion-color-tty.snapshot
test/fixtures/test-runner/output/non-tty-forced-color-output.js
test/fixtures/test-runner/output/non-tty-forced-color-output.snapshot
test/parallel/test-runner-output.mjs

This PR should backport #55404, as a manual backport is required, and also addresses #52249 in this version

[v22.x backport] lib: ensure FORCE_COLOR forces color output in non-TTY environments

---

test/es-module/test-esm-no-addons.mjs
test/parallel/test-assert-fail.js
tools/test.py

This PR intends to change the test reporter in Jenkins CI to report errors only.
Follow up of #56739

test: change jenkins reporter

---

lib/internal/modules/cjs/loader.js

Make sure `node:quic` is not included in `module.builtinModules` when the `--experimental-quic` flat is not used.

lib: filter node:quic from builtinModules when flag not used

---

src/node_url_pattern.cc
test/parallel/test-urlpattern-invalidthis.js

See the test. It would fail with an abort/crash before without this change.

src: prevent URLPattern property getters from crashing with invalid this

---

src/node_url_pattern.cc
test/parallel/test-urlpattern-types.js

Improve test coverage for URLPattern, fixup a typecheck error, and eliminate an unnecessary `UNREACHABLE` branch.

src,test: expand test coverage for urlpattern and fix error

---

doc/api/process.md
lib/internal/bootstrap/node.js
lib/internal/process/per_thread.js
test/parallel/test-process-ref-unref.js

Backport of:
- https://github.com/nodejs/node/pull/56400
- https://github.com/nodejs/node/pull/56517
- https://github.com/nodejs/node/pull/56552

[v22.x backport] process: add `process.ref()` and `process.unref()` methods

---

src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-custom-functions.js

This commit adds support for the situation where SQLite is trying to report an error while JavaScript already has an exception pending.
Fixes: https://github.com/nodejs/node/issues/56772
Opening this PR since there hasn't been a reply on #56773 yet.

sqlite: handle conflicting SQLite and JS errors

---

common.gypi
deps/v8/src/codegen/riscv/cpu-riscv.cc

This upstream v8 commit fixes SIGILLs in v8 on riscv64 like https://github.com/riscv-forks/electron/issues/6
Main branch, v23.x, v22.x should need this. I didn't check on older branches.
CC @luyahan 
[riscv] Flush icache in both local and remote harts
Fix the I-Cache flush flag according to the implementation of flush_icache_mm in Linux kernel.
Change-Id: I6e6b1f56c377c2c0a629e170737bfac6c357ce8d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6080611
Commit-Queue: Yahan Lu (LuYahan) <yahan@iscas.ac.cn>
Reviewed-by: Ji Qiu <qiuji@iscas.ac.cn>
Cr-Commit-Position: refs/heads/main@{#97673}
Refs: https://github.com/v8/v8/commit/9ab40592f697795f13e71325a18ecbe8cf5857ed

deps: V8: cherry-pick 9ab40592f697

---

src/memory_tracker-inl.h
src/memory_tracker.h
src/node_url_pattern.cc
test/pummel/test-heapdump-urlpattern.js

Add `MemoryRetainerTraits` to reveal external type memory info without
forcing them to inherit from `MemoryRetainer`.
Refs: https://github.com/nodejs/node/pull/56871#discussion_r1938503993

src: add memory retainer traits for external types

---

benchmark/url/urlpattern-parse.js
benchmark/url/urlpattern-test.js

Add a couple of simple benchmarks for `URLPattern` that we can use to help judge performance improvements.

benchmarks: add simple parse and test benchmarks for URLPattern

---

configure.py
node.gyp
unofficial.gni

The `_sources` variables are also read by GN and putting anything other than filenames in them would end up with GN errors.

build: do not put commands in sources variables

---

src/node_url.cc

Eliminate uses of USE and ToLocalChecked to properly propagate errors.
Also clean up `v8::` prefix uses and switch to using `ToV8Value(...)` where appropriate

src: improve error handling in node_url

---

doc/api/http.md

The link `WebSocket` is pointing to the section itself.
https://github.com/nodejs/node/blob/793c7936c394aba54875f84b135684e38a30ff94/doc/api/http.md?plain=1#L4241

doc: update websocket link to avoid linking to self

---

src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-statement-sync.js

This patch updates `StatementSync` to store a strong reference to the database base object.
`DatabaseSync` may be garbage collected and freed while `StatementSync` is using it (due to `MakeWeak()`). The following code crashes with a segmentation fault:
```js
import { DatabaseSync } from "node:sqlite";
const db = new DatabaseSync(':memory:');
db.exec('CREATE TABLE test (value INTEGER)');
const stmt = db.prepare('INSERT INTO test VALUES (?)');
for(;;) stmt.run(0);
```
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x38)
frame #0: 0x000000010036e358 node`node::sqlite::StatementSync::Run(v8::FunctionCallbackInfo<v8::Value> const&) + 432
node`node::sqlite::StatementSync::Run:
->  0x10036e358 <+432>: ldr    x1, [x8, #0x38]
0x10036e35c <+436>: ldr …
```

sqlite: fix use-after-free in StatementSync due to premature GC

---

doc/contributing/security-release-process.md

Fixes: https://github.com/nodejs-private/security-release/issues/52 & https://github.com/nodejs-private/security-release/issues/53

doc: update post sec release process

---

doc/api/sqlite.md
src/env_properties.h
src/node_sqlite.cc
src/node_sqlite.h
test/parallel/test-sqlite-backup.mjs
tools/doc/type-parser.mjs

Closes #55413
This PR exposes the [SQLite Online Backup API](https://www.sqlite.org/backup.html), which allows database backup.
The API is inspired by better-sqlite3 https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#backupdestination-options---promise.
As long as writes come from the same process and handle (`sqlite*`), the backup will continue progressing as expected. Other than that, it can cause the backup process to restart. From docs:
> ...If the source database is not an in-memory database, and the write is performed from within the same process as the backup operation and uses the same database handle (pDb), then the destination database (the one opened using connection pFile) is automatically updated along with the source.
> Writes to an in-memory source database, …

sqlite: expose backup api

---

src/node_sqlite.cc

PR #55373 introduced a performance improvement for the `all()` method of prepared statements. Those changes appear to have been accidentally overwritten in #54181. This change restores the overwritten code.
Refs: https://github.com/nodejs/node/pull/55373
Refs: https://github.com/nodejs/node/pull/54181

sqlite: restore changes from #55373

---

src/env-inl.h
src/env.h

src: remove obsolete NoArrayBufferZeroFillScope

---

src/node_builtins.cc
src/node_builtins.h
src/util-inl.h
src/util.h

We can leverage C++20 and use `std::views::keys()` which returns `std::ranges::elements_view<T, S>` which avoids creating a vector for `GetBuiltinIds()`

src: avoid copy by using std::views::keys

---

src/encoding_binding.cc
src/inspector_agent.cc
src/inspector_js_api.cc
src/node_contextify.cc
src/node_credentials.cc

Move away from `ToLocalChecked()` uses and handle errors properly in those cases

src: improve error handling in multiple c++ files

---

doc/api/buffer.md

doc: make MDN links to global classes more consistent in `buffer.md`

---

doc/api/util.md
tools/doc/type-parser.mjs

doc: make MDN links to global classes more consistent in `util.md`

---

doc/api/worker_threads.md

doc: make MDN links to global classes more consistent in `worker_threads.md`

---

doc/api/assert.md

doc: make MDN links to global classes more consistent in `assert.md`

---

doc/api/stream.md

Adds the exact version for when the 2nd `options` argument is available.
Refs: https://github.com/nodejs/node/pull/43515

doc: update history of stream.Readable.toWeb()

---

doc/api/globals.md
lib/internal/bootstrap/web/exposed-window-or-worker.js
test/wpt/test-urlpattern.js

url: expose urlpattern as global

---

lib/internal/test_runner/reporter/spec.js
test/fixtures/test-runner/output/test-runner-watch-spec.mjs
test/fixtures/test-runner/output/test-runner-watch-spec.snapshot
test/parallel/test-runner-output.mjs

Following this discussion: https://github.com/nodejs/node/pull/56662#discussion_r1939602370
This PR should address #56902

test_runner: print formatted errors on summary

---

doc/api/fs.md
lib/internal/fs/promises.js
test/parallel/test-filehandle-readablestream.js

The original implementation of the experimental
`FileHandle.readableWebStream` API created non-`type: 'bytes'` streams, which prevented callers from creating `mode: 'byob'` readers from the returned stream, which means they could not achieve the associated "zero-copy" performance characteristics.
Then, #46933 added a parameter allowing callers to pass the `type` parameter down to the ReadableStream constructor, exposing the same semantics to callers of `FileHandle.readableWebStream`.
But there is no point to giving callers this choice: FileHandle-derived streams are by their very nature byte streams. We should not require callers to explicitly opt in to having byte stream semantics. Moreover, I do not see a situation in which callers would ever want to have a non-bytes stream: …

fs: make `FileHandle.readableWebStream` always create byte streams

---

src/debug_utils-inl.h
src/util.h

Following @addaleax's recommendation on https://github.com/nodejs/node/pull/56452#discussion_r1932994017, let's disallow copy/move functions and constructors on MaybeStackBuffer.

src: disallow copy/move fns/constructors

---

test/common/tmpdir.js

What if we just called the shell directly to avoid the cost of booting a Node.js instance? 
cc @nodejs/build any concerns?

test: execute shell directly for refresh()

---

src/crypto/crypto_keys.cc

src: add nullptr handling for `NativeKeyObject`

---

doc/api/esm.md

Backport of https://github.com/nodejs/node/pull/55855

[v18.x backport] doc: add history entries for JSON modules stabilization

---

tools/dep_updaters/update-openssl.sh

The fix landed on `main` with an unrelated commit (https://github.com/nodejs/node/commit/021cf912084005f4ecd7db06e0bad75353067a46#diff-0d4336c14130a2e69ae463aa9dc439815825ee04ce8419ca65b3428d2af83f17), it seems better to make a new PR for it than to attempt to cherry-pick the original commit.

[v18.x] tools: fix failing GHA workflows

---

src/node_options.cc
src/node_v8_platform-inl.h
src/util.cc
src/util.h

Replaces SplitString function with built-in implementation available for C++20

src: replace splitstring with built-in

---

src/node_sqlite.cc

This commit fixes several coverity warnings related to the recently landed backup() API.

sqlite: fix coverity warnings related to backup()

---

doc/api/zlib.md

Original PR didn't make these functions experimental. Let's make it, before we know the API surface is stable.
Ref: https://github.com/nodejs/node/pull/52100
cc @jkrems

zlib: make all zstd functions experimental

---

lib/zlib.js
test/parallel/test-zlib-invalid-input.js
test/parallel/test-zlib-zero-byte.js

All other classes in zlib has deprecated the usage of calling them without the new qualifier. Since this API is extremely new and experimental, let's remove them.

zlib: use modern class syntax for zstd classes

---

test/common/index.js
test/pummel/test-crypto-dh-hash.js
test/pummel/test-crypto-dh-keys.js
test/pummel/test-dh-regr.js
test/pummel/test-fs-watch-system-limit.js
test/pummel/test-hash-seed.js
test/pummel/test-heapsnapshot-near-heap-limit-bounded.js
test/pummel/test-heapsnapshot-near-heap-limit-by-api.js
test/pummel/test-heapsnapshot-near-heap-limit.js
test/pummel/test-next-tick-infinite-calls.js
test/pummel/test-webcrypto-derivebits-pbkdf2.js
test/sequential/test-child-process-pass-fd.js

Before this PR, we made a sys call to /proc/cpuinfo even if we don't need it... let's improve our test runner

test: remove unnecessary syscall to cpuinfo

---

test/common/debugger.js

Apparently, 5 seconds is not enough for some cases and causes flakiness on Github CI. 
Example: https://github.com/nodejs/node/actions/runs/13218322573/job/36900266760?pr=56962
cc @nodejs/inspector

test: improve timeout duration for debugger events

---

src/node_zlib.cc

Refs: https://github.com/nodejs/node/pull/53474

src: use `args.This()` in zlib

---

lib/internal/modules/cjs/loader.js
test/parallel/test-require-resolve-invalid-paths.js

Fixes: #47698
Previously, `require.resolve()` would crash when:
- The first parameter was a relative path and
- The `paths` array contained non-string entries
This commit fixes the issue by adding a check in `Module._findPath` to ensure all elements in `paths` are strings, and adding a validation in `stat` before calling `InternalModuleStat` to guard against non-string filenames.

module: prevent crashes in require.resolve() when path is not a string

---

src/string_bytes.cc
src/string_decoder.cc

src: improve error handling in string_bytes/decoder

---

src/node_dotenv.cc
test/fixtures/dotenv/lines-with-only-spaces.env
test/parallel/test-dotenv-edge-cases.js

the trimming functionality that the dotenv parsing uses currently only takes into consideration plain spaces (' '), other type of space characters such as tabs and newlines are not trimmed, this can cause subtle bugs, so the changes here make sure that such characters get trimmed as well
Fixes #56686

src: improve node::Dotenv trimming

---

deps/uv/unofficial.gni

Which was broken after 756a24242ed6dd99be7ccaed68346c3b9fd1bbea.

build: fix GN build of uv

---

src/node_sockaddr-inl.h

Fixes: https://github.com/nodejs/node/issues/56718
Maybe it's pointless, but imho more clear

src: add self-assigment memcpy checks

---

test/parallel/parallel.status
test/sequential/sequential.status

Most those test have either been fixed in a semver-minor way on later release lines, or seems to not affect the other release lines for another reason.

[v18.x] test: skip and mark flaky some tests

---

doc/api/cli.md
doc/api/inspector.md
doc/api/url.md
doc/api/util.md

The vast majority of our docs put the stability index after the history table, except for those 8 which this PR is fixing. I didn't bother putting back `> Stability: 2 - Stable.` back for `util.styleText` since it inherit the stable status from the parent level https://nodejs.org/api/util.html#util.

doc: move stability index after history section for consistency

---

eslint.config.mjs
tools/eslint/package-lock.json
tools/eslint/package.json

It's going to be useful for https://github.com/nodejs/node/pull/56919, IMO it makes sense to put it in a separate PR to avoid backporting issues.

tools: add support for `import source` syntax in linter

---

doc/contributing/security-release-process.md

Since https://github.com/nodejs-private/security-release/pull/56 this process has been automated.

doc: update cleanup to trust on vuln db automation
