nodejs/node

- src/crypto/crypto_context.cc
- src/crypto/crypto_util.cc
Refs https://github.com/nodejs/node/pull/56526.
Fixes compilation failure when `OPENSSL_NO_ENGINE` is defined:
```
../../third_party/electron_node/src/crypto/crypto_util.cc:32:16: error: no member named 'EnginePointer' in namespace 'ncrypto'; did you mean 'ECPointPointer'?
32 | using ncrypto::EnginePointer;
|       ~~~~~~~~~^~~~~~~~~~~~~
|                ECPointPointer
../../third_party/electron_node/deps/ncrypto/ncrypto.h:889:7: note: 'ECPointPointer' declared here
889 | class ECPointPointer final {
|       ^
```
> crypto: fix missing `OPENSSL_NO_ENGINE` guard

- src/README.md
This PR updates the documentation to clearly explain the approach used for argument validation in Node.js, 
with respect to public APIs and internal code.
It wasn't very clear to me while trying to validate the argument in https://github.com/nodejs/node/pull/56942, thanks to @joyeecheung for providing the additional context that was missing from the documentation. :)
> doc: improve documentation on argument validation

- test/node-api/test_uv_threadpool_size/node-options.js
- test/parallel/test-dotenv-edge-cases.js
@anonrig as per https://github.com/nodejs/node/pull/56983#discussion_r1948279168 🙂
> test: remove unnecessary assert requiring from tests

- test/parallel/test-crypto-prime.js
Refs https://github.com/nodejs/node/pull/56559
Allows this test to pass with both BoringSSL and OpenSSL.
> test,crypto: make tests work for BoringSSL

- test/parallel/test-without-async-context-frame.mjs
The test is spawning the python test runner directly without considering whether the current build is a debug build or not i.e. does not propage the mode parameter when the test is run with --mode=debug, so it always ends up using the release build to run the test even if the test is being run for debug builds. This patch fixes that.
> test: fix test-without-async-context-frame.mjs in debug mode

- test/common/README.md
This update improves the [test/common/README.md](https://github.com/nodejs/node/blob/1b2d2f7e682268228b1352cba7389db01614812a/test/common/README.md) file by explaining why the common module is essential when writing tests.
I became curious about its importance while working on [PR #56942](https://github.com/nodejs/node/pull/56942), and @joyeecheung kindly provided the additional context that was missing from the documentation. :)
> doc: update testing documentation

- doc/api/cli.md
- src/crypto/crypto_context.cc
- test/parallel/test-native-certs.mjs
crypto: support --use-system-ca on non-Windows and non-macOS
On other platforms, load from the OpenSSL default certificate
file and diretory.
This is different from --use-openssl-ca in that it caches
the certificates on first load, instead of always reading
from disk every time a new root store is needed.
When used together with the statically-linked OpenSSL, the
default configuration usually leads to this behavior:
- If SSL_CERT_FILE is used, load from SSL_CERT_FILE. Otherwise
load from /etc/ssl/cert.pem
- If SSL_CERT_DIR is used, load from all the files under
SSL_CERT_DIR. Otherwise, load from all the files under
/etc/ssl/certs
I've only checked Ubuntu and RHEL so far. It may be worth checking whether this works on other popular distributions - from what I can tell, though, it seems the …
> crypto: support --use-system-ca on non-Windows and non-macOS

- src/env.cc
- test/cctest/test_environment.cc
- test/cctest/test_platform.cc
Otherwise it may fail the DCHECK that uses the locked thread as a fast path to get the current thread.
> src: lock the isolate properly in IsolateData destructor

- src/node_dotenv.cc
Fix an assertion caused by accessing empty string:
```
(lldb) run -e "process.loadEnvFile('./test/fixtures/dotenv/eof-without-value.env')"
../../third_party/gn/third_party/libc++/src/include/string_view:411: assertion !empty() failed: string_view::front(): string is empty
(lldb) bt
* thread #1, name = 'MainThread', queue = 'com.apple.main-thread', stop reason = signal SIGABRT
* frame #0: 0x00007ff81b4dfc52 libsystem_kernel.dylib`__pthread_kill + 10
frame #1: 0x00007ff81b519f85 libsystem_pthread.dylib`pthread_kill + 262
frame #2: 0x00007ff81b43ab19 libsystem_c.dylib`abort + 126
frame #3: 0x0000000101b96cb2 node`std::__Cr::__libcpp_verbose_abort(format=<unavailable>) at verbose_abort.cpp:74:3 [opt]
frame #4: 0x00000001000fe088 node`node::Dotenv::ParseContent(std::__Cr::basic_string_view<char …
```
> src: fix accessing empty string

- doc/api/module.md
The loader hooks examples have been broken for a while:
1. The nextLoad() hook cannot be used on a .coffee file that ends
up going to the default load step without an explict format,
which would cause a ERR_UNKNOWN_FILE_EXTENSION. Mention
adding a package.json with a type field to work around it
in the example.
2. Pass the context parameter to the nextLoad() invocation and
document that context.format is mandatory when module type
is not explicitly inferrable from the module.
3. Correct the getPackageType() implementation which returns
false instead of undefined in the absence of an explict format,
which is not a valid type for format.
---
I still feel that moving the examples to a proper repository that have the examples actually tested in a workflow is the right way to go, which was why …
> doc: fix transpiler loader hooks documentation

- doc/api/modules.md
It's somewhat esoteric at best to define distance in terms of squared length!
> doc: `modules.md`: fix `distance` definition

- doc/api/modules.md
updates the sentence saying that `module.builtinModule` only contains the modules that can be loaded without `node:` (since v23.5.0 also prefix-only modules are included in the list)
Refs: https://github.com/nodejs/node/pull/56185
> doc: update `module.builtinModules` sentence

- BUILDING.md
- Mention that when the individual components cannot be found despite already being installed, try re-installing.
- Mention that with newer version of Visual Studio, ccache should be copied to `clang-cl.exe` instead.
- Mention how to use clang-cl with ccache
> doc: update clang-cl on Windows building guide

- doc/api/modules.md
the statement `set Y to be the file system root` can be wrongly interpreted as the file system root being updated to match Y, removing the `be` term removes this potential interpretation
Fixes https://github.com/nodejs/node/issues/51780
> doc: disambiguate pseudo-code statement

- lib/internal/modules/customization_hooks.js
- test/module-hooks/test-module-hooks-load-context-merged-esm.mjs
- test/module-hooks/test-module-hooks-load-context-merged.js
- test/module-hooks/test-module-hooks-load-context-optional-esm.mjs
- test/module-hooks/test-module-hooks-load-context-optional.js
- test/module-hooks/test-module-hooks-resolve-context-merged-esm.mjs
- test/module-hooks/test-module-hooks-resolve-context-merged.js
- test/module-hooks/test-module-hooks-resolve-context-optional-esm.mjs
- test/module-hooks/test-module-hooks-resolve-context-optional.js
This aligns the behavior of synchronous hooks with asynchronous hooks by allowing omission of the context parameter in the invocation of next hooks. The contexts are merged along the chain.
Fixes: https://github.com/nodejs/node/issues/57030
> module: allow omitting context in synchronous next hooks

- doc/api/module.md
- doc/api/modules.md
Fixes: https://github.com/nodejs/node/issues/57094
Refs: https://github.com/nodejs/node/pull/48461
Refs: https://github.com/nodejs/node/pull/47790
> doc: fix link and history of `SourceMap` sections

- lib/internal/bootstrap/web/exposed-wildcard.js
- lib/internal/util.js
- src/node_messaging.cc
- src/node_util.cc
- test/common/wpt.js
- test/wpt/test-domexception.js
This allows us to have getters not observable from JS side, getting our implementation closer to the other runtimes.
> src: port `defineLazyProperties` to native code

- src/cares_wrap.cc
- src/node_binding.cc
- src/node_buffer.cc
- src/node_i18n.cc
- src/spawn_sync.cc
> src: replace NewFromUtf8 with OneByteString where appropriate

- Makefile
Task `format-md` takes quite a long time (30 seconds). So, Added console output like the other tasks.
> build: print 'Formatting Markdown...' for long task markdown formatting

- BUILDING.md
- common.gypi
macOS 11 is no longer supported by Apple since September 2023, and macOS 12 since September 2024
Let's not lock ourselves on already EoL versions for future Node.js 24 LTS.
This also enables access to more C++20 features,
in particular `std::format` (which requires at least 13.3).
I chose 13.5 because it's the last one to provide a kernel upgrade, according to https://en.wikipedia.org/wiki/MacOS_Ventura#Release_history, but I'm happy to use another target as long as it's >=13.3.
> build: bump supported macOS version to 13.5

- test/parallel/test-http2-client-promisify-connect-error.js
I'm getting a quite useless error output on Nix CI, showing there's a failed assertion but not showing the actual assertion error. Using `assert.rejects` should improve it greatly, and also makes the test code more readable.
For reference, the current output is:
```
not ok 1611 parallel/test-http2-client-promisify-connect-error
---
duration_ms: 70.93100
severity: fail
exitcode: 1
stack: |-
node:internal/process/promises:394
triggerUncaughtException(err, true /* fromPromise */);
^
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ 'ERR_ASSERTION'
- 'ECONNREFUSED'
at /build/node-v22.14.0/test/parallel/test-http2-client-promisify-connect-error.js:21:16
at /build/node-v22.14.0/test/common/index.js:435:15
at process.processTicksAndRejections …
```
> test: improve error output of test-http2-client-promisify-connect-error

- doc/api/process.md
- lib/internal/bootstrap/node.js
- lib/internal/process/per_thread.js
- src/node_process_methods.cc
- test/parallel/test-process-threadCpuUsage-main-thread.js
- test/parallel/test-process-threadCpuUsage-worker-threads.js
- typings/globals.d.ts
- typings/internalBinding/process.d.ts
This PR add the `threadCpuUsage` method to `process`.
The method works exactly like `cpuUsage` but it returns thread specific metrics.
This is already implemented (by me :)) in user-land in `https://www.npmjs.com/package/thread-cpu-usage`.
The PR is currently a draft as I'm gonna use the CI to see which platform don't support this. I'll add documentation updates once this is solved.
> process: add threadCpuUsage

- src/node_url_pattern.cc
Thanks to @erikcorry's recommendation, we can speed up regexp performance of URLPattern
Benchmarks show no improvement, but I believe that is due to our lack of proper benchmark cases. (we don't have any benchmarks that use *)
Benchmark CI: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1658
```
url/urlpattern-parse.js n=100000 pattern='"[https://(sub.)?example(.com/)foo](https://(sub.)/?example(.com/)foo)"'                                                                  -0.34 %       ±0.57% ±0.76% ±1.01%
url/urlpattern-parse.js n=100000 pattern='{"hostname":"xn--caf-dma.com"}'                                                                *     -0.50 %       ±0.48% ±0.64% ±0.84%
url/urlpattern-parse.js …
```
> url: improve urlpattern regexp performance

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/utils.js
Refs: https://github.com/nodejs/node/pull/56919/files#r1955336054
> lib: fix ImportModuleDynamicallyCallback return type declaration

- test/parallel/test-http2-client-promisify-connect-error.js
There is no need to try to create a TCP connection that fails due to a
missing listening server. Also, the port used for the connection might
be used by another process when the connection is made.
> test: simplify test-http2-client-promisify-connect-error

- doc/api/perf_hooks.md
The actual implementation of the `observe` method does not count the `buffered` flag if we use the `entryTypes` with it. Therefore, examples with both `entryTypes` and `buffered` are confusing because it doesn't have any effect on the actual behaviour.
I see that we have somewhat [similar PR](https://github.com/nodejs/node/pull/47025) on the same topic. However, it doesn't provide changes to the examples. Also, I'm not sure at what stage the PR I linked is. If it stuck and not going anywhere I can work on it and deliver the whole fix instead of just examples.
> doc: remove buffered flag from performance hooks examples

- lib/async_hooks.js
- lib/internal/async_hooks.js
- lib/internal/inspector_async_hook.js
- test/parallel/test-inspector-async-call-stack.js
Instead of filtering out promises in the async hooks added for async task tracking, add an internal path to skip adding the promise hook completely for the inspector async hook. The actual user-land promise tracking is already handled by V8 inspector. This prevents the internal promise hook from showing up and creating unnecessary noise when stepping into async execution in the inspector.
Refs: https://issues.chromium.org/issues/390581540
Quoting myself from the DevTools issue:
> From some code archeology my guess is:
> 1. Node.js uses its own async hooks to call asyncTaskScheduled for all the async tasks so that they show up in the inspector https://github.com/nodejs/node/pull/13870
> 2. The Node.js async hooks implementation unconditionally adds Promise hooks because the API is designed …
> inspector: skip promise hook in the inspector async hook

- doc/api/deprecations.md
- doc/api/fs.md
- lib/fs.js
- test/parallel/test-fs-constants.js
Follow-up from: https://github.com/nodejs/node/pull/49686 (runtime deprecation)
> fs: remove `fs.F_OK`, `fs.R_OK`, `fs.W_OK`, `fs.X_OK`

- src/node_errors.h
- src/node_util.cc
- test/parallel/test-vm-util-lazy-properties.js
V8 should invoke native functions in their creation context,
preventing dynamic context by the caller. However, the lazy getter has
no JavaScript function representation and has no creation context. It
is not invoked in the original creation context. Fix the null realm by
retrieving the creation context via `this` argument.
Fixes https://github.com/nodejs/node/issues/57166
> src: fix crash when lazy getter is invoked in a vm context

- doc/contributing/pull-requests.md
The old link wasn't prefilling the channel name for me, and this is the format suggested in the docs: <https://libera.chat/guides/webchat#kiwiirc>
It works, too!
> doc fix web.libera.chat link in pull-requests.md

- test/fixtures/eval/eval_messages.snapshot
- test/fixtures/eval/stdin_messages.snapshot
- test/parallel/test-node-output-eval.mjs
Same approach as in https://github.com/nodejs/node/pull/55401 - allows Electron to run Node.js' smoke tests.
> test: make eval snapshot comparison more flexible

- BUILDING.md
I tried building node.js on Windows following the instructions and the path to the configurations is wrong:
```
PS C:\Users\Tim\code\node> winget configure .\configurations\configuration.dsc.yaml
File does not exist: .\configurations\configuration.dsc.yaml
PS C:\Users\Tim\code\node> winget configure .\.configurations\configuration.dsc.yaml
Apply :: WinGetPackage [pythonPackage]
```
> doc: fix typo in Windows building instructions

- lib/inspector.js
- src/inspector/network_agent.cc
- src/inspector/network_agent.h
- src/inspector/network_inspector.cc
- src/inspector/network_inspector.h
- src/inspector/node_inspector.gypi
- src/inspector/protocol_helper.h
- src/inspector_agent.cc
- src/inspector_agent.h
- src/inspector_js_api.cc
- test/parallel/test-inspector-emit-protocol-event.js
Event params object can be converted to inspector protocol directly.
This also enables binary data, like `Network.dataReceived`, to be sent
in the inspector protocol from JavaScript since JSON representation
does not support plain binary data.
> inspector: convert event params to protocol without json

- src/node_config_file.h
It is not needed, and on Windows files including the header needs some other configs otherwise errors like this may happen:
```
../../node/deps/simdjson/simdjson.h(12949,7): error: implicitly declaring library function '_BitScanReverse64' with type 'unsigned char (unsigned long *, unsigned long long) noexcept' [-Werror,-Wimplicit-function-declaration]
12949 |   if (_BitScanReverse64(&leading_zero, input_num))
|       ^
../../node/deps/simdjson/simdjson.h(12949,7): note: include the header <intrin.h> or explicitly provide a declaration for '_BitScanReverse64'
```
> src: do not expose simdjson.h in node_config_file.h

- lib/internal/bootstrap/realm.js
- test/fixtures/permission/processbinding.js
- test/parallel/test-http-parser-timeout-reset.js
- test/parallel/test-process-binding-internalbinding-allowlist.js
Namely: `async_wrap`, `crypto`, `http_parser`, `signal_wrap`, `url`, and `v8`.
They were runtime-deprecated 4 years ago.
> lib: unexpose six process bindings

- src/node_file.cc
- test/parallel/test-fs-rm.js
Return the correct error code, when a directory_not_empty error occurred.
Fixes: https://github.com/nodejs/node/issues/57095
> fs: fix rmSync error code

- doc/api/util.md
This PR adds the missing `ESM` counterparts of the `CJS` examples for [the Util documentation](https://nodejs.org/api/util.html).
I also destructured the (`require`)  imports for the current `CJS` examples following a feedback I had received in previous PRs.
For the `numericSeparator` example of [`util.inspect(object[, showHidden[, depth[, colors]]])`](https://nodejs.org/api/util.html#utilinspectobject-showhidden-depth-colors) I took the liberty to leave the numbers like this:
```js
const thousand = 1000;
const million = 1000000;
...
```
Instead of:
```js
const thousand = 1_000;
const million = 1_000_000;
...
```
Because that's actually what we want to showcase, how `numericSeparator` would add the missing underscores to print:
```bash
1_000
1_000_000
...
```
For the `Box` and …
> doc: add esm examples to `node:util`

- src/node_url.cc
Fixes #57133.
Replaces `nullptr` with `std::nullopt` when calling `ThrowInvalidURL` in `PathToFileURL`. This ensures the function receives the correct argument type and aligns with the expected behavior.
PS: I'm not sure how to test this, any help would be appreciated.
> src: fix ThrowInvalidURL call in PathToFileURL

- doc/api/http2.md
Title: Documentation Update: Include streamResetBurst and streamResetRate Options in http2.CreateSecureServer
Description:
This PR addresses the issue where the streamResetBurst and streamResetRate options were missing in the documentation for http2.CreateSecureServer.
Changes:
Added documentation for the streamResetBurst and streamResetRate options in the http2.CreateSecureServer section.
If you need any adjustments or further additions, feel free to let me know!
> #57169 fix/streamResetBurst-and-streamResetRate-options-are-missing-in-the-documentation-of-http2.CreateSecureServer

- doc/api/sqlite.md
- src/env_properties.h
- src/node_sqlite.cc
- test/parallel/test-sqlite-backup.mjs
- test/parallel/test-sqlite-database-sync.js
- test/parallel/test-sqlite.js
Closes #56940
This PR adds the capability to the sqlite module to accept Buffer and URL as the database location.
> sqlite,test,doc: accept Buffer and URL as paths

- node.gypi
This is a continuation of the [previously landed PR](https://github.com/nodejs/node/pull/56847) disabling V8 pch when using ClangCL and ccache. The issue here is similar, only not visible in each build (as some V8 files are generated during the build phase).
I've disabled the ClangCL compilation in the CI until this lands as it can block valid PRs from landing. For more details check any failed build [here](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022_clang/). What you'll find there is that either embedtest.pch or libnode.pch is causing issue, and this change will resolve that.
cc @joyeecheung @nodejs/platform-windows 
P.S. I'd also like to use fast-tracking here so that I can reenable the ClangCL compilation in the CI ASAP.
> build,win: disable node pch with ccache

- test/parallel/test-buffer-bigint64.js
https://nodejs.org/api/buffer.html#bufwritebigint64bevalue-offset
> Returns: [<integer>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) `offset` plus the number of bytes written.
add more cases that assert this
discovered by https://github.com/oven-sh/bun/issues/17694
> test: assert write return values in buffer-bigint64

- test/parallel/test-buffer-bigint64.js
The `actual` and the `expected` parameters are respectively the first and the second.
> test: swap assert.strictEqual() parameters

- lib/fs.js
The deprecation is only for invalid types, it could be confusing the warning show up for an unrelated error.
Refs: https://github.com/nodejs/node/pull/55753
> fs: only show deprecation warning when error code matches

- doc/api/assert.md
This commit documents the return types for `assert.rejects()` and `assert.doesNotReject()`.
> doc: add missing assert return types

- src/node_messaging.cc
- src/tcp_wrap.cc
- src/tty_wrap.cc
More error handling improvements.
In case folks are curious why I've been working on these across multiple PRs.. Consider this example:
```js
Object.defineProperty(Object.prototype, 'port1', {
set() { throw new Error('boom'); }
});
new MessageChannel();
```
Before this PR: crashes the process
With this PR: throws the catchable error
> src: improve error handling in tcp_wrap.cc

- lib/net.js
- test/parallel/test-net-connect-custom-lookup-non-string-address.mjs
Fixes: #57112
This PR fixes the crash when the lookup function resolves to a non-string address. Instead, it will emit an ERR_INVALID_IP_ADDRESS error.
> net: emit an error when custom lookup resolves a non-string address

- src/node_sqlite.cc
It seems the latest changes are allocating unnecessary strings, js objects etc. This change fixes all performance related issues.
> src: reduce string allocations on sqlite

- doc/api/deprecations.md
This currently renders without the word `Promise` on the website since `<Promise>` was used and ends up as an HTML element.
> doc: fix rendering of DEP0174 description

- lib/timers.js
- test/parallel/test-timers-invalid-clear.js
Fixes https://github.com/nodejs/node/issues/57063
> timers: check for immediate instance in clearImmediate

- doc/api/path.md
Since `path.isAbsolute()` it’s likely used for mitigating path traversals, I’m documentating that it doesn’t resolve paths.
I didn’t test its usages but for example it looks that it’s used for that here: https://github.com/nodejs/node/blob/47ae886e43537365ccc54beff0b1ac08a5a5aa19/lib/fs.js#L1803C3-L1815C4
> doc: clarify path.isAbsolute is not enough for mitigating path traversals

- test/parallel/test-net-eaddrinuse.js
- test/parallel/test-net-listen-close-server.js
- test/parallel/test-net-listen-error.js
- test/parallel/test-tls-close-error.js
- test/parallel/test-tls-handshake-error.js
common.mustCall and common.mustNotCall are always better than empty callbacks when ensuring correctness
> test: more common.mustNotCall in net

- src/node_contextify.cc
- src/node_process_events.cc
- test/es-module/test-esm-cjs-load-error-note.mjs
- test/es-module/test-esm-long-path-win.js
- test/es-module/test-typescript-commonjs.mjs
I improved the error message to include specific file and package.json details, trying to make it clearer and more actionable as requested in the TODO
> module: add dynamic file-specific ESM warnings

- src/node_config_file.h
Fix the same compilation error of https://github.com/nodejs/node/pull/57173, without breaking building after https://github.com/nodejs/node/pull/57170.
> src: fix node_config_file.h compilation error in GN build

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/module_job.js
- src/module_wrap.cc
This handles two cases caused by using Promise.all() with multiple dynamic import() that can make an asynchronously linked module job that has finished/failed linking but has not yet started actual evaluation appear in the load cache when another require request is in turn to handle it. It's similar to how we handle the case when the two are both asynchronous.
- When the cached async job has finished linking but has not started its evaluation because the async run() task would be later in line, start the evaluation from require() with runSync(). The evaluation, being synchronous, is guaranteed to complete by the time the other run() is about to start evaluation, the other task would just get the cached evaluation results instead of re-evaluating it, similar to what would happen if both …
> module: handle cached linked async jobs in require(esm)

- doc/api/typescript.md
TypeScript 5.8 is now released which adds a new tsconfig flag (`--erasableSyntaxOnly`) that aligns the TypeScript checker with Node's default behavior.
https://www.typescriptlang.org/tsconfig/#erasableSyntaxOnly
Two weeks ago this options was added to the recommended TSConfig for Node which resides in the `tsconfig/bases` project.
https://github.com/tsconfig/bases/blob/main/bases/node-ts.json
cc: @nodejs/typescript
> doc: TypeScript docs should recommend `erasableSyntaxOnly`

- doc/api/v8.md
- lib/v8.js
- src/node_v8.cc
- test/parallel/test-cppheap-stats.js
Expose `CppHeap` data via `cppgc::CppHeap::CollectStatistics()` in the v8 module.
Fixes: #56533
> v8: add v8.getCppHeapStatistics() method

- doc/contributing/maintaining/maintaining-dependencies.md
- tools/inspector_protocol/README.md
Add instructions on how to run `tools/inspector_tools/roll.py`.
> tools: add more details about rolling inspector_protocol

- lib/internal/crypto/aes.js
- lib/internal/crypto/cfrg.js
- lib/internal/crypto/diffiehellman.js
- lib/internal/crypto/ec.js
- lib/internal/crypto/hkdf.js
- lib/internal/crypto/keys.js
- lib/internal/crypto/mac.js
- lib/internal/crypto/pbkdf2.js
- lib/internal/crypto/rsa.js
- lib/internal/crypto/util.js
- test/parallel/test-webcrypto-derivebits-cfrg.js
- test/parallel/test-webcrypto-derivebits-ecdh.js
- test/parallel/test-webcrypto-derivekey-cfrg.js
- test/parallel/test-webcrypto-derivekey-ecdh.js
- test/parallel/test-webcrypto-encrypt-decrypt.js
- test/parallel/test-webcrypto-export-import.js
- test/parallel/test-webcrypto-keygen.js
This PR refactors the algorithm operation validations of the normalized algorithm and length (where applicable) that can be performed without accessing parameters such as key, data, ciphertext, etc.
This will allow #57270 to invoke these sync validations as part of the `SubtleCrypto.supports()` steps without repeating them in its own implementation.
This code is well tested throught WebCryptoAPI WPTs and I've also covered some previously missed lines in our own test suite.
> src: refactor SubtleCrypto algorithm and length validations

- doc/api/readline.md
- lib/internal/readline/interface.js
While writing https://github.com/nodejs/node/issues/57232#issuecomment-2692630669, I thought to myself it would be more elegant to use the explicit resource management proposal.
> readline: add support for `Symbol.dispose`

- tools/eslint/package-lock.json
- tools/eslint/package.json
@stylistic/eslint-plugin-js v4 has been updated to ship ESM-only, which needs require(esm) support due to the monkey-patching we do in our eslint.config.mjs. The node-test-linter job in Jenkins still runs Node.js v20 which has not yet released unflagging of require(esm). Revert to use v3 for now until we upgrade the Node.js version used in the CI.
Refs: https://github.com/nodejs/node/pull/57261
For an example of broken CI, see https://ci.nodejs.org/job/node-test-linter/59234/console
> tools: revert to use @stylistic/eslint-plugin-js v3

- src/node_process_events.cc
This patch uses the emit v8::String, which is already cached.
> src: use cached `emit` string

- lib/internal/webstreams/writablestream.js
- test/parallel/test-whatwg-writablestream-close.js
`sizeAlgorithm` seems to be set to `undefined` when the stream is closed as well. This patch adds the unchecked `closed` state to the assertion.
https://streams.spec.whatwg.org/#writable-stream-default-controller-process-close
> WritableStreamDefaultControllerProcessClose(controller) performs the following steps:
> 
>> 6. Perform ! WritableStreamDefaultControllerClearAlgorithms(controller).  <- Set `strategySizeAlgorithm` to undefined.
>> 7.1 Perform ! WritableStreamFinishInFlightClose(stream). <- Set stream.[[state]] to "closed".
Fixes: https://github.com/nodejs/node/issues/57272
Refs: https://github.com/nodejs/node/pull/56067
> stream: fix `sizeAlgorithm` validation in WritableStream

- doc/api/n-api.md
- doc/contributing/releases-node-api.md
Updated node-api release document to reflect the step as well.
Fixes: https://github.com/nodejs/node/issues/57284
Refs: https://github.com/nodejs/node/pull/55676
> doc: update node-api version matrix

- BUILDING.md
This PR fixes the position of Windows ccache section, which was previously added in the `Unix and macOS` section by accident.
> doc: fix Windows ccache section position

- test/addons/uv-thread-name/test.js
Similar to AIX, IBM i does not support get/set thread name from libuv.
See: https://github.com/libuv/libuv/pull/4599#issuecomment-2498376606
CC
@nodejs/platform-ibmi
> test: skip uv-thread-name on IBM i

- tools/dep_updaters/update-openssl.sh
Change `tools/dep_updaters/update-openssl.sh` to fetch updates from
official OpenSSL.
Refs: https://github.com/nodejs/node/pull/57142
---
I was intending to test this in https://github.com/nodejs/node-auto-test but ran into some sort of branch protection rule that prevented me from pushing to main there.
I'll open another draft PR with the results of running the update script locally so we can test CI with the resultant replaced `deps/openssl`.
> tools: switch back to official OpenSSL

- benchmark/assert/assertion-error.js
- lib/internal/assert/myers_diff.js
fix: https://github.com/nodejs/node/issues/57242
I reviewed the codebase and identified both some quick-win optimizations and the primary reason for the performance degradation when generating the error diff.
@Rymar, using the code example you posted in the related issue for testing during the fix, we should achieve performance levels close to what we had with the previous linear algorithm that Node.js used before switching to the Myers algorithm.
/cc @BridgeAR
> assert: improve myers diff performance

- src/quic/application.cc
- src/quic/bindingdata.cc
- src/quic/data.cc
- src/quic/endpoint.cc
- src/quic/http3.cc
- src/quic/logstream.cc
- src/quic/packet.cc
- src/quic/preferredaddress.cc
- src/quic/session.cc
- src/quic/sessionticket.cc
- src/quic/streams.cc
- src/quic/tlscontext.cc
- src/quic/transportparams.cc
Removes redundant qualifiers in src/quic folder. cc @jasnell
> src: remove redundant qualifiers in src/quic

- doc/api/typescript.md
- Fixes: https://github.com/nodejs/node/issues/57294
> doc: recommend setting `noEmit: true` in `tsconfig.json`

- src/node_process.h
- src/node_process_events.cc
This patch uses `Maybe<void>` in the function where only the success result seems needed.
> src: use Maybe<void> in ProcessEmitWarningSync

- test/es-module/test-esm-import-meta.mjs
My guess was that it was added before `assert.match` was a thing
> test: use `assert.match` in `test-esm-import-meta`

- common.gypi
- configure.py
- vcbuild.bat
This adds an option to `vcbuild.bat` to compile with CFG (Control Flow Guard). 
CFG is a programming or security concept used to ensure that the execution of a program follows its intended flow and prevents unauthorized or unintended behavior. It is often used to detect and mitigate attacks that exploit vulnerabilities, such as control flow hijacking, which occurs when an attacker manipulates the program’s control flow to execute malicious code.
- CFG validates that indirect calls (e.g., calls via function pointers) and jumps go to legitimate, pre-determined destinations within the program.
- When the application is compiled with CFG enabled, the compiler generates metadata about the valid control flow targets.
- At runtime, Windows uses this metadata to verify the destination of indirect …
> win,build: add option to enable cfg

- benchmark/eslint.config_partial.mjs
- doc/eslint.config_partial.mjs
- eslint.config.mjs
- test/eslint.config_partial.mjs
- tools/eslint/eslint.config_partial.mjs
- tools/eslint/eslint.config_utils.mjs
Refs: https://github.com/nodejs/node/pull/57314
> tools: import rather than require ESLint plugins

- tools/make-v8.sh
- tools/v8/node_common.py
Recent changes to `depot_tools`'s `ninja.py` proxy is causing infinite recursion in our V8 CI builds as we checkout `depot_tools` into a directory with a leading `_` (i.e. `_depot_tools`) and the proxy now checks for an exact match (i.e. `== "depot_tools"`) instead of `endswith("depot_tools")`.
Rename our checkout to `depot_tools` (without the leading `_`) so the `ninja.py` proxy can exclude it when reinvoking `ninja`.
Refs: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/6259139
Fixes: https://github.com/nodejs/build/issues/4027
---
cc @nodejs/v8-update @targos
> build: fix compatibility with V8's `depot_tools`

- lib/internal/timers.js
Simplifies the compare function by returning directly if `expiryDiff` is equal to 0
We don't need to compare twice here, or return 1 or -1 -- if the ids are equal, which only happens if the same object is passed, we can just return the result of the difference as `expiryDiff` is 0 too
Before:
```
util/priority-queue.js
util/priority-queue.js n=100000: 5,113,431.506786623
```
After:
```
util/priority-queue.js
util/priority-queue.js n=100000: 5,559,752.550981263
```
> timers: simplify the compareTimersLists function

- doc/api/process.md
- lib/internal/bootstrap/node.js
- src/api/embed_helpers.cc
- src/api/hooks.cc
- src/env-inl.h
- src/env.h
- test/es-module/test-esm-tla-unfinished.mjs
- test/fixtures/es-modules/tla/unresolved-with-listener.mjs
- test/fixtures/es-modules/tla/unresolved-withexitcode-and-listener.mjs
- test/fixtures/es-modules/tla/unresolved-withexitcode.mjs
- test/fixtures/es-modules/tla/unresolved.mjs
fix listeners registered via `process.on('exit', ...` not receiving error code 13 when an unsettled top-level-await is encountered in the code
Fixes: https://github.com/nodejs/node/issues/53551
> src: fix process exit listeners not receiving unsettled tla codes

- doc/api/typescript.md
This PR is a follow up to this comment:
- https://github.com/nodejs/node/pull/57320#discussion_r1983677462
> doc: revise `tsconfig.json` note

- src/debug_utils.cc
Fixes this error that I hit when working on a Chromium bump today in Electron:
> 2025-03-07T01:05:01.8637705Z ../../third_party/electron_node/src/debug_utils.cc(257,12): error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
> 2025-03-07T01:05:01.8638267Z   257 |     return nullptr;
> 2025-03-07T01:05:01.8638481Z       |            ^~~~~~~
> 2025-03-07T01:05:01.8638700Z 1 error generated.
This code has been around for awhile in Node.js, so the new build failure is probably an Electron issue, e.g. CI config.
Even so, upstreaming a fix feels worthwhile since building a `std::string` from `nullptr`is undefined behavior in [C++20](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2166r1.html#introduction-and-motivation) and is prohibited as of …
> src: do not pass `nullptr` to `std::string` ctor

- doc/api/module.md
The method `module.registerSync` does not exist and the comment refers to `module.registerHooks`.
> doc: fix usage of module.registerSync in comment

- src/node_sqlite.cc
- test/parallel/test-sqlite-statement-sync.js
This commit updates `StatementSync.prototype.run()` to reset the prepared statement immediately after calling `sqlite3_step()` to return the correct change metadata.
Fixes: https://github.com/nodejs/node/issues/57344
This matches the better-sqlite3 implementation.
> sqlite: reset statement immediately in run()

- lib/dns.js
- lib/internal/dns/promises.js
- lib/internal/dns/utils.js
`validFamilies` variable is defined 2 times, so remove redundant code by defining `validFamilies` in util. Plus, apply the same approach to `validDnsOrders` because it's also used multiple times.
> dns: remove redundant code using common variable

- doc/api/util.md
`frameCount` is optional because its default value is 10. And change parameter name from `frameCountOrOptions` to `frameCount` because it's described as `frameCount` in below description.
> doc: make first parameter optional in `util.getCallSites`

- lib/net.js
- test/parallel/test-net-connect-options-invalid.js
This fixes another issue discovered while reviewing #57112.
Internally, `socket.connect` checks the host string, implicitly coercing an array to a string in the process. That leads to the error below.
```js
import net from 'node:net';
net.createConnection({
host: ['192.168.0.1'],
port: 8080,
});
```
```shell
----- Native stack trace -----
1: 0x102d7b7 node::Assert(node::AssertionInfo const&) [node]
2: 0x11aa8c2 void node::TCPWrap::Connect<sockaddr_in>(v8::FunctionCallbackInfo<v8::Value> const&, std::function<int (char const*, sockaddr_in*)>) [node]
3: 0x11a9a73 node::TCPWrap::Connect(v8::FunctionCallbackInfo<v8::Value> const&) [node]
4: 0x7f5b17e0f186
----- JavaScript stack trace -----
1: internalConnect (node:net:1096:26)
2: defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18) …
```
> net: validate non-string host for `socket.connect`

- test/parallel/test-child-process-kill.js
This PR disables a `SIGQUIT` test case on Windows for `test-child-process-kill.js`. As it can be seen from the [CI results](https://ci.nodejs.org/job/mefi-node-test-binary-windows-js-suites/), this is the only blocker for enabling tests for ClangCL binaries on all CI runs. IMHO, this is a worthy trade-off.
In addition, this is a temporary thing as I plan to investigate it further and re-enable it ASAP. This problem does not exist when compiling Node.js on the latest Windows 10. Our CI compilation machines use Windows 2022 (Windows 11 basically), so the issue is Windows version specific, and I didn't experience it a few months ago.
I am currently reinstalling my Windows 11 machine (talk about bad timing...), so I should be able to investigate it there later this week.
I'll also request …
> win,test: disable test case failing with ClangCL

- doc/api/tls.md
- src/crypto/crypto_common.cc
- test/parallel/test-https-agent-create-connection.js
- test/parallel/test-tls-addca.js
- test/parallel/test-tls-friendly-error-message.js
- test/parallel/test-tls-set-secure-context.js
- test/parallel/test-tls-socket-default-options.js
This change appends a hint suggesting that if the root CA is installed locally, try running with the --use-system-ca flag. 
For errors like `UNABLE_TO_VERIFY_LEAF_SIGNATURE`,` DEPTH_ZERO_SELF_SIGNED_CERT`, or `UNABLE_TO_GET_ISSUER_CERT` occur.
This change directs developers toward a secure solution — preventing them from using unsafe workarounds (e.g. disabling TLS verification entirely) that have been discussed in the threads online like the following:
- https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs
- https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate
- and https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request.
Thanks …
> Suggest --use-system-ca when a certificate error occurs

- lib/internal/timers.js
`insert` has a third optional parameter and sometimes it's called with 2 arguments instead of 3
This is not the case for `insertGuarded`, its third parameter is never used and the function is not exported, so it's safe to remove
> timers: remove unused parameter from insertGuarded

- doc/api/process.md
Just a small typo I stumbled across.
> docs: Fix small typo in process.md

- lib/_tls_wrap.js
Following up on @jasnell's recommendation: https://github.com/cloudflare/workerd/pull/3594#discussion_r1978193326
> tls: remove unnecessary type check on normalize

- doc/api/fs.md
I added deprecation marks to the APIs that are deprecated in the fs module.
> doc: add deprecation mark to some documents in fs module

- src/aliased_buffer.h
- Mark `AliasedBufferBase` as `final` as nothing derives from it.
- Simplify scalar check with `std::is_scalar_v`.
- Remove redundant `const`-qualifiers from function declaration parameters (see [[readability-avoid-const-params-in-decls]](https://releases.llvm.org/20.1.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability/avoid-const-params-in-decls.html)).
- Add `const`-qualifiers to function definition parameters where appropriate.
- Remove redundant `inline` specifiers from functions that are templates or has template parents, and from functions that are entirely declared inside class definitions (see [[readability-redundant-inline-specifier]](https://releases.llvm.org/20.1.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability/redundant-inline-specifier.html)).
- Remove …
> src: cleanup aliased_buffer.h

- .github/workflows/update-openssl.yml
- doc/contributing/maintaining/maintaining-openssl.md
Update the instructions for maintaining OpenSSL in the Node.js source tree to reflect switching back from the quictls fork of OpenSSL back to official OpenSSL.
Refs: https://github.com/nodejs/node/pull/57335#issuecomment-2708306368
Refs: https://github.com/nodejs/node/pull/57301
Refs: https://github.com/nodejs/node/pull/57142
---
AFAICT we've been cherry-picking the OpenSSL commits from `main` to `v23.x-staging`, `v22.x-staging`, `v20.x-staging` and `v18.x-staging` instead of opening release line specific pull requests. This is much easier with the update tooling, but does mean the step for updating the 32-bit Windows assembler directives needs to happen (the automation does this) even though we don't build/test on 32-bit Windows from Node.js 23 onwards.
> doc: update maintaining-openssl.md for openssl

- README.md
I don't feel comfortable being a collaborator. While I am not actively involved in the day-to-day work within nodejs/node, I believe my contributions are still critical to it. However, I do not feel at ease participating in conversations within nodejs/collaborators. Given the internal discussions, I genuinely prefer to refrain from engaging in conversations related to collaborations; otherwise, I feel like I'm compromising my values and being hypocritical.
I will continue to do critical work, but I don’t think I should be a core collaborator as I don't belong in the "core collaborators" team.
Thank you.
> meta: remove ovflowd as collaborator

- SECURITY.md
This request came from Github Open Source Secure and it's always welcome to clarify the policy
> doc: explicit mention arbitrary code execution as a vuln

- doc/api/tls.md
Noticed it while going through
https://github.com/nodejs/node/pull/57107/files#diff-6114e55c49ec9bc0edc33830f7770a335a46373a84b8372957c387d88a23b7deR2399, so thought of removing it.
> doc: remove typo YAML snippet from tls.getCACertificates doc

- doc/api/cli.md
These are the PRs for --use-system-ca:
- initial implementation of the option with just macOS support https://github.com/nodejs/node/pull/56599 landed in v23.8.0.
- Windows support https://github.com/nodejs/node/pull/56833 landed in v23.8.0
- non-Windows and non-macOS support https://github.com/nodejs/node/pull/57009 landed in v23.9.0
This change documents the history info.
> doc: add history info for --use-system-ca

- doc/api/url.md
Fix a typo "objg" should be "obj".
Fixes: https://github.com/nodejs/node/issues/57464
> doc: fix typo in url.md

- doc/api/crypto.md
- lib/internal/crypto/diffiehellman.js
- src/crypto/crypto_dh.cc
- test/parallel/test-crypto-dh-stateless-async.js
This adds optional callback for the stateless `crypto.diffieHellman` method to allow for the key derivation to happen in libuv's threadpool.
In the asynchronous case, the OpenSSL code/library/reason error decoration is missing (because it relies on retrieving details from OpenSSL's error queue, which does not work across threads), this is something we will have to refactor in a semver-major with a broader callback methods error handling reimagining (as I've discussed privately with @tniessen), this is likely a larger endeavor now that ncrypto is in the mix.
cc @jasnell
> crypto: add optional callback to crypto.diffieHellman

- .github/workflows/update-wpt.yml
There is a bug in `create-or-update` action [here](https://github.com/gr2m/create-or-update-pull-request-action/blob/master/index.js#L153) which is causing url subsystem updates to mistakenly update the wrong PR (as seen in https://github.com/nodejs/node/pull/57368). The match being performed in that API call is not an exact match, which causes inference in L158 to pick up the wrong PR.
> build: fix update-wpt workflow

- lib/internal/fs/glob.js
- test/parallel/test-fs-glob.mjs
In at least some situations, the root path was
being added to the results of globbing even if
it matched the optional exclude function.
In the relevant test file, a variable was renamed
for consistency. (There was a patterns and pattern2, rather than patterns2.) The test case is added to
patterns2.
Fixes: https://github.com/nodejs/node/issues/56260
> fs: apply exclude function to root path

- GOVERNANCE.md
I don't know if we _need_ guidelines, but here is that PR anyway :) those are based only on my way of reviewing, so feel free to disagree / suggest improvements.
> doc: add review guidelines for collaborator nominations

- common.gypi
- deps/v8/src/heap/heap.cc
- deps/v8/src/heap/heap.h
fix: #57412
This upstream V8 commit fixes the issue where the size of RetainedMaps continuously increases, leading to higher memory usage.
This issue has been occurring since AddRetainedMap was changed to AddRetainedMaps in the commit [d8c97e48573ef9679751be0c7a308e08d0101c47](https://github.com/nodejs/node/commit/d8c97e48573ef9679751be0c7a308e08d0101c47).
As a result, the Main branch, v23.x.x, and v22.x.x should need this.
Compact retained maps array more often
When we add maps to the retained maps array, we compacted the array if
it's full. But, since we are now adding maps in a batch, it's unlikely
to meet the condition. Thus, update the condition to check whether new
size exceeds the capacity.
Bug: 398528460
Change-Id: I89caa47b69532c6397596edfe5caf7c7d24768cc …
> deps: V8: cherry-pick c172ffc5bf54

- lib/internal/crypto/hashnames.js
- lib/internal/crypto/rsa.js
- test/parallel/test-webcrypto-export-import-rsa.js
While working on SHA-3 addition to webcrypto and updating the test suite I noticed that RSA import JWK "alg" values were forced to e.g. PS256 (depending on the digest) even for RSA-OAEP and RSASSA-PKCS1-v1_5 algorithms which should be rejected.
While debugging this I noticed that
1) the expected JWK "alg" prefix (RS, PS, RSA-OAEP) is not checked at all; and after fixing that by using the right `normalizeHashName` context that;
2) the JWK "alg" is not checked as a case-sensitive value
In this PR I made the following changes:
- normalizeHashName is now case sensitive (as the need for its lowercasing went away when I've implemented the proper WebCryptoAPI normalize algorithm routine in #46067)
- RSA JWK alg check uses the right RSA algorithm type context
I've updated tests to
- use the …
> crypto: ensure expected JWK alg in SubtleCrypto.importKey RSA imports

- test/parallel/test-tls-dhe.js
The output of the `s_client` command invoked by the test has changed in the OpenSSL 3.5.0 version of `s_client`. Update the test so that it works with both the old and new output -- the `s_client` binary being run may not be at the exact same version of OpenSSL as used by Node.js so the updated test allows either output.
Refs: https://github.com/openssl/openssl/pull/26734
> test: update parallel/test-tls-dhe for OpenSSL 3.5

- doc/contributing/releases.md
- onboarding.md
Although not required, I think adding this as a "recommended" is a good thing.
cc: @aduh95
> doc: prefer to sign commits under nodejs repository

- src/node_builtins.cc
Refs https://github.com/nodejs/node/pull/57361
cc @JonasBa
Fixes the following:
```
node on git:main ❯ ninja -C out/Release                       10:13AM
ninja: Entering directory `out/Release'
ninja: error: '../../lib/internal/tls/secure-pair.js', needed by 'gen/node_javascript.cc', missing and no known rule to make it
```
> src: remove deleted tls file

- src/node_url_pattern.cc
- test/parallel/test-urlpattern.js
> url: fix constructor error message for URLPattern

- doc/api/cli.md
- doc/api/typescript.md
This commit removes two NOTEs that render properly as Markdown, but not on the docs website.
> doc: replace NOTEs that do not render properly

- doc/api/sqlite.md
- lib/sqlite.js
- test/parallel/test-sqlite-database-sync-dispose.js
This commit adds support for the explicit resource management proposal to the sqlite module.
Refs: https://github.com/nodejs/node/pull/53752#discussion_r1667750387
> sqlite: add DatabaseSync.prototype[Symbol.dispose]()

- doc/api/webstreams.md
Fixes https://github.com/nodejs/node/issues/45381
> doc: add node.js streams references to Web Streams doc

- doc/api/deprecations.md
> doc: remove some inconsistencies in `deprecations.md`

- doc/changelogs/CHANGELOG_V20.md
The backported patches already include the commit that disables the warning unless `--trace-require-module` is explicitly used. Correct the changelog to match the status.
Fixes: https://github.com/nodejs/node/issues/57517
> doc: correct status of require(esm) warning in v20 changelog

- doc/api/deprecations.md
Refs: https://github.com/nodejs/node/pull/57199
> doc: deprecate passing `args` to `spawn` and `execFile`

- doc/api/sqlite.md
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-database-sync.js
This commit adds a getter to indicate whether or not the database is currently open.
Fixes: https://github.com/nodejs/node/issues/57521
> sqlite: add DatabaseSync.prototype.isOpen

- GOVERNANCE.md
This PR tries to address a few concerns raised in https://github.com/nodejs/TSC/issues/1702 that seems small enough that it may get consensus already. This PR:
- recommend more strongly a private discussion prior to a public one.
- ~remove requirement for at-mentioning the collaborators team.~
- add requirement for the nominee to publicly accept the nomination.
- move recommendation for heads up comment from "How to review
nominations" section to "Nominating new Collaborator" section.
This shouldn't block us from discussing making deeper changes to the nomination process, but it should already improve the status quo IMO.
/cc @nodejs/collaborators
> meta: edit collaborator nomination process

- benchmark/assert/deepequal-buffer.js
- benchmark/assert/partial-deep-equal.js
- lib/internal/util/comparisons.js
- test/parallel/test-assert-partial-deep-equal.js
This implements fast paths for typed arrays, array buffers and sets
and maps that contain only objects as keys.
> assert: improve partialDeepStrictEqual

- benchmark/util/diff.js
- doc/api/util.md
- lib/internal/assert/myers_diff.js
- lib/internal/util/diff.js
- lib/util.js
- test/parallel/test-diff.js
fix: https://github.com/nodejs/node/issues/51740
Exporting the new `util.diff(actual, expected)` function.  
This function is the one internally used by the `assert` module when an `AssertionError` occurs and it is just an utility to better show differences between the two params `actual` and `expected`.  
It is internally using the "new" `Myers` diff algorithm so you can expect the same output provided by this PR: https://github.com/nodejs/node/pull/54862
> util: expose diff function used by the assertion errors

- onboarding.md
The note in
https://github.com/openjs-foundation/cross-project-council/blob/main/community-fund/COMMUNITY_FUND_POLICY.md#community-fund-rules says that the funds may not be used for visa costs, so this change corrects the doc.
> doc: remove mention of visa fees from onboarding doc

- lib/internal/timers.js
This doesn't cause that problem anymore
> timers: remove unnecessary allocation of _onTimeout

- GOVERNANCE.md
Anyone with sufficient involvement in Node.js (such that becoming a collaborator would benefit Node.js) is going to have plenty of people to ask. The self-nomination process has been entirely superfluous the entire time I've been involved in Node.js. Simplify things and get rid of it.
This is based on my comment at https://github.com/nodejs/node/pull/57503/files#r1997694900. If there isn't consensus on this, then that's OK and we can just close it. I don't feel so strongly that I want to have a long back-and-forth about it. But if there is consensus, let's take this opportunity to simplify our governance.
Since this is a change to the Governance doc, I think it's appropriate to @-mention the TSC. @nodejs/tsc
> meta: remove collaborator self-nomination

- src/api/environment.cc
Right now `InitializePrimordials` is invoked twice on a context created via `node::NewContext`: 
1. `InitializeMainContextForSnapshot` invokes `InitializePrimordials`.
2. `InitializePrimordials` invokes `GetPerContextExports` unconditionally.
1. `GetPerContextExports` invokes `InitializePrimordials` when `node:per_context_binding_exports` private was not set.
1. `InitializePrimordials` invokes `GetPerContextExports` and initialize primordials for the first time.
2. Initialize primordials for the second time.
`GetPerContextExports` will be invoked during `node_mksnapshot` by [initializing the principal realm](https://github.com/nodejs/node/blob/38390e5f28043146391d61d9b899b47aa72f53f9/src/node_realm.cc#L48) so it is safe to remove invocation of `InitializePrimordials` in …
> src: ensure primordials are initialized exactly once

- doc/api/child_process.md
- doc/api/deprecations.md
- lib/child_process.js
- test/parallel/test-child-process-execfile.js
- test/parallel/test-child-process-spawn-shell.js
- test/parallel/test-child-process-spawnsync-shell.js
This will make it throw an error when args are passed to execFile or
spawn when the shell option is true. The reason for this is that when it
accepts args, it gives the false impression that the args are escaped while
really they are just concatenated. This makes it easy to introduce bugs
and security vulnerabilities.
This will break any code that relies on passing args to execFile or
spawn with `{ shell: true }`.
Fixes: https://github.com/nodejs/node/issues/57143
> child_process: disallow args in execFile/spawn when shell option is true

- doc/api/sqlite.md
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-named-parameters.js
This commit adds a method for toggling support for unknown named parameters in prepared statements.
Fixes: https://github.com/nodejs/node/issues/55533
> sqlite: add support for unknown named parameters

- doc/api/esm.md
- doc/api/modules.md
I found ~~two~~ three errors in the pseudocode for the resolution algorithm. Permalinks to the implementations which show the correct behavior:
https://github.com/nodejs/node/blob/579fc67d495daf76d1cb8f895d4ce79769dde5f3/lib/internal/modules/package_json_reader.js#L244
https://github.com/nodejs/node/blob/579fc67d495daf76d1cb8f895d4ce79769dde5f3/lib/internal/modules/esm/resolve.js#L594-L601
https://github.com/nodejs/node/blob/6fe0723e40c298a862737604e08870a6671bc811/lib/internal/modules/cjs/loader.js#L1982-L1990
> docs: module resolution pseudocode corrections

- test/parallel/test-buffer-indexof.js
add some more cases that assert the success result is relative to the start of the Buffer and not the byteOffset parameter
existing number cases only checked 0 and -1 returns
discovered by https://github.com/oven-sh/bun/issues/17555
> test: buffer.indexOf: add more number cases

- .github/workflows/build-tarball.yml
- .github/workflows/coverage-linux-without-intl.yml
- .github/workflows/coverage-linux.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-macos.yml
Refs: https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/
Refs: https://github.com/mozilla/sccache/pull/2339
> tools: update sccache to support GH cache changes

- doc/api/deprecations.md
- doc/api/tls.md
This was removed in https://github.com/nodejs/node/pull/22033
> doc: remove cryptoStream API reference

- .github/SUPPORT.md
This PR updates the SUPPORT.md adding the Node.js Website Learn section and the new Discord server.
> doc: update support channels

- README.md
I would like to apply for the role of a triager in this project.
My motivation for being added as a triager is to be more connected with the Node.js community, helping to resolve people's issues with Node.js, and also to continue learning more about Node.js core to be more involved in future changes.
I hearby declare that I have read and understood the Code of Conduct of the project and will adhere to that.
> docs: add bjohansebas as triager

- lib/timers.js
After:
```sh
timers/immediate.js
timers/immediate.js type="depth" n=5000000: 80,080.39740943641
timers/immediate.js type="depth1" n=5000000: 81,172.49117847806
timers/immediate.js type="breadth" n=5000000: 6,043,891.345759598
timers/immediate.js type="breadth1" n=5000000: 3,625,307.3296283777
timers/immediate.js type="breadth4" n=5000000: 3,390,438.1071638097
timers/immediate.js type="clear" n=5000000: 17,872,894.015227303
timers/set-immediate-breadth-args.js
timers/set-immediate-breadth-args.js n=5000000: 2,719,426.8722150475
timers/set-immediate-breadth.js
timers/set-immediate-breadth.js n=10000000: 5,408,182.94584942
timers/set-immediate-depth-args.js
timers/set-immediate-depth-args.js n=5000000: 81,470.89492708661
timers/timers-breadth-args.js
timers/timers-breadth-args.js n=1000000: …
```
> timers: optimize timer functions with improved argument handling

- doc/contributing/pull-requests.md
I just wanted to open this PR to see if there could be some consensus on closing PRs that
have been state for a significant amount of time (I'm proposing 6 months here, this is very
arbitrary and can definitely be changed/generalized).
The fact is that the number of current PRs in the project, as I am opening this one is 492,
although that's not very problematic it feels rather messy to me (without providing any
noticeable value I think?), having a clear policy on when a PR is so stale that it should probably
be closed could be beneficial in trying to clean outdated and stale PRs without the risk to
generate too much controversy (since right now, as far as I can tell, abandoned PRs just stay
there indefinitely and there isn't a clear procedure on what to do with them).
> doc: add section stating that very stale PRs should be closed

- SECURITY.md
Refs: https://github.com/nodejs/moderation/issues/830
cc: @nodejs/security @nodejs/tsc 
Once approved I can also update H1 content (which is a mirror of SECURITY.md)
> doc: mention reports should align with Node.js CoC

- doc/api/cli.md
With `require(esm)` being unflagged, `node --require module` now also supports ES modules.
> Update `--require` docs

- doc/api/n-api.md
Refs: https://github.com/nodejs/node/pull/57351
- based on recent request to update one of the tests
> doc: clarify behaviour of node-api adjust function

- deps/undici/src/lib/dispatcher/pool.js
- deps/undici/src/lib/llhttp/wasm_build_env.txt
- deps/undici/src/package.json
- deps/undici/src/types/interceptors.d.ts
- deps/undici/undici.js
- src/undici_version.h
This should be updated to v23.x, v22.x and v20.x
> [v23.x] deps: update undici to 6.21.2

- README.md
I would like to apply for the role of triager.
After Fastify, [I started regularly contributing to Node.js a few months ago](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Agurgunday), and I have no intention of slowing down! I love the Node.js project, its community structure, and pretty much everything else about it. I'd love to help as much as possible and be a part of this awesome project! Like I said, I already have a bunch of merged PRs and I've been occasionally commenting on other people's issues to help them for a while. I believe this is a natural next step for me.
I hereby declare that I have read and understood the Code of Conduct of the project and will adhere to that.
> doc: add gurgunday as triager

- .github/workflows/update-wpt.yml
The comment says every week, but the actual string defines every day. Let's set it to one week, as it is quite noisy at the moment.
> tools: fix WPT update cron string

- eslint.config.mjs
- test/eslint.config_partial.mjs
Those files used to be linted, until b6738c1af040505bcb241b8740eb91e81c15eb44 moved them to the `fixtures/` dir, which is excluded from lint rules (for good reasons, we have there files that are purposefully testing e.g. edge-case syntax which would be forbidden in the other areas of the codebase). However, with the recent addition of `globalIgnores` (pending #57673), it's now possible for us to define more precise rules regarding which files are ignored.
(I've chosen to enable it only on subfolder where the files are already passing the linter, I'll open follow-up PRs to enable it in more areas, but the diff is too large for a single PR, see https://github.com/nodejs/node/compare/main...aduh95:node:lint-snapshot-files?expand=1)
> tools: enable linter on some fixtures file

- doc/contributing/diagnostic-tooling-support-tiers.md
Chrome DevTools Protocol is the de-facto debugger protocol for
Node.js and is tested regularly in Node.js test suite / CI. It matches
the tier 2 classification but lacks proper documentation in Node.js for tier 1.
Classify the Chrome DevTools Protocol as tier 2 with a target of
tier 1 once we have proper documentation on stable protocols.
On the other hand, the Chrome DevTools Frontend is not shipped with
Node.js and not tested in Node.js CI. So keep it as tier 3.
The legacy V8 Debug Protocol is not supported.
> doc: classify Chrome DevTools Protocol as tier 2

- node.gyp
- src/node.cc
- test/cctest/node_test_fixture.cc
- tools/v8_gypfiles/abseil.gyp
Abseil deadlock detection is reporting false positives in tests in V8.
Abseil mutexes are not used in node core, so disable it for now.
Refs: https://github.com/nodejs/node-v8/issues/301
> src: disable abseil deadlock detection

- doc/api/globals.md
Updated `fetch` documentation:
- added a fetch example
- explained its connection with `undici`
- explained how to get the current `undici` version
- explained how to use a custom dispatcher
- added link to related HTTP classes
Refs:
- https://undici.nodejs.org
- https://github.com/nodejs/undici/discussions/2167
- https://nodejs.org/en/blog/release/v18.0.0#fetch-experimental
> doc: improved `fetch` docs

- doc/api/process.md
Fixes https://github.com/nodejs/node/issues/50075
> doc: clarify `unhandledRejection` events behaviors in process doc

- test/fixtures/test-runner/no-isolation/global-hooks.cjs
- test/fixtures/test-runner/no-isolation/global-hooks.js
- test/fixtures/test-runner/no-isolation/global-hooks.mjs
- test/known_issues/test-runner-no-isolation-hooks.mjs
- test/parallel/test-runner-no-isolation-hooks.mjs
The `--import`ed / `--require`d file contained an un-`await`ed dynamic import, so it's subsequent code was not guaranteed to finish before the entry-point starts. Strangely that should have caused this test to fail _some_ times, but it seems to be consistently fast enough so that the race condition doesn't occur.
I checked with the original author of the test, and this was not intended (it was only done that way in an attempt to simplify setup and recycle fixtures).
However, after speed improvements in https://github.com/nodejs/node/pull/57419, the race condition was exposed and does occur consistently (causing the global hooks to get registered out of their intended/expected sequence).
> test: fix dangling promise in test_runner no isolation test setup

- doc/api/assert.md
- lib/internal/util/comparisons.js
- test/parallel/test-assert-deep.js
This reverts commit 575784b4cff6eb7fbb16e41cdd2b576563756a09.
This was an intentional commit at that time to make a bigger PR not breaking. This should in the real world never have a negative impact, since the algorithm somewhat works more correct with this change and it would very likely have resulted in a difference in user code, if this case really exists.
> Revert "assert,util: revert recursive breaking change"

- lib/internal/quic/quic.js
- src/quic/streams.cc
> quic: fix debug log

- deps/amaro/dist/errors.js
- deps/amaro/dist/package.json
- deps/amaro/dist/strip-loader.js
- deps/amaro/dist/transform-loader.js
- deps/amaro/package.json
- lib/internal/modules/typescript.js
- src/amaro_version.h
- test/es-module/test-typescript-eval.mjs
This PR finally removed the extra padding from errors and this is the final result:
```
[eval]:1
declare module F { export type x = number }
^^^^^^^^
SyntaxError [ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX]: `module` keyword is not supported. Use `namespace` instead.
at parseTypeScript (node:internal/modules/typescript:67:40)
at processTypeScriptCode (node:internal/modules/typescript:145:42)
at stripTypeScriptModuleTypes (node:internal/modules/typescript:212:22)
at parseAndEvalModuleTypeScript (node:internal/process/execution:360:26)
at node:internal/main/eval_string:39:3 {
code: 'ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX'
}
```
> module: remove extra padding from ts errors

- doc/api/cli.md
- doc/api/module.md
- doc/api/process.md
- doc/api/typescript.md
Refs: https://github.com/nodejs/typescript/issues/24
The design of this feature is pretty much stable and we have just been working on bug fixing and aesthetic improvements like error messages.
There is 1 issue open right now, and not many issues opened in general so I feel pretty confident in marking this as release candidate
cc @nodejs/typescript
> doc: mark type stripping as release candidate

- src/env_properties.h
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-statement-sync.js
This commit refactors the StatementSync iterator implementation in two primary ways:
- The iterator internal state is no longer exposed to JavaScript.
- The iterator prevents the prepared statement from being GC'ed.
Fixes: https://github.com/nodejs/node/issues/57493
> sqlite: refactor prepared statement iterator

- src/node_sqlite.cc
- test/parallel/test-sqlite-statement-sync.js
This PR is a minor refactor on converting SQLite values to JS. It makes the work for https://github.com/nodejs/node/pull/56600 easier and reduces duplication.
> sqlite,src: refactor sqlite value conversion

- src/node.h
- test/parallel/test-child-process-kill.js
This PR fixes the cause of the failure when killing the process with `SIGQUIT` on Windows on a ClangCL-produced binary. Since it is fixed now, the test is reenabled.
> win: fix SIGQUIT on ClangCL

- src/inspector_js_api.cc
- src/util-inl.h
- src/util.h
v8_inspector::StringView can either be one-byte or two-byte strings. Node has currently two places where it's unconditionally assumed that it's a two-byte StringView.
This requires the upstream V8 inspector to unnecessarily create a copy of the string:
https://source.chromium.org/chromium/chromium/src/+/main:v8/src/inspector/v8-inspector-session-impl.cc;l=192-199;drc=05bacd38e7a31e92afe0fd66081dfa2cc03b934a
This is particularly slow, especially for large CDP messages, as the serialized JSON is iterated 8-bit char by 8-bit char and each one widened to a 16-bit char.
This PR introduces a small helper that correctly converts a StringView to a v8::String instance honoring the "is8Bit" flag. This allows upstream V8 to remove the unnecessary widening copy.
Tested locally with removing the …
> src: Fix inefficient usage of v8_inspector::StringView

- src/permission/permission.cc
- src/permission/permission_base.h
- test/fixtures/permission/fs-read.js
- test/fixtures/permission/fs-write.js
- test/parallel/test-permission-child-process-cli.js
- test/parallel/test-permission-inspector.js
- test/parallel/test-permission-wasi.js
- test/parallel/test-permission-worker-threads-cli.js
This commit also adds a suggestion flag (if exists) when ERR_ACCESS_DENIED is thrown, so users don't need to jump into the documentation to see how to manage that permission error.
> src, permission: make ERR_ACCESS_DENIED more descriptive

- doc/api/process.md
execve() call is available on Android as well. When process.execve was first added, it seems like no one checked if that is actually available on Android as well and works out of the box as `__POSIX__` is defined on Android. process.execve call seems to behave just as fine as on Linux environment in my testing, so just make the docs specify it.
> doc: process.execve is only unavailable for Windows

- src/process_wrap.cc
- test/parallel/test-child-process-kill.js
The [previous changes to this file](https://github.com/nodejs/node/pull/55514) missed the special case of `process.kill(0)`, thus breaking it on Windows. This PR fixes that.
Refs: https://github.com/nodejs/node/pull/55514
Refs: https://github.com/nodejs/node/issues/42923
Fixes: https://github.com/nodejs/node/issues/57669
> src: fix kill signal 0 on Windows

- eslint.config.mjs
- test/fixtures/eval/eval_typescript.js
- test/fixtures/eval/stdin_typescript.js
> tools: enable linter in `test/fixtures/eval`

- doc/api/index.md
If we're not including the documentation anytime soon, we should probably remove the link for now.
Fixes: https://github.com/nodejs/node/issues/57252
> doc: remove link to `QUIC.md`

- onboarding.md
Thanks to the incredible support from the community in https://github.com/openjs-foundation/cross-project-council/issues/1240 we were able to amend the OpenJS Foundation travel fund policy to now cover visa costs (even in case the visa is denied).
> doc: add back mention of visa fees to onboarding doc

- lib/internal/http2/compat.js
- test/parallel/test-http2-compat-write-head-after-close.js
Fixes: https://github.com/nodejs/node/issues/57416
This issue can be reproduced by destroying the session immediately after the client sends a request.
You may occasionally see an error after running it a few times.
``` sh
seq 100 | xargs -n1 -P100 node client.js
```
``` js
// server.js
const http2 = require('http2');
const server = http2.createServer((req, res) => {
setTimeout(() => {
res.writeHead(200, { 'content-type': 'text/plain' });
res.end('Hello from HTTP/2 server!\n');
}, 100); 
});
server.listen(6000, () => {});
```
``` js
// client.js
const http2 = require('http2');
const client = http2.connect('http://localhost:6000');
const req = client.request({ ':path': '/' });
setTimeout(() => {
client.destroy();
}, 100);
```
If writeHead() is called after the server receives a GOAWAY …
> http2: skip writeHead if stream is closed

- src/node_messaging.cc
A follow up of https://github.com/nodejs/node/pull/57578 to replace all std::vector<v8::Local> to use v8::LocalVector
This is the last of these updates, we don't have anymore uses `std::vector<v8::Local>` after this :)
> src: update std::vector<v8::Local<T>> to use v8::LocalVector<T>

- benchmark/assert/deepequal-map.js
- benchmark/assert/deepequal-prims-and-objs-big-loop.js
- benchmark/assert/deepequal-set.js
- benchmark/assert/partial-deep-equal.js
- lib/internal/util/comparisons.js
- test/parallel/test-assert-deep.js
This improves the performance for almost all objects when comparing
them deeply significantly.
```
assert/deepequal-buffer.js method='deepEqual' arrayBuffer=0 strict=0 len=100 n=20000                                        -0.64 %       ±0.69%  ±0.92%  ±1.20%
assert/deepequal-buffer.js method='deepEqual' arrayBuffer=0 strict=0 len=1000 n=20000                               ***     -1.27 %       ±0.60%  ±0.80%  ±1.04%
assert/deepequal-buffer.js method='deepEqual' arrayBuffer=0 strict=1 len=100 n=20000                                ***      3.67 %       ±0.56%  ±0.74%  ±0.97%
assert/deepequal-buffer.js method='deepEqual' arrayBuffer=0 strict=1 len=1000 n=20000                               ***      3.46 %       ±0.82%  ±1.09%  ±1.42%
assert/deepequal-buffer.js method='deepEqual' …
```
> assert,util: improve deep object comparison performance

- doc/api/deprecations.md
- doc/api/repl.md
- lib/repl.js
- test/parallel/test-repl-options.js
> repl: deprecate `repl.builtinModules`

- doc/api/repl.md
- test/parallel/test-repl-top-level-await.js
> [!Note]
> I'm just trying to do a bit of caretaking here and trying to resolve this stalled PR: https://github.com/nodejs/node/pull/45939
> credit to the original author @deokjinkim :slightly_smiling_face: 
Clarify that the lexical scope of `const` is
invalidated when using top-level `await` in REPL.
As part of this change also add tests for the
documented behavior
Fixes: https://github.com/nodejs/node/issues/45918
> doc: update example of using `await` in REPL

- src/node_buffer.cc
objects I defined them as const so that they cannot be changed.
> buffer: define global v8::CFunction objects as const

- src/api/environment.cc
- src/node_builtins.cc
- src/node_internals.h
- src/node_messaging.cc
- src/node_realm.cc
In some cases, `per_context` files need to access privateSymbols. This commit lets `GetPerContextExports` to be able to pass down `IsolateData` to `InitializePrimordials`, so it can compile `per_context` files with `privateSymbols` from `IsolateData`.
With this change we can access `privateSymbols` in `per_context/domexception.js` like
```
const { transfer_mode_private_symbol } = privateSymbols;
```
> src: initialize privateSymbols for per_context

- lib/internal/modules/cjs/loader.js
- lib/internal/modules/package_json_reader.js
> module: remove unnecessary `readPackage` function

- lib/internal/modules/package_json_reader.js
- src/node_modules.cc
- src/node_modules.h
- typings/internalBinding/modules.d.ts
`packageJsonReader#getPackageType` currently gets the whole package scope config from the C++ binding and then extracts its `type` field, my understanding is that this is wasteful (since the whole object needs to be serialized to cross the C++/JS boundary) and that gathering the type in C++ and returning only that would be more efficient, that's what I'm attempting to do in this PR :slightly_smiling_face: (I hope my C++ makes sense as I am pretty inexperienced with it :crossed_fingers:)
> module: improve `getPackageType` performance

- lib/internal/watch_mode/files_watcher.js
- test/parallel/test-watch-mode-files_watcher.mjs
Fixes: https://github.com/nodejs/node/issues/57422
> watch: check parent and child path properly

- test/parallel/test-module-loading-error.js
It started failing on my machine recently, if I have to guess I'd say it's probably related to the recent 15.4 macOS update.
> test: update expected error message for macOS

- doc/node-config-schema.json
- lib/internal/options.js
The documentation states people can use the `$schema` property, but the JSON schema forbids this. This change allows it.
> doc: allow the $schema property in node.config.json

- src/api/encoding.cc
- src/crypto/crypto_ec.cc
- src/crypto/crypto_hash.cc
- src/crypto/crypto_hmac.cc
- src/crypto/crypto_keys.cc
- src/crypto/crypto_spkac.cc
- src/crypto/crypto_util.cc
- src/encoding_binding.cc
- src/fs_event_wrap.cc
- src/node.h
- src/node_buffer.cc
- src/node_dir.cc
- src/node_file.cc
- src/node_i18n.cc
- src/node_os.cc
- src/string_bytes.cc
- src/string_bytes.h
- src/string_decoder.cc
Improve error handling and the signature of `StringBytes::Encode(...)`.
Also, mark the `node::Encode(...)` C++ APIs as deprecated since those do not propagate errors correctly. Added `node::TryEncode(...)` replacements that properly return `MaybeLocal<String>` and propagate errors.
> src: improve StringBytes error handling

- doc/api/fs.md
Changed position type from `integer` to `integer | null `to reflect the ability for position to accept `null`.
> doc: update position type to integer | null in fs

- doc/api/corepack.md
The generic "future versions of" Node.js is causing a confusion among corepack users.
Example https://github.com/nodejs/corepack/issues/688#issuecomment-2778719004
This PR explicitly changes it to v25+ as agreed in TSC vote in https://github.com/nodejs/TSC/pull/1697#issuecomment-2737093616
> doc: explicitly state that corepack will be removed in v25+

- lib/internal/fs/glob.js
Benchmark results:
```
fs/bench-glob.js recursive='false' mode='async' pattern='*.js' dir='lib' n=1000                    -0.28 %       ±2.63% ±3.50% ±4.56%
fs/bench-glob.js recursive='false' mode='async' pattern='**/*' dir='lib' n=1000                     0.15 %       ±2.85% ±3.81% ±4.98%
fs/bench-glob.js recursive='false' mode='async' pattern='**/**.js' dir='lib' n=1000                -1.03 %       ±2.85% ±3.79% ±4.94%
fs/bench-glob.js recursive='false' mode='sync' pattern='*.js' dir='lib' n=1000                     -0.49 %       ±1.39% ±1.86% ±2.42%
fs/bench-glob.js recursive='false' mode='sync' pattern='**/*' dir='lib' n=1000               *      0.82 %       ±0.68% ±0.91% ±1.19%
fs/bench-glob.js recursive='false' mode='sync' …
```
> fs: improve globSync performance

- src/node_env_var.cc
Refs: https://github.com/nodejs/node/pull/57707#discussion_r2029934600
> src: improve error handling in `node_env_var.cc`

- lib/internal/async_context_frame.js
Not sure if this was intentional, but `(In)ActiveAsyncContextFrame` seems to extend `Map` without using primordials
Tracked down the change to ef6b9ffc8dfc7b2a395c864d2729a0ce1be9ef18
Cc @bengl
> lib: use SafeMap primordial for ActiveAsyncContextFrame

- doc/api/repl.md
This is pretty minor, but I just figured a little bit of polishing wouldn't hurt :slightly_smiling_face: 
The current examples presented at the bottom of the REPL doc have three issues which I am trying to address here:
- they look like they're part of the section above (on how to run multiple REPL instances in the same process) but they are not
see the table of contents at the top of the REPL page:
| before | after |
|--------|--------|
|  ![before-1](https://github.com/user-attachments/assets/53c66c4b-2138-4e48-9526-ca9ba1911a3d) (the examples are under the multiple REPL section) |   ![after-1](https://github.com/user-attachments/assets/7b7cff09-5780-4441-8484-12ee2a5e4c6c) (the examples are listed on their own) |  
- they link to old gists with code that uses outdates JS syntax (e.g …
> doc: clarify examples section in REPL doc

- doc/contributing/writing-docs.md
Just a small typo in that document
> doc: fix typo in writing-docs

- doc/changelogs/CHANGELOG_ARCHIVE.md
- doc/changelogs/CHANGELOG_V012.md
https://github.com/nodejs/node/pull/57343#issuecomment-2781525987 made me notice that we don't have a changelog entry for v0.11.15, despite being a real release, with some actual changes as outlined in https://github.com/nodejs/node/releases/tag/v0.11.15.
My understanding is this is due to having been released after the io.js fork (according to Wikipedia, the fork happened on December 2024, and v0.11.15 was released by Joyent on January 2015), which I think is why we're missing the changelog entry.
https://github.com/nodejs/node/blob/000ef895d714f269c109185b869411ffebc31391/doc/CHANGELOG.ARCHIVE.md?plain=1#L1428
Since then, io.js and Node.js have merged, so I think it's time to add the missing changelog entry; if there are v0.11.14 users out there, consider updating to ~v0.11.15~ …
> doc: add missing v0.11.15 changelog entry

- doc/api/sqlite.md
- src/env_properties.h
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-aggregate-function.mjs
Closes #56511
inspired by https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#aggregatename-options---this
> sqlite: add aggregate function

- src/node_zlib.cc
The function AllocForBrotli prefixes the allocated memory with its size, and returns a pointer to the region after it. This pointer can however no longer be suitably aligned. Correct this by allocating the maximum of the the size of the size_t and the max alignment.
On Arm 32bits the size_t is 4 bytes long, but the alignment is 8 for some NEON instructions. When Brotli is compiled with optimizations enabled newer GCC versions will use the NEON instructions and trigger a bus error killing node.
see https://github.com/google/brotli/issues/1159
I don't think there is any additional test needed, since existing test will crash node already.
Not sure about the notable-change label.
> zlib: fix pointer alignment

- doc/api/errors.md
List `DOMException` as a potential error type raised by Node.js in `errors.md`, along with
standard JS error types.
This should also clarify that a change to DOMException message does not need semver-major.
Refs: https://github.com/nodejs/node/pull/57735
> doc: list DOMException as a potential error raised by Node.js

- lib/internal/modules/esm/loader.js
This pull request includes minor wording and punctuation tweaks to fix the formatting of the require(esm) cycle error message. The message still seems a bit confusing to me, but these changes should at least be an improvement.
I am not sure whether tests should be implemented for this change, as the original error message didn't have tests either, but I can try my hand at implementing some if that would be preferred.
Fixes: https://github.com/nodejs/node/issues/57451
> module: fix incorrect formatting in require(esm) cycle error message

- src/node_http2.cc
- test/parallel/test-http2-premature-close.js
http2: fix a typo in the check for frame->hd.type in 1b693fa
According to the description above, this should be checking 
whether frame->hd.type is NGHTTP2_GOAWAY,
and the value of NGHTTP2_GOAWAY is 0x07. However, 
it is written as 0x03 here, which I think  it is a typo.
Refs: https://github.com/nodejs/node/commit/1b693fa03a0d36bc1dc9ec8d95060e3e5ceeee7b
> http2: fix a error in the check for frame->hd.type (related to CVE-2025-23085)

- doc/api/deprecations.md
[DEP0148](https://nodejs.org/api/deprecations.html#DEP0148) is EOL since v17.0.0 but description says `Runtime`. Let's fix this.
Refs: https://github.com/nodejs/node/pull/40121
> doc: fix deprecation type for `DEP0148`

- lib/internal/crypto/cipher.js
- src/crypto/crypto_cipher.cc
- src/crypto/crypto_cipher.h
- test/parallel/test-crypto-cipheriv-decipheriv.js
As far as I can tell, the `iv` parameter can never be `undefined` (but it can be `null`!), so this code appears to have been dead since Node.js 22.
This change removes dead code and adds a tiny test case for passing `undefined` as the IV.
Refs: https://github.com/nodejs/node/pull/50973
> crypto: remove CipherBase::Init

- src/crypto/crypto_cipher.cc
- src/crypto/crypto_sig.cc
- src/node_buffer.cc
- src/node_http2.cc
- src/stream_base.cc
- src/udp_wrap.cc
When passing the return value of `BackingStore::Data()` as the first or second argument to `memcpy()`, it is unnecessary to cast the returned pointer to `char*`.
Refs: https://github.com/nodejs/node/pull/52292
> src: remove `void*` -> `char*` -> `void*` casts

- src/base_object-inl.h
- src/base_object.h
- src/histogram.cc
- src/node_blob.cc
- src/node_http2.cc
- src/node_sockaddr.cc
- src/node_sqlite.cc
- src/quic/session.h
- test/cctest/test_base_object_ptr.cc
Allow comparing a `BaseObjectPtr` or implicitly construct a
`BaseObjectPtr` with `nullptr`.
> src: add BaseObjectPtr nullptr operations

- tools/actions/commit-queue.sh
- tools/actions/merge.sh
IIRC the script was written like this so it could work even without `set -xe` while maintaining a verbose enough output to allow debugging. However, with `set -e`, it's kind of an unnecessary step, and it's a bit annoying to have those temp files popping up when running the scripts.
> tools: do not use temp files when merging PRs

- lib/internal/util.js
- test/parallel/test-util-deprecate.js
More radical (and probably breaking some existing tests) solution would be wrapping original function in `Proxy` instead of separate `deprecated()` function.
> util: preserve `length` of deprecated functions

- doc/api/repl.md
clarify the example presented where multiple REPL
instances are run in the same process by:
- clarifying that they share the same `global` object (which currently is a bit ambiguous/half implied)
- making sure that they do share the same `global` object (via `useGlobal` set to `true`)
- they delete the unix socket if present (so that people running the code twice don't get confused/annoyed that the second time it doesn't properly work)
Fixes https://github.com/nodejs/node/issues/43118
> doc: clarify the multi REPL example

- tools/osx-pkg-postinstall.sh
According to https://github.com/nodejs/node/issues/4635#issuecomment-170956761, it's no longer in use, IIUC it was replaced with `tools/macos-installer/pkgbuild/npm/scripts/postinstall` in 03954f778ec491fe5a4f8e42996e3edbe35554d9 – you can see it removed `tools/osx-pkg.pmdoc/02npm.xml` which was the only mention of this script:
https://github.com/nodejs/node/blob/6975c490d11d4aa937c9df6835f4e75ac8c72cee/tools/osx-pkg.pmdoc/02npm.xml#L22
/cc @nodejs/build @nodejs/platform-macos
> tools: remove unused `osx-pkg-postinstall.sh`

- src/node_types.cc
- test/parallel/test-util-types.js
All util.types.is##Type() calls are ported to the fast API.
This improves the performance for multiple APIs such as:
- util.inspect (and util.format and console methods respectively)
- util.isDeepStrictEqual
- assert.(not)deepEqual (including strict and partial mode)
Local benchmark
```
assert/deepequal-prims-and-objs-big-loop.js method='deepEqual' strict=0 n=100000 primitive='array'                    *      1.09 %       ±1.06% ±1.41%  ±1.85%
assert/deepequal-prims-and-objs-big-loop.js method='deepEqual' strict=0 n=100000 primitive='boolean'                         1.68 %       ±2.20% ±2.93%  ±3.84%
assert/deepequal-prims-and-objs-big-loop.js method='deepEqual' strict=0 n=100000 primitive='circular'                       -1.71 % …
```
> src: implement util.types fast API calls

- doc/api/module.md
Fixes: https://github.com/nodejs/node/pull/55756#discussion_r2030296655
> doc: add missing TS formats for `load` hooks

- lib/internal/crypto/cipher.js
The fourth positional argument of `createCipherBase` is `true` when called from within the `Cipheriv` constructor and `false`when called from within the `Decipheriv` constructor. This value is then passed to the `CipherBase::New()` method, which treats it as follows:
args[0]->IsTrue() ? kCipher : kDecipher
However, the current name of said positional argument is `decipher` and thus indicates the exact opposite: when the argument is set to true, the instance is *not* a `Decipheriv` object. Therefore, this commit renames the argument to `isEncrypt`, which matches the actual semantics.
> crypto: fix misleading positional argument

- doc/api/corepack.md
Follow-up to https://github.com/nodejs/node/pull/57747
This highlights the removal, and gives a call to action for existing users.
This is similar to the documentation for punycode https://nodejs.org/api/punycode.html
> doc: clarify future Corepack removal in v25+

- tools/actions/create-release-proposal.sh
GitHub actions does not allow a body greater than 65536. Therefore, if it exceeds this, it only write the RELEASE_DATE
@RafaelGSS could you pls review it? thx
> tools: edit create-release-proposal workflow to handle pr body length

- deps/ncrypto/engine.cc
- deps/ncrypto/ncrypto.cc
- deps/ncrypto/ncrypto.h
- src/crypto/crypto_cipher.cc
- src/crypto/crypto_cipher.h
- src/crypto/crypto_context.cc
- src/crypto/crypto_ec.cc
- src/crypto/crypto_hash.cc
- src/crypto/crypto_hkdf.cc
- src/crypto/crypto_hmac.cc
- src/crypto/crypto_keys.cc
- src/crypto/crypto_pbkdf2.cc
- src/crypto/crypto_rsa.cc
- src/crypto/crypto_sig.cc
- src/crypto/crypto_sig.h
- src/crypto/crypto_tls.cc
- src/crypto/crypto_util.cc
An `std::string_view v` is a `const char* v.data()` along with an `std::size_t v.size()` that guarantees that `v.size()` contiguous elements of type `char` can be accessed relative to the pointer `v.data()`.
One of the main reasons behind the existence of  `std::string_view` is the ability to operate on `char` sequences without requiring null termination, which otherwise often requires expensive copies of strings to be made. As a consequence, it is generally incorrect to assume that `v.data()` points to a null-terminated sequence of `char`, and the only way to obtain a null-terminated string from an `std::string_view` is to make a copy. It is not even possible to check if the sequence pointed to by `v.data()` is null-terminated because the null character would be at position `v.data() + …
> crypto: revert dangerous uses of std::string_view

- lib/internal/streams/end-of-stream.js
- test/async-hooks/test-async-local-storage-stream-finished.js
> stream: preserve asynclocalstorage context in finished()

- lib/internal/readline/interface.js
- test/parallel/test-repl-multiline-navigation.js
fixing an issue introduced in the last commit of https://github.com/nodejs/node/pull/57400:  
when editing a multiline history in REPL, the string gets reversed.
Added relevant automated tests
> repl: fix multiline history editing string order

- lib/internal/test_runner/runner.js
- lib/internal/test_runner/test.js
- test/parallel/test-runner-run-watch.mjs
Re-running a test using the `--watch` flag keeps the duration unchanged across the various reruns.  
I've drafted a trivial implementation.
The test I introduced is flaky by design; I need to consider a better approach even though the number of digits is high and the likelihood of getting the same number in two consecutive runs is really low.
> test_runner: recalculate run duration on watch restart

- src/README.md
- src/node_contextify.cc
- src/node_contextify.h
- src/node_sea.cc
- src/node_snapshotable.cc
A follow up of https://github.com/nodejs/node/pull/57578 to replace all `std::vector<v8::Local<T>>` to use `v8::LocalVector<T>`
Also updates `src/README.md` to document the same.
> Update std::vector<v8::Local<T>> to use v8::LocalVector<T> (Part 2)

- lib/internal/crypto/random.js
- test/wpt/status/WebCryptoAPI.cjs
- test/wpt/test-webcrypto.js
Depends on: https://github.com/nodejs/node/pull/57879
> crypto: forbid passing `Float16Array` to `getRandomValues()`

- doc/api/worker_threads.md
- lib/internal/worker.js
- src/async_wrap.h
- src/env_properties.h
- src/node_worker.cc
- src/node_worker.h
- test/parallel/test-worker-heap-statistics.js
- test/sequential/test-async-wrap-getasyncid.js
- typings/internalBinding/worker.d.ts
Adds `worker.getHeapStatistics()` so that the heap usage of the worker could be observer from the parent thread.
> worker: add worker.getHeapStatistics()

- doc/api/util.md
- lib/internal/util/inspect.js
- test/parallel/test-util-format.js
Fixes: https://github.com/nodejs/node/issues/57818
Imo, built-in [Symbol.toPrimitive] can make use of inspect, just like built-in toString, because for built-in objects like Symbol and Date, their [Symbol.toPrimitive] and toString() return the same result.
> util: fix formatting of objects with built-in Symbol.toPrimitive

- src/api/hooks.cc
- src/node.h
- test/addons/async-hooks-id/binding.cc
- test/addons/async-hooks-id/test.js
Adds a variant of `node::AsyncHooksGetExecutionAsyncId` that takes a `v8::Local<v8::Context>` and returns the async ID belonging to the `node::Environment` (if any) of that Context. 
This is not dissimilar to how e.g. `node::Environment::GetCurrent` method also exists with overloads for both `v8::Isolate*` and `v8::Local<v8::Context>`.
In certain situations it would be useful to pass a Context object different from `v8::Isolate::GetCurrentContext`, e.g. the one returned by `v8::Isolate::GetEnteredOrMicrotaskContext` would be useful in recording the async ID in a V8 GC prologue callback when current context is not set.
> src: add ExecutionAsyncId getter for any Context

- doc/api/inspector.md
This marks the whole devtools integration section as in active development.
> doc: mark devtools integration section as active development

- doc/api/process.md
- lib/internal/process/per_thread.js
- src/node_process_methods.cc
- test/parallel/test-process-execve-abort.js
- test/parallel/test-process-execve-on-exit.js
- test/parallel/test-process-execve-permission-fail.js
- test/parallel/test-process-execve-permission-granted.js
- test/parallel/test-process-execve-socket.js
- test/parallel/test-process-execve-validation.js
- test/parallel/test-process-execve-worker-threads.js
- test/parallel/test-process-execve.js
The `execve` syscall does exist on IBM i but
it has caveats that make it not usable in Node.js context.
These changes disable building with `execve` like Windows does.
Fixes https://github.com/nodejs/node/issues/57882
> process: disable building execve on IBM i

- src/node_sqlite.cc
This PR fixes a typo in `node_sqlite.cc` file
> src: fix typo in comments

- benchmark/assert/deepequal-prims-and-objs-big-loop.js
- lib/internal/util/comparisons.js
- lib/internal/util/inspect.js
- test/parallel/test-assert-deep.js
The latest performance deep equal optimization did not take into account that
an object may have a property called constructor. This is addressed
in this PR by adding a new fast path and using fallbacks.
On top of that, this adds a few performance optimizations for the constructor
name in util.inspect().
> assert,util: fix constructor lookup in deep equal comparison

- lib/internal/http2/core.js
- src/env_properties.h
- src/node_http2.cc
- src/node_http2.h
- test/parallel/test-http2-client-rststream-before-connect.js
- test/parallel/test-http2-session-graceful-close.js
Fix issue where session.close() prematurely destroys the session when response.end() was called with an empty payload while active http2 streams still existed. This change ensures that sessions are closed gracefully only after all http2 streams complete and clients properly receive the GOAWAY frame as per the HTTP/2 spec.
Refs: https://nodejs.org/api/http2.html\#http2sessionclosecallback
Fixes: #57809 
Please refer detailed explanation below to know the intention behind updating `test/parallel/test-http2-client-rststream-before-connect.js` test.
https://github.com/nodejs/node/pull/57808#issuecomment-2799023031
> http2: fix graceful session close

- src/node_api.cc
- src/node_api_internals.h
Convert local `v8impl::NewEnv` function to the `node_napi_env__::New` method.
The new method helps creating new Node-API environment by any code that includes the `node_api_internals.h` header file.
There are no changes to the function bodies except for moving them to the top of the file.
The `ThrowNodeApiVersionError` had to be moved because the node_napi_env__::New uses it.
This change is required for the new C-based Node.js embedding API - PR #54660.
Since the PR #54660 is too big, it was decided in a Node-API meeting to split it up into smaller PRs.
This is the first PR in the series.
> node-api: convert NewEnv to node_napi_env__::New

- lib/internal/util/comparisons.js
- test/parallel/test-assert-partial-deep-equal.js
- test/parallel/test-assert-typedarray-deepequal.js
Depends on: https://github.com/nodejs/node/pull/57879
> assert: support `Float16Array` in loose deep equality checks

- doc/api/worker_threads.md
- Add ESM version to all examples
- Add `'use strict'` directive to all cjs blocks, doing this only because there are blocks includes them, better add it consistently
- Change first argument to `new Worker()` in ESM version from `url.fileURLToPath(import.meta.url)` to `new URL(import.meta.url)`
> worker: add ESM version examples to worker docs

- lib/internal/util.js
- lib/os.js
- test/parallel/test-internal-util-getCIDR.js
Modified to check the format of the netmask instead of just checking that each part of the netmask is even number.
(Ref: https://www.rfc-editor.org/rfc/rfc1878)
The result of the previous run was like this.
```js
...
if ((binary & 1) !== 0) {
return null;
}
...
console.log(getCIDR('127.0.0.1', '242.0.0.0', 'IPv4')); // 127.0.0.1/5
// 242 = 11110010(2)
```
This does not satisfy the condition in netmask, but it passes the conditional statement and returns an invalid value.
I'm not sure if that conditional is necessary(if the correct value is always passed, etc), but I think it's doing the wrong thing, so I've modified it to look like this.
```js
...
if (StringPrototypeIncludes(binary.toString(2), '01')) {
return null;
}
console.log(getCIDR('127.0.0.1', '242.0.0.0', 'IPv4')); // null
...
``` …
> os: fix netmask format check condition in getCIDR function

- doc/api/sqlite.md
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-database-sync.js
This commit adds an `isTransaction` getter to the `DatabaseSync` class for determining if the database is currently within a transaction.
Fixes: https://github.com/nodejs/node/issues/57922
> sqlite: add getter to detect transactions

- test/parallel/test-file-write-stream4.js
Reduce `test/parallel/test-file-write-stream4.js` flakiness.
Refs: https://github.com/nodejs/node/pull/57927
> test: force GC in test-file-write-stream4

- src/api/encoding.cc
- src/api/environment.cc
- src/js_stream.cc
- src/js_udp_wrap.cc
- src/node_contextify.cc
- src/node_http_common.h
- src/pipe_wrap.cc
- src/tcp_wrap.cc
- src/util.cc
More general error handling improvements by eliminating more `ToLocalChecked()` calls.
> src: fixup errorhandling more in various places

- tools/actions/lint-release-proposal-commit-list.mjs
Supersedes https://github.com/nodejs/node/pull/57827
> tools: add semver-major release support to release-lint

- src/node_dotenv.cc
- test/parallel/test-dotenv-edge-cases.js
This PR fixes an issue with `util.parseEnv()` where invalid lines in the input were being incorrectly concatenated into key names instead of being skipped. The fix ensures that lines without an equals sign are properly skipped during parsing
Fixes: https://github.com/nodejs/node/issues/56775
I lost my old pr due to a git failure 😅
#56778
> util: fix parseEnv handling of invalid lines

- doc/api/sqlite.md
- src/node_sqlite.cc
- src/node_sqlite.h
- test/parallel/test-sqlite-database-sync.js
> sqlite: add location method

- .github/workflows/tools.yml
"config" is not recognized as a valid subsystem by `core-validate-commit@4.1.0`.
Refs: https://github.com/nodejs/node/commit/478a2e656d803970e93c
> meta: fix subsystem in commit title

- src/node_platform.cc
- src/node_platform.h
Closes https://github.com/nodejs/node/issues/56236.
Improve thread safety of TaskQueue by making locking of TaskQueue explicit and thus hopefully preventing a crash due to `uv_async_send` being called with `nullptr`.
> src: improve thread safety of `TaskQueue`

- src/api/environment.cc
- src/node_constants.cc
Setting the prototype can be achieved by the v8::Object::New() constructor. We don't need to call SetPrototypeV2().
> src: avoid calling SetPrototypeV2()

- src/util-inl.h
- src/util.h
We don't need to define these functions for non-windows systems. We can just put it behind a _WIN32 defined check.
> src: move windows specific fns to _WIN32

- src/node_sqlite.cc
Add DCHECK_EQ check before other Object::New calls as in https://github.com/nodejs/node/pull/57942
> src: add DCHECK_EQ for Object::New calls

- doc/api/async_context.md
I can confirm that the change in behavior started with **Node.js 20.x**.
```
0: start  
1: start  
0: finish  
1: finish
```
```
0: start  
0: finish  
1: start  
1: finish
```
According to the official [Node.js changelog](https://nodejs.org/en/blog/release/v20.0.0#notable-changes), this difference is due to **bug fixes and improvements in async context handling** introduced in v20:
> "Several subtle bugs and inconsistencies in edge cases (e.g., using `AsyncResource`, event emitters, timers) have been fixed in v20.  
> Node.js now handles `setTimeout`, `setImmediate`, and event emitters more predictably in relation to the async context."
So if your code depends on `AsyncLocalStorage` or similar context-tracking features, be aware that behavior may differ between Node 18 and 20+ due to …
> doc: fix `AsyncLocalStorage` example response changes after node v18

- lib/internal/crypto/webidl.js
- test/parallel/test-crypto-subtle-cross-realm.js
https://github.com/nodejs/node/pull/57828 only fixed the code for `ArrayBuffer`, let's handle `SharedArrayBuffer` as well. This also refactors the test to include the nits that didn't make it in the original PR.
> crypto: fix cross-realm `SharedArrayBuffer` validation

- lib/internal/main/watch_mode.js
- test/sequential/test-watch-mode.mjs
clarify the messages that `node --watch` presents to the user when the process terminates (either successfully or because of some error) by clearly conveying that node is waiting for new file changes before restarting the process
___
I am not sure if it fixes it but it might partially help with https://github.com/nodejs/node/issues/57657
> watch: clarify completion/failure watch mode messages

- doc/abi_version_registry.json
This PR reserves NMV 136 for Electron 37 as part of our regular [release preparation work](https://github.com/orgs/electron/projects/112/views/3?pane=issue&itemId=100704744). Thanks! 🙇
> doc: reserve module version 136 for Electron 37

- src/node_http2.cc
args.Holder() has been removed in newer version of V8.
Blocks https://github.com/nodejs/node/pull/57753
> http2: use args.This() instead of args.Holder()

- src/node_options-inl.h
This PR uses C++20 ranges to slightly simplify a piece of code. To be honest, the real motivation of this PR is to introduce ranges and test whether the platforms play nice with ranges. If so, then this could be generalized in the code base.
> src: use ranges library (C++20) to simplify code

- test/js-native-api/6_object_wrap/binding.gyp
- test/js-native-api/6_object_wrap/myobject.cc
- test/js-native-api/6_object_wrap/myobject.h
- test/js-native-api/6_object_wrap/nested_wrap.cc
- test/js-native-api/6_object_wrap/nested_wrap.h
- test/js-native-api/6_object_wrap/nested_wrap.js
- test/js-native-api/6_object_wrap/test-basic-finalizer.js
- test/js-native-api/6_object_wrap/test-object-wrap-ref.js
- test/js-native-api/6_object_wrap/test.js
Test that an napi_ref can be nested inside another ObjectWrap. The test
shows a critical case where a finalizer deletes an `napi_ref` whose
finalizer is also scheduled.
This add a test for comments at:
https://github.com/nodejs/node/blob/68cc1c9cd3b8e33fdc27fe1d752c0678944cdf12/src/node_api.cc#L116-L118
The changes in `test/js-native-api/6_object_wrap/myobject.cc` are auto-formatted by `make format-cpp` as the file is renamed.
Refs: https://github.com/nodejs/node/pull/57861#pullrequestreview-2767792272
> node-api: add nested object wrap and napi_ref test

- lib/internal/readline/interface.js
- test/parallel/test-readline-interface.js
- test/parallel/test-readline-promises-interface.js
- test/parallel/test-readline-promises-tab-complete.js
- test/parallel/test-repl-import-referrer.js
- test/parallel/test-repl-no-terminal.js
- test/parallel/test-repl-uncaught-exception-async.js
This reverts commit 8e7f32f968a723bc8811e9f146876a1061f7941b (PR #57680) since the PR is introducing an unexpected issue in the REPL, see: https://github.com/nodejs/node/pull/58014#issuecomment-2830647559
Fixes https://github.com/nodejs/node/issues/58009
___
Thanks a lot @lpinca for spotting the problem 🙏 
Once again I'm super sorry for the inconvenience here, I'm really surprised that such an issue didn't cause any test failures 😓 
I'm try to reintroduce the changes in #57680 later making sure not to break the REPL 🙇
> Revert "readline: add stricter validation for functions called after close

- lib/internal/fs/dir.js
ref: #55764
We create a `queueHandler`, and in every iteration we execute the handlers in the `queueHandler` until we get a non-null result.
> lib: resolve the issue of not adhering to the specified buffersize

- test/parallel/test-async-local-storage-http-agent.js
Add a test to verify AsyncLocalStore functionality for HTTP using a keep alive agent.
AsyncLocalStore moves away from using async_hooks therefore relying on async_hooks tests alone is not longer valid.
Refs: #55712
Refs: #13325
> test: add ALS test using http agent keep alive

- src/timers.cc
- src/timers.h
- test/parallel/test-timers-now.js
Adds a test for the v8 fast api we use for getLibuvNow() method.
> test: add fast api tests for getLibuvNow()

- src/node_external_reference.h
- src/node_url.cc
- src/node_url.h
- test/parallel/test-whatwg-url-canparse.js
V8 Fast API now supports v8::Local<v8::Value> as a parameter type and we can access isolate and context through the fast api. Let's update our implementation to reflect the new limitations.
Benchmark CI: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1702
```
url/whatwg-url-canParse.js n=1000000 type='auth'              ***      5.55 %       ±2.05% ±2.75% ±3.61%
url/whatwg-url-canParse.js n=1000000 type='dot'               ***      3.90 %       ±0.69% ±0.92% ±1.20%
url/whatwg-url-canParse.js n=1000000 type='file'                       1.13 %       ±1.20% ±1.60% ±2.09%
url/whatwg-url-canParse.js n=1000000 type='idn'               ***      2.78 %       ±0.31% ±0.42% ±0.55%
url/whatwg-url-canParse.js …
```
> url: improve canParse() performance for non-onebyte strings

- Makefile
Ref: #48462
Equal to https://github.com/nodejs/node/blob/d74c4987351252f39c18305dd53dbf047639017f/configure.py#L2363-L2372
When `out/Makefile` is generated during `./configure`, `-Dpython=` is passed to GYP, however, when it's generated from the Makefile, it is not passed. This can lead to an undefined variable python on some systems.
> build: define python when generating `out/Makefile`

- lib/internal/async_local_storage/async_hooks.js
- test/parallel/test-async-local-storage-enter-with.js
This fixes the leak behavior when using `enterWith` when no
`AsyncLocalStorage`s were enabled inside a promise. With this
change, the following code snippets will behave the same:
```js
import { AsyncLocalStorage } from 'node:async_hooks';
const als = new AsyncLocalStorage();
async function main () {
await 1
als.enterWith('internal');
}
await main()
console.log(als.getStore() ?? 'default');
```
```js
import { AsyncLocalStorage } from 'node:async_hooks';
const als = new AsyncLocalStorage();
als.enterWith(undefined); // Forcefully enable the AsyncLocalStorage.
async function main () {
await 1
als.enterWith('internal');
}
await main()
console.log(als.getStore() ?? 'default');
```
On the performance side, given that an `AsyncLocalStorage` is constructed, we should assume that it will be used …
> async_hooks: enable AsyncLocalStorage once constructed

- src/node_options.h
- test/parallel/test-internal-async-context-frame-disable.js
- test/parallel/test-internal-async-context-frame-enabled.js
`default_is_true` in bool OptionsParser is a hint for help text. The
default value for an option is still required to be set in the option
struct.
> src: fix EnvironmentOptions.async_context_frame default value

- .github/codeql-config.yml
- .github/workflows/codeql.yml
A previous change designed to ignore test files in CodeQL scans had multiple problems. This fixes the CodeQL scan breakage. It adds a CodeQL config file, which allows us to ignore the test directory in our scans.
Refs: https://github.com/nodejs/node/pull/57978#issuecomment-2829182983
Refs: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#specifying-directories-to-scan
> tools: enable CodeQL config file

- test/parallel/test-repl-function-definition-edge-case.js
- test/parallel/test-repl-import-referrer.js
- test/parallel/test-repl-options.js
- test/parallel/test-repl-require-context.js
- test/parallel/test-repl-require-self-referential.js
I noticed that some repl tests write `".exit"` in the repl, without a newline character (`\n`), as far as I can tell such write operations don't have any effect (removing those lines don't cause any test failures (AFAICT)).
I'm adding the missing newline characters so that the exit command is actually executed.
As part of this I'm also removing some `end` calls applied to the repl streams that are no longer necessary.
> test: add missing newlines to repl .exit writes

- doc/api/buffer.md
"Buffers" -> "Buffer's" in `Buffer` documentation.
> doc: fix typo in `buffer.md`

- .github/ISSUE_TEMPLATE/4-report-a-flaky-test.yml
- .github/workflows/label-flaky-test-issue.yml
- BUILDING.md
There are a bunch of issues on that platform with recent V8 versions and we don't have the capacity to fix them.
/cc @nodejs/tsc @nodejs/build @nodejs/platform-arm
> build: downgrade armv7 support to experimental

- src/node_buffer.cc
- src/node_external_reference.h
This improves the performance for non one-byte strings.
Benchmark CI: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1705/
> buffer: improve byteLength performance

- src/node_buffer.cc
We don't have to deference the args pointer to create an environment variable while having access to isolate using `args.GetIsolate()`
> buffer: avoid creating unnecessary environment

- lib/fs.js
- lib/internal/fs/promises.js
- lib/internal/modules/cjs/loader.js
- lib/internal/modules/esm/resolve.js
- lib/internal/modules/package_json_reader.js
- src/node_external_reference.h
- src/node_file.cc
- test/parallel/test-permission-fs-internal-module-stat.js
v8 fast path was not triggering before this. I've updated the implementation and added proper test for it.
cc @nodejs/cpp-reviewers @nodejs/performance
> src: fix internalModuleStat v8 fast path

- src/node_buffer.cc
> src: remove unused detachArrayBuffer method

- lib/internal/error_serdes.js
- test/sequential/test-error-serdes.js
`serializeError` should avoid StackOverflow and the test should not
rely on `--stack-size`.
Refs: https://github.com/nodejs/node/pull/58070#issuecomment-2837874067
> lib: avoid StackOverflow on `serializeError`

- Makefile
These checks would previously fail in the case that a user built a Debug-only build of the project, now, it checks `$(BUILDTYPE)`, so any build type passes the check.
> build: use `$(BUILDTYPE)` when cleaning coverage files

- BUILDING.md
- tools/bootstrap/windows_boxstarter
- vcbuild.bat
This PR changes the documentation to fit the new compiler on Windows - ClangCL. The main focus is the `BUILDING.md` file. All three `Windows Prerequisites` sections are updated to reflect the compiler change (WinGet configuration already supported it, so no changes there).
In addition, there are changes to `vcbuild.bat` to add the `clang-cl` flag for Node.js v24+ even if not provided. Since v24 will include https://github.com/nodejs/node/pull/57753 (or some other V8 update), compiling with MSVC will result in errors, so IMHO, there is not much use in allowing MSVC compilation at all, although I'm open to suggestions and different opinions on this.
> doc,build,win: update docs with clang

- doc/api/util.md
The actual one is https://nodejs.org/api/cli.html#no_colorany
> doc: fix env variable name in `util.styleText`

- doc/api/esm.md
> doc: fix formatting of `import.meta.filename` section

- .github/codeql-config.yml
CodeQL reports hundreds of errors in V8 tests indicating 'A parse error occurred'. Code quality issues (real or spurious) in V8 tests are not a concern for Node.js. Exclude the tests from CodeQL scans.
> tools: ignore V8 tests in CodeQL scans

- CHANGELOG.md
> doc: mark Node.js 18 as End-of-Life

- lib/url.js
As part of my ongoing review of the `assert` codebase, I started examining the `lib/url.js` file and optimizing some straightforward code that could be further refined for better performance.
Here are the benchmark results for the `benchmarks/url/url-format.js` file:
```bash
OLD:
  url/url-format.js n=25000000 type="slashes": 23,427,608.256140668
url/url-format.js n=25000000 type="file": 15,799,023.358977374
NEW: 
 url/url-format.js n=25000000 type="slashes": 52,260,146.83010853
url/url-format.js n=25000000 type="file": 23,652,608.462879658
```
For type="slashes":
123% improvement
For type="file":
50% improvement
> url: improve performance of the format function

- doc/api/readline.md
From the source code, `readlinePromises.createInterface()` calls
`new Interface()` imported from `internal/readline/interface`, which
works the same as the non-promise version. If non-promise version
accepts options.signal, it should also work for
`readlinePromises.createInterface()`. Hence this information need to be
indicated in the documentation.
Refs: https://github.com/nodejs/node/blob/main/lib/readline/promises.js
> doc: add missing options.signal to readlinePromises.createInterface()

- node.gni
Use `//third_party/simdutf` by default in the GN build instead of `deps/simdutf`. Similar to what's currently done for `//third_party/zlib` for the same reason.
Added in https://chromium-review.googlesource.com/c/v8/node-ci/+/6177642
> build: use //third_party/simdutf by default in GN

- doc/api/events.md
- lib/events.js
Updates the documentation for `emitter.eventNames()` to clarify that it returns` (string | symbol)[]`.
> doc: update return types for eventNames method in EventEmitter

- src/node.cc
- test/common/globals.js
- test/wpt/status/encoding.json
These features are enabled in stable Chrome 136 but not in V8 by default.
> src: enable Float16Array and explicit resource management

- .github/codeql-config.yml
This will remove three of the four "A parse error occurred" issues during JavaScript CodeQL scans. (The fourth occurrence is in our code base, although it might be a false positive. Someone can figure that one out sooner or later, but we certainly can bypass scanning V8 tools.)
> tools: exclude deps/v8/tools from CodeQL scans

- lib/internal/main/watch_mode.js
- test/sequential/test-watch-mode.mjs
Currently the [logic for filtering out watch related flags](https://github.com/nodejs/node/blob/25842c5e35efb45df169e591c775a3c4f853556d/lib/internal/main/watch_mode.js#L42-L55) before passing them to the watch target script is flawed, as it includes any flag (starting with `-`) that follows a flag starting with `--watch` ([code](https://github.com/nodejs/node/blob/25842c5e35efb45df169e591c775a3c4f853556d/lib/internal/main/watch_mode.js#L49-L51)), this allows some watch flags to make it pass the filtering resulting in the generation of multiple watch processes which is both wasteful and can cause duplicate terminal logs (alongside other issues if the target script is side-effectful).
For example if I run
```sh
node --watch --watch index.js
```
the current implementation [will …
> watch: fix watch args not being properly filtered

- doc/api/vm.md
Current alignment mislead doc reader into thinking
`importModuleDynamically` is a separate positional param right next to
`options`, which is incorrect and need to be fixed.
This misalignment is introduced in a PR merged in Feb 2024.
I belive this doc fix applies to node v20 and above.
Refs: https://github.com/nodejs/node/pull/51244
> doc: fix misaligned options in vm.compileFunction()

- test/pummel/test-heapdump-http2.js
By the time the response event is emitted on the client's side, the file may have already been fully piped and the stream pipe may have been destroyed, so the test should not look for the stream pipe in the snapshot.
This doesn't seem to reproduce in the CI (the CI is seeing a timeout caused by the deadlock instead) but locally when I was trying to reproduce the deadlock with with `tools/test.py -J --repeat=1000 pummel/test-heapdump-http2` using a shared library build on macOS, this failure comes up first instead of the deadlock because the uv_try_write done for writing the file finishes too fast & synchronously - maybe because it's already cached under repeated runs - destroying the stream pipe already before the snapshot is taken.
> test: reduce flakiness in test-heapdump-http2

- test/sequential/test-watch-mode.mjs
Earlier I merged https://github.com/nodejs/node/pull/57936 which was out of sync with main so it didn't include the watch completion messages introduced in https://github.com/nodejs/node/pull/57926
This causes the watch tests to be failing on main, this PR is addressing this issue
I'm really sorry for the inconvenience :bow:
> test: fix watch tests not including completion messages

- vcbuild.bat
Escape the `>` metachar in vcbuild.bat to avoid that a file named as the major node version number is created.
Refs: #57991
> build: escape > metachar in vcbuild

- src/node_buffer.cc
Self-explanatory cc @nodejs/buffer
> buffer: use constexpr where possible

- src/util.h
I added this class in 823d86c47ce15fba8875fcebd412593b02aab362 in 2018 when we did not yet use `std::optional`. The last uses were removed in 5b9bf39b47afcf26aaad810eec2ba8bdff904d4c, so remove it.
Refs: https://github.com/nodejs/node/pull/24234
Refs: https://github.com/nodejs/node/pull/55368
> src: remove NonCopyableMaybe

- lib/internal/async_local_storage/async_context_frame.js
- test/async-hooks/test-async-local-storage-gcable.js
- test/parallel/test-async-local-storage-isolation.js
Avoid that one `AsyncLocalStore` instance changes the state of another `AsyncLocalStore` instance by restoring only the owned store instead the complete `AsyncContextFrame`.
> async_hooks: ensure AsyncLocalStore instances work isolated

- common.gypi
- deps/v8/src/compiler/backend/code-generator.cc
- deps/v8/src/diagnostics/perf-jit.cc
- deps/v8/src/diagnostics/perf-jit.h
- deps/v8/src/flags/flag-definitions.h
- deps/v8/src/logging/log.cc
- deps/v8/src/logging/log.h
Manual backport for v22.x of the changes in https://github.com/nodejs/node/pull/58010 which has been closed in favor of the V8 upgrade https://github.com/nodejs/node/pull/58070 which already contains this change.
Enable --perf-prof flag on MacOS
MacOS actually can share the implementation of {PerfJitLogger} with
Linux. From the issue 40112126, only Fuzzer tests on Windows ran
into UNREACHABLE/FATAL because of the unimplemented {PerfJitLogger}.
This CL enables the flag --perf-prof on MacOS.
Bug: 403765219
Change-Id: I97871fbcc0cb9890c51ca14fd7a6e65bd0e3c0d2
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6385655
Reviewed-by: Clemens Backes <clemensb@chromium.org>
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Auto-Submit: 杨文明 …
> [v22.x backport] deps: V8: backport e5dbbbadcbff

- doc/api/cli.md
> doc: add history entries to `--input-type` section

- lib/internal/crypto/cipher.js
- src/crypto/crypto_cipher.cc
- src/crypto/crypto_cipher.h
Now that `CipherBase.init` has been removed, instances of the class are always initialized by a call to `initiv` immediately after the constructor has returned. Instead of calling into C++ twice from `createCipherBase`, pass all required arguments to the constructor and fully initialize the instance before the constructor returns.
> crypto: merge CipherBase.initiv into constructor

- benchmark/buffers/buffer-iterate.js
- benchmark/buffers/buffer-read-with-byteLength.js
- benchmark/buffers/buffer-read.js
- benchmark/buffers/buffer-slice.js
- benchmark/buffers/buffer-write.js
- doc/api/buffer.md
- doc/api/cli.md
- doc/api/deprecations.md
- doc/contributing/writing-and-running-benchmarks.md
- doc/node.1
- lib/buffer.js
- src/node_options.cc
- test/parallel/test-buffer-alloc.js
- test/parallel/test-buffer-bytelength.js
- test/parallel/test-buffer-failed-alloc-typed-arrays.js
- test/parallel/test-buffer-inspect.js
- test/parallel/test-buffer-no-negative-allocation.js
- test/parallel/test-buffer-over-max-length.js
- test/parallel/test-buffer-slow.js
- test/parallel/test-buffer-tostring-rangeerror.js
- test/parallel/test-buffer-zero-fill-cli.js
- test/parallel/test-icu-transcode.js
- test/pummel/test-buffer-large-size-slowbuffer.js
This reverts commit 647175ee0b8ca19d6f315216c879b1dc89ad2759.
The API in question was runtime-deprecated (#55175) and EOLd (#58008 which i'm reverting here) in the same major release. The intended cycle is that it gets runtime-deprecated as a major, and then EOLd in another later major.
Despite best efforts to detect it in the EOL PR there is breakage in the jsonwebtoken > jws > jwa dependency chain (29-30M weekly downloads on jwa).
This PR reverts to the [runtime-deprecation state](https://github.com/nodejs/node/pull/55175) that was pending release with 24.0.0, EOL shouldn't have landed yet.
https://openjs-foundation.slack.com/archives/C019MGJQ8RH/p1746596637445769
We would re-land the EOL and ship it with a future major release after this revert.
> Revert "buffer: move SlowBuffer to EOL"

- eslint.config.mjs
- test/parallel/test-assert-partial-deep-equal.js
- test/parallel/test-assert-typedarray-deepequal.js
- test/parallel/test-util-types.js
- test/parallel/test-v8-serdes.js
- test/wpt/test-webcrypto.js
No `dont-land-on-v24.x` assuming that https://github.com/nodejs/node/commit/f75a1265a8eef5c2058be1fde6eefa4ca0b5990f gets included in v24.x
> test: remove Float16Array flag

- src/string_bytes.cc
- src/string_bytes.h
This change refactors `StringBytes::WriteUCS2()` in multiple ways.
The `flags` argument being passed to `WriteUCS2()` is not useful: the only really relevant flag is `NO_NULL_TERMINATION` since V8 ignores `REPLACE_INVALID_UTF8`, `HINT_MANY_WRITES_EXPECTED`, and `PRESERVE_ONE_BYTE_NULL` for UTF-16 strings. However, `WriteUCS2()` might not null-terminate the result correctly regardless of whether `NO_NULL_TERMINATION` is set because it makes multiple calls to `String::Write()` internally. For these reasons, this patch removes the `flags` argument entirely and always assumes `NO_NULL_TERMINATION`.
Next, this patch replaces the calls to the deprecated function `String::Write()` with calls to the new function `String::WriteV2()`, which always succeeds and always writes a predictable number of …
> src: refactor WriteUCS2 and remove flags argument

- lib/internal/test_runner/coverage.js
- test/fixtures/test-runner/coverage/bar.mts
- test/fixtures/test-runner/coverage/foo.mts
- test/fixtures/test-runner/output/typescript-coverage.mts
- test/fixtures/test-runner/output/typescript-coverage.snapshot
- test/parallel/test-runner-output.mjs
Fixes: https://github.com/nodejs/node/issues/58119
> lib: fix sourcemaps with ts module mocking

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/module_job.js
- src/debug_utils.h
- src/module_wrap.cc
- src/module_wrap.h
- test/es-module/test-require-module-instantiated.mjs
- test/fixtures/es-modules/require-module-instantiated/a.mjs
- test/fixtures/es-modules/require-module-instantiated/b.cjs
- test/fixtures/es-modules/require-module-instantiated/c.mjs
When require(esm) encounters a cached module job that is instantiated but not yet evaluated, run the evaluation. This catches an edge case previously missed in https://github.com/nodejs/node/pull/57187.
Fixes: https://github.com/nodejs/node/issues/58061
> module: handle instantiated async module jobs in require(esm)

- src/node.cc
Node calls tcsetattr on exit to reset the tty to its state on program start. Good idea in general but tcsetattr can fail for a number of reasons and since there really isn't anything we can do about it at that point, simply ignore the error instead of aborting with an inscrutable error message.
Most of the time it'll be fine because the most common failure is when the user has already logged off and there isn't anything to restore in the first place.
Fixes: https://github.com/nodejs/node/issues/51519
> src: remove overzealous tcsetattr error check

- src/node_http_parser.cc
I've added TODOs to all functions that can be added a v8 fast api.
> http: remove unused functions and add todos

- src/util.cc
Since `String::Write()` is deprecated, use `String::WriteV2()` instead.
> src: use String::WriteV2() in TwoByteValue

- test/parallel/test-http2-client-socket-destroy.js
The socket can be destroyed by the other peer while data is still being written. Add a listener for the `'error'` event.
> test: deflake test-http2-client-socket-destroy

- src/debug_utils.cc
GetLoadedLibraries is used in process.report.GetReport to generate a list of loaded libraries. This PR fixes the following:
* Random failures when retrieving module file paths
* Retrieve only up to half the max file path length intended
* Allocating unused memory for module handles
* Memory leak from converting file path wchar* strings to utf8 std::strings
--
1) **GetModuleFileNameExW can fail randomly**: Microsoft's Documentation recommends using GetModuleFileNameW over GetModuleFileNameExW when a process is trying to get a list of it's own dlls. GetModuleFileNameExW can fail unexpectedly for some calls.
<details>
<summary>Sources from Docs + Raymond Chen</summary>
* "To retrieve the name of a module in the current process, use the …
> src: fix bugs and refactor NativeSymbolDebuggingContext::GetLoadedLibraries

- benchmark/buffers/buffer-iterate.js
- benchmark/buffers/buffer-read-with-byteLength.js
- benchmark/buffers/buffer-read.js
- benchmark/buffers/buffer-slice.js
- benchmark/buffers/buffer-write.js
- doc/api/buffer.md
- doc/api/cli.md
- doc/api/deprecations.md
- doc/contributing/writing-and-running-benchmarks.md
- doc/node.1
- lib/buffer.js
- src/node_options.cc
- test/parallel/test-buffer-alloc.js
- test/parallel/test-buffer-bytelength.js
- test/parallel/test-buffer-failed-alloc-typed-arrays.js
- test/parallel/test-buffer-inspect.js
- test/parallel/test-buffer-no-negative-allocation.js
- test/parallel/test-buffer-over-max-length.js
- test/parallel/test-buffer-slow.js
- test/parallel/test-buffer-tostring-rangeerror.js
- test/parallel/test-buffer-zero-fill-cli.js
- test/parallel/test-icu-transcode.js
- test/pummel/test-buffer-large-size-slowbuffer.js
This re-lands #58008 for the next https://github.com/nodejs/node/labels/semver-major as originally intended.
cc @jasnell
> buffer: move SlowBuffer to EOL

- lib/internal/fs/dir.js
- test/parallel/test-fs-opendir.js
It's the promise version, it should return a rejected Promise, not throw.
> fs: ensure `dir.read()` does not throw synchronously

- lib/fs.js
- lib/internal/fs/promises.js
- lib/path.js
In #57513 `fs.glob` was marked as stable, but that was only in the documentation, so if it's considered stable, it should not emit experimental warnings.
> fs: glob is stable, so should not emit experimental warnings

- doc/api/diagnostics_channel.md
- lib/internal/http2/core.js
- test/parallel/test-diagnostics-channel-http2-client-stream-created.js
> http2: add diagnostics channel 'http2.client.stream.created'

- doc/api/fs.md
- lib/internal/fs/dir.js
- test/parallel/test-fs-promises-file-handle-dispose.js
> fs: add support to `Dir` for explicit resource management

- doc/api/fs.md
- lib/internal/fs/glob.js
- test/parallel/test-fs-glob.mjs
For the sake of consistency, all the Node.js APIs that take a path also accept `URL` instances.
> fs: add support for `URL` for `fs.glob`'s `cwd` option

- test/message/test-testpy-env-var-via-comment.js
- test/message/testcfg.py
- test/parallel/test-testpy-env-var-via-comment.js
- test/pseudo-tty/test-testpy-env-var-via-comment.js
- test/pseudo-tty/testcfg.py
- test/testpy/__init__.py
- tools/test.py
It should address #58179 by adding support for environment variables via comments.
I've not run the entire test suite, only a subset.
A full CI run will be needed to catch any potential regressions!
> tools: support environment variables via comments

- .github/workflows/lint-release-proposal.yml
- .github/workflows/notify-on-push.yml
Not having this permission is OK because the repo is public, but on private forks (e.g. the one where security releases are getting prepared), it fails at the checkout step.
> tools: add read permission to workflows that read contents

- typings/primordials.d.ts
Add missing typings for the `TypedArray` domain we used in the codebase.
This enables typing intellisense for typed array. e.g. 
```
const buffer = Buffer.allocUnsafe(length); // FastBuffer extends Uint8Array
TypedArrayPrototypeFill(buffer, 0, pos, length);
```
will be evaluated to
```
const TypedArrayPrototypeFill: <FastBuffer>(self: FastBuffer, value: number, start?: number, end?: number) => FastBuffer
```
> typings: add missing typings for `TypedArray`

- deps/ncrypto/ncrypto.cc
`OPENSSL_TLS_SECURITY_LEVEL` isn't defined at all in BoringSSL and will cause compilation failures.
Ref https://github.com/nodejs/node/pull/57323
Ref https://github.com/nodejs/node/pull/56601
See [boringssl search results](https://source.chromium.org/search?q=OPENSSL_TLS_SECURITY_LEVEL&sq=package:chromium)
> crypto: handle missing OPENSSL_TLS_SECURITY_LEVEL

- doc/api/n-api.md
This edge case is ambiguous and it is unclear from the existing documentation what happens in this case.
> doc: clarify napi_get_value_string_* for bufsize 0

- src/node_contextify.cc
This PR is removing the `shouldRetryAsESM` internal binding, which I believe is no longer used.
I believe that the binding stopped being used in https://github.com/nodejs/node/pull/52047.
> src: remove unused `shouldRetryAsESM` internal binding

- src/node_messaging.cc
- src/node_messaging.h
- typings/internalBinding/messaging.d.ts
This PR is removing the `checkMessagePort` internal binding, which I believe is no longer used.
I believe that the binding stopped being used in https://github.com/nodejs/node/pull/52370.
> src: remove unused `checkMessagePort` internal binding

- configure.py
I was getting error about libuvwasi not found, this patch makes the error go away.
> build: fix uvwasi pkgname

- doc/api/diagnostics_channel.md
Fixes: https://github.com/nodejs/node/issues/58234
> doc: update stability status for diagnostics_channel to experimental

- .mailmap
- README.md
Fixes: https://github.com/nodejs/node/issues/58088
> doc: add puskin to collaborators

- doc/contributing/commit-queue.md
update the commit-queue contributing documentation by:
- removing the references of the feature being experimental
- clarifying that it applies to mergeable pull requests
> [!Note]
> I'm proposing to remove the references of the feature being experimental since it's been 
> implemented 5 years ago and I think that it's widely used, so I think that it can be considered
> stable at this point
> doc: update commit-queue documentation

- lib/internal/main/watch_mode.js
- test/sequential/test-watch-mode-watch-flags.mjs
I'm re-introducing this change that previously landed in https://github.com/nodejs/node/pull/57936 but got reverted in https://github.com/nodejs/node/pull/58190.
I believe that one of the main reasons for reverting the PR was the fact that when it landed it didn't include the changes that I however later introduced in https://github.com/nodejs/node/pull/58183 (that also got reverted as part of #58190) (making me wonder if the revert was actually completely necessary after all :thinking:).
Another reason for the revert was that I was adding the tests to the `test/sequential/test-watch-mode.mjs` file (which is marked as flaky) instead of creating a new test file.
I am not sure if there were other issues associated to the original PR, however I am opening this PR that reintroduces the …
> watch: fix watch args not being properly filtered (second attempt)

- test/parallel/test-repl-null-thrown.js
Super minor, but I noticed this rouge `console.log` and figured that we might just as well get rid of it :slightly_smiling_face:
> test: remove unnecessary `console.log` from test-repl-null-thrown

- test/parallel/test-child-process-stdout-flush-exit.js
This commit was added by @addaleax to fix the CI in https://github.com/nodejs/node/pull/58124, opening it as a separate PR as the automation keeps removing it from the other PR. This should be landed manually so the commit authorship is credited to Anna and not myself.
> test: reduce iteration count in test-child-process-stdout-flush-exit

- src/crypto/crypto_hash.cc
- src/crypto/crypto_hash.h
This PR is removing the `internalVerifyIntegrity` internal binding, which I believe is no longer used.
I believe that the binding stopped being used in https://github.com/nodejs/node/pull/52583 (see [`lib/internal/policy/manifest.js` line 30](https://github.com/nodejs/node/pull/52583/files#diff-2f71d951c9d2207a687adc8c02df2cd06c725d0a2fae6e02c6c57ba14a28c807L30)).
> src: remove unused `internalVerifyIntegrity` internal binding

- doc/api_assets/style.css
This should make https://nodejs.org/api/documentation.html look less weird.
> doc: make Stability labels not sticky in Stability index

- doc/api/diagnostics_channel.md
- lib/internal/http2/core.js
- test/parallel/test-diagnostics-channel-http2-client-stream-start.js
> http2: add diagnostics channel 'http2.client.stream.start'

- doc/api/permissions.md
Fixes: https://github.com/nodejs/node/issues/58287
> doc: remove comma delimiter mention on permissions doc

- doc/api/crypto.md
The current documentation lists the `callback` argument of `crypto.generatePrime` as optional (it's surrounded by square brackets), but this is incorrect - calling the function without a callback will result in an error:
```
> crypto.generatePrime(3)
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received undefined
at Object.generatePrime (node:internal/crypto/random:476:3) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
For the record, the correct way to generate a prime synchronously, without a callback, is to use the `generatePrimeSync` API.
This PR fixes the documentation and marks the callback argument as mandatory. The `options` (second) argument, is indeed optional, and is marked as such.
Fixes: https://github.com/nodejs/node/issues/58298
> doc: mark the callback argument of crypto.generatePrime as mandatory

- .github/codeql-config.yml
This should solve https://github.com/nodejs/security-wg/issues/1453#issuecomment-2863222963
> tools: ignore deps and benchmark folder

- lib/internal/modules/esm/module_job.js
- test/es-module/test-require-module-error-catching.js
This PR copies the error message used for cjs global-like import errors from `ModuleJob` to `ModuleJobSync` to cover more cases.
> module: clarify cjs global-like error on ModuleJobSync

- src/module_wrap.cc
- test/parallel/test-vm-module-dynamic-import-promise.js
A `import` call should returns a promise created in the context where
the `import` was called, not the context of `importModuleDynamically`
callback.
This is also a requirement in ECMA262 https://tc39.es/ecma262/#sec-evaluate-import-call
step 7 and 14:
```
13.3.10.2 EvaluateImportCall ( specifierExpression [ , optionsExpression ] )
...
7. Let promiseCapability be ! NewPromiseCapability(%Promise%).
...
14. Return promiseCapability.[[Promise]].
```
Fixes: https://github.com/nodejs/node/issues/53575
> vm: import call should return a promise in the current context

- configure.py
Since https://github.com/nodejs/node/pull/24870, we only support llhttp as HTTP parser, let's use this as default libname – and `libllhttp` as pkgname.
> build: fix defaults for shared llhttp

- src/js_native_api_v8.cc
Since `String::Write()` is deprecated, use `String::Write2()` instead. That requires us to compute the correct number of characters ahead of time but removes the need for dealing with the return value.
> node-api: use WriteV2 in napi_get_value_string_utf16

- src/js_native_api_v8.cc
Replace usage of deprecated `WriteOneByte` with `WriteOneByteV2`.
> node-api: use WriteOneByteV2 in napi_get_value_string_latin1

- .github/workflows/test-linux.yml
This is ignored in test-macos, however the change was not ported to test-linux.
> meta: ignore mailmap changes in linux ci

- .mailmap
- README.md
Fixes https://github.com/nodejs/node/issues/57410
> doc: add JonasBa to collaborators

- lib/internal/worker/io.js
This fixes names for:
- `worker_threads.MessagePort.prototype.hasRef` (was: anonymous)
- `worker_threads.MessagePort.prototype.close` (was: anonymous)
- `worker_threads.MessagePort.prototype.[kCreateEvent]` (was: `value`)
> worker: give names to `MessagePort` functions

- src/node_buffer.cc
`Utf8Length()` is deprecated and was replaced during the V8 update (0e68481bf82), but 084a91291e5 introduced a new occurrence.
Refs: https://github.com/nodejs/node/pull/58070
Refs: https://github.com/nodejs/node/pull/58048
> buffer: use Utf8LengthV2() instead of Utf8Length()

- doc/api/diagnostics_channel.md
- lib/internal/http2/core.js
- test/parallel/test-diagnostics-channel-http2-client-stream-finish.js
> http2: add diagnostics channel 'http2.client.stream.finish'

- doc/api/diagnostics_channel.md
- lib/net.js
- test/parallel/test-diagnostics-channel-net-client-socket-tls.js
- test/parallel/test-diagnostics-channel-net.js
Previously, the 'net.client.socket' diagnostics channel was only published to when `net.connect()` was called. This change ensures the message is also published for the following calls:
- `net.createConnection()`
- `net.Socket#connect()`
- `tls.connect()`
> net: always publish to 'net.client.socket' diagnostics channel

- lib/internal/main/repl.js
- lib/internal/readline/interface.js
- lib/internal/repl/history.js
- lib/repl.js
- test/parallel/test-readline-interface.js
- test/parallel/test-readline-promises-interface.js
- test/parallel/test-readline-promises-tab-complete.js
- test/parallel/test-repl-close.js
- test/parallel/test-repl-import-referrer.js
- test/parallel/test-repl-no-terminal.js
- test/parallel/test-repl-uncaught-exception-async.js
This PR makes it so that calling `pause()`, `resume()` or `write()` on a closed readline interface results in `ERR_USE_AFTER_CLOSE` errors being thrown (following the same behavior as `question()`)
___
> [!Note]
> This PR reintroduces the changes committed in https://github.com/nodejs/node/pull/57680 but reverted in https://github.com/nodejs/node/pull/58024 they also include @lpinca's [suggested test changes](https://github.com/nodejs/node/pull/58014#issuecomment-2830647559) to prevent [test flakiness](https://github.com/nodejs/node/issues/58009).
>
> The reason why this was reverted was because of REPL still calling `pause()` and `resume()` even after it has been closed, which I am addressing that here (the lib repl files changes are specifically for that), just to be extra sure I am …
> readline: add stricter validation for functions called after closed (second attempt)

- test/parallel/test-crypto-authenticated.js
Both `createCipher()` and `createDecipher()` were removed in Node.js 22.
> test: remove references to create(De|C)ipher

- src/tty_wrap.cc
As of 0315283cbd, the libuv `UV_TTY_MODE_RAW_VT` flag is available for applications on Windows in order to have the terminal itself translate keypresses into control sequences, rather than libuv. This aligns the TTY setup more closely with POSIX platforms, and enables handling of control sequences in applications which libuv is not able to emit at all.
Since the Node.js `readline` implementation already handles divergences between different control character sequences for the same keypresses (e.g. `<ESC>[[A` vs `<ESC>OP` for the F1 key), this should not present a visible change for typical Node.js TTY applications.
Testing is handled on the libuv side, and not easily feasible with Node.js’s current TTY test setup.
> tty: use terminal VT mode on Windows

- doc/api/diagnostics_channel.md
- lib/internal/http2/core.js
- test/parallel/test-diagnostics-channel-http2-client-stream-close-error.js
- test/parallel/test-diagnostics-channel-http2-client-stream-close.js
> http2: add diagnostics channel 'http2.client.stream.close'

- test/parallel/test-crypto-authenticated.js
Add ChaCha20-Poly1305 to the algorithms for which we ensure that the authentication tag can be set either before or after calling `update()`.
Change the key size to 256 bits for all algorithms so that we can use the same key across all three algorithms being tested.
> test: add chacha20-poly1305 to auth tag order test

- test/parallel/test-crypto-authenticated.js
This loop used to iterate over two elements, but since commit 215f4d04b7a9de0b04bb430d191abf5f79d3494d, it only iterates over a single element. Therefore, move the test out of the loop body and remove the loop itself.
Refs: https://github.com/nodejs/node/pull/50973
> test: remove loop over single element

- doc/api/inspector.md
- lib/inspector.js
- src/inspector/network_agent.cc
- src/inspector/network_agent.h
- src/inspector/node_protocol.pdl
- src/inspector/node_string.cc
- src/inspector/node_string.h
- test/parallel/test-inspector-emit-protocol-event.js
- test/parallel/test-inspector-network-data-received.js
Add `inspector.Network.dataReceived` API to allow DevTools to monitor received http data chunks.
Refs: https://github.com/nodejs/node/issues/53946
Refs: https://github.com/nodejs/undici/issues/4166
> inspector: add protocol method Network.dataReceived

- node.gyp
- src/README.md
- src/cppgc_helpers-inl.h
- src/cppgc_helpers.cc
- src/cppgc_helpers.h
- src/memory_tracker-inl.h
- src/memory_tracker.h
- src/node_contextify.h
- src/node_realm-inl.h
- src/node_realm.cc
- src/node_realm.h
src: track cppgc wrappers with a list in Realm
This allows us to perform cleanups of cppgc wrappers that rely
on a living Realm during Realm shutdown. Otherwise
the cleanup may happen during object destruction, which can
be triggered by GC after Realm shutdown, leading to invalid
access to Realm.
The general pattern for this type of non-trivial destruction is
designed to be:
```c++
class MyWrap final : CPPGC_MIXIN(MyWrap) {
public:
~MyWrap() { this->Finalize(); }
void Clean(Realm* realm) override {
// Do cleanup that relies on a living Realm. This would be
// called by CppgcMixin::Finalize() first during Realm shutdown,
// while the Realm is still alive. If the destructor calls
// Finalize() again later during garbage collection that happens after
// Realm shutdown, Clean() would be …
```
> src: track cppgc wrappers with a list in Realm

- test/parallel/test-http2-debug.js
Use spawnSyncAndAssert() so that the stderr is logged when it doesn't match expectations.
Refs: https://github.com/nodejs/node/issues/58353
> test: show more information in test-http2-debug upon failure

- test/parallel/test-crypto-authenticated.js
I believe that OCB should work in FIPS mode, and only CCM should be skipped here.
> test: do not skip OCB decryption in FIPS mode

- BUILDING.md
- common.gypi
- configure.py
- deps/cares/cares.gyp
- deps/cares/config/openharmony/ares_config.h
- deps/openssl/openssl-cl_asm.gypi
- deps/openssl/openssl-cl_asm_avx2.gypi
- deps/openssl/openssl-cl_no_asm.gypi
- deps/openssl/openssl-cli.gypi
- deps/openssl/openssl-fips_asm.gypi
- deps/openssl/openssl-fips_asm_avx2.gypi
- deps/openssl/openssl-fips_no_asm.gypi
- deps/openssl/openssl_asm.gypi
- deps/openssl/openssl_asm_avx2.gypi
- deps/openssl/openssl_no_asm.gypi
- deps/uv/uv.gyp
- deps/zlib/zlib.gyp
- node.gyp
- node.gypi
- tools/v8_gypfiles/d8.gyp
- tools/v8_gypfiles/features.gypi
- tools/v8_gypfiles/toolchain.gypi
- tools/v8_gypfiles/v8.gyp
[OpenHarmony](https://www.openharmony.cn/) is an open-source operating system. It supports running on hardware such as phones, tablets, PCs, and embedded devices.
OpenHarmony supports the following system types: 
* Mini system (device memory >= 128 KiB)
* Small system (device memory >=1 MiB)
* Standard system (device memory >= 128 MiB)
We only need to focus on the OpenHarmony standard system, as the other two types are insufficient in memory to run Node.js
The OpenHarmony standard system uses the Linux kernel but does not use the GNU userland. This architecture is similar to that of the Android operating system. Therefore, my adaptation process for OpenHarmony is also similar to that for Android.
This adaptation only focuses on the arm64 architecture, as I don't have other environments to …
> build: add support for OpenHarmony operating system

- lib/eslint.config_partial.mjs
The rule often makes code less readable by requiring the additional brackets. I am also not aware that this rule ever caught a real issue in our code.
I have definitely stumbled upon it multiple times and I had to adjust my code to add the brackets due to not thinking about that initially.
If we want to have this rule, I would suggest to check for tenaries with other operators such as `['?:', '||']`, `['?:', '&&']`.
Refs: https://eslint.org/docs/latest/rules/no-mixed-operators
> lib: remove no-mixed-operators eslint rule

- tools/test.py
[`optparse`](https://docs.python.org/3.10/library/optparse.html) has been deprecated since Python 3.2 / 2.7, so we should upgrade to the currently maintained and recommended `argparse`. It's mostly a drop-in replacement.
> test: switch from deprecated `optparse` to `argparse`

- test/parallel/test-crypto-authenticated.js
This test, so far, has been ensuring that `setAuthTag()` can be called either before or after `update()`. This commit expands the test to ensure that `setAuthTag()` can be called before, between, or after calls to `setAAD()` and `update()`, and it also covers scenarios in which `update()` is never called (e.g., in case of GMAC).
> test: test reordering of setAAD and setAuthTag

- lib/internal/bootstrap/node.js
- src/node_config.cc
- test/parallel/test-crypto-getcipherinfo.js
- test/parallel/test-crypto-hkdf.js
- test/parallel/test-process-features.js
- test/parallel/test-tls-getprotocol.js
- test/parallel/test-tls-write-error.js
This PR exposes `process.features.openssl_is_boringssl`. This allows knowing which crypto library is in use at the JS level - previously the only way to know was to check the version string, which would be `0.0.0` when built with BoringSSL.
This also sets the stage for adapting some of Node.js' crypto tests to run and pass with both BoringSSL and OpenSSL.
> crypto: expose `process.features.openssl_is_boringssl`

- test/parallel/test-crypto-stream.js
- test/parallel/test-crypto.js
- test/parallel/test-tls-alert-handling.js
As in title - this PR makes crypto tests work with BoringSSL. Similar to previous PRs.
> test: make crypto tests work with BoringSSL

- tools/install.py
When building with `--shared`, `ninja` will output the `libnode.so` into a `{build_dir}/lib` directory, not in the root `{build_dir}`. This fixes the install script to look for it in the correct place.
---
Found during review of a Fedora rpm, where we apparently been moving the `libnode.so` manually to the root of the build directory manually this entire time. Let's see if we can stop doing that. :sweat_smile:
> build: look for libnode.so in lib subdirectory

- doc/api/process.md
This PR fixes the order of functions in the `process` API documentation. 
Specifically, it moves the documentation of `availableMemory` and `execve` to the right place, so the functions documented in this document are ordered alphabetically.
Fixes: https://github.com/nodejs/node/issues/58402
> doc: fix the order of the process API doc

- src/node_report.cc
use `uv_getrusage_thread` in report.
> report: use uv_getrusage_thread in report

- src/node_i18n.cc
Not sure if that's the correct fix, but that seems to unblock me.
> src: fix build when using shared simdutf

- lib/internal/fs/cp/cp-sync.js
- src/env-inl.h
- src/env.h
- src/node_file.cc
- typings/internalBinding/fs.d.ts
move the logic in `cpSync` that overrides existing dest files from JavaScript to C++ increasing its performance
___
This is the type of perf improvement that this change makes:
> fs: improve `cpSync` dest overriding performance

- benchmark/fs/bench-cpSync.js
This PR enhances the benchmark for the `fs.cpSync` function to measure the performance of the dereference and force options.
Key changes:
- Added `dereference` and `force` options to the `bench-cpSync.js` file.
- Implemented a `prepareTestDirectory` function that creates a test directory with symbolic links.
- Added pre-copy logic for testing the force option.
> benchmark: add dereference and force options to fs.cpSync

- test/pummel/test-blob-slice-with-large-size.js
The test only cares about whether a size outside the range of the 32-bit signed integers works with Blob.prototype.slice(). If it fails due to allocation failure when the system does not have enough memory, the test should just be skipped. The test previously only skipped the test when the allocation failure happens during allocation of the buffer source, but it could also happen during Blob.prototype.slice().
Fixes: https://github.com/nodejs/node/issues/57235
> test: fix missing edge case in test-blob-slice-with-large-size

- test/parallel/test-buffer-tostring-rangeerror.js
If the buffer allocation fails due to insufficient memory, there is no point continue testing toString().
https://github.com/nodejs/node/pull/58142 is not sufficient to skip the test because `require('os').totalmem()` > 1.75GB is not sufficient to safe guard from allocation failure. It's better to directly skip on a case-by-case basis.
> test: skip in test-buffer-tostring-rangeerror on allocation failure

- test/parallel/test-buffer-tostring-4gb.js
- test/parallel/test-buffer-tostring-range.js
If the test cannot allocate a buffer over 4GB, there is no point continue testing toString() on it.
This also split the test case to a different file for clarity and reduce interference with other cases.
Fixes: https://github.com/nodejs/node/issues/56726
> test: fix test-buffer-tostring-range on allocation failure

- doc/api/diagnostics_channel.md
- lib/internal/http2/core.js
- test/parallel/test-diagnostics-channel-http2-server-stream-created.js
> http2: add diagnostics channel 'http2.server.stream.created'

- doc/api/fs.md
- lib/_http_server.js
- lib/dgram.js
- lib/https.js
- lib/internal/fs/dir.js
- lib/internal/fs/promises.js
- lib/internal/http2/core.js
- lib/internal/readline/interface.js
- lib/internal/streams/readable.js
- lib/internal/streams/writable.js
- lib/net.js
This brings more consistency to `[Symbol.dispose]` and `[Symbol.asyncDispose]` functions across the core, and fulfills two things:
1. [The description of the `Disposable` Interface](https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#the-disposable-interface) states that the function should return `undefined`. This PR removes `return`s that resolve with `null` or even pass the value returned by the named cleanup function.
2. The dispose function should explicitly appear in the stack trace, hence it should not be an alias to the named function.
Consider this snippet:
```mjs
import { opendir } from 'node:fs/promises';
{
await using dir = await opendir('.');
try {
// lots of code
} finally {
await dir.close(); // line 8
}
} // line 10
```
With this change, the …
> lib: make ERM functions into wrappers returning undefined

- lib/internal/http2/core.js
This is a followup cleanup on a previous PR. Current source code and doc
explicitly states that `selectPadding` has been removed for all exports.
Refs: https://github.com/nodejs/node/pull/29144
Refs: https://nodejs.org/api/http2.html
> http2: remove no longer userful options.selectPadding

- src/node_sqlite.cc
- test/parallel/test-sqlite-aggregate-function.mjs
This commit updates the aggregate function 'result' callback handling to not crash when an exception is thrown.
Fixes: https://github.com/nodejs/node/issues/58425
> sqlite: handle thrown errors in result callback

- doc/api/errors.md
- lib/internal/errors.js
- lib/internal/webstreams/compression.js
- lib/zlib.js
- test/parallel/test-zlib-type-error.js
- test/wpt/status/compression.json
Close #58247
Introduce `ERR_TRAILING_JUNK_AFTER_STREAM_END` error to handle unexpected data after the end of a compressed stream. This ensures proper error reporting when decompressing deflate or gzip streams with trailing junk. Added tests to verify the behavior.
> stream: making DecompressionStream spec compliant for trailing junk

- doc/api/esm.md
- lib/internal/main/worker_thread.js
- lib/internal/modules/esm/initialize_import_meta.js
- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/translators.js
- lib/internal/modules/esm/utils.js
- lib/internal/worker.js
- test/es-module/test-esm-import-meta-main-eval.mjs
- test/es-module/test-esm-import-meta-main.mjs
- test/es-module/test-esm-import-meta.mjs
- test/fixtures/es-modules/import-meta-main.mjs
Implements #57226
This PR supersedes #32223
Fixes: https://github.com/nodejs/node/issues/57226
> esm: implement import.meta.main

- doc/api/zlib.md
- lib/zlib.js
`Z_TREES` is never exposed on `DefineZlibConstants()`, hence it shall be
removed.
This fix is applicable to v18+.
Refs: https://github.com/nodejs/node/blob/main/src/node_zlib.cc
> zlib: remove mentions of unexposed Z_TREES constant

- test/parallel/test-crypto-authenticated.js
This change should have no effect since the test does not appear to emit any warnings. If there are warnings, we probably should handle them properly instead of passing this flag to the runtime.
Refs: https://github.com/nodejs/node/pull/35093
> test: remove --no-warnings flag

- benchmark/fs/bench-cpSync.js
https://github.com/nodejs/node/pull/58278 added some options to `benchmark/fs/bench-cpSync.js`, however after the changes the benchmark fails with an `ERR_FS_CP_EINVAL` error:
I believe this is surfacing an actual bug in the cp/cpSync logic (see: https://github.com/nodejs/node/issues/58468) (please check out the issue and let me know if I am getting something wrong here :pray:) so here I am simply skipping the `force: true` option in the benchmarking file to make the benchmark actually work until the underlying issue is resolved.
> benchmark: fix broken fs.cpSync benchmark

- doc/api/repl.md
- lib/internal/main/repl.js
- lib/internal/readline/interface.js
- lib/internal/repl.js
- lib/internal/repl/history.js
- lib/repl.js
- test/parallel/test-repl-persistent-history.js
- test/parallel/test-repl-programmatic-history-setup-history.js
Refactored and decoupled the history logic into its own separate module and made both REPL and readline depend on it as little as possible, still not breaking functionality.
Updated the `repl.setupHistory` function to accept more parameters than just a string for the history file path and a callback. Before this change you had to manually update the REPL instance to accept history parameters. With the decoupling of this PR, you can now achieve the same result calling the updated method:
```javascript
repl.setupHistory({
filePath: './path/to/history/file',
size: 50,
removeHistoryDuplicates: true,
onHistoryFileLoaded: callback,
});
```
> repl: extract and standardize history from both repl and interface

- doc/api/cli.md
- doc/api/quic.md
- doc/api/test.md
- src/node_platform.h
- src/quic/session.cc
- src/quic/session.h
- src/quic/sessionticket.h
- src/quic/streams.cc
fix typos
- `Snapsnot` → `Snapshot` 
- `maxumum` → `maximum `
- `memeber ` → `member`
- `acutually` → `actually`
- `processsing` → `processing`
- `sesson` → `session`
-  `receied` → `received`
> doc,src,test: fix typos

- lib/internal/inspector/network_http.js
- lib/internal/inspector/network_undici.js
- src/inspector/network_agent.cc
- src/inspector/node_protocol.pdl
- test/parallel/test-inspector-emit-protocol-event.js
- test/parallel/test-inspector-network-content-type.js
- test/parallel/test-inspector-network-fetch.js
- test/parallel/test-inspector-network-http.js
Refs: https://github.com/nodejs/node/issues/53946
It supports the mimeType and charset defined in Network.Response.
https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response
> inspector: add mimeType and charset support to Network.Response

- doc/api/zlib.md
Source code of `function Brotli()` calls ctor of parent `ZlibBase` via
`ReflectApply()`
By inspecting `opts` in `ZlibBase` ctor, we can see `opts?.info` is
further used to determine the return shapes of `*Sync()` methods in
children class. This information will need to be revealed in nodejs doc.
This PR is separated from the one for `ZstdOptions`, since these two
changes potentially need to be backported to different minimum versions.
> doc: add missing options.info for BrotliOptions

- doc/api/deprecations.md
- doc/api/http2.md
Ref https://github.com/nodejs/node/pull/58293
and https://github.com/nodejs/node/pull/57269.
> http2: deprecate priority

- doc/api/child_process.md
The `child_process` documentation already explains when `code` and `signal` can be `null` in the parameters of [`spawnSync()`](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options) and the description of [`exit` event](https://nodejs.org/api/child_process.html#event-exit). This change now consistently explains this in the `close` and `exit` event parameters and descriptions.
Refs: https://github.com/nodejs/node/issues/58463#issuecomment-2911460454
> doc: explain child_process code and signal null values everywhere

- src/README.md
- src/env-inl.h
- src/env.h
- src/node_contextify.cc
Reduce some of the boilerplate code needed to access the cppgc::AllocationHandle from the Node.js Environment.
> src: add env->cppgc_allocation_handle() convenience method

- src/node_api.cc
There is a CHECK_NOT_NULL check before dereferencing node_env on line 710 in the if block, but there is no CHECK_NOT_NULL check before dereferencing node_env on line 721. Maybe it makes sense to put CHECK_NOT_NULL right after calling the Environment::GetCurrent function?
> src: fix possible dereference of NULL pointer

- test/fixtures/console/stack_overflow.js
Refs https://chromium-review.googlesource.com/c/v8/v8/+/6011806
The V8 team just enabled the `JSON.stringify` fast path by default, which is iterative and won't throw. Pre-emptively preserve test functionality by forcing the slow path. See above linked PR for approach this is borrowed from.
> test: force slow `JSON.stringify` path for overflow

- src/node.cc
- test/parallel/test-crypto-fips.js
If `--enable-fips` or `--force-fips` fails to be applied during `ProcessFipsOptions()`, the node process might exit with `ExitCode::kNoFailure` because `ERR_GET_REASON(ERR_peek_error())` can return `0` since `ncrypto::testFipsEnabled()` does not populate the OpenSSL error queue.
This is problematic because an exit code of `0` (i.e., `kNoFailure`) indicates successful execution of the `node` command, even though it already failed during initialization. (Error messages also appear to be broken, but fixing that is not as urgent as not pretending that the command succeeded.)
For example, if a user invokes `node` from within a bash script and `NODE_OPTIONS` includes `--force-fips`, the execution of the command will appear to have succeeded even if the actual user script was never executed due …
> src: fix FIPS init error handling

- doc/api/test.md
- lib/internal/test_runner/runner.js
- test/parallel/test-runner-run-watch.mjs
The goal of this PR is to add a `test:watch:restarted` event to signal to the reporter that some tests have restarted while in watch mode.
This will enable a trivial fix for [nodejs/node#57206](https://github.com/nodejs/node/issues/57206), which I plan to address later.
> test_runner: emit test:watch:restarted event on watched file changes

- test/parallel/test-sqlite-database-sync.js
Does what it states on the tin.
My shared library sqlite seems to report this particular error without `"`'s, but otherwise seems perfectly functional.
> test: make sqlite-database-sync tests work with system sqlite

- doc/api/deprecations.md
We started making such changes for zlib and repl. I recommend documentation-only deprecating instantiating these classes without new qualifier, and runtime deprecating in next major depending on the usage. If usage is high, we can postpone runtime deprecating it.
cc @nodejs/tsc @nodejs/http
> http: deprecate instantiating classes without new

- src/cares_wrap.cc
- test/parallel/test-dns.js
Refs: https://github.com/nodejs/node/pull/57640
It turns out #57640 was incomplete and I missed including this option mask flag. Thank you to @augjoh for [pointing this out](https://github.com/nodejs/node/issues/57641#issuecomment-2888235890).
> dns: fix dns query cache implementation

- doc/api/deprecations.md
- lib/internal/child_process.js
- test/parallel/test-child-process-fork.js
The `._channel` property has been deprecated for many years now. It's time to remove it.
> child_process: move _channel to end-of-life

- doc/api/errors.md
Handful of error messages that have been marked experimental for years... in one case 8 years! I think it's safe to mark them stable.
> lib: graduate error codes that have been around for years

- src/node_file.cc
- test/parallel/test-permission-fs-internal-module-stat.js
There are several motivation for removing this:
1. The implementation does not align with InternalModuleStat, most noticably it does not namespace the path or convert it to UTF-16 before using it with std::filesystem::path on Windows which could crash on non-English locale. This could be  the cause of https://github.com/nodejs/node/issues/56670 (or at least one of them since there are still many points in the code base where this is done incorrectly).
2. It needs the Environment - if not for decoding the string, at least for env->exec_path() to resolve the path for namespacing - and therefore needs a handle to the Context which requires a handle scope which actually makes the fast API version slower than the normal binding.
For simplicity this just removes the fast API to fix the bug and …
> src: remove fast API for InternalModuleStat

- src/crypto/crypto_cipher.cc
- src/crypto/crypto_cipher.h
This change simplifies the C++ AEAD implementation. Instead of storing the authentication tag when the user calls `setAuthTag()` and passing it to OpenSSL later in `MaybePassAuthTagToOpenSSL()`, the modified code forwards it to OpenSSL from within `setAuthTag()` already, removing the need to store it.
For clarity, I have also renamed the possible `AuthTagState` values to better reflect the actual state of the authentication tag.
I assume that we did not originally do this due to issues with some old versions of OpenSSL when reordering certain function calls, but even with the recent additions I made to the relevant test (namely, 1ef99237f566c89247660b935667fbf4efa606ce and 53944c44629b651425f8d18c4d33f9bc99657d37), it seems to pass in both OpenSSL 3 and OpenSSL 1.1.1 with this …
> crypto: forward auth tag to OpenSSL immediately

- lib/repl.js
- test/parallel/test-repl-completion-on-getters-disabled.js
- test/parallel/test-repl-save-load.js
- test/parallel/test-repl-tab-complete.js
the REPL completion logic evaluates code, this is generally ok
but it can be problematic when there are objects with nested
properties since the code evaluation would trigger their potential
getters (e.g. the `obj.foo.b` line would trigger the getter of
`foo`), the changes here disable the completion logic when proxies
and getters are involved thus making sure that code evaluation does
not take place when it can potentially (and surprisingly to the user)
trigger side effectful behaviors
___
Partially addresses https://github.com/nodejs/node/issues/57829
> disable REPL completion on proxies and getters

- test/parallel/test-fs-read-empty-buffer.js
- test/parallel/test-fs-read-offset-null.js
`test-fs-read-empty-buffer.js` did not close used filehandle.
`test-fs-read-offset-null` reused same variable in async tests, creating potential race condition.
> test: dispose of filehandles in filehandle.read tests

- common.gypi
- deps/v8/src/parsing/parser-base.h
- deps/v8/test/mjsunit/harmony/for-using-of-await-using-of.js
[explicit-resource-management] Fix parsing for (using of=null;;)
Apparently `using of` is allowed in the initializer position of C-style
for loops.
See https://github.com/tc39/proposal-explicit-resource-management/issues/248
Bug: 42203506
Change-Id: Ia056b161f4ea28a0f3ba4e3e420f1718195274a4
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6594471
Commit-Queue: Shu-yu Guo <syg@chromium.org>
Reviewed-by: Rezvan Mahdavi Hezaveh <rezvan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#100531}
Refs: https://github.com/v8/v8/commit/249de887a8d317357ab5a27640e849787e498c06
> deps: V8: cherry-pick 249de887a8d3

- tools/sign.bat
This PR finalizes the work on the new signing tool, Azure Trusted Signing. As discussed in [the build issue](https://github.com/nodejs/build/issues/4036), the release CI was set up to work with new tools, and this change moves to using them when building Node.
When this PR lands, the same changes should be applied to all the LTS branches, as they are still released and signed.
cc @nodejs/build 
Refs: https://github.com/nodejs/build/issues/4036
> win,tools: use Azure Trusted Signing

- doc/api/deprecations.md
It seems that the deprecated `_transformState` property was removed at some point in the past but the deprecation metadata was not updated accordingly.
@ronag or @mcollina ... do you happen to know which PR and which release removed the `_transformState`?
> doc: update metadata for _transformState deprecation

- src/api/callback.cc
- src/node.h
These APIs have been deprecated in https://github.com/nodejs/node/pull/18632.
Given the parameter `async_context` is essential for stable API `AsyncLocalStorage`, it'd be better to remove them now.
> src: remove node.h APIs to make callback without an async context

- doc/api/cli.md
- doc/api/module.md
- doc/api/modules.md
- doc/api/process.md
- lib/internal/source_map/source_map_cache.js
- test/parallel/test-source-map-enable.js
Update links of source map specs to the standardized ECMA426, with proper IPR policies.
> doc,lib: update source map links to ECMA426

- doc/api/packages.md
Close #58576
I have added a new section called `# Path Rules and Validation for Export Targets` that goes over the invalid paths that are possible & and their valid counter parts
> doc: add path rules and validation for export targets in package.json

- test/parallel/test-fs-open.js
- test/parallel/test-fs-promises-file-handle-read.js
- test/parallel/test-fs-promises-file-handle-readFile.js
- test/parallel/test-whatwg-readablebytestream.js
Separated out from #58536. Specifically *not* using `using` so the test changes can be backported.
This is in preparation for moving the close-filehandle-on-gc to EOL.
> test: close FileHandle objects in tests explicitly

- src/node_contextify.cc
I converted esm_syntax_error_messages and throws_only_in_cjs_error_messages to const vector
> src: make global error message vectors const in contextify

- test/es-module/test-esm-dynamic-import.js
- test/es-module/test-vm-main-context-default-loader-eval.js
- test/es-module/test-vm-main-context-default-loader.js
- test/parallel/test-vm-module-referrer-realm.mjs
Split indirect eval import tests as they depend on the JS stack to
resolve the referrer.
These tests can be wonky if the loader internals are changed and performs
microtasks with a JS stack (e.g. with `CallbackScope`). In this case, the
referrer will be resolved to the top JS stack frame [`node:internal/process/task_queues.js`](https://github.com/nodejs/node/blob/b23648ef2e85b39fea6ded5e687a1b2eb4da6678/lib/internal/process/task_queues.js#L105).
This is due to the [implementation detail](https://github.com/nodejs/node/blob/b23648ef2e85b39fea6ded5e687a1b2eb4da6678/deps/v8/src/interpreter/bytecode-generator.cc#L7631) of how V8 finds the referrer for a dynamic import
call.
> test: split indirect eval import tests

- lib/internal/modules/esm/module_job.js
- src/module_wrap.cc
- test/es-module/test-import-preload-require-cycle.js
- test/fixtures/import-require-cycle/a.js
- test/fixtures/import-require-cycle/b.js
- test/fixtures/import-require-cycle/c.js
- test/fixtures/import-require-cycle/preload.mjs
When --import is used, the ESM loader is used to handle even pure CJS entry points, and it can run into CJS module facades in the evaluating state when the parent CJS module is being evaluated. In this case it should be allowed, since the ESM <-> CJS cycles that are meant to be disallowed (for the time being) should already be detected before evaluation and wouldn't get here, and CJS <-> CJS cycles are fine.
Fixes: https://github.com/nodejs/node/issues/58515
> module: allow cycles in require() in the CJS handling in ESM loader

- lib/internal/http2/core.js
- test/parallel/test-http2-client-priority-before-connect.js
- test/parallel/test-http2-client-set-priority.js
- test/parallel/test-http2-priority-cycle-.js
- test/parallel/test-http2-priority-event.js
- test/parallel/test-http2-server-stream-session-destroy.js
Refs #58293 
Noticed the mentioned RFC in deprecation warning is typed as `1993`, and the correct one should be `9113`.
> http2: fix DEP0194 message

- lib/internal/modules/esm/translators.js
- test/es-module/test-esm-import-meta-main-eval.mjs
- test/fixtures/es-modules/import-meta-main.ts
Fixes: https://github.com/nodejs/node/issues/58660
> module: fix typescript import.meta.main

- test/parallel/test-source-map-enable.js
- test/parallel/test-v8-coverage.js
- test/parallel/test-v8-stop-coverage.js
- test/parallel/test-v8-take-coverage-noop.js
- test/parallel/test-v8-take-coverage.js
some test files manually check for `!process.features.inspector` to to see if the tests should be skipped, the changes here update those checks to instead use the more appropriate `common.skipIfInspectorDisabled()`
> test: use `common.skipIfInspectorDisabled()` to skip tests

- test/parallel/test-repl-tab-complete-buffer.js
- test/parallel/test-repl-tab-complete-custom-completer.js
- test/parallel/test-repl-tab-complete-files.js
- test/parallel/test-repl-tab-complete-on-editor-mode.js
- test/parallel/test-repl-tab-complete-require.js
- test/parallel/test-repl-tab-complete.js
refactor the test/parallel/test-repl-tab-complete.js file by:
- making the tests in the file self-contained (instead of all of them sharing the same REPL instance and constantly calling `.clear` on it)
- using the test runner with appropriate descriptions to make clearer what is being tested
- extracting some tests in their own js test files (to increase isolation of the tests and help with issues such as flakiness)
> test: refactor repl tab complete tests

- README.md
Fixes: https://github.com/nodejs/node/issues/58559
> doc: add islandryu to collaborators

- src/node_file.cc
Continuation of https://github.com/nodejs/node/pull/42811 which fixes https://github.com/nodejs/node/issues/42808 for the async case
Happy to try to write a test but left as is for now seeing as the previous PR also didn't: https://github.com/nodejs/node/pull/42811#pullrequestreview-948610220
> fs: fix fs.promises.mkdir to also report ENOSPC correctly

- lib/repl.js
- test/parallel/test-repl-tab-complete-computed-props.js
I noticed that the repl tab completion doesn't correctly handle computed properties targeted by strings.
For example given the following context:
```js
const obj = { one: 1 };
```
The current repl would provide valid (number) completions for lines such as:
```js
obj.one.to
```
But would not provide correct completions for lines such as:
```js
obj['one'].to
```
In fact it would provide incorrect (string) completions.
See:
This PR addresses the above issue
> [!Note]
> This PR is not making everything work perfectly, for example it is not addressing lines such as
> `obj['o' + 'ne'].to` (but it's not making them any worse either).
> I think that a generally great solution would require more substantial code changes (potentially with some AST analysis).
> I am planning on keeping improving …
> repl: fix tab completion not working with computer string properties

- lib/internal/fs/utils.js
Fixes: https://github.com/nodejs/node/issues/58726 [^1]
These constants can be precomputed.
[^1]: even though it's not a Node.js bug
> fs: avoid computing time coefficient constants in runtime

- tools/v8_gypfiles/abseil.gyp
- tools/v8_gypfiles/toolchain.gypi
- tools/v8_gypfiles/v8.gyp
This sets proper SIMD build flags for abseil on ia32. Also moves `include_dirs` of `V8_ROOT` from `toolchain.gyp` to `v8.gyp` as it is mainly for V8 targets.
Fixes: https://github.com/nodejs/node/issues/58569
> tools: include toolchain.gypi in abseil.gyp

- doc/api/inspector.md
- lib/inspector.js
- lib/internal/inspector/network.js
- lib/internal/inspector/network_http.js
- lib/internal/inspector/network_undici.js
- src/inspector/network_agent.cc
- src/inspector/network_agent.h
- src/inspector/node_protocol.pdl
- test/parallel/test-inspector-emit-protocol-event.js
- test/parallel/test-inspector-network-data-received.js
- test/parallel/test-inspector-network-data-sent.js
Add protocol method `Network.dataSent` to buffer request data. And
expose protocol methods `Network.getRequestPostData` and
`Network.getResponseBody` allowing devtool to retrieve buffered data.
> inspector: add protocol methods retrieving sent/received data

- doc/api/fs.md
- lib/internal/fs/dir.js
- test/parallel/test-fs-promises-file-handle-dispose.js
As per draft explicit resource management guidelines (#58526) regarding disposer behaviour.
refs: #58206
> fs: make `Dir` disposers idempotent

- src/node_process_methods.cc
- src/process_wrap.cc
- src/spawn_sync.cc
- test/parallel/test-permission-child-process-cli.js
- test/parallel/test-process-execve-permission-fail.js
**src: pass resource on permission checks for spawn**
```
This commit enhances the permission model errors
when no --allow-child-process is used and the error is emitted.
```
> src: pass resource on permission checks for spawn

- tools/configure.d/nodedownload.py
FancyURLopener and URLopener have been deprecated since Python 3.3 and they are removed completely from 3.14.
Fixes: https://github.com/nodejs/node/issues/58740
> tools: make nodedownload module compatible with Python 3.14

- lib/repl.js
This PR replaces the usage of require.extensions in the REPL autocompletion logic with Module._extensions.
require.extensions has been runtime-deprecated under [DEP0039](https://nodejs.org/api/deprecations.html#requireextensions), and its usage triggers a warning in recent Node.js versions. Since require.extensions is just a user-land alias for Module._extensions, we can safely access the same object via Module._extensions without any behavioral change or deprecation warning.
- this.context.require.extensions → Module._extensions in the REPL complete() function
- Adds an inline comment explaining the deprecation and replacement
- No functional behavior change
Fixes: https://github.com/nodejs/node/issues/58641
> repl: avoid deprecated `require.extensions` in tab completion

- .github/workflows/coverage-linux-without-intl.yml
- .github/workflows/coverage-linux.yml
Those have been failing for a while, and no one has managed to find out how to fix it. Keeping a failing job that we ignore the result is really not healthy, and just wasteful at this point, let's disable it.
> [v22.x] tools: disable failing coverage jobs

- src/crypto/crypto_keys.cc
- src/node_file.cc
- src/node_util.cc
- src/node_v8.cc
- src/node_zlib.cc
- src/process_wrap.cc
- src/udp_wrap.cc
- src/util-inl.h
From the following comment in the pull request: https://github.com/nodejs/node/pull/57146#discussion_r1963799600
Add a template utility method `FromV8Value<T>()` to replace the repetitive `static_cast<...>(value.As<>()‑>Value())` pattern. It also additionally adds compile‑time range checks for integers.
I've also replaced a bunch of `static_cast`s with the new `FromV8Value<T>()`
> src: add FromV8Value<T>() for integral and enum types

- lib/_http_server.js
- test/parallel/test-http-keep-alive-empty-line.mjs
Fixes: https://github.com/nodejs/node/issues/58140
As shown in the test code, sending an empty line after a request can result in a state where the keep-alive timer is reset, but neither requestTimeout nor keepAliveTimeout is active.
Unless a custom timeout is implemented, this allows the client to hold the socket indefinitely.
Modified behavior so that data like an empty line, which does not indicate the start of an HTTP message, no longer resets the keep-alive timeout.
Here is the behavior of other HTTP servers:
nginx: When client_header_timeout is set, sending an empty line after a request triggers a 408 timeout response once the timeout period expires.
Apache: When RequestReadTimeout header=5-10,MinRate=500 is configured, the connection times out after the specified duration, but no …
> http: fix keep-alive not timing out after post-request empty line

- src/cares_wrap.cc
c-ares set `timeout` to  DEFAULT_TIMEOUT(2000ms) When timeout is <= 0, so we should schedule timer every 1000ms.
```c
if (optmask & ARES_OPT_TIMEOUTMS) {
/* Apparently some integrations were passing -1 to tell c-ares to use
* the default instead of just omitting the optmask */
if (options->timeout <= 0) {
optmask &= ~(ARES_OPT_TIMEOUTMS);
} else {
channel->timeout = (unsigned int)options->timeout;
}
}
if (channel->timeout == 0) {
channel->timeout = DEFAULT_TIMEOUT;
}
```
cc @jasnell
> dns: set timeout to 1000ms when timeout <= 0

- lib/repl.js
- test/parallel/test-repl-tab-complete-computed-props.js
improve the tab completion capabilities around computed properties by replacing the use of brittle and error prone Regex checks with more robust AST based analysis
___
Followup from https://github.com/nodejs/node/pull/58709
> repl: improve tab completion on computed properties

- src/cleanup_queue.cc
- src/crypto/crypto_util.cc
- src/inspector_socket.cc
- src/inspector_socket_server.cc
- src/node.cc
- src/node_credentials.cc
- src/node_dotenv.cc
- src/node_http2.h
- src/node_messaging.cc
- src/node_platform.cc
- src/node_process_object.cc
- src/node_report.cc
- src/node_sea.cc
- src/node_task_runner.cc
- src/node_watchdog.cc
- test/cctest/test_inspector_socket_server.cc
In PR https://github.com/nodejs/node/pull/57975, I introduced C++20 ranges as an experiment. This current PR extends the application of ranges to simplify even more code.
> src: use ranges library (C++20) more systematically

- lib/internal/modules/typescript.js
fix type in getTypeScriptParsingMode's jsdoc: `@type {string}` should be `@type {() => TypeScriptMode}`
@marco-ippolito
> lib: fix `getTypeScriptParsingMode` jsdoc

- doc/api/stream.md
For some reason, `stream.isErrored` and `stream.isReadable` sections were in between `stream.Readable` static methods sections.
> doc: fix `stream.md` section order

- lib/internal/test_runner/mock/mock.js
The current message contains a period within the quotes around the specifier, making it look malformed.
> test_runner: correct "already mocked" error punctuation placement

- doc/api/globals.md
I noticed this while working on the new documentation generator.
> doc: add missing colon to headers in `globals.md`

- doc/api/http.md
The http.request allows sending headers as an array of strings.
Fixes: https://github.com/nodejs/node/issues/57986
> doc: add Array type in http request headers

- node.gni
- src/inspector/unofficial.gni
- unofficial.gni
This PR allows building against `//third_party/inspector_protocol` which would align Electron when building with chromium shared dependencies.
This allows us to remove a [patch](https://github.com/electron/electron/blob/82a59d989425dc9d58e561325e955b826d12044c/patches/node/build_option_to_use_custom_inspector_protocol_path.patch#L4-L5)
The precursor to this PR was merged via [#58001](https://github.com/nodejs/node/pull/58001) which contains changes necessitated by [this CL](https://chromium-review.googlesource.com/c/v8/v8/+/5996636)
> build: option to use custom `inspector_protocol` path

- lib/internal/fs/dir.js
- lib/internal/fs/streams.js
- test/parallel/test-fs-opendir.js
- test/parallel/test-fs-write-stream-autoclose-option.js
This PR makes `Dir.prototype.path`, `ReadStream.prototype.autoClose`, and `WriteStream.prototype.autoClose` getters and setters throw `ERR_INVALID_THIS` instead of failing with internal implementation-specific messages when called on invalid `this`.
> fs: throw `ERR_INVALID_THIS` on illegal invocations

- lib/repl.js
- test/parallel/test-repl-eval-error-after-close.js
Fixes https://github.com/nodejs/node/issues/58784
prevent incorrect throws of `ERR_USE_AFTER_CLOSE` errors when the eval function of a repl server returns an error after the repl server has been closed
> repl: fix eval errors thrown after close throwing `ERR_USE_AFTER_CLOSE`

- doc/api/vm.md
- lib/internal/vm/module.js
- src/module_wrap.cc
- test/parallel/test-vm-module-errors.js
- test/parallel/test-vm-module-modulerequests.js
- tools/doc/type-parser.mjs
Expose import phase on `vm.SourceTextModule.moduleRequests`. This deprecates `vm.SourceTextModule.dependencySpecifiers` as it does not expose import attributes nor import phase.
Refs: https://github.com/nodejs/node/issues/37648
> vm: expose import phase on SourceTextModule.moduleRequests

- test/parallel/test-fs-opendir.js
Two subtests in `test-fs-opendir.js` are not closing dir. Let's fix it.
> test: close dirs in `fs-opendir` test

- test/parallel/test-inspector-network-fetch.js
Remove the dependency on the in-tree copy of Undici in `deps/undici` from `parallel/test-inspector-network-fetch`. For downstream rebuilders of Node.js using an externalized Undici it is not uncommon to remove `deps/undici` to ensure that the build is not using the in-tree copy.
Refs: https://github.com/nodejs/node/issues/58865
> test: remove reliance on in-tree `deps/undici`

- lib/internal/test_runner/runner.js
- test/fixtures/test-runner/options-propagation/experimental-config-file.test.mjs
- test/fixtures/test-runner/options-propagation/node.config.json
- test/parallel/test-runner-cli.js
> test_runner: correctly filter --experimental-config-file

- common.gypi
Refs https://github.com/nodejs/node/pull/58171
Ensure `v8_enable_pointer_compression_shared_cage` is also disabled on non-64-bit architectures, as V8 pointer compression only supports 64bit architectures.
> build: disable `v8_enable_pointer_compression_shared_cage` on non-64bit

- doc/api/test.md
Existing links explaining the various target file-related `run([options])` point to the wrong section.
> doc: fix links in test.md

- test/parallel/test-cli-node-cli-manpage-env-vars.mjs
- test/parallel/test-cli-node-cli-manpage-options.mjs
add tests to make sure that the content of the doc/node.1 file is kept in snyc with the content of the doc/api/cli.md file (to make sure that when a flag or environment variable is added or removed to one, the same change is also applied to the other)
> test: add tests to ensure that node.1 is kept in sync with cli.md

- test/known_issues/test-fs-cp-async-buffer.js
- test/known_issues/test-fs-cp-filter.js
- test/known_issues/test-fs-cp-non-utf8.js
Refs: https://github.com/nodejs/node/issues/58634
Refs: https://github.com/nodejs/node/issues/58869
@nodejs/fs
> test: add known issue tests for fs.cp

- src/node_config.cc
Refs https://github.com/nodejs/node/pull/58387.
Fixes `OPENSSL_IS_BORINGSSL ` not being defined in cases where it should be due to missing include. See [relevant BoringSSL file](https://source.chromium.org/chromium/chromium/src/+/main:third_party/boringssl/src/include/openssl/base.h)
> crypto: fix inclusion of `OPENSSL_IS_BORINGSSL` define

- doc/api/vm.md
Synthetic Module Record is defined in the ECMA262. Link indirect eval
calls to MDN with rich examples.
> doc: update vm doc links

- test/known_issues/test-fs-readdir-promise-recursive-with-buffer.js
- test/known_issues/test-fs-readdir-recursive-with-buffer.js
- test/known_issues/test-fs-readdir-sync-recursive-with-buffer.js
> test: add known issue tests for recursive readdir calls with Buffer path

- doc/api/cli.md
- doc/api/permissions.md
- lib/child_process.js
- lib/internal/process/permission.js
- lib/internal/process/pre_execution.js
- test/parallel/test-permission-allow-child-process-cli.js
- test/parallel/test-permission-child-process-inherit-flags.js
Previously, only child_process.fork propagated the exec arguments (execvArgs) to the child process.
This commit adds support for spawn and spawnSync to propagate permission model flags — except when they are already provided explicitly via arguments or through NODE_OPTIONS.
> permission: propagate permission model flags on spawn

- src/permission/fs_permission.cc
**src,permission: enhance permission model debug**
```
This commit enhances the permission model debug logs when NODE_DEBUG_NATIVE=PERMISSION_MODEL is used
Example
Inserting /Users/rafaelgss/repos/os/node/t.js
└─ /
├─ Users/rafaelgss/repos/os/node/t.js
└─ tm
├─ 3
├─ 2
└─ p/*
```
> src,permission: enhance permission model debug

- README.md
This PR adds @ovflowd back to the list of core collaborators, as they believe they should be added back. (Among other reasons)
cc @nodejs/tsc
> docs: add @ovflowd back to core collaborators

- doc/api/buffer.md
- doc/api/cli.md
- doc/api/globals.md
- doc/api/http.md
- tools/doc/type-parser.mjs
It feels inconsistent to treat differently JS built-ins and web classes. Using types also lowers the maintenance burden as we don't need to manage it in the markdown file.
> tools,doc: move more MDN links to types

- doc/api/globals.md
- doc/api/http.md
Our docs are inconsistent when it comes to `Class:` prefix for sections documenting classes. This PR adds the ones that were missing.
> doc: add missing `Class:` mentions

- doc/api/globals.md
I'm pretty sure those were meant as subsections for `fetch`
| Before | After
| - | - |
| ![Before](https://github.com/user-attachments/assets/4a3a557d-15f7-43e6-b4f3-561d74a28937) | ![After](https://github.com/user-attachments/assets/91f37478-2f7b-4498-8dd2-9e8e9fbe6ead) |
> doc: fix `fetch` subsections in `globals.md`

- doc/contributing/strategic-initiatives.md
There haven't been much more progress, it seems safe to assume what could realistically be done has been done.
Closes: https://github.com/nodejs/TSC/issues/1094
> doc: move "Core Promise APIs" to "Completed initiatives"

- src/node_os.cc
> os: fix GetInterfaceAddresses memory leaky

- lib/internal/fs/dir.js
- test/parallel/test-fs-opendir.js
Fixes: https://github.com/nodejs/node/issues/58854
~~Test blocked on: https://github.com/nodejs/node/pull/58855~~
> fs: close dir before throwing if `options.bufferSize` is invalid

- test/parallel/test-runner-watch-mode-kill-signal.mjs
While trying to deflake the tests I've refactored making them much clearer and more performant (since there are no longer `setTimeout` calls), as far as I can tell the flake is also gone :slightly_smiling_face: 
Results:
- https://ci.nodejs.org/job/node-stress-single-test/586
- https://ci.nodejs.org/job/node-stress-single-test/587
Ref: https://github.com/nodejs/reliability/issues/1250
> test: deflake test-runner-watch-mode-kill-signal

- GOVERNANCE.md
Alternative to https://github.com/nodejs/node/pull/58837
To be clear, I don't think any changes to our governance doc are needed, but others have proposed edits and additional requirements. This PR represents the version of those changes that I think would be better if any changes are made at all. See the discussion in #58837 for background.
> doc: clarify details of TSC public and private meetings

- lib/internal/inspector/network.js
- lib/internal/inspector/network_undici.js
- test/parallel/test-inspector-network-fetch.js
Support undici sent and received data inspection in Chrome DevTools.
> inspector: support undici traffic data inspection

- doc/api/permissions.md
The permission model grew enough to be splited into multiple files, the link in the md file is broken. And as it is not part of a single file, the best way to fix this is just remove the link, many APIs in Node.js does not have the source code linked, this is not bad for our docs.
---
The link is pointing to https://github.com/nodejs/node/blob/v24.3.0/src/permission.cc, which is a "404". Everything is under `src/permission/*.{cc,h}` not a single file.
> doc: remove broken link to permission model source code

- benchmark/util/deprecate.js
- lib/internal/util.js
Refs: https://github.com/nodejs/node/issues/58218
In this specific benchmark, the performance difference between `modifyPrototype=0` and `modifyPrototype=1` is marginally significant at the 5% level:
* **Mean (modifyPrototype=0)**: 390,196.99 ops/sec
* **Mean (modifyPrototype=1)**: 382,521.21 ops/sec
* **p-value**: 0.05087
While this case is borderline, other benchmarks (e.g., [https://github.com/nodejs/node/pull/58907](https://github.com/nodejs/node/pull/58907)) have shown a more noticeable improvement, so I think this worth the change.
> lib: flag to conditionally modify proto on deprecate

- doc/api/net.md
- lib/internal/blocklist.js
- test/parallel/test-blocklist.js
- test/parallel/test-net-blocklist.js
Fixes: https://github.com/nodejs/node/issues/56252
> net: update net.blocklist to allow file save and file management

- test/parallel/test-debugger-extract-function-name.mjs
In the `test-debugger-extract-function-name` file the inspector port is not set to `0`, this causes the test (at least on my machine) to consistently (always) fail when run with the python runner with any repeat value greater than 1:
So I am making sure that the port is indeed set to `0` solving the issue.
Also the test has also been a bit flaky in the CI lately:
- https://github.com/nodejs/reliability/issues/1246
- https://github.com/nodejs/reliability/issues/1245
- https://github.com/nodejs/reliability/issues/1244
- https://github.com/nodejs/reliability/issues/1243
- https://github.com/nodejs/reliability/issues/1242
So hopefully this change should address the flakiness :slightly_smiling_face: 
However I am not completely sure, since I did try to run some stress tests on the file on …
> test: add missing port=0 arg in test-debugger-extract-function-name

- typings/primordials.d.ts
This fixes a very minor type error I just noticed.
Before:
After:
> lib: fix incorrect `ArrayBufferPrototypeGetDetached` primordial type

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/module_job.js
- test/es-module/test-import-module-retry-require-errored.js
- test/es-module/test-require-module-retry-import-errored-2.js
Re-evaluating an errored ESM should lead to rejecting the rejection again - this is also the case when importing it twice. In the case of retrying with require after import, just throw the cached error.
Drive-by: add some debug logs.
Fixes: https://github.com/nodejs/node/issues/58945
> module: throw error when re-runing errored module jobs

- lib/repl.js
- test/parallel/test-repl-completion-on-getters-disabled.js
https://github.com/nodejs/node/pull/57909 introduced the disabling of REPL tab completion on object containing proxies and getters (since such completion triggers code evaluation which can be unexpected/disruptive for the user)
the solution in 57909 did not address all possible such cases, the changes here improve on such solution by using acorn and AST analysis to cover most if not all possible cases
> repl: improve REPL disabling completion on proxies and getters

- src/module_wrap.cc
Import attribute key and value only support literal string values. Add DCHECKs to ensure that the types are expected.
> src: check import attributes value types as strings

- doc/api/cli.md
- doc/api/inspector.md
- doc/node.1
- lib/inspector.js
- lib/internal/inspector/network_resources.js
- src/inspector/io_agent.cc
- src/inspector/io_agent.h
- src/inspector/network_agent.cc
- src/inspector/network_agent.h
- src/inspector/network_inspector.cc
- src/inspector/network_inspector.h
- src/inspector/network_resource_manager.cc
- src/inspector/network_resource_manager.h
- src/inspector/node_inspector.gypi
- src/inspector/node_protocol.pdl
- src/inspector/worker_inspector.cc
- src/inspector/worker_inspector.h
- src/inspector_agent.cc
- src/inspector_agent.h
- src/inspector_js_api.cc
- src/node_options.cc
- src/node_options.h
- test/fixtures/inspector-network-resource/app.js.map
- test/parallel/test-inspector-network-resource.js
- typings/internalBinding/inspector.d.ts
Fixes: https://github.com/nodejs/node/issues/57873
Adds initial support for Network.loadNetworkResource in the inspector.
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-loadNetworkResource
~Resource fetching is done via a spawned child process to keep the inspector's event loop clean and isolated.
The JavaScript code for the fetch process is currently hardcoded, which may not be ideal, but I couldn't come up with a better approach at this point.~
When --experimental-inspector-network-resource is set, a dedicated worker for loadNetworkResource is launched.
This worker fetches the resource and returns the result to the frontend.
https://github.com/nodejs/node/pull/58077/files#diff-5d3d58cbcfda008f49966a11d73863e67b78a237aa386f1fbdc5c9124136c1eb
To verify this change …
> inspector: initial support for Network.loadNetworkResource

- lib/internal/test_runner/mock/mock_timers.js
- test/parallel/test-runner-mock-timers.js
Add some cleanup logic to `#setIntervalPromisified` and `#promisifyTimer` to remove the abort listener when the timer either resolves or throws.
Also makes some structural simplifications to both methods. In particular, the previous implementation of `#setIntervalPromisified` created a single-use anonymous async iterator, before `yield*`ing from it; this can trivially be converted to yielding from a `for await` loop.
Needs dont-land-on-v20.x for `Promise.withResolvers`.
> test_runner: improve mock timer promisifiers

- doc/node.1
- test/parallel/test-cli-node-cli-manpage-env-vars.mjs
**Description:**
Adds missing environment variables to manpage:
- `NODE_COMPILE_CACHE`
- `NODE_DISABLE_COMPILE_CACHE` 
- `NODE_PENDING_PIPE_INSTANCES`
- `NODE_TEST_CONTEXT`
- `NODE_USE_ENV_PROXY`
**Reference:**
Fixes: #58894
> doc: add missing environment variables to manpage

- doc/api/deprecations.md
- lib/internal/crypto/hash.js
- src/crypto/crypto_hash.cc
- test/parallel/test-crypto-default-shake-lengths-oneshot.js
- test/parallel/test-crypto-default-shake-lengths.js
- test/parallel/test-crypto-hash.js
Follow up to #58942.
I wish to move forward with runtime deprecation straight away since the default lengths are half the size necessary for full collision resistance supported by these algorithms.
> crypto: runtime-deprecate default shake128/256 output lengths

- lib/repl.js
- test/parallel/test-repl-tab-complete.js
Fixes: https://github.com/nodejs/node/issues/59029
> repl: fix repl crashing on variable declarations without init

- doc/api/util.md
The default value is legal by means other than defaulting.
> doc: "if and only if" should be "if" in util.parseArgs default value

- doc/api/errors.md
Fix: clarify ERR_FS_FILE_TOO_LARGE message to reflect fs.readFile() I/O limit
The error previously suggested the issue might be due to Buffer limitations,
but in fact it's an internal constraint of fs.readFile(). Updated the
documentation to avoid confusion and guide users toward fs.createReadStream()
for large files.
ref #55864
> doc: clarify ERR_FS_FILE_TOO_LARGE explanation to reflect fs.readFile() I/O limit

- test/es-module/test-import-module-retry-require-errored.js
- test/es-module/test-require-module-retry-import-errored-2.js
- test/es-module/test-require-module-tla-retry-import-2.js
- test/es-module/test-require-module-tla-retry-import.js
- test/es-module/test-vm-main-context-default-loader-eval.js
- test/es-module/test-vm-main-context-default-loader.js
- test/eslint.config_partial.mjs
- test/module-hooks/test-module-hooks-load-esm-mock.js
- test/module-hooks/test-module-hooks-load-esm.js
- test/parallel/test-crypto-async-sign-verify.js
- test/parallel/test-fs-open.js
- test/parallel/test-stream-readable-async-iterators.js
- test/parallel/test-vm-context-dont-contextify.js
> tools,test: enforce best practices to detect never settling promises

- doc/api/n-api.md
Section numbers can change over time. Use the section names as the link
text for better readability.
Also, use https://tc39.es/ecma262/ as the unified host of living version
of ECMA-262.
> node-api,doc: update links to ecma262 with section names

- lib/repl.js
- test/parallel/test-repl-tab-complete-getter-error.js
> repl: handle errors from getters during completion

- src/node_config_file.cc
- test/fixtures/rc/warnings-false.json
- test/parallel/test-config-file.js
Fixes #58929
This PR fixes config file parsing for boolean options that are enabled by default. 
In my last [PR](https://github.com/nodejs/node/pull/58039), I did a quick fix for boolean values. Such a fix missed the case where the flag is `true` by default, as `--warnings`. To ensure we're disabling a flag, we have to output that flag prefixed with `--no-`.
> src,test: fix config file parsing for flags defaulted to true

- src/node_file-inl.h
- src/node_file.cc
- test/fixtures/permission/fs-write.js
Fixed: https://github.com/nodejs/node/issues/58747
The C++ layer just reject the Promise but does not return the Promise to JS layer when an error occurs(Libuv error or permission error).
> fix return value of fs APIs

- doc/api/deprecations.md
- lib/internal/crypto/hash.js
- lib/internal/util.js
- src/crypto/crypto_hash.cc
- test/parallel/test-crypto-default-shake-lengths.js
- test/parallel/test-crypto-hash.js
- test/parallel/test-crypto-oneshot-hash.js
Backports https://github.com/nodejs/node/pull/58942 to v22.x
> [v22.x backport] crypto: fix SHAKE128/256 breaking change introduced with OpenSSL 3.4

- lib/internal/modules/package_json_reader.js
Fixes #58126. 
My benchmark was based on the example app shared by @BridgeAR 
In PR #50322, moving the `package_json_reader` cache from JS to C++ preserved the heavy JSON parsing in native code but removed the original JS level cache. As a result, the resolution logic now invokes the C++ binding more frequently.
The worst offender is `modulesBinding.getNearestParentPackageJSON` called ≈ 102 000 times during a typical run.
1. **Initial run (current main branch):**
```bash
time ./node test.js 
```
2. **With a C++ side cache:**
* Cache stats: 270 misses, \~101 700 hits
* Run time `≈4.5s`, showing the bridge overhead remains.
3. **With a JS side cache:**
```bash
time ./node test.js 
```
Introducing a JS level cache for `getNearestParentPackageJSON` to avoid repeated C++ crossings eliminates …
> src: add cache to nearest parent package json

- test/addons/report-fatalerror/test.js
- test/eslint.config_partial.mjs
- test/js-native-api/test_object/test.js
- test/parallel/test-buffer-write-fast.js
- test/parallel/test-net-listen-exclusive-random-ports.js
- test/parallel/test-stream-toArray.js
- test/report/test-report-fatalerror-oomerror-compact.js
- test/report/test-report-fatalerror-oomerror-directory.js
- test/report/test-report-fatalerror-oomerror-filename.js
- test/report/test-report-fatalerror-oomerror-not-set.js
- test/report/test-report-fatalerror-oomerror-set.js
Expands the existing restrictions around not using literal messages to the `not` variants of `strictEqual` and `deepStrictEqual`, and forbids `assert()` where the second argument is a non-string literal, which almost always is a mis-typed `assert.strictEquals()`.
> test: expand linting rules around `assert` w literal messages

- SECURITY.md
**doc: add constraints for mem leak to threat model**
```
As discussed in https://github.com/nodejs-private/node-private/pull/719.
We should clarify what the criteria are to accept
memory leak as a vulnerability (potential DoS).
```
cc: @nodejs/tsc @nodejs/security-wg
> doc: add constraints for mem leak to threat model

- doc/api/cli.md
- src/inspector_profiler.cc
- test/sequential/test-cpu-prof-name.js
This patch adds support for runtime substitution of the ${pid} placeholder
in the --cpu-prof-name option. This is helpful when using cluster/forked
processes to avoid profile file name collisions.
Previously, patterns like ${pid} were not substituted. Now, ${pid} will
be replaced with the current process ID.
Example:
node --cpu-prof --cpu-prof-name 'CPU.${pid}.cpuprofile' index.js
Also updated the CLI documentation accordingly.
Fixes: #57418
> cli: support `${pid}` placeholder in --cpu-prof-name

- benchmark/sqlite/sqlite-is-transaction.js
The variable deadCodeElimination is declared
but not initialized, making it undefined by default. When using the &&= operator with an undefined left operand, the result will always remain undefined regardless of how many iterations run.
```js
let deadCodeElimination;
deadCodeElimination &&= true
deadCodeElimination // undefined
```
> benchmark: fix sqlite-is-transaction

- benchmark/run.js
This option will measure how long the benchmark
takes to run. Example:
```
$ ./node benchmark/run.js --track assert
assert/assertion-error.js
assert/assertion-error.js size=2 n=200: 22,987.24012781365
assert/assertion-error.js size=75 n=200: 296.2362823364434
[740ms] assert/assertion-error.js
...
```
> benchmark: add --track to benchmark

- tools/lint-readme-lists.mjs
There was some confusion when landing https://github.com/nodejs/node/pull/59157 when the handle and the link doesn't match and the error message wasn't very clear about what's going on.
> tools: clarify README linter error message

- benchmark/string_decoder/string-decoder.js
**benchmark: adjust configuration for string-decoder bench**
According to https://github.com/nodejs/node/pull/59186 this benchmark file takes 6 hours to complete a full benchmark/compare.js script (60 runs in total) and these regression tests unrealitics to do between Node.js releases. By using calibrate-n scripts I could find a better N also ajusting some bench configs. e.g: avoid dead code elimination by V8.
Refs: https://github.com/nodejs/node/pull/59186
Results from `calibrate-n.js`
```
Overall average CV: 3.57%
✓ Overall CV is below 5% and no configuration has CV above 10%
→ New best n: 400000 with average CV: 3.57%
✓ Found optimal n=400000 (Overall CV=3.57% < 5% and no configuration has CV > 10%)
Final CV for each configuration: …
```
> benchmark: adjust configuration for string-decoder bench

- test/parallel/test-worker-message-port-transfer-filehandle.js
Fixes: https://github.com/nodejs/node/issues/59145
Wrap all script into `setInterval` and you will see the error
```js
'use strict';
const common = require('../common');
const assert = require('assert');
const fs = require('fs').promises;
const vm = require('vm');
const { MessageChannel, moveMessagePortToContext } = require('worker_threads');
const { once } = require('events');
setInterval(async () => {
(async function() {
const fh = await fs.open(__filename);
const { port1, port2 } = new MessageChannel();
assert.throws(() => {
port1.postMessage(fh);
}, {
constructor: DOMException,
name: 'DataCloneError',
code: 25,
});
// Check that transferring FileHandle instances works.
assert.notStrictEqual(fh.fd, -1);
port1.postMessage(fh, [ fh ]);
assert.strictEqual(fh.fd, -1);
const [ fh2 ] = await …
```
> test: fix flaky test-worker-message-port-transfer-filehandle test

- test/wpt/status/web-locks.json
Refs: https://github.com/nodejs/node/issues/59142
> test: mark web lock held test as flaky

- README.md
Fixes: https://github.com/nodejs/node/issues/58904
Currently, the only documented way relies on third-party server, albeit a well-trusted one, but one that the project doesn't control, and one that's not very convenient to use for consumers. Instead, let's document nodejs/release-keys as the trusted source of truth when it comes to verifying Node.js releases.
I'm keeping the instructions on how to download the keys from key.openPGP.org as some tools out there might be scraping our README looking for that, and it's still a valid way to get the release keys, simply not the preferred one.
> doc: update the instruction on how to verify releases

- doc/api/esm.md
- lib/internal/main/worker_thread.js
- lib/internal/modules/esm/initialize_import_meta.js
- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/translators.js
- lib/internal/modules/esm/utils.js
- lib/internal/worker.js
- test/es-module/test-esm-import-meta-main-eval.mjs
- test/es-module/test-esm-import-meta-main.mjs
- test/es-module/test-esm-import-meta.mjs
- test/fixtures/es-modules/import-meta-main.mjs
- test/fixtures/es-modules/import-meta-main.ts
Backport #57804 and #58661 to v22.x release line
> [v22.x backport] esm: implement import.meta.main

- doc/api/worker_threads.md
- lib/internal/worker.js
- src/async_wrap.h
- src/env_properties.h
- src/node_worker.cc
- src/node_worker.h
- test/parallel/test-worker-cpu-usage.js
- test/sequential/test-async-wrap-getasyncid.js
- typings/internalBinding/worker.d.ts
Add `worker.cpuUsage` for worker, like `worker.getHeapStatistics` and `worker.getHeapSnapshot`.
> worker: add cpuUsage for worker

- doc/api/crypto.md
- doc/api/diagnostics_channel.md
- doc/api/dns.md
- doc/api/events.md
- doc/api/http2.md
- doc/api/inspector.md
- doc/api/module.md
- doc/api/modules.md
- doc/api/stream.md
- doc/api/tls.md
- doc/api/util.md
- doc/api/webcrypto.md
- doc/api/webstreams.md
After completing the web generator's initial implementation, it was easy to identify some slight inconsistencies that clashed.
> doc: format safely for `doc-kit`

- src/module_wrap.cc
- src/module_wrap.h
- test/parallel/test-internal-module-wrap.js
There are two phases in module linking: link, and instantiate. These
two operations are required to be separated to allow cyclic
dependencies.
`v8::Module::InstantiateModule` is only required to be invoked on the
root module. The global references created by `ModuleWrap::Link` are
only cleared at `ModuleWrap::Instantiate`. So the global references
created for depended modules are usually not cleared because
`ModuleWrap::Instantiate` is not invoked for each of depended modules,
and caused memory leak.
The change references the linked modules in an object internal slot.
This is not an issue for Node.js ESM support as these modules can not be
off-loaded. However, this could be outstanding for `vm.Module`.
Fixes: https://github.com/nodejs/node/issues/50113
> src: clear all linked module caches once instantiated

- tools/test.py
Previously, selecting subsystems with numbers in their names, like http2, weren't matched due to a restrictive regex:
```
$ tools/test.py http2
No tests to run.
```
The regex now allows digits, so these tests run as expected:
```
$ tools/test.py http2
[00:17|% 100|+ 286|-   0]: Done
All tests passed.
```
> tools: allow selecting test subsystems with numbers in their names

- doc/api/deprecations.md
- lib/_http_server.js
- test/parallel/test-write-header.js
It’s been over 7 years since it was deprecated in documentation only. I think it’s time to deprecate it at the runtime level.
> http: deprecate writeHeader

- doc/node.1
> doc: add manpage entry for --use-system-ca

- tools/cpplint.py
Adds a lint rule to disallow the usage of `std::vector<v8::Local<T>>`.
Follow up from the clean up of `std::vector<v8::Local<T>>` we did before. 
From pull request: https://github.com/nodejs/node/pull/57578:
> According to V8's public API documentation, local handles (i.e., objects of type v8::Local) "should never be allocated on the heap". This replaces the usage of heap-allocated data structures containing instances of v8::Local, specifically the std::vector<v8::Local<v8::String>> with recently introduced v8::LocalVector<T>.
> tools: check for std::vector<v8::Local> in lint

- typings/globals.d.ts
- typings/internalBinding/async_context_frame.d.ts
- typings/internalBinding/constants.d.ts
- typings/internalBinding/http_parser.d.ts
- typings/internalBinding/icu.d.ts
- typings/internalBinding/sea.d.ts
- typings/internalBinding/symbols.d.ts
- typings/internalBinding/util.d.ts
- typings/primordials.d.ts
- Add typings for `async_context_frame`, `icu`, and `sea` bindings
- Add a few missing exports on other bindings
- Add a few missing primordials
> typings: improve internal binding types

- doc/api/documentation.md
This PR updates the Experimental `1.2 - Release candidate` stability index to indicate that changes may occur not only because of user feedback but also, in some cases, due to the underlying specification late development changes.
I wish to be able to mark upcoming Web Cryptography additions 1.1 - Active development with runtime experimental warning but when the dust around the WICG spec settles I wish to remove the experimental warning and mark them as 1.2 - Release candidate.
However, given past experience it may take a long time before the features get merged into the main Web Cryptography spec and in those cases I wish to reserve the option to reflect last minute changes to the spec in the implementation.
cc @nodejs/tsc
> doc: clarify release candidate stability index

- .github/actions/install-clang/action.yml
- .github/workflows/build-tarball.yml
- .github/workflows/coverage-linux-without-intl.yml
- .github/workflows/coverage-linux.yml
- .github/workflows/test-internet.yml
- .github/workflows/test-linux.yml
- configure.py
This is now required by V8.
Refs: https://github.com/nodejs/node-v8/issues/302
> build: bump minimum Clang version to 19

- test/known_issues/test-fs-cp-sync-dereference.js
Refs: https://github.com/nodejs/node/issues/58939
> test: add known issue test for fs.cpSync dereference bug

- BUILDING.md
Very often, someone appears in the #node-core slack channel asking for guidance on this compilation error
> doc: clarify the need of compiler compatible with c++20

- doc/contributing/investigating-native-memory-leaks.md
- tools/msvs/msi/nodemsi/product.wxs
"exempli gratia" is abbreviated "e.g."
> doc: correct orthography `eg.` → `e.g.`

- doc/api/http.md
- lib/_http_server.js
- test/parallel/test-http-keep-alive-timeout-buffer.js
This introduces a new server.keepAliveTimeoutBuffer option to control
an additional buffer time added to the socket timeout used for HTTP keep-alive.
The actual socket timeout for incoming HTTP connections is now computed as:
socketTimeout = server.keepAliveTimeout + server.keepAliveTimeoutBuffer
This buffer helps prevent ECONNRESET errors caused by the server closing
the socket slightly earlier than expected by some clients.
- Added new property: server.keepAliveTimeoutBuffer (default: 1000ms)
- Replaces the previously hardcoded constant
HTTP_SERVER_KEEP_ALIVE_TIMEOUT_BUFFER = 1000 in lib/_http_server.js
(was marked with a TODO: make this configurable)
- Updated documentation in doc/api/http.md
- Added new test file: test/parallel/test-http-keep-alive-timeout-buffer.js
This change does …
> http: add server.keepAliveTimeoutBuffer option

- lib/internal/crypto/aes.js
- lib/internal/crypto/cfrg.js
- lib/internal/crypto/ec.js
- lib/internal/crypto/keys.js
- lib/internal/crypto/mac.js
- lib/internal/crypto/rsa.js
- lib/internal/crypto/util.js
- lib/internal/crypto/webcrypto.js
This PR does not change any observable behaviour in codes or import/export key results. It refactors the code in preparation for the upcoming https://redirect.github.com/WICG/proposals/issues/220 webcrypto extension.
This will keep the diffs from future modern algos implementation PRs cleaner.
> crypto: prepare webcrypto key import/export for modern algorithms

- src/crypto/crypto_dsa.cc
- src/crypto/crypto_dsa.h
Removes the unused `DSAKeyExportJob`, a remnant of Node-only Web Cryptography algorithms.
> src: remove unused DSAKeyExportJob

- doc/api/globals.md
Add missing preposition "by" to clarify how to change the global dispatcher.
> doc: fix grammar in global dispatcher usage

- doc/contributing/collaborator-guide.md
Based on some recent confusion around the objection process for PRs, this commit adds some additional
clarification to the collaborator guide.
Specifically, it clarifies that:
* Objections must be made in the PR itself
* All objections are considered equal... no special additional weight is given to objections from TSC members.
* When mistakes happen and a PR lands despite having an unresolved objection, any revert or fixup PR is subject to the same regular objection process, albeit with a callout that fast-tracking is possible if uncontroversial.
@nodejs/tsc
> meta: clarify pr objection process further

- configure.py
Fix OpenSSL version detection in `configure.py` when `pkg-config` is used to configure building with a shared OpenSSL library.
Fixes: https://github.com/nodejs/node/pull/59249#discussion_r2249368196
---
cc @jasnell
> build: fix OpenSSL version detection

- doc/api/http.md
This PR fixes missing or broken Markdown reference links in [http.md#serverkeepalivetimeout](https://github.com/nodejs/node/blob/main/doc/api/http.md#serverkeepalivetimeout)
There was an issue where some Markdown reference links were not rendered correctly in the generated documentation, as shown in the screenshot below:
> doc: fix missing reference links for server.keepAliveTimeoutBuffer

- src/node_realm.h
- src/node_shadow_realm.h
Since these classes use virtual methods extensively, adding `final` should allow compilers to optimize accesses better.
> src: mark realm leaf classes final

- common.gypi
- deps/v8/src/base/platform/platform-posix.cc
In illumos, madvise(3C) now takes `void *` for its first argument post-illumos#14418, but uses `caddr_t` pre-illumos#14418. This fix will detect if the illumos is pre-or-post-illumos#14418 so builds can work either way.
Cf. https://illumos.org/issues/14418
> deps: support madvise(3C) across ALL illumos revisions

- lib/internal/assert/utils.js
This PR changes a for...of loop to an index-based for loop in the getErrMessage() function within lib/internal/assert/utils.js.
Refs: https://github.com/nodejs/node/blob/main/doc/contributing/primordials.md#unsafe-array-iteration
> assert: change utils to use index instead of for...of

- node.gni
- unofficial.gni
Refs https://github.com/nodejs/node/pull/58122
Fixes a issue where Sqlite didn't work in GN builds by default after the above PR as the defines weren't correctly set.
> build: fix `node_use_sqlite` for GN builds

- tools/v8_gypfiles/toolchain.gypi
Seems Clang-specific and doesn't only affect macOS.
This is a very noisy warning from abseil-cpp.
> tools: disable nullability-completeness warnings

- test/parallel/test-crypto-aes-wrap.js
- test/parallel/test-crypto-authenticated-stream.js
- test/parallel/test-crypto-authenticated.js
- test/parallel/test-crypto-default-shake-lengths.js
- test/parallel/test-crypto-des3-wrap.js
- test/parallel/test-crypto-ecb.js
- test/parallel/test-crypto-padding-aes256.js
Skip unsupported ciphers in some crypto tests. Improves BoringSSL compatibility.
> test,crypto: skip unsupported ciphers

- lib/internal/streams/writable.js
Improved the `clearBuffer` function in `lib/internal/streams/writable.js` by replacing `buffered.splice(0, i)` with `ArrayPrototypeSlice(buffered, i)`. This change eliminates the O(N) shifting overhead of `splice` when clearing the buffer, especially for large buffers, leading to better CPU utilization and reduced garbage collection overhead.
Profiling before and after the change showed a significant reduction in 10 CPU ticks attributed to the `clearBuffer` function, from 90 ticks to 1 tick.
> lib: optimize writable stream buffer clearing

- deps/ncrypto/ncrypto.cc
- deps/ncrypto/ncrypto.h
- src/crypto/crypto_keys.cc
- src/crypto/crypto_keys.h
- src/crypto/crypto_ml_dsa.cc
- src/crypto/crypto_ml_dsa.h
The existing checks would not be true for OpenSSL 4.0.0 up until 4.5.0.
> src: update OpenSSL pqc checks

- src/large_pages/node_text_start.S
Add note indicating support of Intel CET for large_pages.S file based on annocheck guide: https://sourceware.org/annobin/annobin.html/Test-cf-protection.html
This change should serve as preparation for enabling Intel CET feature, as all object have to support it, and linking with assembly file without this note would disable the feature for the final binary.
In this linking step the object **node_text_start.o** is used and without the note inserted by this PR into the source assembly file the feature is disabled for the object and therefore for node binary itself.
`g++ -o /node/out/Release/node -pthread -Wl, -rdynamic **/node/out/Release/obj.target/node_text_start/src/large_pages/node_text_start.o** -Wl,--whole-archive /node/out/Release/obj.target/libnode.a `
The PR adds to the …
> src: add Intel CET properties to large_pages.S

- doc/api/http.md
- lib/_http_agent.js
- test/parallel/test-http-agent-keep-alive-timeout-buffer.js
This introduces a new agentKeepAliveTimeoutBuffer option for http.Agent.
The agent uses this buffer to adjust the effective timeout when interpreting the Keep-Alive: timeout=N header sent by the server:
effectiveTimeout = (timeout * 1000) - agentKeepAliveTimeoutBuffer
This helps prevent premature socket closure by giving clients a safety margin before server-side timeouts.
Added: agentKeepAliveTimeoutBuffer option (default: 1000ms)
Follows up on: TODO(jazelly): make this configurable
Applies fallback for invalid values
Updates documentation (http.md)
Adds test: test-http-agent-keep-alive-timeout-buffer.js
This change does not affect existing connections when the value is modified.
> http: add Agent.agentKeepAliveTimeoutBuffer option

- configure.py
`configure.py` throws an error in `Python 3.12.3`.
```python
Traceback (most recent call last):
File "/home/ubuntu/node/./configure", line 27, in <module>
import configure
File "/home/ubuntu/node/configure.py", line 2328, in <module>
check_compiler(output)
File "/home/ubuntu/node/configure.py", line 1297, in check_compiler
ok, is_clang, clang_version, gcc_version, is_apple = try_check_compiler(CXX, 'c++')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 4)
```
> tools: fix return value of try_check_compiler

- doc/contributing/strategic-initiatives.md
I'd like to step up and lead some work on the nodejs/performance team. I'm still unsure if this should be a strategic initiative since there's no end goal for this, but it seems doable to provide some insights whenever we get it from nodejs/performance.
> doc: add RafaelGSS as performance strategic lead

- lib/assert.js
- test/parallel/test-fs-promises.js
Two small changes that should be rather safe, but it's probably a better idea not to backport to avoid breaking anyone (not sure if it qualifies as semver-major):
- remove self-ref `assert.ok.ok.ok…`, I doubt anyone is using it.
- `require('node:assert').name` is now `assert` instead of `ok` – for the sake of having clearer stack traces.
> assert: resolve TODO and rename function

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/translators.js
This completes the TODO to compile WASM synchronously and thus making translation (i.e. compilation + instantiation) synchronous.
Refs: https://github.com/nodejs/node/issues/55782
> esm: sync-ify module translation

- test/parallel/test-child-process-send-returns-boolean.js
- test/parallel/test-dgram-blocklist.js
- test/parallel/test-fs-watchfile.js
Replace manual error checks (`if (err) assert.fail(err)` and `assert.ok(!err)`) with `assert.ifError()` or `common.mustSucceed()` in a few tests to improve clarity and follow project conventions.
- test/parallel/test-child-process-send-returns-boolean.js
- test/parallel/test-dgram-blocklist.js
- test/parallel/test-fs-watchfile.js
No functional changes to the tests, only improved readability and consistency.
> test: replace manual error checks with assert.ifError/mustSucceed

- benchmark/crypto/create-keyobject.js
- benchmark/crypto/oneshot-sign.js
- benchmark/crypto/oneshot-verify.js
updates the crypto benchmarks so that they can be executed on OpenSSL < 3.5 and don't always run non 3.5 jobs in CI into flake status.
> benchmark: reflect current OpenSSL in crypto key benchmarks

- deps/ncrypto/ncrypto.cc
Commit 206ebeb44764d58c6a505657edab3a7a78a0b977 added an additional call to `EVP_PKEY_public_check` and an unconditional return from `publicCheck()`. This prevents the control flow from reaching the original call to either `EVP_PKEY_public_check` or `EVP_PKEY_public_check_quick`.
This change restores the previous behavior, which calls `EVP_PKEY_public_check_quick` instead, if possible.
Refs: https://github.com/nodejs/node/pull/56812
> crypto: fix EVPKeyCtxPointer::publicCheck()

- src/crypto/crypto_keys.h
Since copying `shared_ptr` may involve costly atomic operations when copied implicitly, explicitly move both `shared_ptr` objects that are passed to the private `KeyObjectData` constructor.
> src: move shared_ptr objects in KeyObjectData

- test/parallel/parallel.status
- test/parallel/test-fs-cp-sync-copy-symlink-not-pointing-to-folder.mjs
- test/parallel/test-fs-cp-sync-resolve-relative-symlinks-default.mjs
- test/parallel/test-fs-cp-sync-resolve-relative-symlinks-false.mjs
In certain machine configurations on Windows, fs.readlinkSync() may return a path with upper case drive letter while the other paths may be constructed from a base path with a lower case drive letter (e.g. from process.cwd()). Checking path mismatch in a case-sensitive manner can lead to failure in some tests, specifically with the Windows machine configurations in the Jenkins CI. Since paths are case-insensitive on Windows anyway, compare them in a case-insensitive manner in the tests.
This reduces the orange-ness of the Windows CI. I discovered it by logging the output in [a test run](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/36242/#showFailuresLink)
```
process.env.NODE_TEST_DIR: undefined
tmpdir.path: c:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.337 …
```
> test: use case-insensitive path checking on Windows in fs.cpSync tests

- doc/api/single-executable-applications.md
- src/node_sea.cc
- src/node_sea.h
- test/fixtures/sea-exec-argv-empty.js
- test/fixtures/sea-exec-argv.js
- test/sequential/test-single-executable-application-exec-argv-empty.js
- test/sequential/test-single-executable-application-exec-argv.js
The `execArgv` field can be used to specify Node.js-specific arguments that will be automatically applied when the single executable application starts. This allows application developers to configure Node.js runtime options without requiring end users to be aware of these flags.
This implements point 1 in https://github.com/nodejs/node/issues/51688#issuecomment-3144431518 - and leaves point 2 open, which can be implemented together or as a follow-up. It would be helpful to get some feedback about whether that plan is good enough for different use cases before I send this for code review. Currently the behavior in this PR is point 1 + the "env" option in point 2 by default.
Refs: https://github.com/nodejs/node/issues/51688
Refs: https://github.com/nodejs/node/issues/55573
Refs: …
> sea: support execArgv in sea config

- test/parallel/test-debug-process.js
The test `test/parallel/test-debug-process.js` fails on non-English Windows systems due to a locale-dependent error message string.
The test asserts that a call to `process._debugProcess()` on a terminated process throws an error with the message `'The system cannot find the file specified.'`. While this holds true on an English Windows system, the test fails on systems with a different display language.
The underlying `WinapiErrnoException` function correctly retrieves the localized error message from the OS. For example, on a Korean system, the message is "지정된 파일을 찾을 수 없습니다.". This mismatch causes an `AssertionError`.
This behavior can be verified directly in PowerShell:
```powershell
PS> (New-Object System.ComponentModel.Win32Exception 2).Message 
The system cannot find the file …
```
> test: make test-debug-process locale-independent

- doc/api/inspector.md
- lib/inspector.js
- lib/internal/inspector/network_undici.js
- src/inspector/network_agent.cc
- src/inspector/network_agent.h
- src/inspector/node_protocol.pdl
- test/common/websocket-server.js
- test/parallel/test-inspector-emit-protocol-event.js
- test/parallel/test-inspector-network-websocket.js
Refs: https://github.com/nodejs/node/issues/53946
I am implementing WebSocket inspector support using only the data available from undici's diagnostic events.
> inspector: initial support websocket inspection

- lib/internal/util/inspect.js
- test/parallel/test-util-inspect.js
When inspecting errors, node_modules are highlighted with an underscore. So far namespaced modules only highlighted the namespace but not the rest of the module name. This is fixed by matching the full name.
As drive-by it improves the performance slightly by removing the regular expression in favor of indexOf to identify the right spot.
> util: fix error's namespaced node_modules highlighting using inspect

- doc/api/assert.md
- lib/internal/util/comparisons.js
- test/parallel/test-assert-deep.js
It is impossible to look into the content of a promise and it's state. This aligns the comparison with WeakMaps and WeakSets. Only reference equal promises will pass the check in the future.
Fixes https://github.com/nodejs/node/issues/55198
> assert,util: fail promise comparison in deep equal checks

- doc/api/zlib.md
Documents the ZSTD_c_strategy parameter and its possible values (ZSTD_fast … ZSTD_btultra2) that were already exposed in zlib.constants but missing from the API docs and added an example for reference.
Fixes: #59290
> doc: add missing Zstd strategy constants

- benchmark/http/bench-parser.js
- lib/_http_common.js
- test/parallel/test-http-header-overflow.js
- test/parallel/test-http-upgrade-client2.js
- test/parallel/test-https-foafssl.js
This PR replaces remaining usages of the `CRLF` variable with the string literal`\r\n`  and removes the`CRLF`  export from `_http_common.js`.
In [#40101](https://github.com/nodejs/node/pull/40101), it was discussed that using the string literal `\r\n` is clearer and more explicit than using a `CRLF` variable. Based on this consensus, this PR replaces all remaining usages of the `CRLF` variable with the `\r\n` literal.
Previously, there was a TODO comment not to remove the `CRLF` export from `_http_common.js` because the module was considered "semi-public" and should not have breaking changes without proper deprecation ([discussion](https://github.com/nodejs/node/pull/40101#discussion_r708599721)).
However, as of [#59293](https://github.com/nodejs/node/pull/59293), the `_http_common.js` …
> http, benchmark: remove CRLF variables

- benchmark/crypto/kem.js
- deps/ncrypto/ncrypto.cc
- deps/ncrypto/ncrypto.h
- doc/api/crypto.md
- doc/api/errors.md
- lib/crypto.js
- lib/internal/crypto/kem.js
- lib/internal/errors.js
- node.gyp
- src/crypto/crypto_kem.cc
- src/crypto/crypto_kem.h
- src/node_crypto.cc
- src/node_crypto.h
- test/parallel/test-crypto-encap-decap.js
This PR adds `crypto.encapsulate(key[, callback])` and `crypto.decapsulate(key, ciphertext[, callback])` methods to facilitate key encapsulation mechanisms (KEM), namely:
- [ML-KEM](https://docs.openssl.org/3.5/man7/EVP_KEM-ML-KEM/), available with OpenSSL >= 3.5
- [DHKEM(P-256, HKDF-SHA256)](https://docs.openssl.org/3.5/man7/EVP_KEM-EC/), available with OpenSSL >= 3.2
- [DHKEM(P-384, HKDF-SHA256)](https://docs.openssl.org/3.5/man7/EVP_KEM-EC/), available with OpenSSL >= 3.2
- [DHKEM(P-521, HKDF-SHA256)](https://docs.openssl.org/3.5/man7/EVP_KEM-EC/), available with OpenSSL >= 3.2
- [DHKEM(X25519, HKDF-SHA256)](https://docs.openssl.org/3.5/man7/EVP_KEM-X25519/), available with OpenSSL >= 3.2
- [DHKEM(X448, HKDF-SHA512)](https://docs.openssl.org/3.5/man7/EVP_KEM-X25519/), available with …
> crypto: support ML-KEM, DHKEM, and RSASVE key encapsulation mechanisms

- tools/test.py
I've noticed that we're currently parsing the test files twice:
1. In the Python test runner
2. In `test/common/index.js`
By appending `NODE_SKIP_FLAG_CHECK` directly from the test runner, we can avoid this double check.
I'm opening this PR to evaluate whether the change provides any runtime benefits.
> tools: avoid parsing test files twice

- doc/api/globals.md
- doc/api/webstreams.md
- lib/internal/webstreams/compression.js
- test/parallel/test-whatwg-webstreams-compression.js
It has shipped in Safari [18.4](https://webkit.org/blog/16574/webkit-features-in-safari-18-4/#web-api), I don't see a reason to hold off until the spec is written.
Refs: https://github.com/whatwg/compression/issues/34
>  stream: add brotli support to CompressionStream and DecompressionStream 

- doc/api/http2.md
- lib/internal/http2/core.js
- lib/internal/http2/util.js
- test/parallel/test-http2-raw-headers-defaults.js
- test/parallel/test-http2-raw-headers.js
This PR adds raw header array support to `serverStream.respond(headers)`, continuing slowly on from #57917 (which added this client side to `clientSession.request()`).
There's quite a few other HTTP/2 APIs where raw header support will also be relevant that this doesn't touch, I'm intending to keep working through these incrementally as they become up in my other work. I notably haven't included `respondWithFile` and `respondWithFD` here in this change though, and probably won't in future, since these are just wrappers around `respond` (so less likely to be relevant for most raw header use cases) and they do some non-trivial messing around with the headers themselves (e.g. mutating with `statCheck` and injecting file size into content-length) which makes it a bit messy to support both raw …
> http2: add support for raw header arrays in h2Stream.respond()

- doc/api/sqlite.md
This PR is a manual backport of https://github.com/nodejs/node/pull/59074. It adds a missing documentation.
Release reference: https://github.com/nodejs/node/pull/58388
> [v22.x backport] doc: add missing section for setReturnArrays in sqlite.md

- typings/internalBinding/url.d.ts
add getOrigin() and pathToFileURL() to URLBinding interface.
> typings: add missing URLBinding methods

- doc/api/buffer.md
I've been going through the beta documentation generator looking for any bugs, and in the process, I noticed that this should be linked, right?
> doc: link to `TypedArray.from()` in signature

- doc/api/n-api.md
Add a new doc section to highlight other programming language bindings on top of Node-API.
Refs: https://github.com/nodejs/node/pull/59498
> node-api: link to other programming language bindings

- src/node_snapshotable.cc
Refs: https://github.com/nodejs/node/issues/59288
> src: use simdjson to parse --snapshot-config

- src/node_sqlite.cc
- test/parallel/test-sqlite-statement-sync.js
> sqlite: handle ?NNN bind params as positional

- lib/internal/crypto/webcrypto.js
- test/parallel/test-webcrypto-get-public-key.mjs
As per https://wicg.github.io/webcrypto-modern-algos/#SubtleCrypto-method-getPublicKey
> 3. If the cryptographic algorithm identified by algorithm does not support deriving a public key from a private key, then return a Promise rejected with a `NotSupportedError`.
Any secret-type key input should give `NotSupportedError`.
> 8. If the `[[type]]` internal slot of key is not "private", then throw an `InvalidAccessError`.
Public-type key input should give `InvalidAccessError`.
> crypto: fix subtle.getPublicKey error for secret type key inputs

- src/util.h
These functions are both meant to be used with a null-terminated and thus non-empty sequence of `char`s. However, there is nothing stopping call sites from passing zero-length sequences, which would certainly not be null-terminated and also would cause an underflow in `N - 1`. Therefore, this commit
- changes the size `N` of the array from `int` to `std::size_t`,
- ensures that compilation will fail if `N = 0`, and
- adds a runtime assertion that fails if the `N`-th `char` is not `\0`.
Note that the runtime assertion should be eliminated by any optimizing compiler when given a string literal, which is how these functions are used for the most part (though not exclusively).
> src: enforce assumptions in FIXED_ONE_BYTE_STRING

- benchmark/util/diff.js
**benchmark: calibrate length of util.diff**
```
500 + 1000 already covers the curve. 2000 doesn’t add new qualitative insight — it just extends the same curve further down (another ~3–4× slowdown).
According to https://github.com/nodejs/performance/issues/186 this benchmark takes one minute to conclude a single run. This should fix it.
```
> benchmark: calibrate length of util.diff

- src/crypto/crypto_context.cc
- src/crypto/crypto_util.h
- src/node.cc
When --use-system-ca is enabled, load the system CA certificates eagerly off the main thread to avoid blocking the main thread when the first TLS connection is made.
Using the PR, the first tls context creation with --use-system-ca is significantly faster (tested on macOS with 8 system certificates installed):
```js
const tls = require('tls');
tls.createSecureContext();
```
```
hyperfine "./node_main --use-system-ca ./create-context.js" "out/Release/node --use-system-ca ./create-context.js" --warmup 5
Benchmark 1: ./node_main --use-system-ca ./create-context.js
Time (mean ± σ):      53.0 ms ±   6.7 ms    [User: 28.1 ms, System: 7.4 ms]
Range (min … max):    48.7 ms …  81.0 ms    56 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system …
```
> crypto: load system CA certificates off thread

- doc/api/single-executable-applications.md
- src/node.cc
- src/node_sea.cc
- src/node_sea.h
- test/fixtures/sea-exec-argv-extension-cli.js
- test/fixtures/sea-exec-argv-extension-env.js
- test/fixtures/sea-exec-argv-extension-none.js
- test/sequential/test-single-executable-application-exec-argv-extension-cli.js
- test/sequential/test-single-executable-application-exec-argv-extension-env.js
- test/sequential/test-single-executable-application-exec-argv-extension-none.js
This implements the execArgvExtension configuration field for SEA, which takes one of three string values to specify whether and how execution arguments can be extended for the SEA at run time:
* `"none"`: No extension is allowed. Only the arguments specified in `execArgv` will be used, and the `NODE_OPTIONS` environment variable will be ignored.
* `"env"`: _(Default)_ The `NODE_OPTIONS` environment variable can extend the execution arguments. This is the default behavior to maintain backward compatibility.
* `"cli"`: The executable can be launched with `--node-options="--flag1 --flag2"`, and those flags will be parsed as execution arguments for Node.js instead of being passed to the user script. This allows using arguments that are not supported by the `NODE_OPTIONS` environment …
> sea: implement execArgvExtension

- benchmark/v8/serialize.js
**benchmark: calibrate config v8/serialize.js**
```
According to recent tests with `calibrate-n` on
a dedicated Hetzner machine (4vCPUs | 16gb) the
The results got stable with n=1e5.
The work on https://github.com/nodejs/performance/issues/186#issue-3326002531 has shown that this benchmark file takes 2-minutes for a single run. This should improve things a bit.
```
---
Possibly, 1e4 is good too, but I got a higher CV% for the (removed) `1024 * 512` on my tests
```
Configuration: {"n":10000,"len":524288}
CV: 17.20% (lower values mean more stable results)
Stability: ✗ Unstable
```
> benchmark: calibrate config v8/serialize.js

- doc/api/webcrypto.md
This PR makes references to other methods links and when referencing self as a method just says "this method" (so that there's no link to self).
> doc,crypto: cleanup unlinked and self method references webcrypto.md

- doc/api/webcrypto.md
- lib/internal/crypto/argon2.js
- lib/internal/crypto/keys.js
- lib/internal/crypto/util.js
- lib/internal/crypto/webcrypto.js
- lib/internal/crypto/webidl.js
- test/fixtures/webcrypto/supports-modern-algorithms.mjs
- test/parallel/test-webcrypto-derivebits-argon2.js
- tools/doc/type-parser.mjs
Adds Argon2 to SubtleCrypto as per https://wicg.github.io/webcrypto-modern-algos/#argon2
> crypto: add Argon2 Web Cryptography algorithms

- lib/internal/test_runner/mock/mock_timers.js
- test/parallel/test-runner-mock-timers.js
this PR prevents adding timer to execution queue if clearInterval() called.
fixes https://github.com/nodejs/node/issues/59483
> test_runner: set mocktimer's interval undefined when clearInterval called

- doc/api/http.md
This is a small change fixes a link where previously it was broken in the `response.writeHead()` documentation:
> doc: fix missing link to the Error documentation in the `http` page

- src/node_platform.cc
- src/node_watchdog.cc
- src/tracing/agent.cc
```js
const vm = require('vm');
const trace_events = require('trace_events');
trace_events.createTracing({ categories: ['node.perf'] }).enable();
new vm.Script('while(1) {}').runInThisContext({breakOnSigint: true, timeout: 100000});
```
> src: add name for more threads

- node.gyp
This does the same for `--shared-uvwasi` as #55886 does for `ada`,
`simdjson`, and `simdutf`.
Refs: https://github.com/nodejs/node/pull/55886
> build: compile bundled uvwasi conditionally

- common.gypi
- deps/v8/src/codegen/loong64/macro-assembler-loong64.cc
Fixed occasional cpu-prof test errors in loongarch64 CI.
Reference: https://ci.nodejs.org/job/node-test-commit-loongarch64/nodes=clfs23-64/710/
This issue has been haunting me for a long time (node v20.x to the latest version).
Origin commit message:
[loong64][codegen] Avoid memory access under stack pointer
According to LoongArch ABI doc chapter 8.2:
"Procedures must not assume the persistence on-stack data of which
the addresses lie below the stack pointer."
Change-Id: I92735e052227495ac9884c4290b57eaffbf905e1
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6786372
Auto-Submit: Zhao Jiazhong <zhaojiazhong-hf@loongson.cn>
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Commit-Queue: Matthias Liedtke <mliedtke@chromium.org>
Cr-Commit-Position: …
> deps: V8: cherry-pick 6b1b9bca2a8 [loong64][codegen] Avoid memory access under stack pointer

- test/parallel/test-http-keep-alive-empty-line.mjs
- Do not call `client.end()` to ensure that the socket is closed by the server.
- Remove the timer and send the empty line when the response is received.
Fixes: https://github.com/nodejs/node/issues/59577
> test: deflake test-http-keep-alive-empty-line

- doc/api/fs.md
> doc: fix filehandle.read typo

- test/parallel/parallel.status
These tests are likely actual regressions introduced when the monolithic test-fs-cp.mjs was marked as flaky and got ignored due to the flaky status. They are now constantly failing the Windows CI and require the CI to always be re-run on Windows when the job is resumed. Simply skip them until someone fixes them, as there's no point keep running these known regressions on Windows anymore.
Refs: https://github.com/nodejs/node/issues/59636
Refs: https://github.com/nodejs/node/pull/59408
> test: skip test-fs-cp* tests that are constantly failing on Windows

- test/parallel/parallel.status
https://redirect.github.com/nodejs/node/pull/59104 did not fix it and it's still flaky in the CI.
Refs: https://github.com/nodejs/reliability/blob/main/reports/2025-08-26.md
Refs: https://github.com/nodejs/node/issues/59090
> test: mark test-inspector-network-fetch as flaky again

- tools/msvs/install_tools/install_tools.bat
A required free disk space size change in `install_tools.bat` to provide more up-to-date information.
Fixes: https://github.com/nodejs/node/issues/59326
> doc: update install_tools.bat free disk space

- test/internet/test-dns.js
The `nodejs.org` domain has now two TXT records.
Do not verify the exact number of records returned (only their shape),
and check that one of them is the SPF.
> test: fix internet/test-dns

- lib/inspector/promises.js
- lib/internal/buffer.js
- lib/internal/crypto/keys.js
- lib/internal/fs/glob.js
- lib/internal/modules/esm/module_map.js
- lib/internal/per_context/primordials.js
- lib/internal/readline/interface.js
- lib/internal/repl/utils.js
- lib/readline/promises.js
ES2021 altered the behaviour of default constructors for derived classes, such that constructor calls no longer use array spreading when passing arguments to the parent constructor.
The following used to fail, but passes as of v22.0.0:
```js
Reflect.getPrototypeOf(Array.prototype[Symbol.iterator]()).next = function next() {
throw new Error('%ArrayIteratorPrototype%.next called!');
}
new class Derived extends Object {} ();
```
Previously, internal derived classes were given manually-defined "pass-through" constructors in order to avoid exposure to prototype pollution. These are no longer required, and can be safely removed.
cc: @aduh95
> lib: revert to using default derived class constructors

- lib/internal/streams/operators.js
stream: replace manual function validation with validateFunction
Replace repetitive manual function type checking with the existing
validateFunction in multiple stream operator functions.
> stream: replace manual function validation with validateFunction

- test/wasi/Makefile
Refs: https://www.gnu.org/software/make/manual/make.html#Cleanup
Refs: https://www.gnu.org/software/make/manual/make.html#Parallel-Disable
> wasi: fix `clean` target in `test/wasi/Makefile`

- doc/api/path.md
All other glob features were marked stable in https://github.com/nodejs/node/pull/57513, and this function stopped emitting experimental warnings in https://github.com/nodejs/node/pull/58236.
However, `path.matchesGlob` was never explicitly marked stable.
> doc: mark `path.matchesGlob` as stable

- .github/workflows/coverage-windows.yml
GitHub is transitioning `windows-latest` to it.
> build: use `windows-2025` runner

- lib/internal/per_context/domexception.js
- test/parallel/test-domexception-subclass.js
Fixes https://github.com/nodejs/node/issues/59677
> lib: fix DOMException subclass support

- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/module_job.js
- src/env_properties.h
- src/module_wrap.cc
- src/module_wrap.h
Clarify the names - hasAsyncGraph means either the module or its dependencies contains top-level await; hasTopLevelAwait means the module itself contains top-level await. Theoratically the former can be inferred from iterating over the dependencies but for the built-in loader it's currently not fully reliable until we eliminate async linking.
Also remove the hasTopLevelAwait method - we can simply put it on the module wrap for source text modules right after compilation.
> src: separate module.hasAsyncGraph and module.hasTopLevelAwait

- src/node_sqlite.cc
- src/node_sqlite.h
This PR refactors `SatetmentSync::All` and `StatementSyncIterator::Next` methods to reduce complexity.
This will make it a lot easier to move forward with the implementation of the [async api for node:sqlite](https://github.com/nodejs/node/pull/59109)
> src,sqlite: refactor value conversion

- doc/api/typescript.md
The docs state, "To discourage package authors from publishing packages written in TypeScript, Node.js will _by default_ refuse to handle TypeScript files inside folders under a `node_modules` path" (emphasis added). This suggests that there's a way to override that default. However, as far as I can tell, there is not.
> doc: update "Type stripping in dependencies" section

- benchmark/sqlite/sqlite-prepare-select-all.js
- benchmark/sqlite/sqlite-prepare-select-get.js
At the beginning of the two benchmarks `sqlite-prepare-select-all.js` and `sqlite-prepare-select-get.js`, two tables (`foo` and `foo_large`) were created. This PR introduces a conditional to create only the required table for each benchmark, reducing execution time.
|bench| before | after |
|-------|------| ------|
| sqlite-prepare-select-all.js | 4m48.002s | 4m1.381s |
| sqlite-prepare-select-get.js | 0m37.168s |  0m17.383s |
> benchmark: sqlite prevent create both tables on prepare select

- .github/workflows/test-internet.yml
Building `node` takes forever on that job, adding cache should speed it up.
> tools: add sccache to `test-internet` workflow

- src/api/callback.cc
- src/async_wrap.cc
- src/env-inl.h
- src/env.cc
- src/env.h
- src/node_internals.h
- src/node_task_queue.cc
This addresses an existing `TODO` to remove the need for a separate `LocalVector`. Since all relevant handles are already present on the stack, we can track their addresses instead of storing the objects in a separate container.
> src: track async resources via pointers to stack-allocated handles

- lib/internal/test_runner/test.js
- test/fixtures/test-runner/output/name_pattern.snapshot
- test/fixtures/test-runner/todo_exit_code.js
- test/parallel/test-runner-exit-code.js
Fixes https://github.com/nodejs/node/issues/59719
> test_runner: fix todo inheritance

- test/sequential/sequential.status
Theses tests are failing when compiled with clang. Skip for now to avoid breaking the CI when we switch over to building with clang.
Refs: https://github.com/nodejs/node/issues/59561
> test: skip more sea tests on Linux ppc64le

- doc/api/errors.md
- lib/internal/errors.js
- lib/internal/url.js
- test/parallel/test-url-fileurltopath.js
- test/parallel/test-url-invalid-file-url-path-input.js
Otherwise there's no information from the error about what exactly is the invalid URL.
Background: I was debugging https://ci.nodejs.org/job/node-test-binary-windows-js-suites/36647/ and I had no idea why the tests are failing since there's no hint about what the URLs are after they get processed in the loader.
> url: add err.input to ERR_INVALID_FILE_URL_PATH

- lib/internal/crypto/argon2.js
- lib/internal/crypto/diffiehellman.js
- lib/internal/crypto/ml_dsa.js
- lib/internal/crypto/ml_kem.js
- lib/internal/crypto/pbkdf2.js
- lib/internal/crypto/random.js
- lib/internal/crypto/webcrypto.js
> lib: prefer TypedArrayPrototype primordials

- doc/api/deprecations.md
- lib/repl.js
- test/parallel/test-repl.js
This PR moves instantiating without `new` to End-Of-Life for REPL classes, and with that, converts them to the newer class syntax.
Ref: #54869 - This is a semver-major change.
> repl: eol deprecate instantiating without new

- test/parallel/test-fs-mkdtempDisposableSync.js
- test/parallel/test-fs-promises-mkdtempDisposable.js
Removing read-only directory doesn't fail for root.
> test: skip tests failing when run under root

- lib/_http_common.js
Avoid some common string allocation
> http: use cached '1.1' http version string

- lib/repl.js
- test/parallel/test-repl-completion-on-getters-disabled.js
- test/parallel/test-repl-tab-complete-getter-error.js
- test/parallel/test-repl-tab-complete-nosideeffects.js
A number of recent changes to the REPL tab completion logic have introduced the ability for completion to cause side effects, specifically, calling arbitrary functions or variable assignments/updates.
This was first introduced in 07220230d9 and the problem exacerbated in 8ba66c5e7b367. Our team noticed this because our tests started failing when attempting to update to Node.js 20.19.5.
Some recent commits, such as 1093f38c437 or 69453378fc44af, have messages or PR descriptions that imply the intention to avoid side effects, which I can can generally be agreed upon is in line with the expectations that a user has of autocomplete functionality.
However, some of the tests introduced in those commts specifically verify that side effects *can* happen under specific circunmstances. I am …
> repl: do not cause side effects in tab completion

- lib/internal/modules/cjs/loader.js
- lib/internal/modules/esm/loader.js
- lib/internal/modules/esm/translators.js
- lib/internal/modules/helpers.js
- src/env_properties.h
- src/module_wrap.cc
- test/es-module/test-require-esm-from-imported-cjs.js
- test/fixtures/es-modules/require-esm-in-cjs-cache/app.cjs
- test/fixtures/es-modules/require-esm-in-cjs-cache/hooks.js
- test/fixtures/es-modules/require-esm-in-cjs-cache/instrument-sync.js
- test/fixtures/es-modules/require-esm-in-cjs-cache/instrument.js
- test/fixtures/es-modules/require-esm-in-cjs-cache/package.json
- test/fixtures/es-modules/require-esm-in-cjs-cache/test.js
Otherwise if the ESM happens to be cached separately by the ESM loader before it gets loaded with `require(esm)` from within an imported CJS file (which uses a re-invented require() with a couple of quirks, including a separate cache), it won't be able to load the esm properly from the cache.
Refs: https://github.com/nodejs/node/issues/59666
Refs: https://github.com/nodejs/node/issues/57327#issuecomment-3012503512
Refs: https://github.com/nodejs/node/issues/52697
> esm: populate separate cache for require(esm) in imported CJS

- doc/api/deprecations.md
- doc/api/diagnostics_channel.md
Resolves #59756.
This deprecation no longer applies, for the reasons outlined in the linked issue.
> diagnostics_channel: revoke DEP0163

- lib/internal/assert/myers_diff.js
- test/parallel/test-assert-myers-diff.js
The current implementation of `myersDiff` may attempt to allocate an
`Int32Array` larger than the supported limit when the input size
exceeds 2^31 - 1. This can lead to an out-of-range runtime failure.
This patch adds a maximum input size check and throws
`ERR_OUT_OF_RANGE` if the limit is exceeded.
It also resolves the TODO left in `internal/assert/myers_diff.js`.
/cc @BridgeAR
> assert: cap input size in myersDiff to avoid Int32Array overflow

- tools/test.py
this distinguishes test abort from all tests passed.
Previously, "All tests passed." was printed even when the user aborted the test using the keyboard (e.g., Ctrl+C), as long as no test failures had occurred.
fixes https://github.com/nodejs/node/issues/59795
> tools: print appropriate output when test aborted

- src/node_mem-inl.h
- src/node_zlib.cc
Calling `V8::ExternalMemoryAccounter::Increase` with a signed integer on
32-bit platforms causes instances where GC inside GC takes place leading
to a crash in certain cases.
During GC, native objects are destructed. In destructor for
`CompressionStream` class used by zlib, memory release information is
passed onto `V8::ExternalMemoryAccounter::Increase()` instead of
`V8::ExternalMemoryAccounter::Decrease()` which triggers V8's memory
limits, thus triggering GC inside GC which leads to crash.
Bug initially introduced in commit
1d5d7b6eedb2274c9ad48b5f378598a10479e4a7
For full report see https://hackerone.com/reports/3302484
> src: call `V8::ExternalMemoryAccounter::Update` instead of `V8::ExternalMemoryAccounter::Increase` to report memory difference to V8

- doc/api/cli.md
> doc: stabilize --disable-sigusr1

- doc/api/webcrypto.md
Follow up to https://redirect.github.com/nodejs/node/pull/59608
> doc,crypto: update subtle.generateKey and subtle.importKey

- lib/internal/readline/interface.js
- test/parallel/test-repl-paste-big-data.js
Pasting input should not trigger any completions and other calculations. This is now handled by just writing the string to the terminal in case the user is pasting. As soon as pasting is done, the completions will be re-enabled.
Fixes: https://github.com/nodejs/node/issues/40626
Fixes: https://github.com/nodejs/node/issues/43343
The improvement is not linear (former data was always reparsed), so providing a concrete number is not sufficient. On my machine it is 50x faster for `'a'.repeat(5e4)`.
The test case I added has a big time buffer to not be flaky. On some CPUs, it might however still be flaky and I could not think of a better test case that does not cause it to be flaky or have a long runtime.
> repl: fix cpu overhead pasting big strings to the REPL

- lib/internal/util/debuglog.js
- test/sequential/test-util-debug.js
The method returned by the callback is missing the .enabled property. This is added in a consistent way that it also verifies that it's a getter.
Fixes: https://github.com/nodejs/node/issues/56676
> util: fix debuglog.enabled not being present with callback logger

- lib/internal/util/inspect.js
- test/parallel/test-util-inspect.js
`util.inspect()` should handle all kinds of input, even if it is not well defined. Throwing is something that is meant to be worked around in all known cases. This fixes issues inspecting objects where accessing the Symbol.toStringTag would cause an error. The symbol is just ignored in that case.
Refs: https://github.com/nodejs/node/issues/55539
Refs: https://github.com/nodejs/node/pull/55544
> util: inspect objects with throwing Symbol.toStringTag

- lib/url.js
I replaced slice(-1) with at(-1) to avoid creating a new collection, since at() directly accesses the element without copying the array.
I did the same for a string in another place — replaced slice(-1) with at(-1) for consistency and simplicity.
> url: replaced slice with at

- benchmark/dgram/multi-buffer.js
>According to https://github.com/nodejs/performance/issues/186 this benchmark was taking 120 seconds for a single run.
Replaced the `num` config with `n` to be compatible with the `n` CLI argument.
Looking at the outputs:
Chunks 1 and 2 have very similar results, as do 4 and 8. I removed 2 and 4, keeping only `[1, 8]`.
I think `[64, 512, 1024]` covers a sufficient range, making `256` unnecessary.
If you don’t agree with the changes in the configs, let me know, and we can revert them and just proceed with the `num` → `n` change.
**Before:**
```
dgram/multi-buffer.js dur=5 type="send" chunks=1 num=100 len=64: 0.02159776900313264
dgram/multi-buffer.js dur=5 type="recv" chunks=1 num=100 len=64: 0.006370982125852746
dgram/multi-buffer.js dur=5 type="send" chunks=2 num=100 len=64: …
```
> benchmark: calibrate config dgram multi-buffer

- doc/api/assert.md
- doc/api/util.md
- lib/assert.js
- lib/internal/util/comparisons.js
- lib/util.js
- test/parallel/test-assert-class.js
- test/parallel/test-util-isDeepStrictEqual.js
Adds a new `skipPrototype ` option to `util.isDeepStrictEqual()` and `assert.deepStrictEqual()` methods that allows skipping prototype and constructor comparison during deep strict equality checks.
cc @BridgeAR
> util: add skipPrototype option to deep equality checks

- benchmark/zlib/crc32.js
- src/node_zlib.cc
- test/sequential/test-zlib-crc32-fast-api.js
Full benchmarks:
```sh
node % node benchmark/zlib/crc32.js
zlib/crc32.js n=4000000 len=32 type="buffer": 37,396,444.66876052
zlib/crc32.js n=4000000 len=256 type="buffer": 34,468,122.98396251
zlib/crc32.js n=4000000 len=4096 type="buffer": 4,642,218.20245069
zlib/crc32.js n=4000000 len=65536 type="buffer": 414,698.94918172585
zlib/crc32.js n=4000000 len=32 type="string": 27,544,938.95769763
zlib/crc32.js n=4000000 len=256 type="string": 13,360,556.974013995
zlib/crc32.js n=4000000 len=4096 type="string": 3,598,194.020364296
zlib/crc32.js n=4000000 len=65536 type="string": 247,640.72679581624
node % ./node benchmark/zlib/crc32.js
zlib/crc32.js n=4000000 len=32 type="buffer": 47,694,181.36925779
zlib/crc32.js n=4000000 len=256 type="buffer": 41,584,645.71789544
zlib/crc32.js n=4000000 …
```
> zlib: implement fast path for crc32

- lib/internal/streams/end-of-stream.js
The bind method uses ObjectDefineProperty that shows up in flamegraphs. This changes it to avoid the utility.
> stream: use new AsyncResource instead of bind

- src/node_realm.cc
- src/node_sqlite.cc
- src/node_webstorage.cc
- src/stream_wrap.cc
This PR replaces `FIXED_ONE_BYTE_STRING(isolate, "...")` literals with Environment-cached strings.
> src: replace FIXED_ONE_BYTE_STRING with Environment-cached strings

- src/node_file.cc
Do not add a trailing slash if it was not removed by resolve in ToNamespacedPath.
Unfortunatelly I do not know how to test this without 3rd party tools descirbed in #58223.
Refs: https://github.com/nodejs/node/pull/56110
Fixes: https://github.com/nodejs/node/issues/58223
> fs,win: do not add a second trailing slash in readdir

- src/env_properties.h
- src/node_url_pattern.cc
Finishing updating `URLPattern` to use `DictionaryTemplate`
> src: use DictionaryTemplate more in URLPattern

- doc/api/sqlite.md
- src/lru_cache-inl.h
- src/node_sqlite.cc
- src/node_sqlite.h
- src/quic/data.cc
- src/quic/data.h
- test/cctest/test_lru_cache.cc
- test/parallel/test-sqlite-template-tag.js
- tools/doc/type-parser.mjs
Closes #57570
This pr introduces the support for tagged templates and an LRU to cache the templates. We introduced a new object called SqlTagStore that holds the ref to Lru. This acts as the main object that allows us to use tagged templates.
Look at the test file [test-sqlite-template-tag.js](https://github.com/nodejs/node/pull/58748/files#diff-385ea1363f78c84e25edb390ae27537e0b5f440c8564abfc5b16971556f43b85) to see how the api is designed.
> sqlite: add tagged template

- lib/diagnostics_channel.js
- test/fixtures/source-map/output/source_map_assert_source_line.snapshot
- test/parallel/test-diagnostics-channel-gc-maintains-subcriptions.js
- test/parallel/test-diagnostics-channel-gc-race-condition.js
When a garbage collector is executed, the callback of `FinalizationRegistry` it is not executed synchronously with the GC, it is executed later, in the next event loop.
That means that there is a corner case in the `WeakRefMap` object in diagnostics channel. Eventually could happen that an event is GC and created again before the execution of the callback of `FinalizationRegistry`. When this happens, the key object is deleted from the `WeakRefMap` even when it has a valid value.
This behavior can be reproduced with this code added in tests:
```javascript
const assert = require('assert');
const { channel } = require('diagnostics_channel');
function test () {
const testChannel = channel('test-gc');
setTimeout(() => {
const testChannel2 = channel('test-gc');
assert.ok(testChannel === …
```
> diagnostics_channel: fix race condition with diagnostics_channel and GC

- lib/child_process.js
- test/parallel/test-child-process-fork-timeout-kill-signal.js
- test/parallel/test-child-process-spawn-timeout-kill-signal.js
- test/parallel/test-child-process-spawn-typeerror.js
- test/parallel/test-child-process-spawnsync-validation-errors.js
This refactors internal validation helpers in `child_process` to use the common validators in `lib/internal/validators.js` where possible.
This improves code consistency and maintainability.
> lib: use validators for argument validation

- lib/internal/util/inspect.js
- test/es-module/test-esm-loader-with-syntax-error.mjs
- test/parallel/test-util-inspect.js
Fix deduplication logic for `inspect` output when dealing with constructor names that contain custom tags, but checking for tag followed by lowercase characters, e.g: avoiding unnecessary tag `Set` from a constructor extended like `FooSet(3) { 1, 2, 3 }` from a `util.inspect(new FooSet([1, 2, 3]))` but keeping it for `Settings(3) [Set] { 1, 2, 3 }` from a `util.inspect(new Settings([1, 2, 3]))`
cc @BridgeAR
> lib: fix inspect deduplication logic

- deps/ngtcp2/ngtcp2.gyp
This is the unfinished work of PR https://github.com/nodejs/node/pull/59547. I missed this modification point, and it was my mistake. Now I have rechecked and confirmed that there are no other omissions except for this one.
> build: add the missing macro definitions for OpenHarmony

- lib/internal/modules/esm/loader.js
- test/es-module/test-typescript-commonjs.mjs
- test/es-module/test-typescript-module.mjs
- test/fixtures/typescript/cts/issue-59963/a.cts
- test/fixtures/typescript/cts/issue-59963/b.mts
- test/fixtures/typescript/cts/issue-59963/c.cts
- test/fixtures/typescript/mts/issue-59963/a.mts
- test/fixtures/typescript/mts/issue-59963/b.cts
- test/fixtures/typescript/mts/issue-59963/c.mts
Fixes: https://github.com/nodejs/node/issues/59963
> module: use sync cjs when importing cts

- doc/api/cli.md
- doc/api/environment_variables.md
- doc/api/process.md
- doc/api/util.md
As discussed in https://github.com/nodejs/node/issues/49148#issuecomment-3307288256 the feature should be ready to be marked stable.
The change could probably be picked to v24 and be featured in the change log.
This is my first time contributing to node so let me know if there's any mistakes.
> doc: mark --env-file and --env-file-if-exists as stable

- lib/internal/process/promises.js
- test/parallel/test-promise-unhandled-error-with-reading-file.js
Fixes: https://github.com/nodejs/node/issues/60034
When I looked at the crash point in the issue, I found that asyncId was undefined.
https://github.com/nodejs/node/blob/main/src/api/callback.cc#L185
I suspect that the code may have been mistakenly changed in this PR.
https://github.com/nodejs/node/pull/52108/files#diff-04f0a68c4bc76396de863bbe0982c85d70a5b71432bdc26bc503e3ac317c6f82L263
> process: fix wrong asyncContext under unhandled-rejections=strict

- lib/internal/event_target.js
- test/parallel/test-whatwg-events-add-event-listener-options-passive.js
- test/wpt/status/dom/events.json
Implement Web API spec-compliant behavior
for passive event listeners
where preventDefault() and returnValue setting are ignored during
passive listener execution.
- Add kInPassiveListener symbol to track passive listener state
- Modify preventDefault() to ignore calls during
passive listener execution
- Add returnValue setter that respects passive listener state
- Set/clear passive flag around listener invocation in dispatchEvent
Fixes WPT test cases that were previously failing in
AddEventListenerOptions-passive.any.js and
satisfies expected behaviors:
- preventDefault should be ignored
if-and-only-if the passive option is true
- returnValue should be ignored
if-and-only-if the passive option is true
- passive behavior of one listener should be unaffected
by other listeners
Refs: …
> lib: implement passive listener behavior per spec

- src/cares_wrap.cc
- src/env_properties.h
Updates cares_wrap to use DictionaryTemplates
> src: update cares_wrap to use DictionaryTemplates

- lib/internal/priority_queue.js
Further improves performance and fixes leftover issues from my last [PR](https://github.com/nodejs/node/pull/57100)
- Makes heap PACKED
- Forces V8 optimization when resizing
- [Removes dead code](https://github.com/nodejs/node/pull/60039#issuecomment-3343744202)
Benchmarks:
main
```sh
node % ./node benchmark/run.js --filter priority util
util/priority-queue.js
util/priority-queue.js n=100000: 6,676,867.584962973
```
branch
```sh
node % ./node benchmark/run.js --filter priority util
util/priority-queue.js
util/priority-queue.js n=100000: 6,854,890.535966754
```
> lib: optimize priority queue

- benchmark/crypto/getcipherinfo.js
- lib/internal/crypto/cipher.js
- src/crypto/crypto_cipher.cc
- src/env_properties.h
Also, have it use a null prototype, lowercase in the C++ layer, eliminate an unnecessary string conversion, and improve argument validation. Semver-major due to a couple of the changes.
Results in about a 25% performance improvment:
```
crypto/getcipherinfo.js n=50 cipher='aes-128-cbc-hmac-sha1'           ***     24.04 %       ±3.97%  ±5.28%  ±6.88%
crypto/getcipherinfo.js n=50 cipher='aes-128-cbc-hmac-sha256'         ***     24.03 %       ±5.43%  ±7.24%  ±9.43%
crypto/getcipherinfo.js n=50 cipher='aes-128-cbc'                     ***     24.60 %       ±3.35%  ±4.46%  ±5.82%
crypto/getcipherinfo.js n=50 cipher='aes-128-ccm'                     ***     27.13 %       ±6.63%  ±8.85% ±11.59%
crypto/getcipherinfo.js n=50 cipher='aes-128-cfb'                     ***     23.69 %       ±6.45% …
```
> src: update crypto.getCipherInfo() to use DictionaryTemplate

- test/parallel/parallel.status
`parallel/test-runner-run-watch` has failed [33 out of the last 100 CI](https://github.com/nodejs/reliability/blob/main/reports/2025-10-03.md#jstest-failure) runs on macOS. It is already marked flaky on other platforms.
Refs: https://github.com/nodejs/node/issues/54534
> test: mark `test-runner-run-watch` flaky on macOS

- lib/_http_server.js
This change is based on the "Unsafe array iteration" principle from the Node.js core development guidelines. for-of loops rely on the Symbol.iterator property, which can be modified by userland code, potentially leading to unpredictable or insecure behavior. Using a standard for loop directly accesses the array elements by index, ensuring a more stable and secure execution flow.
Refs: https://github.com/nodejs/node/blob/main/doc/contributing/primordials.md#unsafe-array-iteration
> http: improve writeEarlyHints by avoiding for-of loop

- src/env_properties.h
- src/node_contextify.cc
More use of DictionaryTemplate
> src: update contextify to use DictionaryTemplate

- lib/internal/inspector/network.js
- lib/internal/inspector/network_http.js
- lib/internal/inspector/network_http2.js
- lib/internal/inspector/network_undici.js
Improve batch diagnostic channel subscriptions in network inspections. This could prevent a channel from mismatches in subscribe/unsubscribe.
> inspector: improve batch diagnostic channel subscriptions

- doc/api/deprecations.md
after a meeting with userland migration team we saw that we can include our job on the deprecation page.
BTW Codemod is officially openjs partner https://openjsf.org/blog/codemod-openjs-foundation-partner
> doc: add automated migration info to deprecations

- src/api/environment.cc
- src/node.cc
- tools/v8_gypfiles/v8vtune.gyp
Updates VTune include header paths which were changed in v8 https://github.com/v8/v8/commit/846f470ae0b6b334ce3b4e14cca6f7606f6fce42
This fixes the VTune build when built as follows 
```
./configure --enable-vtune-profiling
make
```
and shows the appropriate JIT / Dynamic Code module in VTune.
> Update VTune include paths

- Makefile
- configure.py
- pyproject.toml
- test/testpy/__init__.py
- test/tools/test_checkimports.py
- tools/generate_config_gypi.py
- tools/icu/icutrim.py
- tools/install.py
- tools/test.py
* https://docs.astral.sh/ruff
* https://github.com/astral-sh/ruff/releases
* https://docs.astral.sh/ruff/rules/#flake8-async-async
* https://docs.astral.sh/ruff/rules/#perflint-perf
> build: upgrade Python linter ruff, add rules ASYNC,PERF

- lib/internal/async_hooks.js
- lib/internal/process/task_queues.js
- lib/internal/timers.js
- lib/timers.js
- test/fixtures/errors/async_error_nexttick_main.snapshot
> // Fewer checks may be possible, but these cover everything.
`emitDestroy` already checks these now:
https://github.com/nodejs/node/blob/6f941fcfba50fe7c3a342ed2066770aecaaa9b5a/lib/internal/async_hooks.js#L533-L538
We are essentially checking the same condition twice
Also the invalid id check didn't cover `undefined`. I don't know if it was intentional, but in any case, since https://github.com/nodejs/node/pull/56966, which removed `enroll`, I'm not sure if we can have an undefined `asyncId` anyway
> lib: remove redundant destroyHook checks
